<?
$items = $this->driver->getItems();
$dbLabel = $this->driver->getDbLabel();
$thumb = $this->driver->getThumbnail('medium');
$pubType = $this->driver->getPubType();
$customLinks = $this->driver->getCustomLinks();
$accessLevel = $this->driver->getAccessLevel();
$restrictedView = empty($accessLevel) ? false : true;
$id = $this->driver->getUniqueID();
$source = explode(".", $id)[0];
$maxSubjectsInCore = $config['Record']['max_subjects_in_core'];
?>

<? if ($bibinfo = $this->record($this->driver)->getObalkyKnihJSONV3()): ?>

<? endif; ?>

<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
    <div class="col-sm-3">
        <? $QRCode = $this->record($this->driver)->getQRCode("core");
        $cover = $this->record($this->driver)->getCover('core', 'medium', $this->record($this->driver)->getThumbnail('large'));
        $preview = $this->record($this->driver)->getPreviews(); ?>
        <? if ($QRCode || $cover || $preview): ?>
        <div class="row text-center #cover" id="cover">
            <? $formats = $this->driver->getFormats(); ?>
            <? if (! empty($formats)): ?>
                <div class="iconlabel col-md-12"><i style="font-size: 70px; color: #cccccc;" class="pr-format-<?=$this->record($this->driver)->getFormatClass($formats[0])?>"></i></div>
            <? else: ?>
                <img class="recordcover col-md-12" src="<?=$this->url('cover-unavailable')?>" alt="<?=$this->transEsc('No Cover Image')?>"/>
            <? endif; ?>
            <script type="text/javascript">
                obalky.display_cover_without_links("#cover", <?=$bibinfo?>, <?=json_encode($this->record($this->driver)->getObalkyKnihAdvert("record"))?>);
            </script>
            <? /* Display qrcode if appropriate: */ ?>
            <? $QRCode = $this->record($this->driver)->getQRCode("core"); ?>
            <? if($QRCode): ?>
                <span class="hidden-xs">
                      <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
                    </span>
            <? endif; ?>
        </div>

            <? // if you have a preview tab but want to move or remove the preview link
            // from this area of the record view, this can be split into
            // getPreviewData() (should stay here) and
            // getPreviewLink() (can go in your desired tab) ?>
            <? if ($preview): ?><?=$preview?><? endif; ?>
        <? endif; ?>

        <div class="external-links">
            <? $pLink = $this->driver->getPLink();
            if($pLink): ?>
                <span>
          <a href="<?=$this->escapeHtmlAttr($pLink)?>">
            <?=$this->transEsc('View in EDS')?>
          </a>
        </span><br />
            <? endif; ?>
            <? $pdfLink = $this->driver->getPdfLink();
            if ($pdfLink): ?>
                <span>
          <a href="<?=$pdfLink?>" class="icon pdf fulltext">
            <?=$this->transEsc('PDF Full Text')?>
          </a>
        </span><br />
            <? endif; ?>
            <? if ($this->driver->hasHTMLFullTextAvailable()): ?>
                <span>
          <a href="<?=$this->recordLink()->getUrl($this->driver, 'fulltext')?>#html" class="icon html fulltext">
            <?=$this->transEsc('HTML Full Text')?>
          </a>
        </span><br />
            <? endif; ?>
        </div>
    </div>
    <div class="col-sm-9">
        <h3 property="name"><?=$this->driver->getTitle()?></h3>

        <table class="table table-striped" summary="<?=$this->transEsc('Bibliographic Details')?>">
            <? foreach ($items as $key => $item): ?>
                <? if (!empty($item['Data'])): ?>
                    <tr>
                        <th><?=$this->transEsc($item['Label'])?>:</th>
                        <td><?=$this->driver->linkUrls($item['Data'])?></td>
                    </tr>
                <? endif; ?>
            <? endforeach; ?>

            <? if ($dbLabel): ?>
                <tr>
                    <th><?=$this->transEsc('Database')?>:</th>
                    <td><?=$this->escapeHtml($dbLabel)?></td>
                </tr>
            <? endif; ?>

            <?if ($this->driver->hasHTMLFullTextAvailable() && !$restrictedView):
                $fullText = $this->driver->getHtmlFullText();?>
                <tr id="html">
                    <td colspan="2">
                        <?=$fullText?>
                    </td>
                </tr>
            <? elseif ($this->driver->hasHTMLFullTextAvailable() && $restrictedView): ?>
                <tr id="html">
                    <td>
                        <?=$this->transEsc('Full text is not displayed to guests')?>
                    </td>
                    <td>
                        <a class="login" href="<?=$this->url('myresearch-home')?>" rel="nofollow">
                            <strong><?=$this->transEsc('Login for full access')?></strong>
                        </a>
                    </td>
                </tr>
            <? endif; ?>
        </table>

        <div class="resultItemLine4 custom-links">

            <? $customLinks = array_merge($this->driver->getFTCustomLinks(), $this->driver->getCustomLinks());
            if (!empty($customLinks)): ?>
                <? foreach ($customLinks as $customLink): ?>
                    <? $url = isset($customLink['Url']) ? $customLink['Url'] : '';
                    $mot = isset($customLink['MouseOverText'])? $customLink['MouseOverText'] : '';
                    $icon = isset ($customLink['Icon']) ? $customLink['Icon'] : '';
                    $name = isset($customLink['Text']) ? $customLink['Text'] : '';
                    ?>
                    <span>
        <a href="<?=$this->escapeHtmlAttr($url)?>" target="_blank" title="<?=$this->escapeHtmlAttr($mot)?>" class="custom-link">
          <? if ($icon): ?><img src="<?=$this->escapeHtmlAttr($icon)?>" /> <? endif; ?><?=$this->escapeHtml($name)?>
        </a>
      </span>
                <? endforeach; ?>
            <? endif; ?>
        </div>
    </div>
</div>
