<? $viewList = $this->params->getViewList(); if (count($viewList) > 1): ?>
  <? foreach ($viewList as $viewType => $viewData): ?>
    <? if (!$viewData['selected']): ?>
      <a href="<?=$this->results->getUrlQuery()->setViewParam($viewType)?>" title="<?=$this->transEsc('Switch view to')?> <?=$this->transEsc($viewData['desc'])?>" >
    <? endif; ?>
    <?=ucfirst($this->transEsc($viewType)) ?> <?=$this->transEsc('view') ?><? if (!$viewData['selected']): ?></a><? endif; ?>&nbsp;
  <? endforeach; ?>
<? endif; ?>