<span class="limitSelect">
  <? $limitList = $this->params->getLimitList(); if (count($limitList) > 1): ?>
    <form class="form-inline" action="<?=$this->currentPath() . $this->results->getUrlQuery()->setLimit(null)?>" method="get" name="limit">
      <?=$this->results->getUrlQuery()->asHiddenFields(array('limit' => '/.*/'));?>
      <label for="limit" class="resultsOnPageLimiter"><?=$this->transEsc('Results per page')?></label>
      <select id="limit" name="limit" class="jumpMenu resultsOnPageLimiter" onChange="document.limit.submit()">
        <? foreach ($limitList as $limitVal => $limitData): ?>
          <option value="<?=$this->escapeHtml($limitVal)?>"<?=$limitData['selected']?' selected="selected"':''?>><?=$this->escapeHtml($limitData['desc'])?></option>
        <? endforeach; ?>
      </select>
      <noscript><input type="submit" value="<?=$this->transEsc("Set")?>" /></noscript>
    </form>
  <? endif; ?>
</span>

