<h1>Najděte knihovnu nejblíže vám</h1>
<form class="find-form text-center" action="/Libraries/List/" method="get">
    <input class="form-control find-input" name="query" placeholder="Zadejte hledaný výraz"/>
    <button href="/Libraries/List/" class="btn btn-primary find-button">Hledat</button>
</form>
<div class="col-md-12 text-center" style="margin-top: 10px;">
    <a>Knihovny v mém okolí (TODO)</a>
</div>
