<?
  $title = "Knihovny";
  $this->layout()->title = $title;
  $this->headTitle($title);
  $this->layout()->headerType = "libraries";
  $this->headScript()->appendFile("jquery-ui.min.js");
  setlocale(LC_NUMERIC, "en_US.utf8");
?>


<div class='row'>
  <div class="col-md-6 library-detail">
    <h1><?=$library->getName()?></h1>
    <? if ($library->getAlternativeNamesFormated()!=null):?>
      <h3><?=$library->getAlternativeNamesFormated()?></h3>
    <? endif; ?>
    <? if ($library->getAddress()!=null):?>
    <h2><i class="pr-location-pinmap5"></i><?=$library->getAddress()?></h2>
    <? endif; ?>

    <? if ($library->opening_hours!=null):?>
    <h2><i class="pr-interface-clocktime"></i>Otevírací doba</h2>
      <table class="table">
        <tr>
          <td><?=$this->transEsc('Monday')?></td>
          <td><?=$library->opening_hours->getMo()?></td>
        </tr>
        <tr>
          <td><?=$this->transEsc('Tuesday')?></td>
          <td><?=$library->opening_hours->getTu()?></td>
        </tr>
        <tr>
          <td><?=$this->transEsc('Wednesday')?></td>
          <td><?=$library->opening_hours->getWe()?></td>
        </tr>
        <tr>
          <td><?=$this->transEsc('Thursday')?></td>
          <td><?=$library->opening_hours->getTh()?></td>
        </tr>
        <tr>
          <td><?=$this->transEsc('Friday')?></td>
          <td><?=$library->opening_hours->getFr()?></td>
        </tr>
        <tr>
          <td><?=$this->transEsc('Saturday')?></td>
          <td><?=$library->opening_hours->getSa()?></td>
        </tr>
        <tr>
          <td><?=$this->transEsc('Sunday')?></td>
          <td><?=$library->opening_hours->getSu()?></td>
        </tr>

      </table>
    <? endif; ?>
<!--    <h2><i class="pr-web-linkurl"></i>Odkazy</h2>-->

    <? if ($library->websites!=null):?>
      <h2><i class="pr-web-browseinternetnetwork"></i>Webové stránky</h2>
      <? foreach ($library->websites as $website):?>
        <p><a href="<?=$website->getUrl()?>"><?=$website->getNote()?></a></p>
      <? endforeach; ?>
    <? endif; ?>

    <? if ($library->services!=null):?>
      <h2><i class="pr-interface-circlerighttrue"></i>Služby</h2>
      <? foreach ($library->services as $service):?>
        <p><?=$service->getName()?></p>
      <? endforeach; ?>
    <? endif; ?>

    <? if ($library->projects!=null):?>
      <h2><i class="pr-interface-circlerighttrue"></i>Projekty</h2>
      <? foreach ($library->projects as $project):?>
        <p><?=$project->getName()?></p>
      <? endforeach; ?>
    <? endif; ?>

    <? if ($library->phones!=null):?>
      <h2><i class="pr-communication-phonecall"></i>Telefon</h2>
      <? foreach ($library->phones as $phone):?>
        <p><?=$phone->getPhone()?></p>
      <? endforeach; ?>
    <? endif; ?>

    <? if ($library->emails!=null):?>
      <h2><i class="pr-communication-emailenvelope"></i>E-mail</h2>
      <? foreach ($library->emails as $email):?>
        <p><a href="mailto:<?=$email->getEmail()?>"><?=$email->getEmail()?></a> <?=$email->getNote()?></p>
      <? endforeach; ?>
    <? endif; ?>

    <? if ($library->branches!=null):?>
      <h2><i class="pr-interface-househome"></i>Pobočky</h2>
      <table class="table table-striped">
        <? foreach ($library->branches as $branch):?>
          <tr>
            <td><?=$branch->getName()?></td>
            <td><?=$branch->getAddress()?></td>
          </tr>
        <? endforeach; ?>
      </table>
    <? endif; ?>





  </div>
  <div class="col-md-6">
    <style>
      #map {height: 600px;}
    </style>
    <div id="map"></div>

    <script>
      function initMap() {
        var myLatLng = {lat: 49.78, lng: 15.39};

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 7,
          center: myLatLng
        });
        var position = {lat: <?=$library->getLatitude() ?>, lng: <?=$library->getLongitude() ?>};
        var marker = new google.maps.Marker({
          position: position,
          map: map,
          title: 'name of library'
        });
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=<?=$apikey ?>&callback=initMap"
            async defer></script>

  </div>
</div>
