<?
  $title = "Knihovny";
  $this->layout()->title = $title;
  $this->headTitle($title);
  $this->layout()->headerType = "libraries";
  setlocale(LC_NUMERIC, "en_US.utf8");
?>


<h2><?=$this->from?> - <?=$this->to?> z <?=$this->resultsCount?></h2>
<div class='row'>
  <div class="col-md-6 library-list">
    <? foreach ($this->libraries as $library):?>
      <div class="well">
        <a href="/Libraries/Library?sigla=<?=$library->getSigla()?>">
          <h3><?=$library->getName()?></h3>
        </a>
        <p><i class="pr-location-pinmap5"></i><?=$library->getAddress()?></p>
      </div>
    <? endforeach; ?>
    <div class="row">
      <div class="col-md-8" style="text-align: center">
        <ul class="pagination" align="center">
          <? foreach ($this->pagination as $pag):?>
            <li <? if ($pag == $this->page): ?> class="active"<? endif; ?> >
              <a href="/Libraries/List?query=<?=$this->query?>&page=<?=$pag?>">
                <?=$pag?>
              </a>
            </li>
          <? endforeach; ?>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <style>
      #map {height: 600px;}
    </style>
    <div id="map"></div>

    <script>
    function initMap() {
    var myLatLng = {lat: 49.78, lng: 15.39};

    var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 7,
    center: myLatLng
    });
    <? foreach ($this->libraries as $library):?>
      <? if (($library->getLatitude()!=null)||($library->getLongitude()!=null)):?>
        var position = {lat: <?=$library->getLatitude() ?>, lng: <?=$library->getLongitude() ?>};
        var marker = new google.maps.Marker({
        position: position,
        map: map,
        title: '<?=$library->getName() ?>'
        });
      <? endif; ?>
    <? endforeach; ?>
    }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=<?=$apikey ?>&callback=initMap"
            async defer></script>

  </div>
</div>
