<?
  $title = $this->translate('Central Library Portal');
  $this->layout()->title = $title;
  $this->headTitle($title);
  $this->layout()->headerType = "libraries";
  $this->headScript()->appendFile("jquery-ui.min.js");
  $this->headScript()->appendFile("markerclusterer.js");
  setlocale(LC_NUMERIC, "en_US.utf8");
  $this->layout()->query = $this->query;
?>


<h2><?=$this->from?> - <?=$this->to?> z <?=$this->resultsCount?></h2>
<div class='row'>
  <div class="col-md-6 library-list">
    <? foreach ($this->libraries as $library):?>
      <div class="well">
        <h3>
          <a href="/Libraries/Library?sigla=<?=$library->getSigla()?>">
            <?=$library->getName()?>
          </a>
          <? if ($library->getAlternativeNamesFormated()!=null):?>
            <?=$library->getAlternativeNamesFormated()?>
          <? endif; ?>
        </h3>
        <p><i class="pr-location-pinmap5"></i><?=$library->getAddress()?></p>
      </div>
    <? endforeach; ?>
    <div class="row">
      <div class="col-md-8" style="text-align: center">
        <ul class="pagination" align="center">
          <? foreach ($this->pagination as $pag):?>
            <li <? if ($pag == $this->page): ?> class="active"<? endif; ?> >
              <a href="/Libraries/List?query=<?=$this->query?>&page=<?=$pag?>">
                <?=$pag?>
              </a>
            </li>
          <? endforeach; ?>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <style>
      #map {height: 600px;}
      .loader {
        left: 50%;
        transform: translateX(-50%);
        position:absolute;
        top:200px;
        font-size:40px;
      }
      .marker-info {
        min-width:200px;
        padding: 5px;
      }

      .marker-title {
        font-size: 18px;
        color: #333;
      }

      .marker-subtitle {
        font-size: 15px;
        color: #666;
        margin-top: 10px;
        margin-bottom: 5px;
      }
    </style>


    <div class="loader">Map data loading ...</div>
    <div id="map"></div>

    <script>

      function getData() {
        var url = "/Libraries/markersJson?q=<?=$this->query?>";
        $.getJSON(url, function(data) {
          initialize(data);
        });
      }
    function initialize(libraries) {
    var myLatLng = {lat: 49.78, lng: 15.39};
      var markers = [];
      var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 7,
    center: myLatLng
    });
      var bounds = new google.maps.LatLngBounds();
      var infoWindow = new google.maps.InfoWindow();
      var info = [];
      for(var i = 0; i < libraries.length; i++) {
        var library = libraries[i];
        var contentString = '<div id="content" class="marker-info">'+
            '<div class="marker-title">' + library.name + '</div>'+
            '<div class="marker-subtitle">' + library.address + '</div>' +
            '<div class="marker-link"><a href="https://cpk-front.mzk.cz/Libraries/Library?sigla=' + library.sigla +
            '">Detail knihovny</a>' +
            '</div>';
        info.push(contentString);
        var marker = new google.maps.Marker({
          position: new google.maps.LatLng (library.latitude, library.longitude),
          map: map,
          title: library.name
        });
        bounds.extend(marker.getPosition());
        markers.push(marker);
        google.maps.event.addListener(marker, 'click', (function(marker, index) {
          return function() {
            infoWindow.setContent(info[index]);
            infoWindow.open(map, marker);
          }
        })(marker, i));
      }

      var mcOptions = {gridSize: 75, maxZoom: 10, imagePath: "/themes/cpk-devel/images/markerclusterer/m"};
      var mc = new MarkerClusterer(map, markers, mcOptions);
    }

    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=<?=$apikey ?>&callback=getData"
            async defer></script>

  </div>
</div>
