<? if ($this->status['absent_total'] > 0):?>
  <span class="label <?=($this->status['absent_avail'] > 0)? 'label-success' : 'label-danger'?>">
    <?=$this->transEsc("absent")?> :
    <?=$this->escapeHtml($this->status['absent_avail'])?>
    <?=$this->transEsc("of")?>
    <?=$this->escapeHtml($this->status['absent_total'])?>
  </span>
<? endif;?>
<? if ($this->status['present_total'] > 0):?>
  <span class="label <?=($this->status['present_avail'] > 0)? 'label-success' : 'label-danger'?>">
    <?=$this->transEsc("present")?> :
    <?=$this->escapeHtml($this->status['present_avail'])?>
    <?=$this->transEsc("of")?>
    <?=$this->escapeHtml($this->status['present_total'])?>
  </span>
<? endif;?>
<? if ($this->status['present_total'] == 0 && $this->status['absent_total'] == 0):?>
  <span class="label label-default">
    <?=$this->transEsc("no_available_items")?>
  </span>
<? endif;?>