<meta property="og:url"
      content="https://brno.knihovny.cz/" />
<meta property="og:title"
      content="ČístBrno" />
<meta property="og:description"
      content="Knihy brněnských knihoven" />
<meta property="og:image"
      content="https://www.knihovny.cz/themes/bootstrap3/images/screenshot_20171130.png" />
<meta property="og:image:secure_url"
      content="https://www.knihovny.cz/themes/bootstrap3/images/screenshot_20171130.png" />
<meta property="og:image:type"
      content="image/png" />
<meta name="referrer"
      content="unsafe-url" />
<link href="/themes/bootstrap3/images/logos/logo-brno.png" rel="icon" type="image/png">
