<h4><?=$this->transEsc('Similar Items')?></h4>
<? $similarRecords = $this->related->getResults(); ?>
<? if (!empty($similarRecords)): ?>
    <? foreach ($similarRecords as $similarRecordDriver): ?>
    
        <?
          $recordId = $similarRecordDriver->getUniqueID();
          $formats = $similarRecordDriver->getFormats();
          if (empty($lookfor)) {
              $lookfor = $this->record($similarRecordDriver)->getObalkyKnihAdvert('record');
          }
          
          $fromAdvancedSearchIdParam = (isset($_GET['fromAdvancedSearchId']))
          ? '?fromAdvancedSearchId='.htmlspecialchars($_GET['fromAdvancedSearchId'])
          : '';
        ?>
    	<a class="row well similar-item" href='<?=$this->recordLink()->getUrl($similarRecordDriver)?><?=$fromAdvancedSearchIdParam?>' title='<?=$this->escapeHtml($similarRecordDriver->getTitle())?> (<?=$this->translate($formats[0])?>)'>
          	<div class='col-md-3  #cover' id='cover'>
          		<? $recordId =  preg_replace("/\./", "", $recordId)?>
                <? $recordId =  preg_replace("/:/", "", $recordId)?>
          		<div class="coverThumbnail cover_<?=$recordId?>" tabindex='-1'>
                    <? if ($bibinfo = $this->record($similarRecordDriver)->getObalkyKnihJSONV3()): ?>
                        <script type="text/javascript">
                            obalky.display_thumbnail_without_links(".cover_<?=$recordId?>", <?=$bibinfo?>, <?=json_encode($lookfor)?>);
                        </script>
                    <? endif;?>
                    
                    <? if (! empty($formats)): ?>
                        <div class="iconlabel"><i class="fa fa-fw <?=$this->record($similarRecordDriver)->getFormatClass($formats[0])?>"></i></div>
                    <? elseif ($summThumb = $this->record($similarRecordDriver)->getThumbnail('small')): ?>
                        <img class="recordcover" src="<?=$this->escapeHtmlAttr($summThumb)?>" alt="<?=$this->transEsc('Cover Image')?>"/>
                    <? else: ?>
                        <img class="recordcover" src="<?=$this->url('cover-unavailable')?>" alt="<?=$this->transEsc('No Cover Image')?>"/>
                    <? endif; ?>
    
                </div>
          	</div>
          	
          	<div class='col-md-9'>
                <strong><?=$this->escapeHtml($similarRecordDriver->getTitle())?></strong>
                
                <? $pubDates = $similarRecordDriver->getPublicationDates(); if (!empty($pubDates)): ?>
                  <?=$this->escapeHtml($pubDates[0])?>
                <? endif; ?>
                
                <? $author = $similarRecordDriver->getPrimaryAuthor(); if (!empty($author)): ?>
                  <br/><?=$this->escapeHtml($author);?>
                <? endif; ?>
            </div>
      </a>
    <? endforeach; ?>
<? else: ?>
  <p><?=$this->transEsc('Cannot find similar records')?></p>
<? endif; ?>