<?
  $this->headScript()->appendFile('obalkyknih/functions.js');
  $this->headScript()->appendFile('obalkyknih/custom.js');
  $recordId = $this->driver->getUniqueID();
  $backLink = $this->serverUrl($this->recordLink()->getUrl($this->driver));
  $id = $this->driver->getUniqueId();
  $source = $this->driver->getResourceSource();

?>

<div class="row-fluid result<?=$this->driver->supportsAjaxStatus()?' ajaxItem':''?>">
  <input type="hidden" value="<?=$this->escapeHtml($this->driver->getUniqueID())?>" class="hiddenId" />
  <div class="availabilityId hide"><?=$this->escapeHtml($this->driver->getAvailabilityID())?></div>
  <input type="hidden" value="<?=$this->escapeHtml($this->driver->getResourceSource())?>" class="hiddenSource" />

  <div class="span2 text-center">
    <div id="cover_<?=$recordId?>" class="coverThumbnail">
      <? if ($bibinfo = $this->record($this->driver)->getObalkyKnihJSON()): ?>
        <script type="text/javascript">
          $(document).ready(function() {
            obalky.process("obalky_display_thumbnail", "cover_<?=$recordId?>", "<?=$backLink?>", <?=$bibinfo?>);
          });
        </script>
      <? endif;?>
      <img src="<?=$this->imageLink('format/Book.png')?>" />
    </div>
    <? $formats = array_map(array($this, 'transEsc'), $this->driver->getFormats())?>
    <? sort($formats)?>
    <div class="coverFormat"><?=implode(', ', $formats)?></div>
  </div>

  <div class="span7 middle">
    <div>
      <a href="<?=$this->recordLink()->getUrl($this->driver)?>" class="title">
      <?
        $summHighlightedTitle = $this->driver->getHighlightedTitle();
        $summTitle = $this->driver->getTitle();
        if (!empty($summHighlightedTitle)) {
          echo $this->highlight($this->addEllipsis($summHighlightedTitle, $summTitle));
        } else if (!empty($summTitle)) {
          echo $this->escapeHtml($this->truncate($summTitle, 180));
        } else {
          echo $this->transEsc('Title not available');
        }
      ?>
      </a>
    </div>

    <div>
      <? if($this->driver->isCollection()): ?>
        <?=implode('<br>', $this->driver->getSummary()); ?>
      <? else: ?>
        <? $summAuthor = $this->driver->getPrimaryAuthor(); if (!empty($summAuthor)): ?>
        <?=$this->transEsc('by')?>
        <a href="<?=$this->record($this->driver)->getLink('author', $summAuthor)?>"><?
          $summHighlightedAuthor = $this->driver->getHighlightedAuthor();
          echo !empty($summHighlightedAuthor)
              ? $this->highlight($summHighlightedAuthor)
              : $this->escapeHtml($summAuthor);
        ?></a>
        <? endif; ?>

        <? $journalTitle = $this->driver->getContainerTitle(); $summDate = $this->driver->getPublicationDates(); ?>
        <? if (!empty($journalTitle)): ?>
          <?=!empty($summAuthor) ? '<br />' : ''?>
          <?=/* TODO: handle highlighting more elegantly here */ $this->transEsc('Published in') . ' <a href="' . $this->record($this->driver)->getLink('journaltitle', str_replace(array('{{{{START_HILITE}}}}', '{{{{END_HILITE}}}}'), '', $journalTitle)) . '">' . $this->highlight($journalTitle) . '</a>';?>
          <?=!empty($summDate) ? ' (' . $this->escapeHtml($summDate[0]) . ')' : ''?>
        <? elseif (!empty($summDate)): ?>
          <!-- <?=!empty($summAuthor) ? '<br />' : ''?> -->
          <?=!empty($summDate[0]) ? $this->transEsc('Published') . ' ' . $this->escapeHtml($summDate[0]) : ''?>
        <? endif; ?>
        <? $summInCollection = $this->driver->getContainingCollections(); if (!empty($summInCollection)): ?>
          <? foreach ($summInCollection as $collId => $collText): ?>
            <div>
              <b><?=$this->transEsc("in_collection_label")?></b>
              <a class="collectionLinkText" href="<?=$this->url('collection', array('id' => $collId))?>?recordID=<?=urlencode($this->driver->getUniqueID())?>">
                <?=$this->escapeHtml($collText)?>
              </a>
            </div>
          <? endforeach; ?>
        <? endif; ?>
      <? endif; ?>
    </div>

    <div>
      <? if(!$this->driver->isCollection()): ?>
        <? if ($snippet = $this->driver->getHighlightedSnippet()): ?>
          <? if (!empty($snippet['caption'])): ?>
            <strong><?=$this->transEsc($snippet['caption']) ?>:</strong> ';
          <? endif; ?>
          <? if (!empty($snippet['snippet'])): ?>
            <span class="quotestart">&#8220;</span>...<?=$this->highlight($snippet['snippet']) ?>...<span class="quoteend">&#8221;</span><br/>
          <? endif; ?>
         <? endif; ?>
        <br/>
      <? endif; ?>

      
      <? /* We need to find out if we're supposed to display an OpenURL link ($openUrlActive),
            but even if we don't plan to display the link, we still want to get the $openUrl
            value for use in generating a COinS (Z3988) tag -- see bottom of file.
          */
        $openUrl = $this->driver->getOpenURL();
        $openUrlActive = $this->driver->openURLActive('results');
        $urls = $this->record($this->driver)->getLinkDetails();
        if ($openUrlActive || !empty($urls)): ?>
        <? if ($openUrlActive): ?>
          <br/>
          <?=$this->openUrl($openUrl)?>
          <? if ($this->driver->replaceURLsWithOpenURL()) $urls = array(); // clear URL list if replace setting is active ?>
        <? endif; ?>
        <? if (!is_array($urls)) $urls = array();
          if(!$this->driver->isCollection()): ?>
            <br/>
            <? foreach ($urls as $current): ?>
              <a href="<?=$this->escapeHtml($this->proxyUrl($current['url']))?>" class="fulltext" target="new"><i class="icon-external-link"></i> <?=($current['url'] == $current['desc']) ? $this->transEsc('Get full text') : $this->escapeHtml($current['desc'])?></a><br/>
          <? endforeach; ?>
        <? endif; ?>
      <? endif; ?>
      
      <?=$this->record($this->driver)->getPreviews()?>
    </div>
  </div>

  <div class="span2">
    <i class="icon-edit"></i> <a href="<?=$this->url('myresearch-edit')?>?id=<?=urlencode($id)?>&amp;source=<?=urlencode($source)?><? if (!is_null($list_id)):?>&amp;list_id=<?=urlencode($list_id)?><? endif; ?>" class="edit tool"><?=$this->transEsc('Edit')?></a><br/>
    <? /* Use a different delete URL if we're removing from a specific list or the overall favorites: */
      $deleteUrl = is_null($list_id)
          ? $this->url('myresearch-favorites')
          : $this->url('userList', array('id' => $list_id));
      $deleteUrlGet = $deleteUrl . '?delete=' . urlencode($id) . '&amp;source=' . urlencode($source);
    ?>
    <div class="dropdown">
      <i class="icon-trash"></i> <a class="dropdown-toggle" id="dLabel" role="button" data-toggle="dropdown" data-target="#" href="<?=$deleteUrlGet ?>">
        <?=$this->transEsc('Delete') ?>
      </a>
      <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
        <li><a onClick="$.post('<?=$deleteUrl?>', {'delete':'<?=$this->escapeHtml($id) ?>','source':'<?=$this->escapeHtml($source) ?>','confirm':true},function(){location.reload(true)})" title="<?=$this->transEsc('confirm_delete_brief')?>"><?=$this->transEsc('confirm_dialog_yes')?></a></li>
        <li><a><?=$this->transEsc('confirm_dialog_no')?></a></li>
      </ul>
    </div>

  </div>
  <?=$openUrl?'<span class="Z3988" title="'.$this->escapeHtml($openUrl).'"></span>':''?>
</div>

