<?
  // Set page title.
  $this->headTitle($this->translate('Infobox').' | '.$this->translate('Administration'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/Search">' . $this->transEsc('Main page') . '</a></li> ' .
      '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'.
      '<li><a href="/Admin/Home">'.$this->transEsc('Administration').'</a></li>'.
      '<li><a href="/Admin/Widgets">'.$this->transEsc('Widgets').'</a></li>'.
      '<li><a href="/Admin/Infobox">'.$this->transEsc('Infobox').'</a></li>'.
      '<li class="active">'.$this->transEsc('Create item').'</li>';

  $this->layout()->title = $this->translate('Infobox');

  $this->headScript()->appendFile("jquery-ui.min.js");
?>
<div class="row clearfix">
  <ul class="breadcrumb hidden-print"><?=$this->layout()->breadcrumbs ?></ul>

  <div class="col-sm-3">
    <?=$this->render("admin/menu.phtml")?>
  </div>

  <div class="col-sm-9" id='homepage-infobox'>
    <h2><?=$this->translate('Create item')?></h2>
    <div class='well'>
	  <div class='row'>
        <form action='/Admin/Infobox/AddItem' method='post'>
          <input type='hidden' name='userId' value='<?=$this->user['id']?>'>
          <fieldset class="form-group">
            <div class="col-xs-8">
              <label><?=$this->translate('Cs title')?></label>
              <input class='form-control' name='title_cs' type='text' placeholder='<?=$this->translate('Enter title')?>' required>
            </div>
          </fieldset>
          <fieldset class="form-group">
            <div class="col-xs-8">
              <label><?=$this->translate('En title')?></label>
              <input class='form-control' name='title_en' type='text' placeholder='<?=$this->translate('Enter title')?>' required>
            </div>
          </fieldset>
          <fieldset class="form-group">
            <label><?=$this->translate('Cs text')?></label>
            <textarea rows='15' class='form-control' name='text_cs' required></textarea>
          </fieldset>
          <fieldset class="form-group">
            <label><?=$this->translate('En text')?></label>
            <textarea rows='15' class='form-control' name='text_en' required></textarea>
          </fieldset>
          <fieldset class="form-group">
            <label><?=$this->translate('Valid from')?></label>
			<span class="input-group">
			  <span class="input-group-addon"><i class="fa fa-calendar fa-fw"></i></span>
			  <input id='dateFrom' name='date_from' class="form-control" type="text" required>
			</span>
          </fieldset>
          <fieldset class="form-group">
            <label><?=$this->translate('Valid to')?></label>
			<span class="input-group">
			  <span class="input-group-addon"><i class="fa fa-calendar fa-fw"></i></span>
			  <input id='dateTo' name='date_to' class="form-control" type="text" required>
			</span>
          </fieldset>
          <fieldset class="form-group">
            <input type='submit' class='btn btn-lg btn-primary pull-right' value='<?=$this->translate('Save')?>'>
          </fieldset>
        </form>
      </div>
	</div>
  </div>
</div>

<script>

	jQuery( document ).ready( function( $ ) {
		$( '#dateFrom, #dateTo' ).datepicker( {
			changeMonth: true,
			changeYear: true,
			dateFormat: "yy-mm-dd"
		});
	});

</script>