<?
  $facets = $this->recommend->getFacets();
  $results = $this->recommend->getResults();
  $topFacetSettings = array ('cols' => 3);
?>
<? if (isset($facets)): ?>
  <? foreach($facets as $field => $cluster):?>
    <a href='#' onclick="(function(obj){ $('#spec_facet_<?=$this->escapeHtmlAttr($field)?>').show(); $(obj).hide(); return false;})(this)">Limit to <?=$this->transEsc($cluster['label'])?></a>
    <div id="spec_facet_<?=$this->escapeHtmlAttr($field)?>" style="display: none;">
      <strong><?=$this->transEsc($cluster['label'])?></strong>
      <div class="row-fluid top-row">
        <? $iter=1; $corner=$topFacetSettings['rows']*$topFacetSettings['cols']; ?>
        <? foreach($cluster['list'] as $thisFacet): ?>
          <span class="span<?=floor(12/$topFacetSettings['cols'])?>">
            <? if (!$thisFacet['isApplied']): ?>
              <a href="<?=$this->currentPath().$this->recommend->getResults()->getUrlQuery()->addFacet($field, $thisFacet['value'], $thisFacet['operator'])?>">
                <?=$this->escapeHtml($thisFacet['displayText'])?>
              </a>
              (<?=$this->localizedNumber($thisFacet['count']) ?>)
            <? endif; ?>
          </span>
          <? /* Close rows */ ?>
          <? if ($iter%$topFacetSettings['cols'] == 0 && $iter > 0): ?></div><div class="row-fluid top-row<? if(++$row > $topFacetSettings['rows']) echo $moreClass ?>"><? endif; ?>
          <? $iter++; ?>
        <?endforeach;?>
      </div>
    </div>
  <?endforeach;?>
<? endif; ?>