<? if (!isset($this->indexStart)) $this->indexStart = 0; ?>
<? $i = $this->indexStart; foreach ($this->results->getResults() as $current):
  $recordNumber = $this->results->getStartRecord()+$i-$this->indexStart; ?>
  <div id="result<?=$i++ ?>" class="row-fluid clearfix result <?if ($i % 2 == 0) echo 'alt'?>">
    <label class="checkbox pull-left small recordNumber">
      <?=$recordNumber?>.
      <? if ($this->cart()->isActive()): ?>
        <?=$this->record($current)->getCheckbox()?>
      <? endif; ?>
    </label>
    <?=$this->record($current)->getSearchResult('list')?>
  </div>
<? endforeach; ?>