<? $viewList = $this->params->getViewList(); if (count($viewList) > 1): ?>
  <? foreach ($viewList as $viewType => $viewData): ?>
    <? if (!$viewData['selected']): ?>
      <a href="<?=$this->results->getUrlQuery()->setViewParam($viewType)?>"
        title="<?=$this->transEsc('Switch view to')?><?=$this->transEsc($viewData['desc'])?>" class="no-underline" >
    <? endif; ?>
    <img src="<?=$this->imageLink('view_' . $viewType  . '.png') ?>" class="search-view-type"></img>
    <? if (!$viewData['selected']): ?>
      </a>
    <? endif; ?>
  <? endforeach; ?>
<? endif; ?>
 