<?
  // Set page title.
  $this->headTitle($this->translate('Email this Search'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li>' . $this->getLastSearchLink($this->transEsc('Search'), '', '</li> ') .
    '<li class="active">' . $this->transEsc('Email this Search') . '</li>';
?>
<?=$this->flashmessages()?>
<form class="form-horizontal" method="post" id="email-search-results">
  <input type="hidden" name="url" value="<?=$this->escapeHtmlAttr($this->url)?>" />
  <?=$this->flashmessages()?>
    <div class="form-group">
      <label class="control-label" for="email_to"><?=$this->transEsc('Email to')?> <?='('.$this->translate("required").')'?>:</label>
      <input type="email" id="email_to" class="form-control" name="to" placeholder='<?=$this->translate('Enter email')?>' required>
    </div>

    <div class="form-group">
      <label class="control-label" for="email_from"><?=$this->transEsc('From')?> <?='('.$this->translate("required").')'?>:</label>
      <input type="email" id="email_from" name="from" class="form-control" placeholder='<?=$this->translate('Enter email')?>' required>
    </div>

    <div class="form-group">
      <div class="checkbox">
        <label>
          <input type="checkbox" name="ccself"/> <?=$this->translate('send_email_copy_to_me'); ?>
        </label>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label" for="email_message"><?=$this->transEsc('Message')?>:</label>
      <textarea id="email_message" class="form-control" name="message" rows="4"><?=isset($this->message) ? $this->message : ''?></textarea>
    </div>

    <div class="form-group">
      <?=$this->recaptcha()->html($this->useRecaptcha) ?>
    </div>

    <div class="control-group">
      <div class="controls">
        <input class="btn btn-primary pull-right" type="submit" name="submit" value="<?=$this->transEsc('Send Email')?>"/>
        <br><br>
      </div>
    </div>
</form>
<script>
jQuery( document ).ready( function(){
	/* Search email form client-side validation */
	$( '#email-search-results' ).validate({ // initialize the plugin
        rules: {
            from: {
                required: true,
                email: true
            },
            to: {
                required: true,
                email: true
            }
        },
        messages: {
        	from: {
              required: VuFind.translate( 'Enter email' ),
              email: VuFind.translate( 'Wrong email format' )
            },
            to: {
              required: VuFind.translate( 'Enter email' ),
              email: VuFind.translate( 'Wrong email format' )
            }
          }
    });
});
</script>
