<?
  // Set page title.
  $this->headTitle($this->translate('Knihovny.cz'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;
  $this->layout()->frontpage = true;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
  }

  // Load search actions and settings (if any):
  $options = $this->searchOptions($this->searchClassId);
  $basicSearch = $options->getSearchAction();
  $advSearch = $options->getAdvancedSearchAction();

  $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/">' . $this->transEsc('Main page') . '</a></li> ';
?>
<div class="searchHomeContent">
  <? if ($this->ils()->getOfflineMode() == "ils-offline"): ?>
    <div class="alert alert-warning">
      <h2><?=$this->transEsc('ils_offline_title')?></h2>
      <p><strong><?=$this->transEsc('ils_offline_status')?></strong></p>
      <p><?=$this->transEsc('ils_offline_home_message')?></p>
      <? $supportEmail = $this->escapeHtmlAttr($this->systemEmail()); ?>
      <p><a href="mailto:<?=$supportEmail?>"><?=$supportEmail?></a></p>
    </div>
  <? endif; ?>
  <div class="col-md-4">
    <h2><?=$this->transEsc('frontpage-most-wanted')?></h2>
    <div class="white-box" style="height: 600px;">
    </div>
  </div>
  <div class="col-md-4">
    <h2><?=$this->transEsc('frontpage-events')?></h2>
    <div class="white-box" style="height: 600px;">
    </div>
  </div>
  <div class="col-md-4">
    <h2><?=$this->transEsc('frontpage-news')?></h2>
    <div class="white-box" style="height: 600px;">
    </div>
  </div>
</div>
