<?
  // Set page title.
  $this->headTitle($this->translate('Knihovny.cz'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;
  $this->layout()->frontpage = true;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
  }

  // Load search actions and settings (if any):
  $options = $this->searchOptions($this->searchClassId);
  $basicSearch = $options->getSearchAction();
  $advSearch = $options->getAdvancedSearchAction();

  $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/">' . $this->transEsc('Main page') . '</a></li> ';
?>
<div class="searchHomeContent">
  <? if ($this->ils()->getOfflineMode() == "ils-offline"): ?>
    <div class="alert alert-warning">
      <h2><?=$this->transEsc('ils_offline_title')?></h2>
      <p><strong><?=$this->transEsc('ils_offline_status')?></strong></p>
      <p><?=$this->transEsc('ils_offline_home_message')?></p>
      <? $supportEmail = $this->escapeHtmlAttr($this->systemEmail()); ?>
      <p><a href="mailto:<?=$supportEmail?>"><?=$supportEmail?></a></p>
    </div>
  <? endif; ?>
  <div class="col-md-4 most-wanted widget">
    <div class='header'>
      <h2><?=$this->transEsc('frontpage-most-wanted')?></h2>
    </div>
    <div class="list-group">
      <? foreach ($this->mostWanted as $book): ?>
      <a href="/Record/<?=$book['record_id']?>" class="list-group-item clearfix">
        <div class='row'>
          <div class="col-xs-3 ">
			<?
			$recordId =  preg_replace("/\./", "", $book['record_id']);
            $recordId =  preg_replace("/:/", "", $recordId);
            $formats = $book['driver']->getFormats();
            if (empty($lookfor)) {
                $lookfor = $this->record($book['driver'])->getObalkyKnihAdvert('record');
            }
            ?>
                <? if ($bibinfo = $this->record($book['driver'])->getObalkyKnihJSONV3()): ?>
                    <script type="text/javascript">
                        obalky.display_thumbnail_without_links(".cover_<?=$book['record_id']?>", <?=$bibinfo?>, <?=json_encode($lookfor)?>);
                    </script>
                <? endif;?>

                <? if (! empty($formats)): ?>
                    <div class="iconlabel"><i style='font-size: 300%; color: #CCCCCC;' class="pr-format-<?=$this->record($book['driver'])->getFormatClass($formats[0])?>"></i></div>
                <? elseif ($summThumb = $this->record($book['driver'])->getThumbnail('small')): ?>
                    <img class="recordcover" src="<?=$this->escapeHtmlAttr($summThumb)?>" alt="<?=$this->transEsc('Cover Image')?>"/>
                <? else: ?>
                    <img class="recordcover" src="<?=$this->url('cover-unavailable')?>" alt="<?=$this->transEsc('No Cover Image')?>"/>
                <? endif; ?>

          </div>
          <div class="col-xs-9 content">
            <h4 class="list-group-item-heading"><?=$book['title']?></h4>
            <p class="list-group-item-text"><?=$book['author']?></p>
          </div>
        </div>
      </a>
      <? endforeach; ?>
	  <a href='#' class="list-group-item clearfix" title='<?=$this->translate('Show all most wanted')?>'>
	    <div class='row more-info'>
	      <div class='col-sm-10'>
	      	<?=$this->translate('Show all most wanted')?>
	      </div>
	      <div class='col-sm-2' style='text-align: right;'>
		    <i class="pr-interface-arrowright"></i>
	      </div>
	    </div>
	  </a>
    </div>
  </div>
  <div class="col-md-4 events widget">
    <div class='header'>
    	<h2><?=$this->transEsc('frontpage-events')?></h2>
    </div>
    <div class="list-group">
      <div class="list-group-item clearfix">
        <div class='row'>
          <div class="col-xs-9 content">
            <a href="">
              <h4>Autorské čtení Romana Vaňka</h4>
            </a>
            <p class="list-group-item-text">Moravská zemská knihovna v Brně</p>
          </div>
          <div class="number pull-right">
             2.2.
          </div>
        </div>
      </div>
      <div class="list-group-item clearfix">
        <div class='row'>
          <div class="col-xs-9 content">
            <a href="">
              <h4>Autorské čtení Romana Vaňka</h4>
            </a>
            <p class="list-group-item-text">Moravská zemská knihovna v Brně</p>
          </div>
          <div class="number pull-right">
             2.2.
          </div>
        </div>
      </div>
      <div class="list-group-item clearfix">
        <div class='row'>
          <div class="col-xs-9 content">
            <a href="">
              <h4>Autorské čtení Romana Vaňka</h4>
            </a>
            <p class="list-group-item-text">Moravská zemská knihovna v Brně</p>
          </div>
          <div class="number pull-right">
             2.2.
          </div>
        </div>
      </div>
      <div class="list-group-item clearfix">
        <div class='row'>
          <div class="col-xs-9 content">
            <a href="">
              <h4>Autorské čtení Romana Vaňka</h4>
            </a>
            <p class="list-group-item-text">Moravská zemská knihovna v Brně</p>
          </div>
          <div class="number pull-right">
             2.2.
          </div>
        </div>
      </div>
      <div class="list-group-item clearfix">
        <div class='row'>
          <div class="col-xs-9 content">
            <a href="">
              <h4>Autorské čtení Romana Vaňka</h4>
            </a>
            <p class="list-group-item-text">Moravská zemská knihovna v Brně</p>
          </div>
          <div class="number pull-right">
             2.2.
          </div>
        </div>
      </div>

	  <a href='#' class="list-group-item clearfix" title='<?=$this->translate('All planned events')?>'>
	    <div class='row more-info'>
	      <div class='col-sm-10'>
	      	<?=$this->translate('All planned events')?>
	      </div>
	      <div class='col-sm-2' style='text-align: right;'>
		    <i class="pr-interface-arrowright"></i>
	      </div>
	    </div>
	  </a>
    </div>
  </div>
  <div class="col-md-4 infobox widget">
  	<div class='header'>
    	<h2><?=$this->transEsc('frontpage-news')?></h2>
    </div>
    <div class="list-group">
      <div class="list-group-item clearfix">
        <div class='row'>
          <div class="col-xs-12 content">
            <a href=""><h4>Narodil se nový spisovatel</h4></a>
            <span style='color: #777;'>2. 2. 2016</span>
            <p class="list-group-item-text">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</p>
            <div class='pull-right'><a href=""><?=$this->translate('Read more')?></a></div>
          </div>
        </div>
      </div>
      <div class="list-group-item clearfix">
        <div class='row'>
          <div class="col-xs-12 content">
            <a href=""><h4>Narodil se nový spisovatel</h4></a>
            <span style='color: #777;'>2. 2. 2016</span>
            <p class="list-group-item-text">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</p>
            <div class='pull-right'><a href=""><?=$this->translate('Read more')?></a></div>
          </div>
        </div>
      </div>
      <div class="list-group-item clearfix">
        <div class='row'>
          <div class="col-xs-12 content">
            <a href=""><h4>Narodil se nový spisovatel</h4></a>
            <span style='color: #777;'>2. 2. 2016</span>
            <p class="list-group-item-text">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</p>
            <div class='pull-right'><a href=""><?=$this->translate('Read more')?></a></div>
          </div>
        </div>
      </div>

	  <a href='#' class="list-group-item clearfix" title='<?=$this->translate('Older news')?>'>
	    <div class='row more-info'>
	      <div class='col-sm-10'>
	      	<?=$this->translate('Older news')?>
	      </div>
	      <div class='col-sm-2' style='text-align: right;'>
		    <i class="pr-interface-arrowright"></i>
	      </div>
	    </div>
	  </a>
    </div>
  </div>
</div>
