<?
  // Set page title.
  $this->headTitle($this->translate('Knihovny.cz'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;
  $this->layout()->frontpage = true;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
  }

  // Load search actions and settings (if any):
  $options = $this->searchOptions($this->searchClassId);
  $basicSearch = $options->getSearchAction();
  $advSearch = $options->getAdvancedSearchAction();

  $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/">' . $this->transEsc('Main page') . '</a></li> ';
?>
<div class="searchHomeContent">
  <? if ($this->ils()->getOfflineMode() == "ils-offline"): ?>
    <div class="alert alert-warning">
      <h2><?=$this->transEsc('ils_offline_title')?></h2>
      <p><strong><?=$this->transEsc('ils_offline_status')?></strong></p>
      <p><?=$this->transEsc('ils_offline_home_message')?></p>
      <? $supportEmail = $this->escapeHtmlAttr($this->systemEmail()); ?>
      <p><a href="mailto:<?=$supportEmail?>"><?=$supportEmail?></a></p>
    </div>
  <? endif; ?>
  <div class="col-md-4 most-wanted">
    <h2><?=$this->transEsc('frontpage-most-wanted')?></h2>
    <div class="list-group">
      <? foreach ($mostWanted as $book): ?>
      <a href="#" class="list-group-item clearfix">
        <div class='row'>
          <div class="col-xs-3 ">
			<img width="50" align="middle" alt="cover" src="https://cache.obalkyknih.cz/api/cover?multi=%7B%22isbn%22%3A%228071693731%22%2C%22nbn%22%3A%22BOA001-svkos.MVK01000235838%22%7D&type=medium&keywords=(V%C5%A1e%3Aphp)">
          </div>
          <div class="col-xs-9 content">
            <h4 class="list-group-item-heading"><?=$book['name']?></h4>
            <p class="list-group-item-text"><?=$book['author']?></p>
          </div>
        </div>
      </a>
      <? endforeach; ?>

    </div>
  </div>
  <div class="col-md-4">
    <h2><?=$this->transEsc('frontpage-events')?></h2>
    <div class="white-box" style="height: 600px;">
    </div>
  </div>
  <div class="col-md-4">
    <h2><?=$this->transEsc('frontpage-news')?></h2>
    <div class="white-box" style="height: 600px;">
    </div>
  </div>
</div>
