<?
  // Set page title.
  $title = "Inspiration";
  $this->headTitle($this->translate('Inspiration'));
  $this->layout()->title = $title;
  $this->headTitle($title);
  $this->layout()->headerType = "inspiration";

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Conspectus
  $results = $this->results;
  $field = $this->field;
  $facets = $this->facets[$field]['list'];
  $sortedList = $this->sortFacetList($results, $field, $facets, 'search-results');
?>

<!--<div>
  <?/*=$this->render('widgets/'.((in_array($this->widgets['first_inspiration_widget'], ['infobox','favorite_authors','most_wanted'])) ? $this->widgets['first_inspiration_widget'] : 'inspiration-widget').'.phtml', ['inspirationWidget' => $this->inspirationWidget1, 'widgetTitle' => 'inspiration_1'])*/?>
  <?/*=$this->render('widgets/'.((in_array($this->widgets['second_inspiration_widget'], ['infobox','favorite_authors','most_wanted'])) ? $this->widgets['second_inspiration_widget'] : 'inspiration-widget').'.phtml', ['inspirationWidget' => $this->inspirationWidget2, 'widgetTitle' => 'inspiration_2'])*/?>
  <?/*=$this->render('widgets/'.((in_array($this->widgets['third_inspiration_widget'], ['infobox','favorite_authors','most_wanted'])) ? $this->widgets['third_inspiration_widget'] : 'inspiration-widget').'.phtml', ['inspirationWidget' => $this->inspirationWidget3, 'widgetTitle' => 'inspiration_3'])*/?>
  <?/*=$this->render('widgets/'.((in_array($this->widgets['fourth_inspiration_widget'], ['infobox','favorite_authors','most_wanted'])) ? $this->widgets['fourth_inspiration_widget'] : 'inspiration-widget').'.phtml', ['inspirationWidget' => $this->inspirationWidget4, 'widgetTitle' => 'inspiration_4'])*/?>
  <?/*=$this->render('widgets/'.((in_array($this->widgets['fifth_inspiration_widget'], ['infobox','favorite_authors','most_wanted'])) ? $this->widgets['fifth_inspiration_widget'] : 'inspiration-widget').'.phtml', ['inspirationWidget' => $this->inspirationWidget5, 'widgetTitle' => 'inspiration_5'])*/?>
  <?/*=$this->render('widgets/'.((in_array($this->widgets['sixth_inspiration_widget'], ['infobox','favorite_authors','most_wanted'])) ? $this->widgets['sixth_inspiration_widget'] : 'inspiration-widget').'.phtml', ['inspirationWidget' => $this->inspirationWidget6, 'widgetTitle' => 'inspiration_6'])*/?>
</div>-->

<div id='conspectus'>
  <h2><?=$this->transEsc('Conspectus')?></h2>
    <? foreach ($sortedList as $url => $value): ?>
      <div class='category'>
        <a href='#' title='<?=$this->translate('Expand category')?>' class='expand-category'>
          <i class='fa fa-plus'> </i>&nbsp;&nbsp;
        </a>
        <a href="<?=$url?>" title='<?=$this->escapeHtml($value)?>' class='category-text'>
          <?=$this->escapeHtml($value)?>
        </a>
        <div class='expanded-category hidden' style='padding-left: 40px;'></div>
      </div>
    <? endforeach; ?>
</div>

<script>
	jQuery( document ).ready( function( $ ) {

		/* Get conspectus subcategories */
		var data = {};
		$( ".category .category-text" ).each( function( index, element ) {
			data['category'] = $( element ).text();

    		$.ajax({
            	type: 'POST',
            	cache: false,
            	dataType: 'json',
            	url: VuFind.getPath() + '/AJAX/JSON?method=getConspectusSubCategories',
            	data: data,
            	success: function( response ) {

            		if (response.status == 'OK') {

                		var subCategories = response.data.subCategories;
						var html = '';

                		subCategories.forEach( function( item ) {
							html += "<a href='/Search/Results?filter[]=subcategory_str:\""+item+"\"' title='"+item+"'>"+item+"</a><br>";
                    	});

    					//$( element ).parent().find( '.expanded-category' ).html( decodeHtml( subCategories.html ) );
    					$( element ).parent().find( '.expanded-category' ).html( html );

            		} else {
            			console.error(response.data);
                	}

            	},
                error: function ( xmlHttpRequest, status, error ) {
                	console.error(xmlHttpRequest.responseText);
                	console.log(xmlHttpRequest);
                	console.error(status);
                	console.error(error);
                	console.log( 'Sent data: ' );
                	console.log( data );
                },
            });

		});

		/* Expand subcategories on click */
		$( '#conspectus' ).on( 'click', '.expand-category', function( event ){

			event.preventDefault();

			var expandedCategoryElement = $( this ).parent().find( '.expanded-category' );
			if( expandedCategoryElement.hasClass( 'hidden' ) ) {
				expandedCategoryElement.removeClass( 'hidden' );
				expandedCategoryElement.parent().find( 'i.fa' ).removeClass( 'fa-plus' ).addClass( 'fa-minus' );
			} else {
				expandedCategoryElement.addClass( 'hidden' );
				expandedCategoryElement.parent().find( 'i.fa' ).removeClass( 'fa-minus' ).addClass( 'fa-plus' );
			}
		});

	});
</script>
