<?
    // Set default value if necessary:
    if (!isset($this->searchClassId)) {
        $this->searchClassId = 'Solr';
    }

    // Load search actions and settings (if any):
    $options = $this->searchOptions($this->searchClassId);
    $handlers = $this->searchbox()->getHandlers(
        $this->searchClassId,
        isset($this->searchIndex) ? $this->searchIndex : null
    );
    $handlerCount = count($handlers);
    $basicSearch = $this->searchbox()->combinedHandlersActive() ? 'combined-searchbox' : $options->getSearchAction();
    $searchHome = $options->getSearchHomeAction();
    $advSearch = $options->getAdvancedSearchAction();
    $lastSort = $options->getLastSort();
    $lastLimit = $options->getLastLimit();
?>
<? if ($this->searchType == 'advanced'): $query = $this->params->getQuery(); $allGroupsOperator = $query->getOperator(); $groups = -1;?>

	<?  //create JSON from query to pass it later as a param into ajax submit
        $queryArray = [];
        $queryArray['groupsCount'] = count($query->getQueries());
        $queryArray['groupsOperator'] = $allGroupsOperator;
        foreach ($query->getQueries() as $key => $queryGroup) {
            $queryArray['groupsData'][$key]['groupOperator'] = $allGroupsOperator;
            $queryArray['groupsData'][$key]['groupQueriesCount'] = count($queryGroup->getQueries());
            foreach ($queryGroup->getQueries() as $index => $searchQuery) {
                $queryArray['groupsData'][$key]['groupQueries'][$index]['type'][]    = $searchQuery->getHandler();
                $queryArray['groupsData'][$key]['groupQueries'][$index]['lookFor'][] = $searchQuery->getString();
            }
        }
        
        $originalQueryJson = json_encode($queryArray);
    ?>
  <div class="searchForm">
  
    <!-- Display advanced search form with queries -->
    <h2 class="flip legend"><?=$this->transEsc('Advanced Search')?></h2>
    <script>
		var originalQueryJson = '<?=$originalQueryJson?>';
    </script>
    <div class='row'>
      <div class='col-md-12'></div>
        <select id='group-join-type' name="join" class="form-control">
          <option value="AND"<?= ($allGroupsOperator == 'AND') ? 'selected="selected"' : ''?>><?=$this->transEsc("group_AND")?></option>
          <option value="OR"<?= ($allGroupsOperator == 'OR') ? 'selected="selected"' : ''?>><?=$this->transEsc("group_OR")?></option>
        </select>
      </div>
    </div>
    <form id='editable-advanced-search-form' name='searchForm'>
      <? foreach ($query->getQueries() as $queryGroup): $groupOperator = $queryGroup->getOperator(); $groups++; $queries = -1; /* @FIXME: This foreach can be done on $queryArray */?>
      <div class='row group' id='group_<?=$groups?>'>
        <a href="#" class="group-close hidden" title="<?=$this->transEsc("del_search")?>">&times;</a>
        <div class='col-md-2'>
          <label class='dropdown-select-label'>
            <select class="group-operator dropdown-select" name='bool<?=$groups?>[]'>
              <option value="AND"<?= ($groupOperator == 'AND') ? 'selected="selected"' : ''?>><?=$this->transEsc("search_AND")?></option>
              <option value="OR"<?= ($groupOperator == 'OR') ? 'selected="selected"' : ''?>><?=$this->transEsc("search_OR")?></option>
              <option value="NOT"<?= ($groupOperator == 'NOT') ? 'selected="selected"' : ''?>><?=$this->transEsc("search_NOT")?></option>
            </select>
          </label>
        </div>
        <div class='col-md-9'>
          <? foreach ($queryGroup->getQueries() as $query): $queryHandler = $query->getHandler(); $queryString  = $query->getString(); $queries++;?>
          <div class='row queries' id='query_<?=$queries?>'>
            <div class='col-md-4 text-right'>
              <select class='form-control query-type' name='type<?=$groups?>[]'>
                <? foreach ($options->getAdvancedHandlers() as $value => $description): ?>
                <option value="<?=$this->escapeHtml($value)?>"<?= ($value == $queryHandler) ? ' selected="selected"' : ''?>>
                  <?=$this->transEsc($description)?>
                </option>
                <? endforeach; ?>
              </select>
            </div>
            <div class='col-md-7'>
              <input name='lookfor<?=$groups?>[]' type='text' class='form-control query-string' value='<?=$this->escapeHtmlAttr($queryString)?>' placeholder='<?=$this->translate('enter-search-query')?>'>
            </div>
            <div class="col-md-1">
              <a href="#" class='close remove-advanced-search-query'>&times;</a>
            </div>
          </div>
          <? endforeach; ?>
          <p>
            <a href="#" class="add-search-query">
              <i class="fa fa-plus-circle"></i> <?=$this->transEsc("add_search")?>
            </a>
          </p>
        </div>
        <div class="col-md-1 close">
          <a class="help-block remove-advanced-search-group" href="#">&times;</a>
        </div>
      </div>
      <? endforeach; ?>
      <p>
        <a href="#" class="add-search-group">
          <i class="fa fa-plus-circle"></i> <?= $this->transEsc('add_search_group') ?>
        </a>
      </p>
      <div class='row'>
        <div class='col-sm-12 text-right' style='margin-top: 20px;'>
          <input class="btn btn-lg btn-primary pull-right flip advanced-find-button" value="<?=$this->translate('Update results')?>" id='submit-edited-advanced-search' type='submit'>
          <a href='/Search/Advanced' title='<?= $this->transEsc('Start a new Advanced Search')?>'>
            <?= $this->transEsc('Start a new Advanced Search')?>
          </a>
          <a href='/Search/Home' title='<?= $this->transEsc('Start a new Basic Search')?>'>
            <?= $this->transEsc('Start a new Basic Search')?>
          </a>
        </div>
      </div>
      
      <!-- Facets -->
      <div class='hidden' id='hiddenFacetFilters'>
      <? foreach ($filterList as $field => $data): ?>
          <? foreach ($data as $value): ?>
            <input type='hidden' class='hidden-filter' name='filter[]' value='<?=$this->escapeHtmlAttr($field)?>:"<?=$this->escapeHtmlAttr($value)?>"'>
          <? endforeach; ?>
      <? endforeach; ?>
      </div>
      <!-- End of facets -->
      
    </form>
    <!-- End of advanced search form -->
    
    <? $tabs = $this->render('search/searchTabs'); ?>
    <? if (!empty($tabs)): ?><?=$tabs ?><div class="tab-content clearfix"><? endif; ?>    
    <? if (!empty($tabs)): ?></div><? endif; ?>
  </div>
<? else: ?> <!-- Autocomplete -->
  <form class="searchForm navbar-form navbar-left flip" method="get" action="<?=$this->url($basicSearch)?>" name="searchForm" autocomplete="off">
    <?= $this->render('search/searchTabs'); ?>
      <script>
          jQuery(document).ready(function($){
              $("#searchForm_lookfor").keyup(function(){
                  $("#searchclear").toggle(Boolean($(this).val()));
              });
              $("#searchclear").toggle(Boolean($("#searchForm_lookfor").val()));
              $("#searchclear").click(function(){
                  $("#searchForm_lookfor").val('').focus();
                  $(this).hide();
              });

              /* Set autocomplete On page load */
              var query = $( ".search-query" ).val();

              var enabledKeepFacets = $( '.searchFormKeepFilters' ).is(':checked');

              var filters = '';
              
              if (enabledKeepFacets) {
				filters = '';
				$( '.applied-filter' ).each(function(){
				  filters += '&filter[]=' + encodeURIComponent( $( this ).val() );
				});
              } else {
                filters = '';
              }
              $( "#run-autocomplete" ).attr("href", "/Search/Results?lookfor=" + encodeURIComponent( query ) + "&type=AllFields" + filters);

              /* Update autocomplete On some change */
              $( ".search-query" ).on( 'change', function( event ) {
               	query = $( this ).val();

               	enabledKeepFacets = $( '.searchFormKeepFilters' ).is(':checked');
               	
               	if (enabledKeepFacets) {
    			  filters = '';
    			  $( '.applied-filter' ).each(function(){
    				  filters += '&filter[]=' + encodeURIComponent( $( this ).val() );
    			  });
                } else {
                    filters = '';
                }
            	$( "#run-autocomplete" ).attr("href", "/Search/Results?lookfor=" + encodeURIComponent( query ) + "&type=AllFields" + filters);
           	  });

              $( 'body' ).on( 'click', '#run-autocomplete', function( event ) {
            	event.preventDefault();

           		// if autocomplete used in Search/Results, load results async 
  			    if ( ! $( 'header' ).hasClass( 'frontpage' ) ) {
  			      var href = $( '#run-autocomplete' ).attr( 'href' );
  			      ADVSEARCH.updateSearchResults( undefined, {queryString: '?' + href.split( '?' )[1]});
  			      return false;
  				}
  				
  				// if autocomplete used on frontpage, load results statically via PHP
  				$( '.searchForm' ).submit();
              });
          });
      </script>
    <div class="col-xs-12 col-sm-6 search-form-container">
      <input class="form-control search-query<? if($this->searchbox()->autocompleteEnabled($this->searchClassId)):?> autocomplete searcher:<?=$this->escapeHtmlAttr($this->searchClassId) ?><? endif ?>" id="searchForm_lookfor" type="text" name="lookfor" value="<?=$this->escapeHtmlAttr($this->lookfor)?>" autofocus placeholder="<?=$this->translate('autocomplete-placeholder')?>"/>
      <i class="fa fa-times" id="searchclear"></i>
    </div>
      <input type="hidden" name="type" value="<?=$this->escapeHtmlAttr($handlers[0]['value'])?>" />
    <a href='/Search/Results?lookfor=&type=AllFields' id='run-autocomplete' class="btn btn-primary find-button" title='<?=$this->transEsc("Find")?>'><i class="pr-interface-search"></i><span> <?=$this->transEsc("Find")?></span></a>
    <span class="adv_search_links">
        <? if ($advSearch): ?>
          <a href="<?=$this->url($advSearch)?>" class="btn btn-link" rel="nofollow"><?=$this->transEsc("Advanced")?></a>
        <? endif; ?>
    	<? if (isset($_GET['lookfor'])): ?>
          | <a class='btn btn-link' id='edit-as-advanced-search-link' rel="nofollow" href="#"><?=$this->transEsc("Edit as Advanced Search")?></a>
        <? endif; ?>
    </span>
    <? $shards = $options->getShards(); if ($options->showShardCheckboxes() && !empty($shards)): ?>
      <?
      $selectedShards = isset($this->selectedShards)
          ? $this->selectedShards : $options->getDefaultSelectedShards();
      ?>
      <br />
      <? foreach ($shards as $shard => $val): ?>
        <? $isSelected = empty($selectedShards) || in_array($shard, $selectedShards); ?>
          <input type="checkbox" <?=$isSelected ? 'checked="checked" ' : ''?>name="shard[]" value='<?=$this->escapeHtmlAttr($shard)?>' /> <?=$this->transEsc($shard)?>
      <? endforeach; ?>
    <? endif; ?>
    <?
      $filterDetails = $this->searchbox()->getFilterDetails(
          isset($this->filterList) && is_array($this->filterList) ? $this->filterList : array(),
          isset($this->checkboxFilters) && is_array($this->checkboxFilters) ? $this->checkboxFilters : array()
      );
    ?>
    <? if ((isset($hasDefaultsApplied) && $hasDefaultsApplied) || !empty($filterDetails)): ?>
      <? $defaultFilterState = $options->getRetainFilterSetting() ? ' checked="checked"' : ''; ?>
      <div class="checkbox">
        <label>
          <input onChange="$('.applied-filter').click(); $( '.search-query' ).trigger( 'change' );" type="checkbox"<?=$defaultFilterState?> class="searchFormKeepFilters"/>
          <?=$this->transEsc("basic_search_keep_filters")?>
        </label>
      </div>
      <div class="hidden">
        <? foreach ($filterDetails as $current): ?>
          <input class="applied-filter" id="<?=$this->escapeHtmlAttr($current['id'])?>" type="checkbox"<?=$defaultFilterState?> name="filter[]" value="<?=$this->escapeHtmlAttr($current['value'])?>" />
          <label for="<?=$this->escapeHtmlAttr($current['id'])?>"><?=$this->escapeHtml($current['value'])?></label>
        <? endforeach; ?>
        <? if (isset($hasDefaultsApplied) && $hasDefaultsApplied): ?>
          <!-- this is a hidden element that flags whether or not default filters have been applied;
               it is intentionally unlabeled, as users are not meant to manipulate it directly. -->
          <input class="applied-filter" id="dfApplied" type="checkbox" name="dfApplied" value="1"<?=$defaultFilterState?> />
        <? endif; ?>
      </div>
    <? endif; ?>
    <?
      /* Show hidden field for active search class when in combined handler mode. */
      if ($this->searchbox()->combinedHandlersActive()) {
        echo '<input type="hidden" name="activeSearchClassId" value="' . $this->escapeHtmlAttr($this->searchClassId) . '" />';
      }
      /* Load hidden limit preference from Session */
      if (!empty($lastLimit)) {
        echo '<input type="hidden" name="limit" value="' . $this->escapeHtmlAttr($lastLimit) . '" />';
      }
      if (!empty($lastSort)) {
        echo '<input type="hidden" name="sort" value="' . $this->escapeHtmlAttr($lastSort) . '" />';
      }
    ?>
    <!-- Facets for basic search -->
      <div class='hidden' id='hiddenFacetFiltersForBasicSearch'>
      <? foreach ($filterList as $field => $data): ?>
          <? foreach ($data as $value): ?>
            <input type='hidden' class='hidden-filter' name='filter[]' value='<?=$this->escapeHtmlAttr($field)?>:"<?=$this->escapeHtmlAttr($value)?>"'>
          <? endforeach; ?>
      <? endforeach; ?>
      </div>
      <!-- End of facets -->
  </form>
  <script type="text/javascript">$(".searchForm_lookfor:visible").focus()</script>
<? endif; ?>

<div class='hidden'>
  <input type="hidden" name="limit" value="<?= (! empty($_GET['limit']) ? $this->escapeHtmlAttr($_GET['limit']) : $lastLimit) ?>">
  <input type="hidden" name="sort" value="<?= (! empty($_GET['sort']) ? $this->escapeHtmlAttr($_GET['sort']) : $lastSort) ?>">
  <input type="hidden" name="page" value="<?= (! empty($_GET['page']) ? $this->escapeHtmlAttr($_GET['page']) : '1') ?>">
  <!-- Set next lines just for first initial search made by PHP from lookfor. In next searches, JS will take care to put here first value from lookfor0[][0] -->
  <input type="hidden" name="last_searched_lookfor0" value="<?= (! empty($_GET['lookfor']) ? $this->escapeHtmlAttr($_GET['lookfor']) : '') ?>">
  <input type="hidden" name="last_searched_type0" value="<?= (! empty($_GET['type']) ? $this->escapeHtmlAttr($_GET['type']) : 'AllFields') ?>">
</div>
