<?
    // Set default value if necessary:
    if (!isset($this->searchClassId)) {
        $this->searchClassId = 'Solr';
    }

    // Load search actions and settings (if any):
    $options = $this->searchOptions($this->searchClassId);
    $handlers = $this->searchbox()->getHandlers(
        $this->searchClassId,
        isset($this->searchIndex) ? $this->searchIndex : null
    );
    $handlerCount = count($handlers);// @FIXME potrebujeme to?
    $basicSearch = $this->searchbox()->combinedHandlersActive() ? 'combined-searchbox' : $options->getSearchAction();
    $searchHome = $options->getSearchHomeAction(); // @FIXME potrebujeme to?
    $advSearch = $options->getAdvancedSearchAction(); // @FIXME potrebujeme to?
    $lastSort = $options->getLastSort();
    $lastLimit = $options->getLastLimit();
    if(!(isset($filterList) && (is_object($filterList) || is_array($filterList)))) {
        $filterList = [];
    }

    $shards = $options->getShards();

    if (isset($_GET['referer'])) { /* Record view */
        $referer = $_GET['referer'];
        $refererUrl = base64_decode(str_pad(strtr($referer, '-_', '+/'), strlen($referer) % 4, '=', STR_PAD_RIGHT));
        $parts = parse_url($refererUrl);
        parse_str($parts['query'], $filters);

        if (empty($filterList)) {
            foreach ($filters['filter'] as $filter) {
                $key = explode(":", $filter, 2)[0];
                $value = explode(":", $filter, 2)[1];
                if(! array_key_exists($key, $filterList)) {
                    $filterList[$key] = [];
                }
                $filterList[$key][] = trim($value, '"');
            }
        }
    }

    $filterDetails = $this->searchbox()->getFilterDetails(
        isset($this->filterList) && is_array($this->filterList) ? $this->filterList : (! empty($filterList) ? $filterList : array()),
        isset($this->checkboxFilters) && is_array($this->checkboxFilters) ? $this->checkboxFilters : array()
    );

    ?>

<div class='search-panel <?=($this->searchResults) ? 'scrollable-search-panel' : ''?>' style='<?=($this->searchResults) ? 'margin-top: 20px;' : ''?>'>

    <?

    /*
     * Render both searchTypeTemplates (basic, advanced) for future switching
     * when on results page.
     * This solutions prevent switching to re-download the same data from Solr.
     * Otherweise render empty autocomplete
     */

    if ($this->searchResults) {
        /* Render advanced search. Decide whether hidden or not. */
        $arrayOfVariablesForAdvancedSearch = [
            'this' => $this,
            'lastSort' => $lastSort,
            'lastLimit' => $lastLimit,
            'filterList' => $filterList,
            'options' => $options,
            'params' => $this->params,
        ];

        if ($this->searchTypeTemplate != 'advanced') {
            $arrayOfVariablesForAdvancedSearch['hiddenAdvancedSearch'] = true;
        }

        echo $this->context($this)->renderInContext(
            "search/ajax/advanced-search.phtml",
            $arrayOfVariablesForAdvancedSearch
        );
    }

    /* Render basic search. Decide whether hidden or not. */
    $arrayOfVariablesForBasicSearch = [
        'this' => $this,
        'options' => $options,
        'shards' => $shards,
        'basicSearch' => $basicSearch,
        'filterList' => $filterList,
        'handlers' => $handlers,
        'filterDetails' => $filterDetails,
    ];

    if ($this->searchTypeTemplate == 'advanced') {
        $arrayOfVariablesForBasicSearch['hiddenBasicSearch'] = true;
    }

    echo $this->context($this)->renderInContext(
        "search/ajax/autocomplete.phtml",
        $arrayOfVariablesForBasicSearch
    );

?>

</div>

<!-- Facets -->
<div class='hidden'>
    <? if (! empty($filters)): ?>
      <input type="hidden" name="limit" value="<?= (! empty($filters['limit']) ? $this->escapeHtmlAttr($filters['limit']) : $lastLimit) ?>">
      <input type="hidden" name="sort" value="<?= (! empty($filters['sort']) ? $this->escapeHtmlAttr($filters['sort']) : $lastSort) ?>">
      <input type="hidden" name="page" value="<?= (! empty($filters['page']) ? $this->escapeHtmlAttr($filters['page']) : '1') ?>">
      <!-- Set next lines just for first initial search made by PHP from lookfor. In next searches, JS will take care to put here first value from lookfor0[][0] -->
      <input type="hidden" name="last_searched_lookfor0" value="<?= (isset($filters['lookfor0'][0]) ? $this->escapeHtmlAttr($filters['lookfor0'][0]) : '') ?>">
      <input type="hidden" name="last_searched_type0" value="<?= (! empty($filters['type0'][0]) ? $this->escapeHtmlAttr($filters['type0'][0]) : 'AllFields') ?>">
      <input type='hidden' name='keepFacetsEnabled' value='0'>
      <input type="hidden" name="searchTypeTemplate" value="<?= (! empty($filters['searchTypeTemplate']) ? $this->escapeHtmlAttr($filters['searchTypeTemplate']) : '') ?>">
    <? else: /* Search Results page */ ?>
      <input type="hidden" name="limit" value="<?= (! empty($_GET['limit']) ? $this->escapeHtmlAttr($_GET['limit']) : $lastLimit) ?>">
      <input type="hidden" name="sort" value="<?= (! empty($_GET['sort']) ? $this->escapeHtmlAttr($_GET['sort']) : $lastSort) ?>">
      <input type="hidden" name="page" value="<?= (! empty($_GET['page']) ? $this->escapeHtmlAttr($_GET['page']) : '1') ?>">
      <!-- Set next lines just for first initial search made by PHP from lookfor. In next searches, JS will take care to put here first value from lookfor0[][0] -->
      <input type="hidden" name="last_searched_lookfor0" value="<?= (isset($_GET['lookfor']) ? $this->escapeHtmlAttr($_GET['lookfor']) : '') ?>">
      <input type="hidden" name="last_searched_type0" value="<?= (! empty($_GET['type']) ? $this->escapeHtmlAttr($_GET['type']) : 'AllFields') ?>">
      <input type='hidden' name='keepFacetsEnabled' value='0'>
      <input type="hidden" name="searchTypeTemplate" value="<?= (! empty($_GET['searchTypeTemplate']) ? $this->escapeHtmlAttr($_GET['searchTypeTemplate']) : '') ?>">
    <? endif; ?>
</div>

<div class='hidden' id='hiddenFacetFilters'>
<? foreach ($filterList as $field => $data): ?>
  <? foreach ($data as $value): ?>
    <input type='hidden' class='hidden-filter' name='filter[]' value='<?=$this->escapeHtmlAttr($field)?>:"<?=$this->escapeHtmlAttr($value)?>"'>
  <? endforeach; ?>
<? endforeach; ?>
</div>
<!-- End of facets -->
