<?=$this->flashmessages()?>
<form class="form-horizontal" id='email-search-results'>

<div class="form-group">
  <label class="control-label" for="email_to"><?=$this->transEsc('Email to')?> <?='('.$this->translate("required").')'?>:</label>
  <input type="email" id="email_to" class="form-control" name="to" placeholder='<?=$this->translate('Enter email')?>' required>
</div>

<div class="form-group">
  <label class="control-label" for="email_from"><?=$this->transEsc('From')?> <?='('.$this->translate("required").')'?>:</label>
  <input type="email" id="email_from" name="from" class="form-control" placeholder='<?=$this->translate('Enter email')?>' required>
</div>

<div class="form-group">
  <div class="checkbox">
    <label>
      <input type="checkbox" name="ccself"/> <?=$this->translate('send_email_copy_to_me'); ?>
    </label>
  </div>
</div>

<div class="form-group">
  <label class="control-label" for="email_message"><?=$this->transEsc('Message')?>:</label>
  <textarea id="email_message" class="form-control" name="message" rows="4"><?=isset($this->message) ? $this->message : ''?></textarea>
</div>

<div class="form-group">
  <?=$this->recaptcha()->html($this->useRecaptcha) ?>
</div>

<div class="control-group">
  <div class="controls">
    <input class="btn btn-primary pull-right" type="submit" name="submit" value="<?=$this->transEsc('Send Email')?>"/>
    <br><br>
  </div>
</div>

</form>
