<div class="modal fade" id="save-these-institutions-confirmation" tabindex="-1" role="dialog" aria-labelledby="save-these-institutions-confirmation-modal-label" style='margin-top: 150px;'>
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
               <?=$this->translate('Institutions saved')?>
            </div>
        </div>
    </div>
</div>