<?
    // Set page title.
    $this->headTitle($this->translate('Search Home'));

    // Disable top search box -- this page has a special layout.
    $this->layout()->searchbox = false;
    $this->layout()->frontpage = true;

    // Set default value if necessary:
    if (!isset($this->searchClassId)) {
        $this->searchClassId = 'Solr';
    }

    // Load search actions and settings (if any):
    $options = $this->searchOptions($this->searchClassId);
    $basicSearch = $options->getSearchAction();
    $advSearch = $options->getAdvancedSearchAction();
?>
<div class="searchHomeContent">
  <? if ($this->ils()->getOfflineMode() == "ils-offline"): ?>
    <div class="sysInfo">
      <h2><?=$this->transEsc('ils_offline_title')?></h2>
      <p><strong><?=$this->transEsc('ils_offline_status')?></strong></p>
      <p><?=$this->transEsc('ils_offline_home_message')?></p>
      <? $supportEmail = $this->escapeHtml($this->systemEmail()); ?>
      <p><a href="mailto:<?=$supportEmail?>"><?=$supportEmail?></a></p>
    </div>
  <? endif; ?>
  <div class="searchHomeForm col-md-12">
    <div class="text-center frontpage-logo">
      <img src="<?=$this->imageLink('mzk_logo_large.png')?>"></img>
    </div>
    <div class="searchbox-frontpage" role="search">
      <?=$this->render("search/searchbox.phtml")?>
    </div>
  </div>
</div>
