<span class='records-in-libraries-title'>
    <? ($countRecords > 1)
        ? $string = $this->translate('institutions-in-locale')
        : $string = $this->translate('institution-in-locale')
    ?>
    <? $titleHtml = $this->translate('Found in') . " " . $this->countRecords . " " . $string ?>
    <?= $this->help()->getElementHelp('element_help_search_results_found_in', $titleHtml) ?>
</span>

<div class="col-sm-12 dedupInformation">
<?php
	if ($this->countRecords <= 2) {
		$maxInstitutionsShown = 2;
	} else if ($this->countRecords === 3) {
		$maxInstitutionsShown = 3;
	} else if ($this->countRecords >= 4) {
		$maxInstitutionsShown = 2;
	}

	 $i = 0; // Print first $maxInstitutionsShown institutions
	 foreach ($this->recordsInLibraries as $source => $value):
	    $i++;
		$record = $value['id'];
		$recordInLibraryOwnershipClass = is_array($this->myLibs) && in_array($source, $this->myLibs) ? 'my-library-record' : 'other-library-record';

		$recordUrl = $this->recordLink()->getUrl($record).'?referer='.$this->referer;

		$anchor = $this->transEsc('source_' . $source, null, $source);

	?>

    <a href="<?=$recordUrl?>" title="<?=$this->translate('Record in institution') . ' ' . $anchor ?>">
        <div class="row">
            <div class="col-sm-12" style='padding-top: 10px;'>
                <span class="<?=$recordInLibraryOwnershipClass?>"><?=$anchor?></span>
            </div>
        </div>
    </a>

    <? if ($i == $maxInstitutionsShown) break; ?>
<? endforeach; ?>

<? if (count($this->recordsInLibraries) > $maxInstitutionsShown):
	// If there is more institutions than $maxInstitutionsShown, print Dropdown
?>
<div class="records-in-groups-dropdown">
	<div class="btn-group">
        <span type="button" class="show-next-institutions dropdown-toggle" data-toggle="dropdown"><?=$this->translate('Show next institutions')?> <b class="caret"></b></span>
        <ul class="dropdown-menu scrollable-menu" role="menu">
            <?
                $i = 0;
                // print rest of institutions, to dropdown
                foreach ($this->recordsInLibraries as $source => $value):
                $i++;
                if ($i <= $maxInstitutionsShown) continue;
                $record = $value['id'];
                $recordInLibraryOwnershipClass = is_array($this->myLibs) && in_array($source, $this->myLibs) ? 'my-library-record' : 'other-library-record';

                $recordUrl = $this->recordLink()->getUrl($record).'?referer='.$this->referer;

                $anchor = $this->transEsc('source_' . $source, null, $source);

                ?>
				<li>
                    <a href="<?=$recordUrl?>" title="<?=$this->translate('Record in institution') . ' ' . $anchor ?>">
                        <div class="row">
                            <div class="col-sm-12" style='margin-top: -10px;'>
                                <span class="<?=$recordInLibraryOwnershipClass?>"><?=$anchor?></span>
                            </div>
                        </div>
                    </a>
                </li>

            <? endforeach; ?>
        </ul>
    </div>
</div>
<? endif; ?>

</div>
