<?
/**
 * @var \VuFind\RecordTab\DedupedRecords
 */
$dedupedRecords = $this->tabs['DedupedRecords'];
$currentInstitution = $dedupedRecords->get_institution_data($this->driver->getUniqueId());
$institutionList = $dedupedRecords->get_sorted_records_groups();

//if the list is empty
if (!$institutionList){
  return;
}

$internalMultiplicity = $dedupedRecords->get_internal_multiplicity($institutionList, $currentInstitution['id']);

/**
 * @var int $resultCount  Number of records found, to further use in conditionals
 */
$resultCount = count($institutionList);
if ($resultCount > 1){
  ?>
<script>
    $(document).ready(function () {
        $('.dropdown.search-enabled').dropFinder(<?= json_encode($this->translate('Search institution')); ?>);
    });
</script>
<?
}
?>
<div<?= ($resultCount > 1)?' class="dropdown search-enabled"' : ''?>>
  <div class="<?= ($resultCount > 1) ? 'btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" id="records-in-groups-nav' :
    'single-institution' ?>" style="width:100%;">
    <h3 style="margin-top: 5px; margin-bottom: 5px; padding: <?= ($resultCount > 1) ? '0px 0px 20px 0px' : '10px 10px 30px 10px'; ?>;">
      <? if ($currentInstitution['logo']) { ?>
        <img class="hidden-xs" height="20" src="<?= $currentInstitution['logo']; ?>" align="left" style="margin-right: 8px;">
      <? } ?>
      <span>
          <span class="pull-left" style="padding-bottom: 6px;"><?= $this->translate($currentInstitution['source']) ?></span>
          <? if ($resultCount > 1) { ?>
            <i class="pr-interface-arrowbottom4 pull-right" align="right" style="display: block;"></i>
          <? } ?>
        </span>
    </h3>
  </div>

  <? if ($resultCount > 1){ ?>
    <ul class="dropdown-menu" aria-labelledby="records-in-groups-nav" style='width: 100%;'>
      <? foreach ($institutionList as $record){
        $institutionTitle = $this->translate($record['source']);?>
        <li data-search="<?= strtolower($institutionTitle); ?>">
          <a href="<?=$this->url('record', array('id' => $record['id']))?>?referer=<?=$this->referer?>#records-in-groups" title="<?=$institutionTitle?>">
            <div class='record-group-list-item'>

              <? if ($record['logo']) { ?>
                <img class="hidden-xs pull-right" height="16" src="<?= $record['logo']; ?>">
              <? } ?>

              <span class="institution-name"<?=($currentInstitution['id'] == $record['id'])? ' style="font-weight: bold !important;"' : ''?>><?=$institutionTitle?></span>
            </div>
          </a>
        </li>
      <? } ?>
    </ul>
  <? } ?>
</div>

<div>
<? if (count($internalMultiplicity) > 0):?>
  <span>
  <?= $this->translate('The library has another record(s) for this publication'); ?>
  <? foreach ($internalMultiplicity as $key => $recordMultiplicity): ?>
    <?= ($key > 0) ? $this->translate('conjunction_or') : '' ?>
    <a href='/Record/<?= $recordMultiplicity ?>?referer=<?= $this->referer ?>#records-in-groups'
       title='<?= $this->translate($currentInstitution['source']) ?>'>
        <?= $this->translate('here_link') ?>
    </a>
  <? endforeach;?>
  </span>
<? endif;?>
</div>
