<div class="record-toolbar-container">
	<?=$this->record($this->driver)->getToolbar()?>
</div>
<?
    $related = $this->related();
    if (! ($this->driver->getAllSubjectHeadings()
        && $this->driver->getDeduplicatedAuthors()
        && $this->driver->getConspectus())
    ) {
        $list = $related->getList($this->driver, ['filter' => 'qf', 'handlerName' => 'morelikethis']);
    } else {
        $list = $related->getList($this->driver);
    }
    foreach ($list as $current) {
        echo $related->render($current);
    }
?>