<div class="record-toolbar-container">
	<?=$this->record($this->driver)->getToolbar()?>
</div>
<?
    $related = $this->related();
    if (! ($this->driver->getAllSubjectHeadings() && $this->driver->getDeduplicatedAuthors())) {
        $list = $related->getList($this->driver, ['filter' => 'qf']);
    } else {
        $list = $related->getList($this->driver);
    }
    foreach ($list as $current) {
        echo $related->render($current);
    }
?>