<?
  $addThis = $this->addThis();
  if (!empty($addThis)) {
    $this->headScript()->appendFile('https://s7.addthis.com/js/250/addthis_widget.js?pub=' . urlencode($addThis));
  }

  // Set up some variables for convenience:
  $id = $this->driver->getUniqueId();
  $controllerClass = 'controller:' . $this->record($this->driver)->getController();
  $cart = $this->cart();
  $cartId = $this->driver->getResourceSource() . '|' . $id;

  $handleOfflineFavorites = ! $this->isLoggedIn && $this->offlineFavoritesEnabled;

?>
<ul class="list-group record-toolbar">
  <li class="list-group-item">
  <? if ($this->referer): ?>
    <div id='records-switching'>
      <script>
        jQuery( document ).ready( function( $ ) {
          var id = '<?=$id?>';
          var referer = '<?=$this->referer?>';
          var previousRecordText = '<?=$this->translate('Switch to previous record')?>';
          var nextRecordText = '<?=$this->translate('Switch to next record')?>';
          var extraRecords = JSON.parse( localStorage.getItem( referer ) );
          var extraRecordsCount = extraRecords.length;
          var currentPosition = arraySearch( extraRecords, id );
          var html = '';

          if ( extraRecordsCount > 1 ) {

            if ( currentPosition > 0 ) {
              var previousRecord = extraRecords[currentPosition-1];
              html += "<a href='/Record/"+previousRecord+"?referer="+referer+"' title='"+previousRecordText+"'>";
              html += "  <i class='pr-interface-arrowleft2'></i>";
              html += "</a>";
            }

            html += "<span> "+(currentPosition+1)+". <?=$this->translate('record')?></span>";

            if ( currentPosition < extraRecordsCount ) {
              var nextRecord = extraRecords[currentPosition+1];
              html += "<a href='/Record/"+nextRecord+"?referer="+referer+"' title='"+nextRecordText+"'>";
              html += "  <i class='pr-interface-arrowright2'></i>";
              html += "</a>";
            }


            $( '#records-switching' ).append( html );
          }

          function arraySearch( arr, value ) {
            for ( var i=0; i<arr.length; i++ ) {
              if ( arr[i] === value ) {
                return i;
              }
            }
            return false;
          };
        });
      </script>
    </div>
  <? endif; ?>
  </li>
  <li class="list-group-item">
    <a id="mail-record" class="modal-link <?=$controllerClass?>" title="<?=$this->transEsc('Email this')?>" rel="nofollow">
      <? $titleHtml = "<i class=\"pr-communication-emailenvelopemail\"> </i>" . $this->transEsc('Email this') ?>
      <?= $this->help()->getElementHelp('element_help_email_this', $titleHtml) ?>
    </a>
  </li>

  <? $exportFormats = $this->export()->getFormatsForRecord($this->driver); ?>
  <? if(count($exportFormats) > 0): ?>
    <li class="dropdown list-group-item">
      <a class="export-toggle dropdown-toggle" data-toggle="dropdown" href="<?=$this->recordLink()->getActionUrl($this->driver, 'Export')?>" rel="nofollow">
        <? $titleHtml = "<i class=\"pr-web-uploadarrow\"> </i>" . $this->transEsc('Export Record') ?>
        <?= $this->help()->getElementHelp('element_help_export_record', $titleHtml) ?>
      </a>
      <ul class="dropdown-menu record-export" role="menu">
        <li><a href="https://www.citacepro.com/nacist-dokument-sysno/<?=$this->driver->getUniqueID()?>?katalog=cpk" title="CitacePRO" target="_blank">CitacePRO</a></li>
        <? foreach ($exportFormats as $exportFormat): ?>
          <li><a <? if ($this->export()->needsRedirect($exportFormat)): ?>target="<?=$this->escapeHtmlAttr($exportFormat)?>Main" <? endif; ?>href="<?=$this->recordLink()->getActionUrl($this->driver, 'Export')?>?style=<?=$this->escapeHtmlAttr($exportFormat)?>" rel="nofollow"><?=$this->transEsc($this->export()->getLabelForFormat($exportFormat))?></a></li>
        <? endforeach; ?>
      </ul>
    </li>
  <? endif; ?>

  <li class="list-group-item" id='permalinkItem'>
    <a class="modal-link" id='permalinkAnchor' title="<?=$this->translate('Permalink')?>" >
      <i class="pr-web-linkurl"> </i> <?=$this->translate('Permalink')?>
    </a>
  </li>

  <? if ($this->userlist()->getMode() !== 'disabled'): ?>
    <li class="list-group-item">
    	<a id="save-record" class="modal-link <?=$controllerClass?>"

  	     <? if ($handleOfflineFavorites) : ?>
        	href="#" data-ng-controller="RecordFavController as recFavCtrl" data-ng-click="recFavCtrl.addOrRemoveFavorite()"
    	 <? else: ?>
        	href="<?=$this->recordLink()->getActionUrl($this->driver, 'Save')?>"
         <? endif; ?>

    title="<?=$this->transEsc('Add to favorites')?>" rel="nofollow"><i class="pr-interface-favoritestar"> </i><span data-add-remove-record="add"><?=$this->transEsc('Add to favorites')?></span><span data-add-remove-record="rem" hidden ><b><?=$this->transEsc('remove_from_favorites')?></b></span></a></li>
  <? endif; ?>
  <? if(! ($this->driver instanceof CPK\RecordDriver\SolrAuthority)): ?>
  <li class="list-group-item" id='citace-pro'>
    <a class="modal-link disabled-link" title="<?=$this->transEsc('Show citations')?>" ><i class="pr-communication-bubblechattalkconversationline"> </i> <?=$this->transEsc('Show citations')?></a>
    <i id='citation-link-spinner' class="fa fa-spinner fa-spin"></i>
  </li>
  <? endif; ?>
  <li class="list-group-item" id='shareItem'>
    <a class="modal-link" id='shareAnchor' title="<?=$this->translate('Share this')?>" >
      <i class="pr-web-sharenetwork"> </i> <?=$this->translate('Share this')?>
    </a>
  </li>
  <? if (!empty($addThis)): ?>
    <li><a class="addThis addthis_button list-group-item" href="https://www.addthis.com/bookmark.php?v=250&amp;pub=<?=urlencode($addThis)?>"><i class="fa fa-fw fa-bookmark"></i> <?=$this->transEsc('Bookmark')?></a></li>
  <? endif; ?>
  <? if ($cart->isActive()): ?>
    <li id="bookbag-menu"  class="list-group-item">
      <input id="cartId" type="hidden" name="ids[]" value="<?=$this->escapeHtmlAttr($cartId)?>" />
      <a id="cart-add" class="<? if(!$cart->contains($cartId)): ?>correct <? endif ?>hidden" href="#"><i class="fa fa-fw fa-plus"></i> <?=$this->transEsc('Add to Book Bag') ?></a>
      <a id="cart-remove" class="<? if($cart->contains($cartId)): ?>correct <? endif ?>hidden" href="#"><i class="fa fa-fw fa-minus-circle"></i> <?=$this->transEsc('Remove from Book Bag') ?></a>
      <noscript>
        <form method="post" name="addForm" action="<?=$this->url('cart-home')?>">
          <input type="hidden" name="ids[]" value="<?=$this->escapeHtmlAttr($cartId)?>" />
          <? if ($cart->contains($cartId)): ?>
            <input class="btn btn-default" type="submit" name="delete" value="<?=$this->transEsc('Remove from Book Bag')?>"/>
          <? else: ?>
            <input class="btn btn-default" type="submit" name="add" value="<?=$this->transEsc('Add to Book Bag')?>"/>
          <? endif; ?>
        </form>
      </noscript>
    </li>
  <? endif; ?>
</ul>
<script>
jQuery( document ).ready(function( $ ) {
	$( '#citace-pro' ).on('click', '.citations-link', function(){
		$( '#citationsModal' ).modal( 'show' );
	});
	$( '#permalinkItem' ).on('click', '#permalinkAnchor', function(){
		$( '#permalinkModal' ).modal( 'show' );
	});
	$( '.record-toolbar' ).on('click', '#mail-record', function(){
		$( '#mailRecordModal' ).modal( 'show' );
	});
	$( '#shareItem' ).on('click', '#shareAnchor', function(){
		$( '#shareModal' ).modal( 'show' );
	});

});
</script>
