<?php
  $this->headScript()->appendFile('obalkyknih/functions.js');
  $this->headScript()->appendFile('obalkyknih/custom.js');
  $backLink = $this->serverUrl($this->recordLink()->getUrl($this->driver));
?>
<? if ($bibinfo = $this->record($this->driver)->getObalkyKnihJSON()): ?>
    <script type="text/javascript">
      $(document).ready(function() {
        obalky.process("obalky_display_cover", "cover", "<?=$backLink?>", <?=$bibinfo?>);
      });
    </script>
<? endif; ?>
<div class="row">

  <div class="col-md-9">
    <h3><?=$this->escapeHtml($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection())?></h3>

    <? $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $summary[0] : false; ?>
    <? if ($summary): ?>
      <p><?=$this->truncate($summary, 300)?></p>
      <? if(strlen($summary) > 300): ?>
        <p><a href='<?=$this->recordLink()->getTabUrl($this->driver, 'Description')?>#tabnav'><?=$this->transEsc('Full description')?></a></p>
      <? endif; ?>
    <? endif; ?>

    <?/* Display Main Details */?>
    <table class="table table-striped" summary="<?=$this->transEsc('Bibliographic Details')?>">
      <? $journalTitle = $this->driver->getContainerTitle(); if (!empty($journalTitle)): ?>
      <tr>
        <th><?=$this->transEsc('Journal Title')?>:</th>
        <td>
          <a href="<?=$this->record($this->driver)->getLink('journaltitle', $journalTitle)?>"><?=$this->escapeHtml($journalTitle)?></a>
          <? $ref = $this->driver->getContainerReference(); if (!empty($ref)) { echo $this->escapeHtml($ref); } ?>
        </td>
      </tr>
      <? endif; ?>

      <? $nextTitles = $this->driver->getNewerTitles(); $prevTitles = $this->driver->getPreviousTitles(); ?>
      <? if (!empty($nextTitles)): ?>
      <tr>
        <th><?=$this->transEsc('New Title')?>: </th>
        <td>
          <? foreach($nextTitles as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? if (!empty($prevTitles)): ?>
      <tr>
        <th><?=$this->transEsc('Previous Title')?>: </th>
        <td>
          <? foreach($prevTitles as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $authors = $this->driver->getDeduplicatedAuthors(); ?>
      <? if (isset($authors['main']) && !empty($authors['main'])): ?>
      <tr>
        <th><?=$this->transEsc('Main Author')?>: </th>
        <td><a href="<?=$this->record($this->driver)->getLink('author', $authors['main'])?>"><?=$this->escapeHtml($authors['main'])?></a></td>
      </tr>
      <? endif; ?>

      <? if (isset($authors['corporate']) && !empty($authors['corporate'])): ?>
      <tr>
        <th><?=$this->transEsc('Corporate Author')?>: </th>
        <td><a href="<?=$this->record($this->driver)->getLink('author', $authors['corporate'])?>"><?=$this->escapeHtml($authors['corporate'])?></a></td>
      </tr>
      <? endif; ?>

      <? if (isset($authors['secondary']) && !empty($authors['secondary'])): ?>
      <tr>
        <th><?=$this->transEsc('Other Authors')?>: </th>
        <td>
          <? $i = 0; foreach ($authors['secondary'] as $field): ?><?=($i++ == 0)?'':', '?><a href="<?=$this->record($this->driver)->getLink('author', $field)?>"><?=$this->escapeHtml($field)?></a><? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $langs = $this->driver->getLanguages(); if (!empty($langs)): ?>
        <tr>
          <th><?=$this->transEsc('Language')?>: </th>
          <td><? foreach ($langs as $lang): ?><?= $this->transEsc($lang)?><br/><? endforeach; ?></td>
        </tr>
      <? endif; ?>

      <? $publications = $this->driver->getPublicationDetails(); if (!empty($publications)): ?>
      <tr>
        <th><?=$this->transEsc('Published')?>: </th>
        <td>
          <? foreach ($publications as $field): ?>
            <?=$this->escapeHtml($field)?><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $edition = $this->driver->getEdition(); if (!empty($edition)): ?>
      <tr>
        <th><?=$this->transEsc('Edition')?>: </th>
        <td><?=$this->escapeHtml($edition)?></td>
      </tr>
      <? endif; ?>

      <?/* Display series section if at least one series exists. */?>
      <? $series = $this->driver->getSeries(); if (!empty($series)): ?>
      <tr>
        <th><?=$this->transEsc('Series')?>: </th>
        <td>
          <? foreach ($series as $field): ?>
            <?/* Depending on the record driver, $field may either be an array with
               "name" and "number" keys or a flat string containing only the series
               name.  We should account for both cases to maximize compatibility. */?>
            <? if (is_array($field)): ?>
              <? if (!empty($field['name'])): ?>
                <a href="<?=$this->record($this->driver)->getLink('series', $field['name'])?>"><?=$this->escapeHtml($field['name'])?></a>
                <? if (!empty($field['number'])): ?>
                  <?=$this->escapeHtml($field['number'])?>
                <? endif; ?>
                <br/>
              <? endif; ?>
            <? else: ?>
              <a href="<?=$this->record($this->driver)->getLink('series', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
            <? endif; ?>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $subjects = $this->driver->getAllSubjectHeadings(); if (!empty($subjects)): ?>
      <tr>
        <th><?=$this->transEsc('Subjects')?>: </th>
        <td>
          <? foreach ($subjects as $field): ?>
          <div class="subjectLine">
            <? $subject = ''; ?>
            <? if(count($field) == 1) $field = explode('--', $field[0]); ?>
            <? $i = 0; foreach ($field as $subfield): ?>
              <?=($i++ == 0) ? '' : ' &gt; '?>
              <? $subject = trim($subject . ' ' . $subfield); ?>
              <a class="backlink" title="<?=$this->escapeHtml($subject)?>" href="<?=$this->record($this->driver)->getLink('subject', $subject)?>" class="subjectHeading"><?=trim($this->escapeHtml($subfield))?></a>
            <? endforeach; ?>
          </div>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <?
        $openUrl = $this->driver->openURLActive('record') ? $this->driver->getOpenURL() : false;
        // Account for replace_other_urls setting
        $urls = ($openUrl && $this->driver->replaceURLsWithOpenURL()) ? array() : $this->record($this->driver)->getLinkDetails();
      ?>
      <? if (!empty($urls) || $openUrl): ?>
      <tr>
        <th><?=$this->transEsc('Online Access')?>: </th>
        <td>
          <? foreach ($urls as $current): ?>
            <a href="<?=$this->escapeHtml($this->proxyUrl($current['url']))?>"><?=$this->escapeHtml($current['desc'])?></a><br/>
          <? endforeach; ?>
          <? if ($openUrl): ?>
            <?=$this->openUrl($openUrl)?><br/>
          <? endif; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $recordLinks = $this->driver->getAllRecordLinks(); ?>
      <? if(!empty($recordLinks)): ?>
        <tr>
          <th><?=$this->transEsc('Related Items')?></th>
          <td>
            <? foreach ($recordLinks as $recordLink): ?>
              <?=$this->transEsc($recordLink['title'])?>:
              <a href="<?=$this->recordLink()->related($recordLink['link'])?>"><?=$this->escapeHtml($recordLink['value'])?></a><br />
            <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>
      
      <? $physical = $this->driver->getPhysicalDescriptions(); ?>
      <? if (!empty($physical)): ?>
        <tr valign="top">
          <th><?=$this->transEsc('Physical Description')?>: </th>
            <td>
              <? foreach ($physical as $field): ?>
                <?=$this->escapeHtml($field)?><br/>
              <? endforeach; ?>
            </td>
        </tr>
      <? endif; ?>
      
      <? $subscribedYears = $this->driver->getSubscribedYears(); ?>
      <? if ($subscribedYears): ?>
        <tr valign="top">
          <th><?=$this->transEsc('Subscribed years')?>: </th>
            <td>
              <?=$this->escapeHtml($subscribedYears)?><br/>
            </td>
        </tr>
      <? endif; ?>

      <? $subscribedVolumes = $this->driver->getSubscribedVolumes(); ?>
      <? if ($subscribedVolumes): ?>
        <tr valign="top">
          <th><?=$this->transEsc('Subscribed volumes')?>: </th>
            <td>
              <?=$this->escapeHtml($subscribedVolumes)?><br/>
            </td>
        </tr>
      <? endif; ?>

    </table>
    
    <? $eodLink = $this->driver->getEODLink();?>
    <? if ($eodLink != null): ?>
      <table class="eod_link">
        <tr>
          <td>
            <a href="<?=$eodLink?>">
              <img src="<?=$this->imageLink('eod/eod_button_cz.png')?>"
                alt="<?=$this->transEsc('EOD text');?>"/>
            </a>
          </td>
        </tr>
      </table>
    <? endif; ?>
    
    <? $digRequest = $this->driver->isAvailableForDigitalization(); ?>
    <? if ($digRequest): ?>
      <table class="digi_req_link">
        <tr>
          <td>
            <a href="<?=$backLink?>/DigiRequest">
              <img src="<?=$this->imageLink('digitalization_request_button_cz.png')?>"
                alt="<?=$this->transEsc('request_for_digitalization_button_text');?>" />
            </a>
          </td>
        </tr>
      </table>
    <? endif; ?>
    
    <?/* End Main Details */?>
  </div>
  
  <div class="col-md-3 cover">
    <div class="text-center">
      <div id="cover">
        <img src="<?=$this->imageLink('format/Book.png')?>" />
      </div>
      <? $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
        <div class="format">
          <?=$this->record($this->driver)->getFormatList()?>
        </div>
      <? endif; ?>
    
      <? /* Display qrcode if appropriate: */ ?>
      <? $QRCode = $this->record($this->driver)->getQRCode("core"); ?>
      <? if($QRCode): ?>
        <img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtml($QRCode);?>"/>
      <? endif; ?>
    </div>

    <? /* Display the lists that this record is saved to */ ?>
    <div class="savedLists hide alert alert-info" id="savedLists">
      <strong><?=$this->transEsc("Saved in")?>:</strong>
    </div>

    <?=$this->record($this->driver)->getPreviews()?>
  </div>
  
</div>
