<?
  $addThis = $this->addThis();
  if (!empty($addThis)) {
    $this->headScript()->appendFile('https://s7.addthis.com/js/250/addthis_widget.js?pub=' . urlencode($addThis));
  }

  // Set up some variables for convenience:
  $id = $this->driver->getUniqueId();
  $ajaxHref = '/AJAX/JSON?method=getLightbox&submodule=Record&id=' . $id;
  $controllerClass = 'controller:' . $this->record($this->driver)->getController();
  $cart = $this->cart();
  $cartId = $this->driver->getResourceSource() . '|' . $id;
?>
<ul class="list-group">
  <li class="list-group-item">
    <i class="fa fa-x fa-asterisk"></i>
    <a class="modal-link <?=$controllerClass?>" href="<?=$this->url('record-cite', array('id'=>$id)) ?>" title="<?=$this->transEsc('Cite this')?>">
      <?=$this->transEsc('Cite this')?>
    </a>
  </li>
  <? if (count($this->driver->getCitationFormats()) > 0): ?>
  <? endif; ?>
  <li class="list-group-item">
    <i class="fa fa-x fa-envelope"></i>
    <a class="modal-link <?=$controllerClass?>" href="<?=$this->url('record-email', array('id'=>$id)) ?>" title="<?=$this->transEsc('Email this')?>">
      <?=$this->transEsc('Email this')?>
    </a>
  </li>
  
  <? $exportFormats = $this->export()->getFormatsForRecord($this->driver); ?>
  <? if(count($exportFormats) > 0): ?>
    <li class="dropdown list-group-item">
      <i class="fa fa-x fa-list-alt"></i>
      <a class="export-toggle dropdown-toggle" data-toggle="dropdown" href="<?=$this->recordLink()->getActionUrl($this->driver, 'Export')?>"><?=$this->transEsc('Export Record') ?></a>
      <ul class="dropdown-menu" role="menu">
        <? foreach ($exportFormats as $exportFormat): ?>
          <li><a <? if ($this->export()->needsRedirect($exportFormat)): ?>target="<?=$this->escapeHtml($exportFormat)?>Main" <? endif; ?>href="<?=$this->recordLink()->getActionUrl($this->driver, 'Export')?>?style=<?=$this->escapeHtml($exportFormat)?>"><?=$this->transEsc('Export to')?> <?=$this->transEsc($exportFormat)?></a></li>
        <? endforeach; ?>
      </ul>
    </li>
  <? endif; ?>
  
  <li class="list-group-item">
    <i class="fa fa-x fa-plus-sign"></i>
    <a class="modal-link <?=$controllerClass?>" href="<?=$this->recordLink()->getActionUrl($this->driver, 'Save')?>" title="<?=$this->transEsc('Add to favorites')?>">
      <?=$this->transEsc('Add to favorites')?>
    </a>
  </li>
  <? if (!empty($addThis)): ?>
    <li class="list-group-item"><a class="addThis addthis_button" href="https://www.addthis.com/bookmark.php?v=250&amp;pub=<?=urlencode($addThis)?>"><i class="fa fa-x fa-bookmark"></i> <?=$this->transEsc('Bookmark')?></a></li>
  <? endif; ?>
  
  <? if ($cart->isActive()): ?>
    <li id="bookbag-menu" class="list-group-item">
      <input id="cartId" type="hidden" name="ids[]" value="<?=$this->escapeHtml($cartId)?>" />
      <span id="cart-add" class="<? if(!$cart->contains($cartId)): ?>correct <? endif ?>hidden"">
        <i class="fa fa-x fa-plus-sign"></i>
        <a href="#"><?=$this->transEsc('Add to Book Bag') ?></a>
      </span>
      <span id="cart-remove" class="<? if($cart->contains($cartId)): ?>correct <? endif ?>hidden"">
        <i class="fa fa-x fa-minus-sign"></i>
        <a href="#"><?=$this->transEsc('Remove from Book Bag') ?></a>
      </span>
      <noscript>
        <form method="post" name="addForm" action="<?=$this->url('cart-home')?>">
          <input type="hidden" name="ids[]" value="<?=$this->escapeHtml($cartId)?>" />
          <? if ($cart->contains($cartId)): ?>
            <input class="btn btn-default" type="submit" name="delete" value="<?=$this->transEsc('Remove from Book Bag')?>"/>
          <? else: ?>
            <input class="btn btn-default" type="submit" name="add" value="<?=$this->transEsc('Add to Book Bag')?>"/>
          <? endif; ?>
        </form>
      </noscript>
    </li>
  <? endif; ?>
</ul>
