<?
  // Set page title.
  $this->headTitle($this->translate('configurations'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/Search">' . $this->transEsc('Main page') . '</a></li> ' .
      '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'.
      '<li class="active"><a href="/Admin/Configurations">'.$this->transEsc('configurations').'</a></li> ';
  $this->layout()->title = $this->translate('configurations');
  $this->layout()->templateName = 'configurations/main';
?>
<div class="row clearfix">
  <ul class="breadcrumb hidden-print"><?=$this->layout()->breadcrumbs ?></ul>

  <div class="col-sm-3">
    <?=$this->render("admin/menu.phtml")?>
  </div>
  <div class="col-sm-9 well">
    <h2><?=$this->transEsc('configurations')?></h2>
    <?=$this->flashmessages() ?>
    <? foreach($configs as $source => $configs):

        $hasRequested = ! empty($configs['requested']);

        $isAleph = isset($configs['active']['Catalog']['dlfport']);

        $template = $isAleph ? $alephTemplate : $ncipTemplate;

        $defs = $template['Definitions'];
        unset($template['Definitions']);

        $hidden = $defs['hidden'];

        $config = $hasRequested ? $configs['requested'] : $configs['active'];
    ?>
      <div class='well'>
        <form action='/Admin/Configurations' method='POST'>
        <table class="table table-striped col-sm-12">
          <thead>
            <tr><td colspan="2"><h3><?=$this->transEsc('source_' . $source)?><img class="pull-right" src="<?=$this->logos()->getLogo($source) ?>" height="32"></h3></td></tr>
            <? if ($hasRequested): ?>
              <tr><td colspan="2"><div class="alert alert-warning"><?=$this->transEsc('request_config_change_pending') ?></div></td></tr>
            <? endif; ?>
          </thead>
          <tbody>
         <? foreach($template as $section => $keys): if(! empty($keys) && array_search($section, $hidden) === false): ?>
            <tr><td colspan="2"><b>[<?=$section ?>]</b></td></tr>
            <? foreach($keys as $key => $value): if (array_search($section . ':' . $key, $hidden) === false):
                    $isRequired = ! in_array($section . ':' . $key, $defs['optional']);
                    $isCheckbox = $defs[$section][$key] === 'checkbox';?>
            <tr title='<?=($isRequired ? $this->transEsc('This field is required') . ' - ' : '')  . $this->transEsc($value) ?>'>
              <td class="col-sm-3"><?=$key . (($isRequired) ? ' *' : '') ?></td>
              <td class="col-sm-9">
                <input class="form-control"
                	type="<?=$defs[$section][$key] ?>"
                	<? if( $isCheckbox ): ?>
                	  <?=( isset($config[$section][$key]) && $config[$section][$key] ) ? 'checked="checked"' : ''; ?>
                	<? else: ?>
                	  value="<?=isset($config[$section][$key]) ? $config[$section][$key] : ''?>"
                	<? endif; ?>
                	placeholder="<?=$this->transEsc($value)?>"
                	title="<?=$this->transEsc($value)?>"
                	name="<?=$section . '[' . $key . ']' ?>"
                	<?=$isRequired ? 'required' : ''?>/>
              </td>
            </tr>
            <? endif; endforeach; ?>
          <? endif; endforeach; ?>
          </tbody>
        </table>
        <div class="btn-group">
          <input class="btn btn-primary" name="requestChange" type="submit" value="<?=$this->transEsc('submit_changes') ?>"/>
          <? if ($hasRequested): ?>
            <input class="btn btn-primary" name="requestChangeCancel" type="submit" value="<?=$this->transEsc('request_config_change_cancel') ?>" formnovalidate/>
          <? endif; ?>
        </div>
        <input type='hidden' name='source' value='<?=$source ?>'/>
        </form>
      </div>
      <? endforeach; ?>
  </div>
</div>