<?=$this->doctype('HTML5')?>
<html lang="<?=explode("-", $this->layout()->userLang)[0]?>">
  <head>
    <?$this->headThemeResources()?>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
    <?=$this->headMeta()?>
    <?=$this->headTitle()?>
    <?
      // Set up OpenSearch link:
      $this->headLink(
        array(
          'href' => $this->url('search-opensearch') . '?method=describe',
          'type' => 'application/opensearchdescription+xml',
          'title' => $this->transEsc('Library Catalog Search'),
          'rel' => 'search'
        )
      );
    ?>
    <?=$this->headLink()?>
    <?=$this->headStyle()?>
    <?
      // Set global path for Javascript code:
      $this->headScript()->prependScript("path = '" . rtrim($this->url('home'), '/') . "';");

      // Deal with cart stuff:
      if (!isset($this->renderingError)) {
        $cart = $this->cart();
        $this->jsTranslations()->addStrings(
          array(
            'bulk_email_success' => 'bulk_email_success',
            'bulk_save_success' => 'bulk_save_success',
            'close' => 'close',
            'loading' => 'Loading',
            'sms_success' => 'sms_success',
            'number_thousands_separator' => ['number_thousands_separator', null, ',']
          )
        );
        if ($cart->isActive()) {
          $this->headScript()->appendFile("vendor/cookies.js");
          $this->headScript()->appendFile("cart.js");
          $domain = $cart->getCookieDomain();
          $this->headScript()->appendScript(
            'var cartCookieDomain = ' . (!empty($domain) ? "'$domain'" : 'false') . ';'
          );
          $this->jsTranslations()->addStrings(
            array(
              'bulk_noitems_advice' => 'bulk_noitems_advice',
              'confirmDelete' => 'confirm_delete',
              'confirmEmpty' => 'bookbag_confirm_empty',
              'viewBookBag' => 'View Book Bag',
              'addBookBag' => 'Add to Book Bag',
              'removeBookBag' => 'Remove from Book Bag',
              'itemsAddBag' => 'items_added_to_bookbag',
              'itemsInBag' => 'items_already_in_bookbag',
              'bookbagMax' => $cart->getMaxSize(),
              'bookbagFull' => 'bookbag_full_msg',
              'bookbagStatusFull' => 'bookbag_full',
              'no_tags' => 'No Tags'
            )
          );
        }
        $this->headScript()->appendScript($this->jsTranslations()->getScript());
        $this->headScript()->appendScript(
          'var userIsLoggedIn = ' . ($this->auth()->isLoggedIn() ? 'true' : 'false') . ';'
        );
      }

      // Session keep-alive
      if ($this->KeepAlive()) {
          $this->headScript()->appendScript('var keepAliveInterval = '
            . $this->KeepAlive());
          $this->headScript()->appendFile("keep_alive.js");
      }

        /*
        * This handles PerunShibboleth's Assertions returned by Shibboleth SP to easily detect returned attributes
        * This part checks if ShibAssertion export is enabled if [Shibboleth] config section & if it is, it gets those assertions
        */
        $authManager = $this->auth()->getManager();
        $assertionExportEnabled = false;
        $isActiveShibbolethIdentityManager = false;
        if ($authManager instanceof \CPK\Auth\Manager) {
            if ($authManager->getAuthMethod() === "PerunShibboleth") {
                $authMethod = $authManager->getAuthInstance("PerunShibboleth");

            } elseif($authManager->getAuthMethod() === "ShibbolethIdentityManager") {
                $authMethod = $authManager->getAuthInstance("ShibbolethIdentityManager");
            }

            if ($authMethod && $authMethod->isShibAssertionExportEnabled()) {
                $assertions = $authMethod->getShibAssertions();

                if (!empty($assertions)) {
                    $assertionExportEnabled = true;
                }
            }
        }

      ?>

    <?=$this->headScript()?>
  </head>
  <body>
    <?=$this->render('cookies-agreement.phtml')?>
    <?=$this->render('info.phtml')?>
    <? // Set up the search box -- there are three possible cases:
      // 1. No search box was set; we should default to the normal box
      // 2. It was set to false; we should display nothing
      // 3. It is set to a custom string; we should display the provided version
      // Set up default search box if no data was provided from the template;
      // this covers case 1.  Cases 2 and 3 are then covered by logic below.
      if (!isset($this->layout()->searchbox)) {
        $this->layout()->searchbox = $this->render('search/searchbox.phtml');
      }
    ?>
    <header role="banner" class="hidden-print">
      <div class="container navbar navbar-inverse">
        <a class="sr-only" href="#content"><?=$this->transEsc('Skip to content') ?></a>
        <?=$this->render('header.phtml')?>
      </div>
      <div class="container">
          <? if ($this->layout()->searchbox !== false): ?>
          <div class="well clearfix">
          <?=$this->layout()->searchbox ?>

                <?
                /*
                * This handles PerunShibboleth's Assertions returned by Shibboleth SP to easily detect returned attributes
                * This part creates button to show/hide division containing messages, which is created later
                */
                if($assertionExportEnabled): ?>
                    <button id="shibAssertionHandler" class="btn btn-link" style="float: right" onclick="handleShibAssertion()" >Show Shib Assertions</button>
                    <script type="text/javascript">
                    function handleShibAssertion() {
                         var __display = document.getElementById('shibAssertionExport').style.display;
                         if (__display == 'block') {
                            document.getElementById("shibAssertionHandler").innerHTML = "Show Shib Assertions";
                            document.getElementById('shibAssertionExport').style.display = 'none';
                         } else {
                            document.getElementById("shibAssertionHandler").innerHTML = "Hide Shib Assertions";
                            document.getElementById('shibAssertionExport').style.display = 'block';
                         }
                    }
                    </script>
                <? endif; ?>

          </div>
          <? endif; ?>
      </div>

        <?
        /*
        * This handles PerunShibboleth's Assertions returned by Shibboleth SP to easily detect returned attributes
        * This part echoes messages to separate division to have it beautiful.
        */
        if($assertionExportEnabled): ?>
            <div class="container" id="shibAssertionExport" style="display: none"><div class="well clearfix">
            <? for($i = 0; $i < sizeof($assertions);) {
                $assertion = htmlentities($assertions[$i]);

                // Create new-lines between "><" char pairs
                $assertion = str_replace("&gt;&lt;", "&gt;<br />&lt;", $assertion);

                // Render it
                ?><h3>Assertion number <?=++$i?></h3><?=$assertion ?><?
            } ?>
            </div></div>
        <? endif; ?>

    </header>
    <div role="main" class="main template-dir-<?=$this->templateDir?> template-name-<?=$this->templateName?>">
      <div class="container">
        <?=$this->layout()->content ?>
      </div>
    </div>
    <footer role="contentinfo" class="hidden-print">
      <div class="container">
        <?=$this->render('footer.phtml')?>
        <?=$this->layout()->poweredBy ?>
      </div>
    </footer>
    <!-- MODAL IN CASE WE NEED ONE -->
    <div id="modal" class="modal fade hidden-print" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 id="modalTitle" class="modal-title"></h4>
          </div>
          <div class="modal-body"><?=$this->transEsc('Loading') ?>...</div>
        </div>
      </div>
    </div>
    <?=$this->googleanalytics()?>
    <?=$this->piwik()?>
  </body>
</html>
