<?
    // Get source of the record to print it to h3 header
    $id = $this->driver->getUniqueID();
    $source = explode(".", $id)[0];
?>

<? if ($bibinfo = $this->record($this->driver)->getObalkyKnihJSONV3()): ?>

<? endif; ?>
<?= $this->render('RecordDriver/SolrDefault/records-in-groups.phtml'); ?>

<div class="well">
<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <div class="col-sm-3">
    <div class="text-center #cover" id="cover">
        <img src="<?=$this->url('cover-unavailable')?>" class="recordcover" alt="<?=$this->transEsc('No Cover Image')?>"/>
        <script type="text/javascript">
            obalky.display_cover("#cover", <?=$bibinfo?>, <?=json_encode($this->record($this->driver)->getObalkyKnihAdvert("record"))?>);
        </script>
        <? /* Display qrcode if appropriate: */ ?>
      <? $QRCode = $this->record($this->driver)->getQRCode("core"); ?>
      <? if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <? endif; ?>
    </div>

    <? // if you have a preview tab but want to move or remove the preview link
       // from this area of the record view, this can be split into
       // getPreviewData() (should stay here) and
       // getPreviewLink() (can go in your desired tab) ?>
    <?=$this->record($this->driver)->getPreviews()?>
  </div>

  <div class="col-sm-9">
    <h3 property="name"><?=$this->escapeHtml($this->driver->getTitle())?></h3>

    <? $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $this->escapeHtml($summary[0]) : false; ?>
    <? if ($summary): ?>
      <p><?=$this->truncate($summary, 300)?></p>

      <? if(strlen($summary) > 300): ?>
        <p><a href='<?=$this->recordLink()->getTabUrl($this->driver, 'Description')?>#tabnav'><?=$this->transEsc('Full description')?></a></p>
      <? endif; ?>
    <? endif; ?>

    <? if ($this->userlist()->getMode() !== 'disabled'): ?>
      <? /* Display the lists that this record is saved to */ ?>
      <div class="savedLists hidden alert alert-info" id="savedLists">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <? endif; ?>

    <?/* Display Main Details */?>
    <table class="table" summary="<?=$this->transEsc('Bibliographic Details')?>">
      <? $journalTitle = $this->driver->getContainerTitle(); if (!empty($journalTitle)): ?>
      <tr>
        <th><?=$this->transEsc('Published in')?>:</th>
        <td>
          <? $containerID = $this->driver->getContainerRecordID(); ?>
          <a href="<?=($containerID ? $this->recordLink()->getUrl("VuFind|$containerID") : $this->record($this->driver)->getLink('journaltitle', $journalTitle))?>"><?=$this->escapeHtml($journalTitle)?></a>
          <? $ref = $this->driver->getContainerReference(); if (!empty($ref)) { echo $this->escapeHtml($ref); } ?>
        </td>
      </tr>
      <? endif; ?>

      <? $nextTitles = $this->driver->getNewerTitles(); $prevTitles = $this->driver->getPreviousTitles(); ?>
      <? if (!empty($nextTitles)): ?>
      <tr>
        <th><?=$this->transEsc('New Title')?>: </th>
        <td>
          <? foreach($nextTitles as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? if (!empty($prevTitles)): ?>
      <tr>
        <th><?=$this->transEsc('Previous Title')?>: </th>
        <td>
          <? foreach($prevTitles as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $authors = $this->driver->getDeduplicatedAuthors(); ?>
      <? if (isset($authors['main']) && !empty($authors['main'])): ?>
      <tr>
        <th><?=$this->transEsc('Main Author')?>: </th>
        <td property="author"><a href="<?=$this->record($this->driver)->getLink('author', $authors['main'])?>"><?=$this->escapeHtml($authors['main'])?></a></td>
      </tr>
      <? endif; ?>

      <? if (isset($authors['corporate']) && !empty($authors['corporate'])): ?>
      <tr>
        <th><?=$this->transEsc('Corporate Author')?>: </th>
        <td property="creator"><a href="<?=$this->record($this->driver)->getLink('author', $authors['corporate'])?>"><?=$this->escapeHtml($authors['corporate'])?></a></td>
      </tr>
      <? endif; ?>

      <? if (isset($authors['secondary']) && !empty($authors['secondary'])): ?>
      <tr>
        <th><?=$this->transEsc('Other Authors')?>: </th>
        <td>
          <? $i = 0; foreach ($authors['secondary'] as $field): ?><?=($i++ == 0)?'':', '?><span property="contributor"><a href="<?=$this->record($this->driver)->getLink('author', $field)?>"><?=$this->escapeHtml($field)?></a></span><? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
        <tr>
          <th><?=$this->transEsc('Format')?>: </th>
          <td><?=$this->record($this->driver)->getFormatList()?></td>
        </tr>
      <? endif; ?>
      
      <? if (! empty($this->sourceDocument['t'])) {
	  
	      	echo "<tr><th>".$this->transEsc('Source document')."</th>";
	      
		      if (! empty($this->sourceDocument['t'])) {
		      	$anchor = join(" ", $this->sourceDocument);
		      	
		      	if (! empty($this->sourceDocument['x'])) {
		      		$sourceDocumentLink = '/Search/Results?join=AND&bool0[]=AND&lookfor0[]="'.$this->sourceDocument['x'].'"&type0[]=isn&bool1[]=NOT&lookfor1[]="'.$id.'"&type1[]=id&sort=title&view=list';
		      	} elseif (! empty($this->sourceDocument['z'])) {
		      		$sourceDocumentLink = '/Search/Results?join=AND&bool0[]=AND&lookfor0[]="'.$this->sourceDocument['z'].'"&type0[]=isn&bool1[]=NOT&lookfor1[]="'.$id.'"&type1[]=id&sort=title&view=list';
		      	} else {
		      		$sourceDocumentLink = '/Search/Results?join=AND&bool0[]=AND&lookfor0[]="'.$this->sourceDocument['t'].'"&type0[]=isn&bool1[]=NOT&lookfor1[]="'.$id.'"&type1[]=id&sort=title&view=list';
		      	}
		      	
		      	echo "<td><a href='".$sourceDocumentLink."' title='".$anchor."'>".$anchor."</a></td>";
		      } else {
		      	echo "<td>".$anchor."</td>";
		      }
	      	echo "</tr>";
      	
      	}
      ?>
      
      <? if ( ! empty($this->field770['t'])  || ! empty($this->field770['g']) ) {
	  
	      	echo "<tr><th>".$this->transEsc('Special print')."</th>";
	      
	      	$anchor = $this->field770['t'].$this->field770['g'];
	      	
		      if (! empty($this->field770['x']) || ! empty($this->field770['z']) || ! empty($this->field770['t'])) {
		      	
		      	if (! empty($this->field770['x'])) {
		      		$link = '/Search/Results?join=AND&bool0[]=AND&lookfor0[]="'.$this->field770['x'].'"&type0[]=isn&bool1[]=NOT&lookfor1[]="'.$id.'"&type1[]=id&sort=title&view=list';
		      	} else if (! empty($this->field770['z'])) {
		      		$link = '/Search/Results?join=AND&bool0[]=AND&lookfor0[]="'.$this->field770['z'].'"&type0[]=isn&bool1[]=NOT&lookfor1[]="'.$id.'"&type1[]=id&sort=title&view=list';
		      	} else if (! empty($this->field770['t'])) {
		      		$link = '/Search/Results?join=AND&bool0[]=AND&lookfor0[]="'.$this->field770['t'].'"&type0[]=AllFields&bool1[]=NOT&lookfor1[]="'.$id.'"&type1[]=id&sort=title&view=list';
		      	}
		      	
		      	echo "<td><a href='".$link."' title='".$anchor."'>".$anchor."</a></td>";
		      } else {
		      	echo "<td>".$anchor."</td>";
		      }
	      	echo "</tr>";
      	
      	}
      ?>
      
      <? if ( ! empty($this->field772['t'])  || ! empty($this->field772['g']) ) {
	  
	      	echo "<tr><th>".$this->transEsc('Special print to')."</th>";
	      
	      	$anchor = $this->field772['t'].$this->field772['g'];
	      	
		      if (! empty($this->field772['x']) || ! empty($this->field772['z']) || ! empty($this->field772['t'])) {
		      	
		      	if (! empty($this->field772['x'])) {
		      		$link = '/Search/Results?join=AND&bool0[]=AND&lookfor0[]="'.$this->field772['x'].'"&type0[]=isn&bool1[]=NOT&lookfor1[]="'.$id.'"&type1[]=id&sort=title&view=list';
		      	} else if (! empty($this->field772['z'])) {
		      		$link = '/Search/Results?join=AND&bool0[]=AND&lookfor0[]="'.$this->field772['z'].'"&type0[]=isn&bool1[]=NOT&lookfor1[]="'.$id.'"&type1[]=id&sort=title&view=list';
		      	} else if (! empty($this->field772['t'])) {
		      		$link = '/Search/Results?join=AND&bool0[]=AND&lookfor0[]="'.$this->field772['t'].'"&type0[]=AllFields&bool1[]=NOT&lookfor1[]="'.$id.'"&type1[]=id&sort=title&view=list';
		      	}
		      	
		      	echo "<td><a href='".$link."' title='".$anchor."'>".$anchor."</a></td>";
		      } else {
		      	echo "<td>".$anchor."</td>";
		      }
	      	echo "</tr>";
      	
      	}
      ?>
      
      <? if ( ! empty($this->field777['t'])  || ! empty($this->field777['g']) ) {
	  
	      	echo "<tr><th>".$this->transEsc('Distributed with')."</th>";
	      
	      	$anchor = $this->field777['t'].$this->field777['g'];
	      	
		      if (! empty($this->field777['x']) || ! empty($this->field777['z']) || ! empty($this->field777['t'])) {
		      	
		      	if (! empty($this->field777['x'])) {
		      		$link = '/Search/Results?join=AND&bool0[]=AND&lookfor0[]="'.$this->field777['x'].'"&type0[]=isn&bool1[]=NOT&lookfor1[]="'.$id.'"&type1[]=id&sort=title&view=list';
		      	} else if (! empty($this->field777['z'])) {
		      		$link = '/Search/Results?join=AND&bool0[]=AND&lookfor0[]="'.$this->field777['z'].'"&type0[]=isn&bool1[]=NOT&lookfor1[]="'.$id.'"&type1[]=id&sort=title&view=list';
		      	} else if (! empty($this->field777['t'])) {
		      		$link = '/Search/Results?join=AND&bool0[]=AND&lookfor0[]="'.$this->field777['t'].'"&type0[]=AllFields&bool1[]=NOT&lookfor1[]="'.$id.'"&type1[]=id&sort=title&view=list';
		      	}
		      	
		      	echo "<td><a href='".$link."' title='".$anchor."'>".$anchor."</a></td>";
		      } else {
		      	echo "<td>".$anchor."</td>";
		      }
	      	echo "</tr>";
      	
      	}
      ?>
      
      <? if ( ! empty($this->field780['t'])  || ! empty($this->field780['g']) ) {
	  
	      	echo "<tr><th>".$this->transEsc('Before like')."</th>";
	      
	      	$anchor = $this->field780['t'].$this->field780['g'];
	      	
		      if (! empty($this->field780['x']) || ! empty($this->field780['z']) || ! empty($this->field780['t'])) {
		      	
		      	if (! empty($this->field780['x'])) {
		      		$link = '/Search/Results?join=AND&bool0[]=AND&lookfor0[]="'.$this->field780['x'].'"&type0[]=isn&bool1[]=NOT&lookfor1[]="'.$id.'"&type1[]=id&sort=title&view=list';
		      	} else if (! empty($this->field780['z'])) {
		      		$link = '/Search/Results?join=AND&bool0[]=AND&lookfor0[]="'.$this->field780['z'].'"&type0[]=isn&bool1[]=NOT&lookfor1[]="'.$id.'"&type1[]=id&sort=title&view=list';
		      	} else if (! empty($this->field780['t'])) {
		      		$link = '/Search/Results?join=AND&bool0[]=AND&lookfor0[]="'.$this->field780['t'].'"&type0[]=AllFields&bool1[]=NOT&lookfor1[]="'.$id.'"&type1[]=id&sort=title&view=list';
		      	}
		      	
		      	echo "<td><a href='".$link."' title='".$anchor."'>".$anchor."</a></td>";
		      } else {
		      	echo "<td>".$anchor."</td>";
		      }
	      	echo "</tr>";
      	
      	}
      ?>
      
      <? if ( ! empty($this->field785['t'])  || ! empty($this->field785['g']) ) {
	  
	      	echo "<tr><th>".$this->transEsc('Then like')."</th>";
	      
	      	$anchor = $this->field785['t'].$this->field785['g'];
	      	
		      if (! empty($this->field785['x']) || ! empty($this->field785['z']) || ! empty($this->field785['t'])) {
		      	
		      	if (! empty($this->field785['x'])) {
		      		$link = '/Search/Results?join=AND&bool0[]=AND&lookfor0[]="'.$this->field785['x'].'"&type0[]=isn&bool1[]=NOT&lookfor1[]="'.$id.'"&type1[]=id&sort=title&view=list';
		      	} else if (! empty($this->field785['z'])) {
		      		$link = '/Search/Results?join=AND&bool0[]=AND&lookfor0[]="'.$this->field785['z'].'"&type0[]=isn&bool1[]=NOT&lookfor1[]="'.$id.'"&type1[]=id&sort=title&view=list';
		      	} else if (! empty($this->field785['t'])) {
		      		$link = '/Search/Results?join=AND&bool0[]=AND&lookfor0[]="'.$this->field785['t'].'"&type0[]=AllFields&bool1[]=NOT&lookfor1[]="'.$id.'"&type1[]=id&sort=title&view=list';
		      	}
		      	
		      	echo "<td><a href='".$link."' title='".$anchor."'>".$anchor."</a></td>";
		      } else {
		      	echo "<td>".$anchor."</td>";
		      }
	      	echo "</tr>";
      	
      	}
      ?>

      <? $langs = $this->driver->getLanguages(); if (!empty($langs)): ?>
        <tr>
          <th><?=$this->transEsc('Language')?>: </th>
          <td><? foreach ($langs as $lang): ?><?= $this->escapeHtml($lang)?><br/><? endforeach; ?></td>
        </tr>
      <? endif; ?>

      <? $publications = $this->driver->getPublicationDetails(); if (!empty($publications)): ?>
      <tr>
        <th><?=$this->transEsc('Published')?>: </th>
        <td>
          <? foreach ($publications as $field): ?>
            <span property="publisher" typeof="Organization">
            <? $pubPlace = $field->getPlace(); if (!empty($pubPlace)): ?>
              <span property="location"><?=$this->escapeHtml($pubPlace)?></span>
            <? endif; ?>
            <? $pubName = $field->getName(); if (!empty($pubName)): ?>
              <span property="name"><?=$this->escapeHtml($pubName)?></span>
            <? endif; ?>
            </span>
            <? $pubDate = $field->getDate(); if (!empty($pubDate)): ?>
              <span property="publicationDate"><?=$this->escapeHtml($pubDate)?></span>
            <? endif; ?>
            <br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $edition = $this->driver->getEdition(); if (!empty($edition)): ?>
      <tr>
        <th><?=$this->transEsc('Edition')?>: </th>
        <td property="bookEdition"><?=$this->escapeHtml($edition)?></td>
      </tr>
      <? endif; ?>

      <?/* Display series section if at least one series exists. */?>
      <? $series = $this->driver->getSeries(); if (!empty($series)): ?>
      <tr>
        <th><?=$this->transEsc('Series')?>: </th>
        <td>
          <? foreach ($series as $field): ?>
            <?/* Depending on the record driver, $field may either be an array with
               "name" and "number" keys or a flat string containing only the series
               name.  We should account for both cases to maximize compatibility. */?>
            <? if (is_array($field)): ?>
              <? if (!empty($field['name'])): ?>
                <a href="<?=$this->record($this->driver)->getLink('series', $field['name'])?>"><?=$this->escapeHtml($field['name'])?></a>
                <? if (!empty($field['number'])): ?>
                  <?=$this->escapeHtml($field['number'])?>
                <? endif; ?>
                <br/>
              <? endif; ?>
            <? else: ?>
              <a href="<?=$this->record($this->driver)->getLink('series', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
            <? endif; ?>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $subjects = $this->driver->getAllSubjectHeadings(); if (!empty($subjects)): ?>
      <tr>
        <th><?=$this->transEsc('Subjects')?>: </th>
        <td>
          <? foreach ($subjects as $field): ?>
          <div class="subjectLine" property="keywords">
            <? $subject = ''; ?>
            <? if(count($field) == 1) $field = explode('--', $field[0]); ?>
            <? $i = 0; foreach ($field as $subfield): ?>
              <?=($i++ == 0) ? '' : ' &gt; '?>
              <? $subject = trim($subject . ' ' . $subfield); ?>
              <a class="backlink" title="<?=$this->escapeHtmlAttr($subject)?>" href="<?=$this->record($this->driver)->getLink('subject', $subject)?>"><?=trim($this->escapeHtml($subfield))?></a>
            <? endforeach; ?>
          </div>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $childRecordCount = $this->driver->tryMethod('getChildRecordCount'); if ($childRecordCount): ?>
      <tr>
        <th><?=$this->transEsc('child_records')?>: </th>
        <td>
          <a href="<?=$this->recordLink()->getChildRecordSearchUrl($this->driver)?>"><?=$this->transEsc('child_record_count', array('%%count%%' => $childRecordCount))?></a>
        </td>
      </tr>
      <? endif; ?>

      <?
        $openUrl = $this->driver->openURLActive('record') ? $this->driver->getOpenURL() : false;
        // Account for replace_other_urls setting
        $urls = ($openUrl && $this->driver->replaceURLsWithOpenURL()) ? array() : $this->record($this->driver)->getLinkDetails();
      ?>
      <? if (!empty($urls) || $openUrl): ?>
      <tr>
        <th><?=$this->transEsc('Online Access')?>: </th>
        <td>
          <? foreach ($urls as $current): ?>
            <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><?=$this->escapeHtml($current['desc'])?></a><br/>
          <? endforeach; ?>
          <? if ($openUrl): ?>
            <?=$this->openUrl($openUrl)?><br/>
          <? endif; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $recordLinks = $this->driver->getAllRecordLinks(); ?>
      <? if(!empty($recordLinks)): ?>
        <tr>
          <th><?=$this->transEsc('Related Items')?>:</th>
          <td>
            <? foreach ($recordLinks as $recordLink): ?>
              <?=$this->transEsc($recordLink['title'])?>:
              <a href="<?=$this->recordLink()->related($recordLink['link'])?>"><?=$this->escapeHtml($recordLink['value'])?></a><br />
            <? endforeach; ?>
            <? /* if we have record links, display relevant explanatory notes */
              $related = $this->driver->getRelationshipNotes();
              if (!empty($related)): ?>
                <? foreach ($related as $field): ?>
                  <?=$this->escapeHtml($field)?><br/>
                <? endforeach; ?>
            <? endif; ?>
          </td>
        </tr>
      <? endif; ?>
    </table>
    <?/* End Main Details */?>
  </div>
</div>
</div>
