<?php
    $id = $this->driver->getUniqueID();

    $anchor = htmlspecialchars($this->driver->getF773_display());
    $prefix = explode(":", $this->driver->getLink773_str())[0];
    $isn = explode(":", $this->driver->getLink773_str())[1];

    if (! empty($anchor)) {
        if (! empty($prefix) || ! empty($isn) ) {

            if ($prefix == 'title') {
                $searchType = 'AllFields';
            } else {
                $searchType = 'isn';
            }

            $url = '/Search/Results?join=AND&bool0[]=AND&lookfor0[]="'.$isn.'"&type0[]="'.$searchType.'"&bool1[]=NOT&lookfor1[]="'.$id.'"&type1[]=id&sort=title&view=list';

            echo $this->translate('In').': '."<a href='" . $url . "' title='" . $anchor . "'>" . $anchor ."</a>\n";
        } else {
            echo $this->translate('In').': '.$anchor . "\n";
        }
    }