<div class="well">

  	<?php   	
	  	$dedupedRecords = array_map("unserialize", array_unique(array_map("serialize", $this->tabs['DedupedRecords']->getRecordsInGroup())));

	  	$recordSource = explode(".", $this->driver->getUniqueId())[0];
	  	
	  	$logoKey = $this->config->IdPLogosMappedToSolr->$recordSource ?: '';
	  	$logoUrl = $this->config->IdPLogos->$logoKey ?: '';
	  	
	  	$currentInstitution = $this->translate('source_'.$recordSource);
  	?>
  	
  	<div class='dropdown pull-right'>
		<a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" id="records-in-groups-nav" href="#">
			<h3 style='display: inline;'>
			<?
				if ($logoUrl)
					echo "<img height='32' src='$logoUrl' alt='$currentInstitution'> ";
				
				echo $currentInstitution;
			?>
			</h3>
			<b class="caret"></b>
		</a>
		<ul class="dropdown-menu" aria-labelledby="records-in-groups-nav">
			<? 
		  		foreach ($dedupedRecords as $record) {
	  				$link = $record['id'];
	  				$source = $record['source'];
	  				if ($source !== 'source_'.$recordSource)
	  					echo "<li><a href='".$this->url('record', array('id' => $link))."' title='".$this->translate($source)."'>".$this->translate($source)."</a></li>";
		  		}
		  	?>
		</ul>
	</div>

  </div>