<div style='padding: 0px !important;'>

  	<?php
	  	$dedupedRecords = array_map("unserialize", array_unique(array_map("serialize", $this->tabs['DedupedRecords']->getRecordsInGroup())));

	  	$recordSource = explode(".", $this->driver->getUniqueId())[0];

	  	$currentInstitution = $this->translate('source_'.$recordSource);

	  	$logoUrl = 'https://'.$_SERVER['SERVER_NAME'].'/themes/cpk-devel/images/institutions/logos/'.$recordSource.'/'.$recordSource.'.png';
	  	$logoPath = __DIR__.'/../../../images/institutions/logos/'.$recordSource.'/'.$recordSource.'.png';
	  	$logoIsAvailable = file_exists($logoPath);
  	?>


	<? if (count($dedupedRecords) !== 1) :?>
	<div class="dropdown">
		<div class='btn btn-default dropdown-toggle' data-toggle='dropdown' aria-haspopup='true' aria-expanded='true' style='width: 100%;' id='records-in-groups-nav'>
		<h3 style="margin-top: 5px; margin-bottom: 5px; padding: 0px 0px 20px 0px">
	<? else : ?>
	<div>
		<div class='single-institution' style='width: 100%;'>
		<h3 style="margin-top: 5px; margin-bottom: 5px; padding: 10px 10px 30px 10px;">
	<? endif;?>

			<? if ($logoIsAvailable) : ?>
				<img class='hidden-xs' height='20' src='<?=$logoUrl?>' align='left' style='margin-right: 8px;'>
			<? endif;?>

			<span>
				<span class='pull-left' style='padding-bottom: 6px;'><?=$currentInstitution?></span>

				<? if (count($dedupedRecords) !== 1) : ?>
					<i class='pr-interface-arrowbottom4 pull-right' align='right' style='display: block;'></i>
				<? endif;?>
			</span>
			</h3>

		</div>
		<ul class="dropdown-menu" aria-labelledby="records-in-groups-nav" style='width: 100%;'>
			<?
    			// put caslin at the end and cnb before caslin, when available
                $tempCnbs = [];
                $tempCaslins = [];
                foreach ($dedupedRecords as $key => $record) {
                    if ($record['source'] === 'source_cnb') {
                        $tempCnbs[] = $record;
                        unset($dedupedRecords[$key]);
                    }

                    if ($record['source'] === 'source_caslin') {
                        $tempCaslins[] = $record;
                        unset($dedupedRecords[$key]);
                    }
                }
                sort($dedupedRecords);
                foreach ($tempCnbs as $key => $record) {
                    $dedupedRecords[] = $record;
                }
                foreach ($tempCaslins as $key => $record) {
                    $dedupedRecords[] = $record;
                }
		  		foreach ($dedupedRecords as $record) {
	  				$link = $record['id'];
	  				$source = $record['source'];
	  				$sourceWithoutPrefix = substr($source, 7);

  					echo "<li><a href='".$this->url('record', array('id' => $link))."?referer=".$this->referer."' title='".$this->translate($source)."'><div class='record-group-list-item'>";

  					$logoUrl = 'https://'.$_SERVER['SERVER_NAME'].'/themes/cpk-devel/images/institutions/logos/'.$sourceWithoutPrefix.'/'.$sourceWithoutPrefix.'.png';
  					$logoPath = __DIR__.'/../../../images/institutions/logos/'.$sourceWithoutPrefix.'/'.$sourceWithoutPrefix.'.png';
  					$logoIsAvailable = file_exists($logoPath);

  					if ($logoIsAvailable)
  					    echo "<img class='hidden-xs pull-right' height='16' src='".$logoUrl."'>";

  					echo "<span>".$this->translate($source)."</span>";

                    echo "</div></a></li>";
		  		}
		  	?>
		</ul>
	</div>
</div>
