<span class=""><?=$this->translate('Found in these institutions') ?>:</span>

<div class="col-sm-12 dedupInformation">

<? $maxInstitutionsShown = 2; $i = 0; foreach ($records as $source => $value):
		$record = $value['id'];
		$recordInLibraryOwnershipClass = in_array($source, $this->myLibs) ? 'my-library-record' : 'other-library-record';
		$recordUrl = $this->recordLink()->getUrl($record);
		$anchor = $this->transEsc('source_' . $source, null, $source);

		$logoKey = $this->config->IdPLogosMappedToSolr->$source ?: '';
		$logoUrl = $this->config->IdPLogos->$logoKey ?: '' ?>

<a href="<?=$recordUrl?>" title="<?=$this->translate('Record in institution') . ' ' . $anchor ?>" <?=(++$i > $maxInstitutionsShown) ? 'hidden="hidden"' : '' ?>>
    <div class="row root-title">
        <div class="col-sm-1 nopadding text-center">
            <? if($logoUrl): ?>
                <img height='16px' src='<?=$logoUrl?>' />
            <? endif; ?>
        </div>
        <div class="col-sm-8 nav-tabs">
            <span class="<?=$recordInLibraryOwnershipClass?>"><?=$anchor?></span>
        </div>
    </div>
</a>

<? endforeach; ?>

<? if ($i > $maxInstitutionsShown): ?>
<div class="margin-bottom">
    <div onclick="showNextInstitutions(this);" class="show-next-institutions text-center"><a><?=$this->translate('Show next institutions')?><b class="caret"></b></a></div>
</div>
<? endif; ?>

</div>