<span class=""><?=$this->translate('Found in these institutions') ?>:</span>

<div class="col-sm-12 dedupInformation">
<?php

	$count = count($records);
	
	// put caslin at the end and cnb before caslin, when available
	// but keep at the front when is set in facet params
	$filters = $params->getFilters();
	
	$caslinFoundInFilters = 0;
	$cnbFoundInFilters = 0;
	if (isset($filters['~institution'])) {
    	$institutionsInFilters = $filters['~institution'];
    	
    	foreach($institutionsInFilters as $institution) {
    	    if (strpos($institution,'CASLIN') !== false) {
    	        $caslinFoundInFilters++;
    	    }
    	    if (strpos($institution,'CNB') !== false) {
    	        $cnbFoundInFilters++;
    	    }
    	}

	}
	 
	if ($cnbFoundInFilters == 0) {
	    if (isset($records['cnb'])) {
	        $cnb = $records['cnb'];
	        unset($records['cnb']);
	        $records['cnb'] = $cnb;
	    }
	}
	
	if ($caslinFoundInFilters == 0) {
	    if (isset($records['caslin'])) {
	        $caslin = $records['caslin'];
	        unset($records['caslin']);
	        $records['caslin'] = $caslin;
	    }
	}
	
	if ($count <= 2) {
		$maxInstitutionsShown = 2;
	} else if ($count === 3) {
		$maxInstitutionsShown = 3;
	} else if ($count >= 4) {
		$maxInstitutionsShown = 2;
	}

	 $i = 0; foreach ($records as $source => $value):
		$record = $value['id'];
		$recordInLibraryOwnershipClass = is_array($this->myLibs) && in_array($source, $this->myLibs) ? 'my-library-record' : 'other-library-record';
		$recordUrl = $this->recordLink()->getUrl($record);
		$anchor = $this->transEsc('source_' . $source, null, $source);

		$logoUrl = isset($this->config['IdPLogos'][$source]) ? $this->config['IdPLogos'][$source] : '' ?>

<a href="<?=$recordUrl?>" title="<?=$this->translate('Record in institution') . ' ' . $anchor ?>" <?=(++$i > $maxInstitutionsShown) ? 'hidden="hidden"' : '' ?>>
    <div class="row root-title">
        <div class="col-sm-1 nopadding text-center">
            <? if($logoUrl): ?>
                <img height='16px' src='<?=$logoUrl?>' />
            <? endif; ?>
        </div>
        <div class="col-sm-8 nav-tabs">
            <span class="<?=$recordInLibraryOwnershipClass?>"><?=$anchor?></span>
        </div>
    </div>
</a>

<? endforeach; ?>

<? if ($i > $maxInstitutionsShown): ?>
<div class="margin-bottom">
    <div onclick="showNextInstitutions(this);" class="show-next-institutions text-center"><a><?=$this->translate('Show next institutions')?><b class="caret"></b></a></div>
</div>
<? endif; ?>

</div>

<? $this->headScript()->appendFile("search-results.js"); ?>
