<span class='records-in-libraries-title'>
	<?=$this->translate('Found in') ?>
    <?=$this->countRecords?>
    <?= ($countRecords > 1)
        ? $this->translate('institutions-in-locale')
        : $this->translate('institution-in-locale')
    ?>
</span>

<?
    // sort records in libraries, put institutions in filters to the beginning
    $foundRecords = $this->records;
    $institutionsFilters = [];
    if (isset($_GET['filter'])) {
        if (count($_GET['filter'])) {
            foreach ($_GET['filter'] as $key => $value) {
                $explodedArray = explode('/', trim($value, '"'));
                $source = strtolower($explodedArray[count($explodedArray)-2]);
                $institutionsFilters[] = $source;
            }
        }
    }

    $prependedLibraries = [];
    if (count($foundRecords) && count($institutionsFilters)) {
        foreach ($foundRecords as $source => $array) {
            if (in_array($source, $institutionsFilters)) {
                unset($foundRecords[$source]);
                $prependedLibraries[$source] = $array;
            }
        }
    }

    $recordsInLibraries = $prependedLibraries + $foundRecords;
?>

<div class="col-sm-12 dedupInformation">
<?php
	if ($this->countRecords <= 2) {
		$maxInstitutionsShown = 2;
	} else if ($this->countRecords === 3) {
		$maxInstitutionsShown = 3;
	} else if ($this->countRecords >= 4) {
		$maxInstitutionsShown = 2;
	}

	 $i = 0; // Print first $maxInstitutionsShown institutions
	 foreach ($recordsInLibraries as $source => $value):
	    $i++;
		$record = $value['id'];
		$recordInLibraryOwnershipClass = is_array($this->myLibs) && in_array($source, $this->myLibs) ? 'my-library-record' : 'other-library-record';

		$recordUrl = $this->recordLink()->getUrl($record).'?referer='.$this->referer;

		$anchor = $this->transEsc('source_' . $source, null, $source);

	?>

    <a href="<?=$recordUrl?>" title="<?=$this->translate('Record in institution') . ' ' . $anchor ?>">
        <div class="row">
            <div class="col-sm-12" style='padding-top: 10px;'>
                <span class="<?=$recordInLibraryOwnershipClass?>"><?=$anchor?></span>
            </div>
        </div>
    </a>

    <? if ($i == $maxInstitutionsShown) break; ?>
<? endforeach; ?>

<? if (count($recordsInLibraries) > $maxInstitutionsShown):
	// If there is more institutions than $maxInstitutionsShown, print Dropdown
?>
<div class="margin-bottom">
	<div class="btn-group">
        <span type="button" class="show-next-institutions dropdown-toggle" data-toggle="dropdown"><?=$this->translate('Show next institutions')?> <b class="caret"></b></span>
        <ul class="dropdown-menu scrollable-menu" role="menu">
            <?
                $i = 0;
                // print rest of institutions, to dropdown
                foreach ($recordsInLibraries as $source => $value):
                $i++;
                if ($i <= $maxInstitutionsShown) continue;
                $record = $value['id'];
                $recordInLibraryOwnershipClass = is_array($this->myLibs) && in_array($source, $this->myLibs) ? 'my-library-record' : 'other-library-record';

                $recordUrl = $this->recordLink()->getUrl($record).'?referer='.$this->referer;

                $anchor = $this->transEsc('source_' . $source, null, $source);

                ?>
				<li>
                    <a href="<?=$recordUrl?>" title="<?=$this->translate('Record in institution') . ' ' . $anchor ?>">
                        <div class="row">
                            <div class="col-sm-12" style='margin-top: -10px;'>
                                <span class="<?=$recordInLibraryOwnershipClass?>"><?=$anchor?></span>
                            </div>
                        </div>
                    </a>
                </li>

            <? endforeach; ?>
        </ul>
    </div>
</div>
<? endif; ?>

</div>
