<?
  $addThis = $this->addThis();
  if (!empty($addThis)) {
    $this->headScript()->appendFile('https://s7.addthis.com/js/250/addthis_widget.js?pub=' . urlencode($addThis));
  }

  // Set up some variables for convenience:
  $id = $this->driver->getUniqueId();
  $controllerClass = 'controller:' . $this->record($this->driver)->getController();
  $cart = $this->cart();
  $cartId = $this->driver->getResourceSource() . '|' . $id;
?>
<ul class="list-group record-toolbar">
  <li class="list-group-item"><a id="mail-record" class="modal-link <?=$controllerClass?>" href="<?=$this->url('record-email', array('id'=>$id)) ?>" title="<?=$this->transEsc('Email this')?>" rel="nofollow"><i class="fa fa-fw fa-envelope"></i> <?=$this->transEsc('Email this')?></a></li>

  <? $exportFormats = $this->export()->getFormatsForRecord($this->driver); ?>
  <? if(count($exportFormats) > 0): ?>
    <li class="dropdown list-group-item">
      <a class="export-toggle dropdown-toggle" data-toggle="dropdown" href="<?=$this->recordLink()->getActionUrl($this->driver, 'Export')?>" rel="nofollow"><i class="fa fa-fw fa-list-alt"></i> <?=$this->transEsc('Export Record') ?></a>
      <ul class="dropdown-menu record-export" role="menu">
        <? foreach ($exportFormats as $exportFormat): ?>
          <li><a <? if ($this->export()->needsRedirect($exportFormat)): ?>target="<?=$this->escapeHtmlAttr($exportFormat)?>Main" <? endif; ?>href="<?=$this->recordLink()->getActionUrl($this->driver, 'Export')?>?style=<?=$this->escapeHtmlAttr($exportFormat)?>" rel="nofollow"><?=$this->transEsc($this->export()->getLabelForFormat($exportFormat))?></a></li>
        <? endforeach; ?>
      </ul>
    </li>
  <? endif; ?>

  <? if ($this->userlist()->getMode() !== 'disabled'): ?>
    <li class="list-group-item"><a id="save-record" class="modal-link <?=$controllerClass?>" href="<?=$this->recordLink()->getActionUrl($this->driver, 'Save')?>" title="<?=$this->transEsc('Add to favorites')?>" rel="nofollow"><i class="fa fa-fw fa-star"></i> <?=$this->transEsc('Add to favorites')?></a></li>
  <? endif; ?>
  <li class="list-group-item hidden" id='citace-pro'><a class="modal-link citations-link" title="<?=$this->transEsc('Show citations')?>" ><i class="fa fa-fw fa-quote-right"></i> <?=$this->transEsc('Show citations')?></a></li>
  <? if (!empty($addThis)): ?>
    <li><a class="addThis addthis_button list-group-item" href="https://www.addthis.com/bookmark.php?v=250&amp;pub=<?=urlencode($addThis)?>"><i class="fa fa-fw fa-bookmark"></i> <?=$this->transEsc('Bookmark')?></a></li>
  <? endif; ?>
  <? if ($cart->isActive()): ?>
    <li id="bookbag-menu"  class="list-group-item">
      <input id="cartId" type="hidden" name="ids[]" value="<?=$this->escapeHtmlAttr($cartId)?>" />
      <a id="cart-add" class="<? if(!$cart->contains($cartId)): ?>correct <? endif ?>hidden" href="#"><i class="fa fa-fw fa-plus"></i> <?=$this->transEsc('Add to Book Bag') ?></a>
      <a id="cart-remove" class="<? if($cart->contains($cartId)): ?>correct <? endif ?>hidden" href="#"><i class="fa fa-fw fa-minus-circle"></i> <?=$this->transEsc('Remove from Book Bag') ?></a>
      <noscript>
        <form method="post" name="addForm" action="<?=$this->url('cart-home')?>">
          <input type="hidden" name="ids[]" value="<?=$this->escapeHtmlAttr($cartId)?>" />
          <? if ($cart->contains($cartId)): ?>
            <input class="btn btn-default" type="submit" name="delete" value="<?=$this->transEsc('Remove from Book Bag')?>"/>
          <? else: ?>
            <input class="btn btn-default" type="submit" name="add" value="<?=$this->transEsc('Add to Book Bag')?>"/>
          <? endif; ?>
        </form>
      </noscript>
    </li>
  <? endif; ?>
</ul>
<script>
jQuery( document ).ready(function( $ ) {
	$( '.citations-link' ).on('click', function(){
		$( '#citationsModal' ).modal( 'show' );
	});
});
</script>