<div id="want-it-container">
	<button class="btn btn-default btn-lg btn-primary pull-right class='want-it'" id='' type="button"  data-toggle="modal" data-target="#want-it-menu"><?= $this->translate('Chci to!') ?></button>
	
	<!-- Modal -->
	<div class="modal fade" id="want-it-menu" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	    </div>
	  </div>
	</div>
	
	<div class="hidden paper-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<ul class="breadcrumb hidden-print want-it-breadcrumb">
				<li><a id='want-it-back-to-default' tabindex="0"><?= $this->translate('Co chci') ?></a></li> 
				<li class="active"><a id='want-it-back-to-paper'><?= $this->translate('Papírová verze') ?></a></li> 
			</ul>
		</div>
		<div class="modal-body">
			<div class="list-group">
				<a class="list-group-item" tabindex="0">
					<h4 class="list-group-item-heading"><?= $this->translate('Objednat')?></h4>
					<p class="list-group-item-text"><?= $this->translate('K výpújčnímu pultu knihovny')?></p>
				</a>
				<a class="list-group-item primary" tabindex="0">
					<h4 class="list-group-item-heading"><?= $this->translate('Rezervovat')?></h4>
					<p class="list-group-item-text"><?= $this->translate('Ve vybrané knihovně')?></p>
				</a>
				<a class="list-group-item primary" tabindex="0">
					<h4 class="list-group-item-heading"><?= $this->translate('Přivézt')?></h4>
					<p class="list-group-item-text"><?= $this->translate('Českou poštou')?></p>
				</a>
			</div>
		</div>
	</div>
	
	<div class="hidden electronic-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<ul class="breadcrumb hidden-print want-it-breadcrumb">
				<li><a id='want-it-back-to-default' tabindex="0"><?= $this->translate('Co chci') ?></a></li> 
				<li class="active"><a id='want-it-back-to-electronic'><?= $this->translate('Elektronická verze') ?></a></li> 
			</ul>
		</div>
		<div class="modal-body">
			<div class="list-group">
				<a class="list-group-item" tabindex="0">
					<h4 class="list-group-item-heading"><?= $this->translate('Zdarma')?></h4>
					<p class="list-group-item-text"><?= $this->translate('Prohlížet')?></p>
				</a>
				<a class="list-group-item primary" tabindex="0">
					<h4 class="list-group-item-heading"><?= $this->translate('Koupit')?></h4>
					<p class="list-group-item-text"><?= $this->translate('Jednotka je dostupná jenom po zaplacení')?></p>
				</a>
			</div>
		</div>
	</div>
	
	<div class="hidden default-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<ul class="breadcrumb hidden-print want-it-breadcrumb">
				<li class="active"><a id='want-it-back-to-default'><?= $this->translate('Co chci') ?></a></li> 
			</ul>
		</div>
		<div class="modal-body">
			<div class="list-group">
				<a class="list-group-item" id='paper' tabindex="0">
					<div class='row'>
						<div class='col-lg-2'>
							<i class="fa fa-book fa-3x"></i>&nbsp;
						</div>
						<div class='col-lg-10'>
							<h4 class="list-group-item-heading"></h4>
							<p class="list-group-item-text"><?= $this->translate('Objednat nebo rezervovat v knihovne')?></p>
						</div>
					</div>
				</a>
				<a class="list-group-item" id='electronic' tabindex="0">
					<div class='row'>
						<div class='col-lg-2'>
							<i class="fa fa-cloud-download fa-3x"></i>&nbsp;
						</div>
						<div class='col-lg-10'>
							<h4 class="list-group-item-heading"><?= $this->translate('Elektronická verze')?></h4>
							<p class="list-group-item-text"><?= $this->translate('Prohížet e-dokument')?></p>
						</div>
					</div>
				</a>
				<a class="list-group-item" id='buy' tabindex="0">
					<div class='row'>
						<div class='col-lg-2'>
							<i class="fa fa-shopping-cart fa-3x"></i>&nbsp;
						</div>
						<div class='col-lg-10'>
							<h4 class="list-group-item-heading"><?= $this->translate('Koupit')?>Koupit</h4>
							<p class="list-group-item-text"><?= $this->translate('Najit na heurece')?></p>
						</div>
					</div>
				</a>
			</div>
		</div>
	</div>
	
	<style>
	.want-it-breadcrumb {
		margin-bottom: 0px;
	}
	.want-it-breadcrumb li a{
		cursor: pointer;
	}
	.want-it-breadcrumb li.active{
		cursor: auto;
		text-decoration: none;
		color: #777;
	}
	#want-it-menu .list-group-item {
		cursor: pointer;
	}
	#paper {
		background-color: #FCF8E3;
	}
	#electronic {
		background-color: #D9EDF7;
	}
	#buy {
		background-color: #DFF0D8;
	}
	#paper:focus, #paper:hover, #paper:active,
	#electronic:focus, #electronic:hover, #electronic:active,
	#buy:focus, #buy:hover, #buy:active {
		background-color: #474747;
		border: 1px solid #fff;
		color: #fff !important;
	}
	#paper:focus h4, #paper:hover h4, #paper:active h4,
	#electronic:focus h4, #electronic:hover h4, #electronic:active h4,
	#buy:focus h4, #buy:hover h4, #buy:active h4 {
		color: #fff !important;
	}
	
	.modal-header {
		border-bottom: 0px;
	}
	
	#want-it-menu, #want-it-electronic {
	  text-align: center;
	}
	
	#want-it-menu:before {
	  display: inline-block;
	  vertical-align: middle;
	  content: " ";
	  height: 100%;
	}
	
	#want-it-menu .modal-dialog, #want-it-electronic.modal-dialog {
	  display: inline-block;
	  text-align: left;
	  vertical-align: middle;
	}
	</style>
	
	<script>
		jQuery( document ).ready( function( $ ) {
	
			$( '.modal-content' ).html( $( '.default-content' ).html() );
	
			$( '#want-it-container' ).on('hidden.bs.modal', '#want-it-menu', function (e) {
				$( '.modal-content' ).hide().html( $( '.default-content' ).html() ).fadeIn('slow');
			})
			
			$( '#want-it-container' ).on( 'click', '#paper', function(){
				$( '.modal-content' ).hide().html( $( '.paper-content' ).html() ).fadeIn('slow');
			});
			
			$( '#want-it-container' ).on( 'click', '#electronic', function(){
				$( '.modal-content' ).hide().html( $( '.electronic-content' ).html() ).fadeIn('slow');
			});
	
			$( '#want-it-container' ).on( 'click', '#want-it-back-to-default', function(){
				$( '.modal-content' ).hide().html( $( '.default-content' ).html() ).fadeIn('slow');
			});

			$( '#want-it-container' ).on( 'click', '#want-it-back-to-electronic', function(){
				$( '.modal-content' ).hide().html( $( '.electronic-content' ).html() ).fadeIn('slow');
			});

			$( '#want-it-container' ).on( 'click', '#want-it-back-to-paper', function(){
				$( '.modal-content' ).hide().html( $( '.paper-content' ).html() ).fadeIn('slow');
			});

		});
	</script>
</div>