<?
    // Set up page title:
    $this->headTitle($this->translate('Interlibrary Loan Requests'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a> </li>'
        . '<li class="active">' . $this->transEsc('Interlibrary Loan Requests') . '</li>';
?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <h2><?=$this->transEsc('Interlibrary Loan Requests') ?></h2>

    <ul>
    <li>
      <a href="?new=monography">
        <?=$this->transEsc('new_ill_request_for_monography')?>
      </a>
    </li>
    <li>
      <a href="?new=serial">
        <?=$this->transEsc('new_ill_request_for_serial')?>
      </a>
    </li>
  </ul>

  <?=$this->flashmessages()?>

  <? if (!empty($this->recordList)): ?>
    <? if ($this->cancelForm): ?>
      <form name="cancelForm" class="inline" action="" method="post" id="cancelILLRequest">
        <input type="hidden" id="submitType" name="cancelSelected" value="1"/>
        <input type="hidden" id="cancelConfirm" name="confirm" value="0"/>
        <div class="btn-group">
          <input id="cancelSelected" name="cancelSelected" type="submit" value="<?=$this->transEsc("ill_request_cancel_selected") ?>" class="btn btn-default dropdown-toggle" data-toggle="dropdown"/>
          <ul class="dropdown-menu">
            <li class="disabled"><a><?=$this->transEsc("confirm_ill_request_cancel_selected_text") ?></a></li>
            <li><a href="#" onClick="$('#cancelConfirm').val(1);$('#submitType').attr('name','cancelSelected');$(this).parents('form').submit(); return false;"><?=$this->transEsc('confirm_dialog_yes') ?></a></li>
            <li><a href="#" onClick="return false;"><?=$this->transEsc('confirm_dialog_no')?></a></li>
          </ul>
        </div>
        <div class="btn-group">
          <input id="cancelAll" name="cancelAll" type="submit" value="<?=$this->transEsc("ill_request_cancel_all") ?>" class="btn btn-default dropdown-toggle" data-toggle="dropdown"/>
          <ul class="dropdown-menu">
            <li class="disabled"><a><?=$this->transEsc("confirm_ill_request_cancel_all_text") ?></a></li>
            <li><a href="#" onClick="$('#cancelConfirm').val(1);$('#submitType').attr('name','cancelAll');$(this).parents('form').submit(); return false;"><?=$this->transEsc('confirm_dialog_yes') ?></a></li>
            <li><a href="#" onClick="return false;"><?=$this->transEsc('confirm_dialog_no')?></a></li>
          </ul>
        </div>
    <? endif; ?>

    <? $iteration = 0; ?>
    <? foreach ($this->recordList as $resource): ?>
      <hr/>
      <? $iteration++; ?>
      <? $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
      <? $id = !is_a($resource, 'VuFind\\RecordDriver\\Missing') ? $resource->getUniqueId() : $ilsDetails['docno']; ?>
      <div id="record<?=$this->escapeHtml($id) ?>" class="row">
        <? if ($this->cancelForm && isset($ilsDetails['cancel_details'])): ?>
          <? $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $resource->getUniqueId()); ?>
          <input type="hidden" name="cancelAllIDS[]" value="<?=$this->escapeHtml($ilsDetails['cancel_details']) ?>" />
          <div class="pull-left">
            <input type="checkbox" name="cancelSelectedIDS[]" value="<?=$this->escapeHtml($ilsDetails['cancel_details']) ?>" id="checkbox_<?=$safeId?>" />
          </div>
        <? endif; ?>
        <div class="col-md-2 text-center">
          <div class="coverThumbnail">
            <img src="<?=$this->imageLink('format/MVS.png')?>" />
          </div>
        </div>
        <div class="col-md-9">

          <? if (isset($ilsDetails['docno']) && !empty($ilsDetails['docno'])): ?>
            <strong><?=$this->transEsc('ill_request_no')?>:</strong> <?=$this->escapeHtml($ilsDetails['docno'])?>
            <br />
          <? endif; ?>

          <? if (isset($ilsDetails['title']) && !empty($ilsDetails['title'])): ?>
            <strong><?=$this->transEsc('Title')?>:</strong> <?=$this->escapeHtml($ilsDetails['title'])?>
            <br />
          <? endif; ?>

          <? if (isset($ilsDetails['author']) && !empty($ilsDetails['author'])): ?>
            <strong><?=$this->transEsc('ill_author')?>:</strong> <?=$this->escapeHtml($ilsDetails['author'])?>
            <br />
          <? endif; ?>

          <? $formats = $resource->getFormats(); if (count($formats) > 0): ?>
            <?=str_replace('class="', 'class="label label-info ', $this->record($resource)->getFormatList())?>
            <br/>
          <? endif; ?>
          <? if (isset($ilsDetails['volume']) && !empty($ilsDetails['volume'])): ?>
            <strong><?=$this->transEsc('Volume')?>:</strong> <?=$this->escapeHtml($ilsDetails['volume'])?>
            <br />
          <? endif; ?>

          <? if (isset($ilsDetails['publication_year']) && !empty($ilsDetails['publication_year'])): ?>
            <strong><?=$this->transEsc('Year of Publication')?>:</strong> <?=$this->escapeHtml($ilsDetails['publication_year'])?>
            <br />
          <? endif; ?>

          <? if (isset($ilsDetails['imprint']) && !empty($ilsDetails['imprint'])): ?>
            <strong><?=$this->transEsc('ill_imprint')?>:</strong> <?=$this->escapeHtml($ilsDetails['imprint'])?>
            <br />
          <? endif; ?>

          <? if (isset($ilsDetails['article_title']) && !empty($ilsDetails['article_title'])): ?>
            <strong><?=$this->transEsc('ill_article_title')?>:</strong> <?=$this->escapeHtml($ilsDetails['article_title'])?>
            <br />
          <? endif; ?>

          <? if (isset($ilsDetails['article_author']) && !empty($ilsDetails['article_author'])): ?>
            <strong><?=$this->transEsc('ill_article_author')?>:</strong> <?=$this->escapeHtml($ilsDetails['article_author'])?>
            <br />
          <? endif; ?>

          <? if (isset($ilsDetails['pickup_location']) && !empty($ilsDetails['pickup_location'])): ?>
            <strong><?=$this->transEsc('ill_pickup_location')?>:</strong> <?=$this->escapeHtml($ilsDetails['pickup_location'])?>
            <br />
          <? endif; ?>

          <? if (isset($ilsDetails['media']) && !empty($ilsDetails['media'])): ?>
            <strong><?=$this->transEsc('ill_request_type')?>:</strong> <?=$this->transEsc('ill_type ' . $ilsDetails['media'])?>
            <br />
          <? endif; ?>

          <? if (isset($ilsDetails['price']) && !empty($ilsDetails['price'])): ?>
            <strong><?=$this->transEsc('ill_price')?>:</strong> <?=$this->transEsc($ilsDetails['price'])?>
            <br />
          <? endif; ?>

          <? /* Depending on the ILS driver, the "location" value may be a string or an ID; figure out the best
             value to display... */ ?>
          <? $pickupDisplay = ''; ?>
          <? $pickupTranslate = false; ?>
          <? if (isset($ilsDetails['location'])): ?>
            <? if ($this->pickup): ?>
              <? foreach ($this->pickup as $library): ?>
                <? if ($library['locationID'] == $ilsDetails['location']): ?>
                  <? $pickupDisplay = $library['locationDisplay']; ?>
                  <? $pickupTranslate = true; ?>
                <? endif; ?>
              <? endforeach; ?>
            <? endif; ?>
            <? if (empty($pickupDisplay)): ?>
              <? $pickupDisplay = $ilsDetails['location']; ?>
            <? endif; ?>
          <? endif; ?>
          <? if (!empty($pickupDisplay)): ?>
            <strong><?=$this->transEsc('pick_up_location') ?>:</strong>
            <?=$pickupTranslate ? $this->transEsc($pickupDisplay) : $this->escapeHtml($pickupDisplay)?>
            <br />
          <? endif; ?>

          <strong><?=$this->transEsc('Created') ?>:</strong> <?=$this->escapeHtml($ilsDetails['create']) ?>
          <? if (!empty($ilsDetails['expire'])): ?>
            | <strong><?=$this->transEsc('Expires') ?>:</strong> <?=$this->escapeHtml($ilsDetails['expire']) ?>
          <? endif; ?>
          <br />

          <? if (isset($this->cancelResults['items'])): ?>
            <? foreach ($this->cancelResults['items'] as $itemId=>$cancelResult): ?>
              <? if ($itemId == $ilsDetails['item_id'] && $cancelResult['success'] == false): ?>
                <div class="alert alert-danger"><?=$this->transEsc($cancelResult['status']) ?><? if ($cancelResult['sysMessage']) echo ' : ' . $this->transEsc($cancelResult['sysMessage']); ?></div>
              <? endif; ?>
            <? endforeach; ?>
          <? endif; ?>

          <? if (isset($ilsDetails['in_transit']) && $ilsDetails['in_transit']): ?>
            <div class="text-success"><?=$this->transEsc("ill_request_in_transit") . (is_string($ilsDetails['in_transit']) ? ': ' . $this->transEsc('institution_' . $ilsDetails['in_transit'], array(), $ilsDetails['in_transit']) : '') ?></div>
          <? endif; ?>
          <? if (isset($ilsDetails['processed']) && $ilsDetails['processed']): ?>
            <div class="text-success"><?=$this->transEsc("ill_request_processed") . (is_string($ilsDetails['processed']) ? ': ' . $ilsDetails['processed'] : '') ?></div>
          <? endif; ?>
          <? if (isset($ilsDetails['available']) && $ilsDetails['available']): ?>
            <div class="text-success"><?=$this->transEsc("ill_request_available") ?></div>
          <? endif; ?>
          <? if (isset($ilsDetails['canceled']) && $ilsDetails['canceled']): ?>
            <div class="text-success"><?=$this->transEsc("ill_request_canceled") . (is_string($ilsDetails['canceled']) ? ': ' . $ilsDetails['canceled'] : '') ?></div>
          <? endif; ?>
          <? if (isset($ilsDetails['cancel_link'])): ?>
            <p><a href="<?=$this->escapeHtml($ilsDetails['cancel_link']) ?>"><?=$this->transEsc("ill_request_cancel") ?></a></p>
          <? endif; ?>

        </div>
      </div>
    <? endforeach; ?>
    <? if ($this->cancelForm): ?></form><? endif; ?>
  <? else: ?>
    <?=$this->transEsc('You do not have any interlibrary loan requests placed') ?>.
  <? endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'ILLRequests'))?>
</div>
