<?
  $account = $this->auth()->getManager();
  $user = $account->isLoggedIn();
  
  $name = '';
  if ($user && isset($user->firstname)) {
      $name = $user->firstname;
  }
  if ($user && isset($user->lastname)) {
      $name = $name . " " . $user->lastname;
  }
?>
<h4><?=$this->escapeHtml($name) ?></h4>
<ul class="nav nav-list myresearch-menu">
  <? if ('ils-none' !== $this->ils()->getOfflineMode()): ?>
    <li<?=$this->active == 'checkedout' ? ' class="active"' : ''?>><a href="<?=$this->url('myresearch-checkedout')?>"><?=$this->transEsc('Checked Out Items')?> <i class="pull-right"></i></a></li>
    <li<?=$this->active == 'checkedouthistory' ? ' class="active"' : ''?>><a href="<?=$this->url('myresearch-checkedouthistory')?>"><?=$this->transEsc('Checked Out History')?> <i class="pull-right"></i></a></li>
    <li<?=$this->active == 'holds' ? ' class="active"' : ''?>><a href="<?=$this->url('myresearch-holds')?>"><?=$this->transEsc('Holds and Recalls')?> <i class="pull-right"></i></a></li>
    <li<?=$this->active == 'bookings' ? ' class="active"' : ''?>><a href="<?=$this->url('myresearch-shortloans')?>"><?=$this->transEsc('Bookings')?> <i class="pull-right"></i></a></li>
    <? if ($this->ils()->checkFunction('StorageRetrievalRequests')): ?>
    <li<?=$this->active == 'storageRetrievalRequests' ? ' class="active"' : ''?>><a href="<?=$this->url('myresearch-storageretrievalrequests')?>"><?=$this->transEsc('Storage Retrieval Requests')?> <i class="pull-right"></i></a></li>
    <? endif; ?>
    <? if ($this->ils()->checkFunction('ILLRequests')): ?>
    <li<?=$this->active == 'ILLRequests' ? ' class="active"' : ''?>><a href="<?=$this->url('myresearch-illrequests')?>"><?=$this->transEsc('Interlibrary Loan Requests')?> <i class="pull-right"></i></a></li>
    <? endif; ?>
    <li<?=$this->active == 'fines' ? ' class="active"' : ''?>><a href="<?=$this->url('myresearch-fines')?>"><?=$this->transEsc('Fines')?> <i class="pull-right"></i></a></li>
    <li<?=$this->active == 'profile' ? ' class="active"' : ''?>><a href="<?=$this->url('myresearch-profile')?>"><?=$this->transEsc('Profile')?> <i class="pull-right"></i></a></li>
  <? endif; ?>
  <li<?=$this->active == 'history' ? ' class="active"' : ''?>><a href="<?=$this->url('search-history')?>?require_login"><?=$this->transEsc('history_saved_searches')?> <i class="pull-right"></i></a></li>
</ul>
  <? if (isset($this->profileChange) && $this->profileChange): ?>
    <h4 class="list"><?=$this->transEsc('profile_change_menu_label')?></h4>
    <ul class="nav nav-list myresearch-profile-menu">
      <li<?=$this->op == 'nickname' ? ' class="active"' : ''?>>
        <a href="<?=$this->url('myresearch-profilechange')?>?op=nickname"><?=$this->transEsc('change_nickname')?></a>
      </li>
      <li<?=$this->op == 'password' ? ' class="active"' : ''?>>
        <a href="<?=$this->url('myresearch-profilechange')?>?op=password"><?=$this->transEsc('change_password')?></a>
      </li>
      <li<?=$this->op == 'email' ? ' class="active"' : ''?>>
        <a href="<?=$this->url('myresearch-profilechange')?>?op=email"><?=$this->transEsc('change_email')?></a>
      </li>
    </ul>
  <? elseif ($user = $this->auth()->isLoggedIn()): ?>
    <h4 class="list"><?=$this->transEsc('Your Lists')?></h4>
    <ul class="nav nav-list myresearch-favorites-list">
      <li<?=$this->active == 'favorites' ? ' class="active"' : ''?>><a href="<?=$this->url('myresearch-favorites')?>"><?=$this->transEsc('Your Favorites')?> <i class="pull-right"></i></a></li>
      <? $lists = $user->getLists() ?>
      <? foreach ($lists as $list): ?>
          <li<?=$this->active == 'list' . $list['id'] ? ' class="active"' : ''?>> <a href="<?=$this->url('userList', array('id' => $list['id']))?>"><?=$this->escapeHtml($list['title'])?> <span class="pull-right"><?=$list->cnt?></span></a></li>
      <? endforeach; ?>
      <li><a href="<?=$this->url('editList', array('id'=>'NEW'))?>" title="<?=$this->transEsc('Create a List') ?>"><?=$this->transEsc('Create a List') ?> <span class="pull-right"></span></a></li>
    </ul>
  <? endif ?>
