<?
    // Set up page title:
    $this->headTitle($this->translate('Bookings'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a> </li>'
        . '<li class="active">' . $this->transEsc('Bookings') . '</li>';
?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <h2><?=$this->transEsc('Bookings')?></h2>
  <?=$this->flashmessages()?>

  <? if (!empty($this->bookings)): ?>
    <? if ($this->cancelForm): ?>
      <form name="cancelForm" class="inline" action="" method="post" id="cancelHold">
        <input type="hidden" id="submitType" name="cancelSelected" value="1"/>
        <input type="hidden" id="cancelConfirm" name="confirm" value="0"/>
        <div class="btn-group">
          <input id="cancelSelected" name="cancelSelected" type="submit" value="<?=$this->transEsc("hold_cancel_selected") ?>" class="btn btn-default dropdown-toggle" data-toggle="dropdown"/>
          <ul class="dropdown-menu">
            <li class="disabled"><a><?=$this->transEsc("confirm_hold_cancel_selected_text") ?></a></li>
            <li><a href="#" onClick="$('#cancelConfirm').val(1);$('#submitType').attr('name','cancelSelected');$(this).parents('form').submit()"><?=$this->transEsc('confirm_dialog_yes') ?></a></li>
            <li><a href="#"><?=$this->transEsc('confirm_dialog_no')?></a></li>
          </ul>
        </div>
        <div class="btn-group">
          <input id="cancelAll" name="cancelAll" type="submit" value="<?=$this->transEsc("hold_cancel_all") ?>" class="btn btn-default dropdown-toggle" data-toggle="dropdown"/>
          <ul class="dropdown-menu">
            <li class="disabled"><a><?=$this->transEsc("confirm_hold_cancel_all_text") ?></a></li>
            <li><a href="#" onClick="$('#cancelConfirm').val(1);$('#submitType').attr('name','cancelAll');$(this).parents('form').submit()"><?=$this->transEsc('confirm_dialog_yes') ?></a></li>
            <li><a href="#"><?=$this->transEsc('confirm_dialog_no')?></a></li>
          </ul>
        </div>
      <table class="table-view">

        <tr>
          <th></th>
          <th><?=$this->transEsc('short_loan_request_start')?></th>
          <th><?=$this->transEsc('short_loan_request_end')?></th>
          <th><?=$this->transEsc('Title')?></th>
          <th><?=$this->transEsc('Description')?></th>
        </tr>

        <? $i = 0; foreach ($this->bookings as $booking): ?>
        <tr>
          <? $ilsDetails = $booking->getExtraDetail('ils_details'); ?>
          <td>
            <? if ($this->cancelForm /*&& isset($ilsDetails['cancel_details'])*/): ?>
              <? $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $booking->getUniqueId()); ?>
              <input type="hidden" name="cancelAllIDS[]" value="<?=$this->escapeHtml($ilsDetails['cancel_details']) ?>" />
              <input type="checkbox" name="cancelSelectedIDS[]" value="<?=$this->escapeHtml($ilsDetails['cancel_details']) ?>" id="checkbox_<?=$safeId?>" />
            <? endif; ?>
          </td>
          <td><?=$this->transEsc($ilsDetails['start'])?></td>
          <td><?=$this->transEsc($ilsDetails['end'])?></td>
          <td>
            <?
            if (is_a($booking, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($booking, 'VuFind\\RecordDriver\\Missing')) {
              $title = $booking->getTitle();
              $title = empty($title) ? $this->transEsc('Title not available') : $this->escapeHtml($title);
              echo '<a href="' . $this->recordLink()->getUrl($booking) .
                '" class="title">' . $title . '</a>';
            } else if (isset($ilsDetails['title']) && !empty($ilsDetails['title'])){
              // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
              echo $this->escapeHtml($ilsDetails['title']);
            } else {
              // Last resort -- indicate that no title could be found.
              echo $this->transEsc('Title not available');
            }
            ?>
          </td>
          <td><?=$this->transEsc($ilsDetails['callnumber'])?></td>
        </tr>
        <? endforeach;?>
      </table>
    </form>
    <? endif;?>
  <? else: ?>
    <?=$this->transEsc('short_loan_empty_reservations_text') ?>
  <? endif;?>

</div>

<div class="<?=$this->layoutClass('sidebar')?>">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'bookings'))?>
</div>
