<?php
$holdings = array();

$libraryValues = array();
$branchValues = array();
$branch2Values = array();
$sheduleOfPeriodicsValues = array();
$signatureValues = array();
$signature2Values = array();
$barcodeValues = array();

$hasSheduleOfPeriodics = true;
$holdings = $this->driver->getHoldings($this->tab->getSelectedFilters(), '993');
$holdings = array_map(array($this->driver, 'unifyHolding'), $holdings);
sortHoldings($holdings);

$callbacks = array();
$callbacks['transEsc'] = array(&$this, 'transEsc');
$callbacks['getExternalLinks'] = array(&$this->driver, 'getExternalLinks');
?>
<? foreach ($holdings as $holding): ?>
  <?=renderHolding($callbacks, $holding)?>
<? endforeach;?>
