<?
    // Set up page title:
    $this->headTitle($this->translate('Checked Out Items'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a> <span class="divider">&gt;</span></li>'
        . '<li class="active">' . $this->transEsc('Checked Out Items') . '</li>';

    $isSynchronous = $this->isSynchronous;

    if (! $isSynchronous)
        $this->headScript()->appendFile("async-checkedout.js");
?>

<div class="<?=$this->layoutClass('mainbody')?>">


  <form name="renewals" action="" method="post" id="renewals">
      <div class="row">
      <h2 class="pull-left"><?=$this->transEsc('Your Checked Out Items')?></h2>
      <div class="toolbar pull-right" style="margin-top: 20px;">
        <input type="submit" class="btn btn-default" name="renewSelected" value="<?=$this->transEsc("renew_selected")?>" />
        <input type="submit" class="btn btn-default" name="renewAll" value="<?=$this->transEsc('renew_all')?>" />
      </div>
      </div>
      <?=$this->flashmessages()?>
      <?= $this->render("myresearch/checkedout-list.phtml"); ?>
  </form>
</div>

<div class="<?=$this->layoutClass('sidebar')?>">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'checkedout'))?>
</div>