<?
    // Set up page title:
    $this->headTitle($this->translate('Checked Out History'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/Search">' . $this->transEsc('Main page') . '</a></li> '.
    '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Checked Out History') . '</li>';
?>
<ul class="breadcrumb hidden-print"><?=$this->layout()->breadcrumbs ?></ul>
<div class="row">
  <div ng-controller="CheckedOutHistoryController as historyCtrl" class="<?=$this->layoutClass('mainbody')?>">
    <h2><?=$this->transEsc('Checked Out History')?></h2>
    <?=$this->flashmessages()?>
    
    <? foreach($this->libraryIdentities as $eppn => $libraryIdentity):
      $source = explode('.', $libraryIdentity['cat_username'])[0]; ?>

      <h3 class="well row blickable" style="margin-bottom: 3px;" id="<?=$source?>">
      <?=$this->transEsc("source_$source", null, $source) ?>
      <img class="pull-right" height="32" src="<?=$this->logos()->getLogo($source) ?>"/>
      </h3>
      <div ng-history-username="<?=$libraryIdentity['cat_username']?>" class="row well" style="margin-bottom: 2px;">
        <i class="fa fa-spinner fa-spin"></i>
        <span class="label label-primary"><?=$this->transEsc('Loading')?> ...</span>
      </div>
    <? endforeach; ?>
  </div>

  <div class="<?=$this->layoutClass('sidebar')?>">
    <?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'checkedouthistory'))?>
  </div>
</div>