<?
// Set up page title:
$this->headTitle($this->translate('Checked Out History'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/Search">' . $this->transEsc('Main page') . '</a></li> ' . '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Checked Out History') . '</li>';

// Add translations for the data-ng-app
$this->jsTranslations()->addStrings(array(

    // For history items
    'Cover Image' => $this->translate('Cover Image'),
    'No Cover Image' => $this->translate('No Cover Image'),
    'by' => $this->translate('by'),
    'Volume' => $this->translate('Volume'),
    'Year of Publication' => $this->translate('Year of Publication'),
    'Renewed' => $this->translate('Renewed'),
    'Due Date' => $this->translate('Due Date'),
    /* Actualization with:
     *
     * cat /tmp/copyPastedPartOfLangFile | awk "{print \"'\"\$1\"'\"}" | awk '{print $1 " => $this->translate(" $1 "),"}'
     */

    '0/ARTICLES/' => $this->translate('0/ARTICLES/'),
    '0/BOOKS/' => $this->translate('0/BOOKS/'),
    '0/ELECTRONIC_SOURCE/' => $this->translate('0/ELECTRONIC_SOURCE/'),
    '0/LARGE_PRINTS/' => $this->translate('0/LARGE_PRINTS/'),
    '0/MANUSCRIPTS/' => $this->translate('0/MANUSCRIPTS/'),
    '0/MAPS/' => $this->translate('0/MAPS/'),
    '0/MUSICAL_SCORES/' => $this->translate('0/MUSICAL_SCORES/'),
    '0/NORMS/' => $this->translate('0/NORMS/'),
    '0/PERIODICALS/' => $this->translate('0/PERIODICALS/'),
    '0/VISUAL_DOCUMENTS/' => $this->translate('0/VISUAL_DOCUMENTS/'),
    '0/AUDIO/' => $this->translate('0/AUDIO/'),
    '1/AUDIO/CD/' => $this->translate('1/AUDIO/CD/'),
    '1/AUDIO/DVD/' => $this->translate('1/AUDIO/DVD/'),
    '1/AUDIO/LP/' => $this->translate('1/AUDIO/LP/'),
    '1/AUDIO/CASSETTE/' => $this->translate('1/AUDIO/CASSETTE/'),
    '1/AUDIO/OTHER/' => $this->translate('1/AUDIO/OTHER/'),
    '0/VIDEO/' => $this->translate('0/VIDEO/'),
    '1/VIDEO/BLURAY/' => $this->translate('1/VIDEO/BLURAY/'),
    '1/VIDEO/VHS/' => $this->translate('1/VIDEO/VHS/'),
    '1/VIDEO/DVD/' => $this->translate('1/VIDEO/DVD/'),
    '1/VIDEO/CDROM/' => $this->translate('1/VIDEO/CDROM/'),
    '1/VIDEO/OTHER/' => $this->translate('1/VIDEO/OTHER/'),
    '0/OTHER/' => $this->translate('0/OTHER/'),
    '1/OTHER/BRAILLE/' => $this->translate('1/OTHER/BRAILLE/'),
    '1/OTHER/KIT/' => $this->translate('1/OTHER/KIT/'),
    '1/OTHER/OBJECT/' => $this->translate('1/OTHER/OBJECT/'),
    '1/OTHER/MICROFORMS/' => $this->translate('1/OTHER/MICROFORMS/'),
    '1/OTHER/MIX_DOCUMENT/' => $this->translate('1/OTHER/MIX_DOCUMENT/'),
    '1/OTHER/UNSPECIFIED/' => $this->translate('1/OTHER/UNSPECIFIED/'),

    // For paginator
    'Prev' => $this->translate('Prev'),
    'Next' => $this->translate('Next')
));
?>
<!-- <ul class="breadcrumb hidden-print"><?=$this->layout()->breadcrumbs ?></ul>-->
<div class="row">
  <div class="<?=$this->layoutClass('mainbody')?>">
    <h2><?=$this->transEsc('Checked Out History')?></h2>
    <?=$this->flashmessages()?>

    <? foreach($this->libraryIdentities as $eppn => $libraryIdentity):
      $source = explode('.', $libraryIdentity['cat_username'])[0]; ?>
    <div data-ng-controller="CheckedOutHistoryController as historyCtrl">
      <h3 class="well row blickable" style="margin-bottom: 3px;" id="<?=$source?>">
      <?=$this->transEsc("source_$source", null, $source) ?>
      <img class="pull-right" height="32" src="<?=$this->logos()->getLogo($source) ?>"/>
      <label style="padding-right: 40px;" class="dropdown-select-label pull-right">
      <select data-ng-pages-count="<?=$libraryIdentity['cat_username']?>" data-ng-model="historyCtrl.perPage" data-ng-change="historyCtrl.perPageUpdated()" class="jumpMenu form-control dropdown-select hidden" style="margin-right: -12px;">
        <option value="10" selected="selected">10 <?=$this->translate('records-in-genitive') ?></option>
        <option value="50">50 <?=$this->translate('records-in-genitive') ?></option>
        <option value="100">100 <?=$this->translate('records-in-genitive') ?></option>
      </select>
      </label>
      </h3>
      <div data-ng-history-item data-ng-repeat="resource in historyCtrl.historyPage">
      </div>
      <div data-ng-history-username="<?=$libraryIdentity['cat_username']?>" class="row well text-center" style="margin-bottom: 2px;">
        <i class="fa fa-spinner fa-spin"></i>
        <span class="label label-info"><?=$this->transEsc('Loading')?> ...</span>
      </div>
      <div data-ng-pagination="<?=$source ?>" class='row well' data-ng-if="paginator && paginator.lastPage != 1" ></div>
    </div>
    <? endforeach; ?>
  </div>

  <div class="<?=$this->layoutClass('sidebar')?>">
    <?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'checkedouthistory'))?>
  </div>
</div>