<?
    // Set up page title:
    $this->headTitle($this->translate('Checked Out Items'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a> <span class="divider">&gt;</span></li>'
        . '<li class="active">' . $this->transEsc('Checked Out Items') . '</li>';
?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <h2><?=$this->transEsc('Your Checked Out Items')?></h2>
  <?=$this->flashmessages()?>

  <?
  $renewalsFormCreated = false;
  foreach ($this->libraryIdentities as $eppn => $libraryIdentity) :
    if (!empty($libraryIdentity['transactions']) && ! $renewalsFormCreated): ?>

    <form name="renewals" action="" method="post" id="renewals">
      <div class="toolbar">
        <input type="submit" class="btn btn-default" name="renewSelected" value="<?=$this->transEsc("renew_selected")?>" />
        <input type="submit" class="btn btn-default" name="renewAll" value="<?=$this->transEsc('renew_all')?>" />
      </div>

  <? $renewalsFormCreated = true; ?>
  <? endif; endforeach;

  if (! $renewalsFormCreated): ?>
    <?=$this->transEsc('You do not have any items checked out')?>.
  <? else: ?>
    <?= $this->render("myresearch/checkedout-list.phtml"); ?>
    </form>
  <? endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'checkedout'))?>
</div>