<?
    // Set up page title:
    $this->headTitle($this->translate('Checked Out Items'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/">' . $this->transEsc('Main page') . '</a></li> '.
    '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a> <span class="divider">&gt;</span></li>'
        . '<li class="active">' . $this->transEsc('Checked Out Items') . '</li>';

    $isSynchronous = $this->isSynchronous;

    if (! $isSynchronous)
        $this->headScript()->appendFile("async-checkedout.js");

    // We will hide the renewal form if we have asynchronous mode ..
    $formAttributes = $isSynchronous ? '' : 'hidden="hidden"';
?>
<ul class="breadcrumb hidden-print"><?=$this->layout()->breadcrumbs ?></ul>
<div class="<?=$this->layoutClass('mainbody')?>">


      <div class="row">
      <h2 class="pull-left"><?=$this->transEsc('Your Checked Out Items')?></h2>
      <form <?=$formAttributes ?> name="renewals" action="" method="post" id="renewTransactions">
        <div class="toolbar pull-right" style="margin-top: 20px;">
          <input type="submit" class="btn btn-default" name="renewSelected" value="<?=$this->transEsc("renew_selected")?>" />
          <input type="submit" class="btn btn-default" name="renewAll" value="<?=$this->transEsc('renew_all')?>" />
        </div>
      </form>
      </div>
      <?=$this->flashmessages()?>

    <? foreach($this->libraryIdentities as $eppn => $libraryIdentity):
        $source = explode('.', $libraryIdentity['cat_username'])[0]; ?>

      <h3 class="well row blickable" style="margin-bottom: 3px;" id="<?=$source?>">
      <?=$this->transEsc("source_$source", null, $source) ?>
      <img class="pull-right" height="32" src="<?=$this->logos()->getLogo($source) ?>"/>
      </h3>

        <? if ($isSynchronous): ?>
          <?= $this->render("myresearch/checkedout-from-identity.phtml", ['libraryIdentity' => $libraryIdentity, 'AJAX' => false]); ?>
        <? else: ?>
          <div id="<?=$libraryIdentity['cat_username']?>" data-type="loadingDiv" class="row well" style="margin-bottom: 2px;">
            <i class="fa fa-spinner fa-spin"></i>
            <span class="label label-primary"><?=$this->transEsc('Loading')?> ...</span>
          </div>
        <? endif; ?>
      <? endforeach; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'checkedout'))?>
</div>
