<?
  $isAJAX = isset($AJAX) && $AJAX === true;
  if (!empty($libraryIdentity->recordList)): ?>

      <? $iteration = 0; ?>
      <? foreach ($libraryIdentity->recordList as $resource): ?>
        <? $iteration++; ?>
        <? $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
        <div id="record<?=$this->escapeHtmlAttr($resource->getUniqueId()) ?>" class="row well" style="margin-bottom: 2px;">
          <? if ($libraryIdentity->cancelForm && isset($ilsDetails['cancel_details'])): ?>
            <? $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $resource->getUniqueId()); ?>
            <input form="cancelHold" type="hidden" name="cancelAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['cancel_details']) ?>" />
            <div class="col-xs-1">
              <input form="cancelHold" type="checkbox" name="cancelSelectedIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['cancel_details']) ?>" id="checkbox_<?=$safeId?>" />
            </div>
          <? endif; ?>
          <div class="col-md-2 text-center">
            <?
            $recordId = $resource->getUniqueId();
            $backLink = $this->serverUrl($this->recordLink()->getUrl($resource));
            $formats = $resource->getFormats();
            ?>
            <? $recordId =  preg_replace('/[\.:]/', '', $recordId)?>
            <div id="cover_<?=$recordId?>" class="coverThumbnail">
              <? if (! $isAJAX && $bibinfo = $this->record($resource)->getObalkyKnihJSONV3()): ?>
                <script type="text/javascript">
                  $(document).ready(function() {
                    obalky.display_thumbnail("#cover_<?=$recordId?>", <?=$bibinfo?>, <?=json_encode($this->record($resource)->getObalkyKnihAdvert('checkedout'))?>);
                  });
                </script>
              <? endif;?>
            </div>
          </div>

          <div class="col-sm-6 col-xs-12">
            <?
              // If this is a non-missing Solr record, we should display a link:
              if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
                $title = $resource->getTitle();
                $title = empty($title) ? $this->transEsc('Title not available') : $this->escapeHtml($title);
                echo '<a href="' . $this->recordLink()->getUrl($resource)
                  . '" class="title">' . $title . '</a>';
              } else if (isset($ilsDetails['title']) && !empty($ilsDetails['title'])){
                // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
                echo $this->escapeHtml($ilsDetails['title']);
              } else {
                // Last resort -- indicate that no title could be found.
                echo $this->transEsc('Title not available');
              }
            ?><br/>
            <? $listAuthor = $resource->getPrimaryAuthor(); if (!empty($listAuthor)): ?>
              <?=$this->transEsc('by')?>:
              <a href="<?=$this->record($resource)->getLink('author', $listAuthor)?>"><?=$this->escapeHtml($listAuthor)?></a><br/>
            <? endif; ?>

            <? $formats = $resource->getFormats(); if (count($formats) > 0): ?>
              <?=$this->record($resource)->getFormatList()?>
              <br/>
            <? endif; ?>
            <? if (isset($ilsDetails['volume']) && !empty($ilsDetails['volume'])): ?>
              <strong><?=$this->transEsc('Volume')?>:</strong> <?=$this->escapeHtml($ilsDetails['volume'])?>
              <br />
            <? endif; ?>

            <? if (isset($ilsDetails['publication_year']) && !empty($ilsDetails['publication_year'])): ?>
              <strong><?=$this->transEsc('Year of Publication')?>:</strong> <?=$this->escapeHtml($ilsDetails['publication_year'])?>
              <br />
            <? endif; ?>

            <? if (!empty($ilsDetails['requestGroup'])): ?>
              <strong><?=$this->transEsc('hold_requested_group') ?>:</strong> <?=$this->transEsc('location_' . $ilsDetails['requestGroup'], array(), $ilsDetails['requestGroup'])?>
              <br />
            <? endif; ?>

            <? /* Depending on the ILS driver, the "location" value may be a string or an ID; figure out the best
               value to display... */ ?>
            <? $pickupDisplay = ''; ?>
            <? $pickupTranslate = false; ?>
            <? if (isset($ilsDetails['location'])): ?>
              <? if ($libraryIdentity->pickup): ?>
                <? foreach ($libraryIdentity->pickup as $library): ?>
                  <? if ($library['locationID'] == $ilsDetails['location']): ?>
                    <? $pickupDisplay = $library['locationDisplay']; ?>
                    <? $pickupTranslate = true; ?>
                  <? endif; ?>
                <? endforeach; ?>
              <? endif; ?>
              <? if (empty($pickupDisplay)): ?>
                <? $pickupDisplay = $ilsDetails['location']; ?>
              <? endif; ?>
            <? endif; ?>
            <? if (!empty($pickupDisplay)): ?>
              <strong><?=$this->transEsc('pick_up_location') ?>:</strong>
              <?=$pickupTranslate ? $this->transEsc($pickupDisplay) : $this->escapeHtml($pickupDisplay)?>
              <br />
            <? endif; ?>

            <? if (!empty($ilsDetails['create'])): ?>
              <strong><?=$this->transEsc('Created') ?>:</strong> <?=$this->escapeHtml($ilsDetails['create']) ?>
              <? if (!empty($ilsDetails['expire'])): ?>|<? endif; ?>
            <? endif; ?>
            <? if (!empty($ilsDetails['expire'])): ?>
              <strong><?=$this->transEsc('Expires') ?>:</strong> <?=$this->escapeHtml($ilsDetails['expire']) ?>
            <? endif; ?>
            <br />

            <? if (isset($libraryIdentity->cancelResults['items'])): ?>
              <? foreach ($libraryIdentity->cancelResults['items'] as $itemId=>$cancelResult): ?>
                <? if ($itemId == $ilsDetails['item_id'] && $cancelResult['success'] == false): ?>
                  <div class="alert alert-danger"><?=$this->transEsc($cancelResult['status']) ?><? if ($cancelResult['sysMessage']) echo ' : ' . $this->transEsc($cancelResult['sysMessage']); ?></div>
                <? endif; ?>
              <? endforeach; ?>
            <? endif; ?>

            <? if (isset($ilsDetails['available']) && $ilsDetails['available'] == true): ?>
              <div class="text-success"><?=$this->transEsc("hold_available") ?></div>
            <? elseif (isset($ilsDetails['position'])): ?>
              <p><strong><?=$this->transEsc("hold_queue_position") ?>:</strong> <?=$this->escapeHtml($ilsDetails['position']) ?></p>
            <? endif; ?>
            <? if (isset($ilsDetails['cancel_link'])): ?>
              <p><a href="<?=$this->escapeHtmlAttr($ilsDetails['cancel_link']) ?>"><?=$this->transEsc("hold_cancel") ?></a></p>
            <? endif; ?>

          </div>
        </div>
      <? endforeach; ?>
    <? else: ?>
    <div class="row well" style="margin-bottom: 2px;">
      <div class="label label-info">
      <?=$this->transEsc('You do not have any holds or recalls placed in this institution') ?>.
      </div>
    </div>
    <? endif; ?>