<?
    // Set up page title:
    $this->headTitle($this->translate('Holds and Recalls'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('My Holds') . '</li>';

    $isSynchronous = $this->isSynchronous;

    if (! $isSynchronous)
        $this->headScript()->appendFile("async-holds.js");
?>

<div class="row">
  <div class="<?=$this->layoutClass('mainbody')?>">
    <h2><?=$this->transEsc('Your Holds and Recalls') ?></h2>

    <?=$this->flashmessages()?>
    <? if ($isSynchronous): ?>
    <? foreach($this->libraryIdentities as $eppn => $libraryIdentity): // We have to detect whether is necessarry creating cancel btns?>

    <? if (! empty($libraryIdentity->recordList) && $libraryIdentity->cancelForm): ?>
        <form name="cancelForm" class="inline" method="post" id="cancelHold">
          <input type="hidden" id="submitType" name="cancelSelected" value="1"/>
          <input type="hidden" id="cancelConfirm" name="confirm" value="0"/>
          <div class="btn-group">
            <input id="cancelSelected" name="cancelSelected" type="submit" value="<?=$this->transEsc("hold_cancel_selected") ?>" class="btn btn-default dropdown-toggle" data-toggle="dropdown"/>
            <ul class="dropdown-menu">
              <li class="disabled"><a><?=$this->transEsc("confirm_hold_cancel_selected_text") ?></a></li>
              <li><a href="#" onClick="$('#cancelConfirm').val(1);$('#submitType').attr('name','cancelSelected');$(this).parents('form').submit(); return false;"><?=$this->transEsc('confirm_dialog_yes') ?></a></li>
              <li><a href="#" onClick="return false;"><?=$this->transEsc('confirm_dialog_no')?></a></li>
            </ul>
          </div>
          <div class="btn-group">
            <input id="cancelAll" name="cancelAll" type="submit" value="<?=$this->transEsc("hold_cancel_all") ?>" class="btn btn-default dropdown-toggle" data-toggle="dropdown"/>
            <ul class="dropdown-menu">
              <li class="disabled"><a><?=$this->transEsc("confirm_hold_cancel_all_text") ?></a></li>
              <li><a href="#" onClick="$('#cancelConfirm').val(1);$('#submitType').attr('name','cancelAll');$(this).parents('form').submit(); return false;"><?=$this->transEsc('confirm_dialog_yes') ?></a></li>
              <li><a href="#" onClick="return false;"><?=$this->transEsc('confirm_dialog_no')?></a></li>
            </ul>
          </div>
          </form>
      <? break; endif; ?>
    <? endforeach; ?>
    <? foreach($this->libraryIdentities as $eppn => $libraryIdentity):
        $source = explode('.', $libraryIdentity['cat_username'])[0]; ?>

      <h3 class="well row blickable" style="margin-bottom: 3px;">
      <?=$this->transEsc("source_$source", null, $source) ?>
      <img class="pull-right" height="32" src="<?=$this->logos()->getLogo($source) ?>"/>
      </h3>

    <?=$this->render('myresearch/holds-from-identity.phtml', [ 'libraryIdentity' => $libraryIdentity] )?>

    <? endforeach; ?>
    <? else: // Here we know we need to use asynchronous holdings?>
        <form hidden="hidden" name="cancelForm" class="inline" method="post" id="cancelHold">
          <input type="hidden" id="submitType" name="cancelSelected" value="1"/>
          <input type="hidden" id="cancelConfirm" name="confirm" value="0"/>
          <div class="btn-group">
            <input id="cancelSelected" name="cancelSelected" type="submit" value="<?=$this->transEsc("hold_cancel_selected") ?>" class="btn btn-default dropdown-toggle" data-toggle="dropdown"/>
            <ul class="dropdown-menu">
              <li class="disabled"><a><?=$this->transEsc("confirm_hold_cancel_selected_text") ?></a></li>
              <li><a href="#" onClick="$('#cancelConfirm').val(1);$('#submitType').attr('name','cancelSelected');$(this).parents('form').submit(); return false;"><?=$this->transEsc('confirm_dialog_yes') ?></a></li>
              <li><a href="#" onClick="return false;"><?=$this->transEsc('confirm_dialog_no')?></a></li>
            </ul>
          </div>
          <div class="btn-group">
            <input id="cancelAll" name="cancelAll" type="submit" value="<?=$this->transEsc("hold_cancel_all") ?>" class="btn btn-default dropdown-toggle" data-toggle="dropdown"/>
            <ul class="dropdown-menu">
              <li class="disabled"><a><?=$this->transEsc("confirm_hold_cancel_all_text") ?></a></li>
              <li><a href="#" onClick="$('#cancelConfirm').val(1);$('#submitType').attr('name','cancelAll');$(this).parents('form').submit(); return false;"><?=$this->transEsc('confirm_dialog_yes') ?></a></li>
              <li><a href="#" onClick="return false;"><?=$this->transEsc('confirm_dialog_no')?></a></li>
            </ul>
          </div>
          </form>

    <? foreach($this->libraryIdentities as $eppn => $libraryIdentity):
        $source = explode('.', $libraryIdentity->cat_username)[0]; ?>

      <h3 class="well row" style="margin-bottom: 3px;" id="<?=$source?>">
      <?=$this->transEsc("source_$source", null, $source) ?>
      <img class="pull-right" height="32" src="<?=$this->logos()->getLogo($source) ?>"/>
      </h3>

      <div id="<?=$libraryIdentity->cat_username?>" data-type="loadingDiv" class="row well" style="margin-bottom: 2px;">
        <i class="fa fa-spinner fa-spin"></i>
        <span class="label label-primary"><?=$this->transEsc('Loading')?> ...</span>
      </div>
    <? endforeach; ?>
    <? endif; ?>
  </div>

  <div class="<?=$this->layoutClass('sidebar')?>">
    <?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'holds'))?>
  </div>
</div>
