<h4><?=$this->transEsc('Your Account')?></h4>
<ul class="list-group">
  <? $user = $this->auth()->isLoggedIn(); if ($user['home_library'] !== 'Dummy'): ?>
	  <? if ('ils-none' !== $this->ils()->getOfflineMode()): ?>
	    <a href="<?=$this->url('myresearch-checkedout')?>" class="list-group-item<?=$this->active == 'checkedout' ? ' active' : ''?>">
	      <?=$this->transEsc('Checked Out Items')?>
	      <span class="pull-right"><i class="icon-typ-kniha"></i></span>
	    </a>
	    <a href="<?=$this->url('myresearch-holds')?>" class="list-group-item<?=$this->active == 'holds' ? ' active' : ''?>">
	      <?=$this->transEsc('Holds and Recalls')?>
	      <span class="pull-right"><i class="icon-rezervace2"></i></span>
	    </a>
	    <? if ($this->ils()->checkFunction('StorageRetrievalRequests')): ?>
	      <a href="<?=$this->url('myresearch-storageretrievalrequests')?>" class="list-group-item<?=$this->active == 'storageRetrievalRequests' ? ' active' : ''?>">
		<?=$this->transEsc('Storage Retrieval Requests')?>
		<span class="pull-right"><i class="fa fa-archive"></i></span>
	      </a>
	    <? endif; ?>
	    <a href="<?=$this->url('myresearch-fines')?>" class="list-group-item<?=$this->active == 'fines' ? ' active' : ''?>">
	      <?=$this->transEsc('Fines and Charges')?>
	      <span class="pull-right"><i class="icon-za-poplatek"></i></span>
	    </a>
	    <a href="<?=$this->url('myresearch-profile')?>" class="list-group-item<?=$this->active == 'profile' ? ' active' : ''?>">
	      <?=$this->transEsc('Profile')?>
	      <span class="pull-right"><i class="icon-profil"></i></span>
	    </a>

	    <? if (! empty($user['major'])): ?>
	      <a href="<?=$this->url('statistics-dashboard')?>" class="list-group-item<?=$this->active == 'statistics' ? ' active' : ''?>">
	        <?=$this->transEsc('Statistics')?>
	        <span class="pull-right"><i class="fa fa-info"></i></span>
	      </a>
	    <? endif; ?>

	  <? endif; ?>
  <? endif; ?>
  <? if ($user && $user->libraryCardsEnabled()): ?>
    <a href="<?=$this->url('librarycards-home')?>" class="list-group-item<?=$this->active == 'librarycards' ? ' active' : ''?>">
      <?=$this->transEsc('Linked accounts')?>
      <span class="pull-right"><i class="icon-propojene-identity"></i></span>
    </a>
  <? endif; ?>
  <a href="<?=$this->url('search-history')?>?require_login" class="list-group-item<?=$this->active == 'history' ? ' active' : ''?>">
    <?=$this->transEsc('Search History')?>
    <span class="pull-right"><i class="icon-hledani"></i></span>
  </a>
  <? if ($user = $this->auth()->isLoggedIn()): ?>
    <a href="<?=$this->url('myresearch-logout')?>" class="list-group-item">
      <?=$this->transEsc("Log Out")?>
      <span class="pull-right"><i class="icon-odhlasit"></i></span>
    </a>
  <? endif; ?>
</ul>
<? if ($this->auth()->isLoggedIn() && $this->auth()->getManager()->supportsPasswordChange()): ?>
  <h4><?=$this->transEsc('Preferences')?></h4>
  <ul class="list-group">
    <a href="<?=$this->url('myresearch-changepassword') ?>" class="list-group-item<?=$this->active == 'newpassword' ? ' active' : ''?>">
      <?=$this->transEsc('Change Password') ?>
      <span class="pull-right"><i class="fa fa-lock"></i></span>
    </a>
  </ul>
<? endif; ?>
<? if ($this->userlist()->getMode() !== 'disabled' && $user = $this->auth()->isLoggedIn()): ?>
  <ul class="list-group">
    <a href="<?=$this->url('myresearch-favorites')?>" class="list-group-item<?=$this->active == 'favorites' ? ' active' : ''?>">
      <?=$this->transEsc('Your Favorites')?>
      <span class="pull-right"><i class="icon-oblibene"></i></span>
    </a>
    <? $lists = $user->getLists() ?>
    <div style=" margin-left: 15px; ">
    <? foreach ($lists as $list): ?>
        <a href="<?=$this->url('userList', array('id' => $list['id']))?>" class="list-group-item<?=$this->active == 'list' . $list['id'] ? ' active' : ''?>">
          <?=$this->escapeHtml($list['title'])?>
          <span class="badge"><?=$list->cnt?></span>
        </a>
    <? endforeach; ?>
    </div>
    <a href="<?=$this->url('editList', array('id'=>'NEW'))?>" title="<?=$this->transEsc('Create a List') ?>" class="list-group-item">
      <?=$this->transEsc('Create a List') ?>
      <span class="pull-right"><i class="fa fa-plus"></i></span>
    </a>
  </ul>
<? endif ?>
