<?

  // Set up page title:
  $this->headTitle(isset($list) ? $list->title : $this->translate('Favorites'));

  // Load Javascript dependencies into header:
  $this->headScript()->appendFile("vendor/angular.min.js"); // AngularJS (we have a really complex problem needed to solve, so let's use MVC)
  $this->headScript()->appendFile("favorites-notlogged.js"); // the so called "favorites" AngularJS app module
    
  // Set up breadcrumbs:
  $currPage = isset($list) ? 'List' : 'Favorites';
  $this->layout()->breadcrumbs = '<li class="active">' . $this->transEsc($currPage) . '</li>';
?>


<?=$this->flashmessages()?>
<ul class="breadcrumb hidden-print"><?=$this->layout()->breadcrumbs ?></ul>
<div class="row" ng-app="favorites" ng-controller="MainController as ctrl">
  <div class="<?=$this->layoutClass('mainbody')?>">
    <div class="clearfix hidden-print">
      <h2 class="pull-left flip">{{ctrl.listTitle}}</h2>
      <div class="pull-right flip">
        <div ng-show="{{ctrl.editModeActive}}">
            <a href="#" ng-click="ctrl.editList(ctrl.listId)" class="btn btn-link" title="<?=$this->transEsc("edit_list")?>"><i class="fa fa-edit"></i> <?=$this->transEsc("edit_list")?></a>
            <div class="btn-group">
              <a class="btn btn-link dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-trash-o"></i> <?=$this->transEsc("delete_list")?>
              </a>
              <ul class="dropdown-menu">
                <li><a href="#" ng-click="ctrl.deleteList(ctrl.listId)"><?=$this->transEsc('confirm_dialog_yes') ?></a></li>
                <li><a href="#"><?=$this->transEsc('confirm_dialog_no')?></a></li>
              </ul>
            </div>
        </div>
        <div ng-hide="{{ctrl.editModeActive}}">
          <?=$this->transEsc("Showing")?>
          <strong>{{ctrl.pagesInterval.from}}</strong> - <strong>{{ctrl.pagesInterval.to}}</strong>
          <?=$this->transEsc('of')?> <strong>{{ctrl.pagesTotal}}</strong>
        </div>
      </div>
    </div>
    <p>{{ctrl.description}}</p>
    <div ng-hide="{{ctrl.listEmpty}}">
      <div class="resulthead">
        <div class="pull-right flip">
          Zde přehled sortace .. <b>TODO !!</b>
        </div>
      </div>
      <form class="form-inline" method="post" name="bulkActionForm" action="#" ng-submit="ctrl.submitBulk()" ng-controller="FavoritesFormController as favCtrl">
        
  <div class="checkbox">
    <label>
      <input type="checkbox" name="selectAll" class="checkbox-select-all"/>
      <?=$this->transEsc('select_page')?> | <?=$this->transEsc('with_selected')?>:
    </label>
  </div>
  <div class="btn-group">
    <input class="btn btn-default" type="submit" name="email" value="<?=$this->transEsc('Email')?>" title="<?=$this->transEsc('email_selected')?>"/>
  
    <input class="btn btn-default" id="delete_list_items_{{ctrl.listId}}" type="submit" name="delete" value="<?=$this->transEsc('Delete')?>" title="<?=$this->transEsc('delete_selected')?>"/>
    <input class="btn btn-default" type="submit" name="export" value="<?=$this->transEsc('Export')?>" title="<?=$this->transEsc('export_selected')?>"/>
    <input class="btn btn-default" type="submit" name="print" value="<?=$this->transEsc('Print')?>" title="<?=$this->transEsc('print_selected')?>"/>
    
    
    
    
    
    
    
    
    
    
    <h1>Prozatím nefunkční ukázka</h1>
    
  </div>


      </form>
      
      Zde paginace .. <b>TODO !!</b>
    </div>
    <div ng-show="{{ctrl.listEmpty}}">
      <p><?=$this->transEsc('You do not have any saved resources')?></p>
    </div>
  </div>
</div>
<img src="http://docs.devel.mzk.cz/shib/Sn%edmek%20obrazovky%20-%2019.1.2016%20-%2010:18:50.png" title="Pro srovnání ..." alt="Pro srovnání ..." style="border:3px black solid" />