<?
    // Set up page title:
    $this->headTitle($this->translate('Profile'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/">' . $this->transEsc('Main page') . '</a></li> '.
    '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Profile') . '</li>';

    // Template for use by the renderArray helper:
    $arrTemplate = '<tr><th>%%LABEL%%:</th><td>%%VALUE%%</td></tr>';

    $asyncTemplate = '<tr hidden="hidden" data-key="%%KEY%%"><th>%%LABEL%%:</th><td></td></tr>';

    $isSynchronous = $this->isSynchronous;

    if (! $isSynchronous)
        $this->headScript()->appendFile("async-profile.js");
?>
<ul class="breadcrumb hidden-print"><?=$this->layout()->breadcrumbs ?></ul>
<div class="row">
  <div class="<?=$this->layoutClass('mainbody')?>">
    <h2><?=$this->transEsc('Profile')?></h2>
    <?=$this->flashmessages();?>
    <? foreach($this->libraryIdentities as $eppn => $libraryIdentity):
        $source = explode('.', $libraryIdentity->profile['cat_username'])[0];?>
    <div class="well blickable" id="<?=$source?>">
    <h3>
    <?=$this->transEsc("source_$source", null, $source) ?>
    <img class="pull-right" height="32" src="<?=$this->logos()->getLogo($source) ?>"/>
    </h3>
    <? if ($isSynchronous): ?>

    <table class="table">
      <?
        echo $this->renderArray(
          $arrTemplate, $libraryIdentity->profile,
          array(
            $this->transEsc('First Name') => 'firstname',
            $this->transEsc('Last Name') => 'lastname'
          )
        );
       ?>
      <? if (isset($libraryIdentity->pickup) && count($libraryIdentity->pickup) > 1): // Only display home library form if we have multiple pickup locations ?>
        <tr><th><?=$this->transEsc('Preferred Library')?>:</th>
        <?
          $selected = (isset($libraryIdentity->profile['home_library']) && $libraryIdentity->profile['home_library'] != "")
              ? $libraryIdentity->profile['home_library'] : $libraryIdentity->defaultPickupLocation
        ?>
        <td>
          <form id="profile_form" class="form-inline" action="" method="post">
            <select id="home_library" name="home_library" class="form-control">
              <? foreach ($libraryIdentity->pickup as $lib): ?>
                <option value="<?=$this->escapeHtmlAttr($lib['locationID'])?>"<?=($selected == $lib['locationID'])?' selected="selected"':''?>><?=$this->escapeHtml($lib['locationDisplay'])?></option>
              <? endforeach; ?>
            </select>
            <input class="btn btn-default" type="submit" value="<?=$this->transEsc('Save')?>" />
          </form>
        </td>
      <? endif; ?>
      <?
        echo $this->renderArray(
          $arrTemplate, $libraryIdentity->profile,
          array(
            $this->transEsc('Address') . ' 1' => 'address1',
            $this->transEsc('Address') . ' 2' => 'address2',
            $this->transEsc('Zip') => 'zip',
            $this->transEsc('City') => 'city',
            $this->transEsc('Country') => 'country',
            $this->transEsc('Phone Number') => 'phone',
            $this->transEsc('Email Address') => 'email',
            $this->transEsc('Group') => 'group',
            $this->transEsc('Expire') => 'expire'
          )
        );
      ?>
    </table>

    <? if (isset($libraryIdentity->profile['prolongRegistrationUrl'])):?>
      <a href="<?=$libraryIdentity->profile['prolongRegistrationUrl']?>"><?=$this->transEsc('Prolong your registration')?></a>
    <? endif; ?>
    <? else: // We have some async deal here .. ?>

      <table id="<?=$libraryIdentity->profile['cat_username']?>" class="table">
        <caption data-type="loading-info">
                <i class="fa fa-spinner fa-spin"></i>
                <span class="label label-primary"><?=$this->transEsc('Loading')?> ...</span>
        </caption>
        <tbody>
        <?
        // We will call CPK\View\Helper\CPK\RenderArray class with async option
            echo $this->renderArray(
            $asyncTemplate, null,
            array(
                $this->transEsc('First Name') => 'firstname',
                $this->transEsc('Last Name') => 'lastname',
                $this->transEsc('Address') . ' 1' => 'address1',
                $this->transEsc('Address') . ' 2' => 'address2',
                $this->transEsc('Zip') => 'zip',
                $this->transEsc('City') => 'city',
                $this->transEsc('Country') => 'country',
                $this->transEsc('Phone Number') => 'phone',
                $this->transEsc('Email Address') => 'email',
                $this->transEsc('Group') => 'group',
                $this->transEsc('Expire') => 'expire'
            ),
                true
            );
        ?>
        </tbody>
      </table>
    <? endif; ?>
    </div>
  <? endforeach; ?>

  </div>

  <div class="<?=$this->layoutClass('sidebar')?>">
    <?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'profile'))?>
  </div>
</div>