<?
    // Set up page title:
    $this->headTitle($this->translate('Settings'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Settings') . '</li>';
?>

<div class="row">
  <div class="<?=$this->layoutClass('mainbody')?>">
    <h2><?=$this->transEsc('Settings') ?></h2>
    <div class='well'>
      <fieldset>
        <legend><?=$this->translate('Citations style') ?></legend>
        <select name='citation_style'>
        <? foreach ($this->availableCitationStyles as $style): ?>
        <option id='<?=$style['id']?>'><?=$style['description']?></option>
        <? endforeach; ?>
        </select>
      </fieldset>
    </div>
  </div>

  <div class="<?=$this->layoutClass('sidebar')?>">
    <?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'settings'))?>
  </div>
</div>
