<?
    // Set up page title:
    $this->headTitle($this->translate('Settings'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Settings') . '</li>';
?>

<div class="row">
  <div class="<?=$this->layoutClass('mainbody')?>">
    <h2><?=$this->transEsc('Settings') ?></h2>
    <div class='well'>
      <fieldset>
        <legend><?=$this->translate('Citations style') ?></legend>
        <select name='citation_style'>
          <option value='asd'>ČSN ISO 690</option>
          <option value='asd'>Harvard</option>
          <option value='asd'>NISO/ANSI Z39.29 (2005)</option>
          <option value='asd'>MLA (7th edition)</option>
          <option value='asd'>Turabian (7th edition)</option>
          <option value='asd'>Chicago (16th edition)</option>
          <option value='asd'>IEEE</option>
          <option value='asd'>CSE</option>
          <option value='asd'>CSE NY</option>
          <option value='asd'>APA</option>
          <option value='asd'>ISO 690</option>
        </select>
      </fieldset>
    </div>
  </div>

  <div class="<?=$this->layoutClass('sidebar')?>">
    <?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'settings'))?>
  </div>
</div>
