<?
  $account = $this->auth()->getManager();
  $user = $account->isLoggedIn();
  $userEmail = '';
  if ($user && isset($user->email)) {
      $userEmail = $user->email;
  }
  $query = array();
  parse_str($_SERVER['QUERY_STRING'], $query);
  $currentUrl = $this->url(null, array(), array('query' => $query, 'force_canonical' => true));
  $feedbackParams = array (
    'formkey'   => 'dHN5S2pMa0pEYnJyQUtzbWU3Wm9YcWc6MQ',
    'entry_3'   => $currentUrl,
    'entry_4'   => $userEmail,
    'TB_iframe' => 'true',
    'height'    => '600',
    'width'     => '600',
  );
  $feedbackUrl = "https://docs.google.com/spreadsheet/viewform?" . http_build_query($feedbackParams);
  $openSearchUrl = (string) $this->url('search-opensearch', array(), array('query' => array('method' => 'describe'), 'force_canonical' => true));
  $openSearchHref = "javascript:window.external.AddSearchProvider('" . $openSearchUrl . "');";
?>
<hr/>
<div class="col-md-12 row small">
  <div class="col-sm-4 col-md-offset-0"><p><strong><?=$this->transEsc('Search Options')?></strong></p>
    <ul>
      <? if ($mobileViewLink = $this->mobileUrl()): // display 'return to mobile' link when applicable ?>
        <li><a href="<?=$this->escapeHtmlAttr($mobileViewLink)?>"><?=$this->transEsc("mobile_link")?></a></li>
      <? endif; ?>
      <li><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></li>
      <li><a href="<?=$this->url('search-conspectus')?>"><?=$this->transEsc('Conspectus')?></a></li>
      <li><a href="<?=$this->url('search-newacquisitions')?>"><?=$this->transEsc('New acquisitions')?></a></li>
      <li><a href="<?=$openSearchHref?>"><?=$this->transEsc('Add as search engine')?></a></li>
    </ul>
  </div>
  <div class="col-sm-4"><p><strong><?=$this->transEsc('Find More')?></strong></p>
    <ul>
      <li><a href="<?=$this->url('alphabrowse-home')?>"><?=$this->transEsc('Browse Alphabetically')?></a></li>
      <li><a href="https://listky.mzk.cz/"><?=$this->transEsc('Card Catalogues')?></a></li>
      <li><a href="http://www.mzk.cz/en/services/borrowing/international-interlibrary-loan-service"><?=$this->transEsc('Interlibrary loan')?></a></li>
    </ul>
  </div>
  <div class="col-sm-4"><p><strong><?=$this->transEsc('Need Help?')?></strong></p>
    <ul>
      <li><a href="<?=$this->url('help-home')?>?topic=search" class="help-link" title="<?=$this->transEsc('Search Tips')?>"><?=$this->transEsc('Search Tips')?></a></li>
      <li><a href="http://www.ptejteseknihovny.cz/zadani-dotazu?q=BOA001"><?=$this->transEsc('Ask a Librarian')?></a></li>
      <li><a href="http://www.mzk.cz/faq"><?=$this->transEsc('FAQs')?></a></li>
      <li><a href="<?=$feedbackUrl?>" class="lightbox"><?=$this->transEsc('Feedback')?></a></li>
    </ul>
  </div>
</div>
