<? $account = $this->auth()->getManager(); ?>
<div class="navbar header">

  <div>
  <? if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
    <ul class="nav navbar-nav pull-right">
      <? foreach ($this->layout()->allLangs as $langCode => $langName): ?>
        <?
          $langImg = 'lang/' . $langCode . '.png';
          $queryParams = array('lng' => $langCode);
          parse_str($_SERVER['QUERY_STRING'], $params);
          $queryParams = array_merge($params, $queryParams);
        ?>
        <li>
          <a class="language" href="<?=$this->url(null, array(), array('query' => $queryParams), true);?>">
            <img class="langFlag" src="<?=$this->imageLink($langImg)?>" alt="<?=$langName?>" />
            <?=$this->displayLanguageOption($langName)?>
          </a>
        </li>
      <? endforeach; ?>
    </ul>
  <? endif; ?>
  </div>
</div>

  <div class="navbar header">

    <? if ($this->layout()->frontpage == false): ?>
      <ul class="nav navbar-nav pull-left">
        <li class="header-logo">
          <a href="http://www.mzk.cz/"><img src="<?=$this->imageLink('logo-mzk.png') ?>"></img></a>
        </li>
        <li>
          <? if ($this->layout()->searchbox !== false): ?>
            <?=$this->layout()->searchbox?>
          <? endif;?>
        </li>
      </ul>
    <? endif; ?>

    <ul class="nav navbar-nav pull-right">
      
      
      <? if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
        <li>
          <div class="loginbox">
            <? if($account->isLoggedIn()): ?>
              <a href="<?=$this->url('myresearch-home')?>" class="myresearch" title="<?=$this->transEsc("MyResearch")?>"><?=$this->transEsc("MyResearch")?></a>
              <a href="<?=$this->url('myresearch-logout')?>" class="logout" title="<?=$this->transEsc("Log Out")?>"><?=$this->transEsc("Log Out")?></a>
            <? else:?>
              <a href="https://www.mzk.cz/registration_mzk" title="<?=$this->transEsc("Register")?>" class="register"><?=$this->transEsc("Register")?></a>
              <? if ($sessionInitiator = $account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
                <a href="<?=$this->escapeHtml($sessionInitiator)?>" class="login"><?=$this->transEsc("Login")?></a>
              <? else: ?>
                <a href="<?=$this->url('myresearch-home')?>" class="login" title="<?=$this->transEsc("Login")?>"><?=$this->transEsc("Login")?></a>
              <? endif; ?>
            <? endif; ?>
          </div>
          <? if ($this->layout()->frontpage == false): ?>
            <? $cart = $this->cart(); if ($cart->isActive()): ?>
              <span id="cartSummary">
                <a id="cartItems" class="modal-link" title="<?=$this->transEsc('View Book Bag')?>" href="<?=$this->url('cart-home')?>">
                  <?=$this->transEsc('Number of items in book bag')?>:
                  <strong><?=count($cart->getItems())?></strong>
                  <?=$cart->isFull() ? ' (' .  $this->transEsc('bookbag_full') . ')' : ''?>
                </a>
              </span>
            <? endif; ?>
          <? endif; ?>
        </li>
      <? endif; ?>
      
    </ul>

    <div class="header-finisher"></div>

  </div>
<!--
</nav>
 -->