<meta property="og:url"
      content="https://mus.knihovny.cz/" />
<meta property="og:title"
      content="Oborová brána MUS" />
<meta property="og:description"
      content="Oborová brána MUS -  jednotný přístup k informačním zdrojům v oblasti hudby a hudební vědy" />
<meta property="og:image"
      content="https://www.knihovny.cz/themes/bootstrap3/images/screenshot_20171130.png" />
<meta property="og:image:secure_url"
      content="https://www.knihovny.cz/themes/bootstrap3/images/screenshot_20171130.png" />
<meta property="og:image:type"
      content="image/png" />
<meta name="referrer"
      content="unsafe-url" />
<link href="/themes/bootstrap3/images/icon-mus.png" rel="icon" type="image/png">
