<?php
// Set page title.
$this->headTitle('Ziskej Alpha');

// Disable search box
$this->layout()->searchbox = false;
?>

<?=$this->flashmessages() ?>

<!-- ziskej select mode -->
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><?=$this->translate('ziskej_settings_title_mode') ?></h3>
  </div>
  <div class="panel-body">
    <form action="<?=$this->url('ziskej') ?>" id="ziskejForm" method="post" name="ziskejForm">
      <div class="form-group">
        <label for="selectZiskejMvs"><?=$this->translate('label_ziskej_mvs_mode') ?>: </label>
        <select name="ziskejMvsMode" class="form-control" id="selectZiskejMvs">
          <?php foreach ($this->Ziskej()->getModes() as $mode): ?>
            <option value="<?=$this->escapeHtmlAttr($mode) ?>" <?php if ($mode == $this->Ziskej()->getCurrentMode()): ?>selected="selected"<?php endif; ?>>
              <?=$this->translate(sprintf('Ziskej_%s', $mode)) ?>
            </option>
          <?php endforeach; ?>
        </select>
      </div>
      <div class="form-group">
        <label for="selectZiskejEdd"><?=$this->translate('label_ziskej_edd_mode') ?>: </label>
        <select name="ziskejEddMode" class="form-control" id="selectZiskejEdd">
          <?php foreach ($this->ziskejEdd()->getModes() as $mode): ?>
            <option value="<?=$this->escapeHtmlAttr($mode) ?>" <?php if ($mode == $this->ZiskejEdd()->getCurrentMode()): ?>selected="selected"<?php endif; ?>>
              <?= $this->translate(sprintf('Ziskej_%s', $mode)) ?>
            </option>
          <?php endforeach; ?>
        </select>
      </div>
      <div class="form-group">
        <input class="btn btn-primary" type="submit" name="submitZiskej" title="<?=$this->translate('Set') ?>" value="<?=$this->translate('Set') ?>">
      </div>
    </form>
  </div>
</div>
<!-- /ziskej select mode -->

<?php if ($this->Ziskej()->isEnabled()): ?>

  <!-- user data -->
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><?=$this->translate('ziskej_settings_title_user') ?></h3>
    </div>
    <div class="panel-body">
      <?php if (!empty($this->user)): ?>
        <div class="row">
          <div class="col-md-6">
            <dl class="dl-horizontal">
              <dt>Username:</dt>
              <dd><?=$this->user->username ?></dd>
              <dt>Home library:</dt>
              <dd><?=$this->user->home_library ?></dd>
            </dl>
          </div>
          <div class="col-md-6">
            <dl class="dl-horizontal">
              <dt>First name:</dt>
              <dd><?=$this->user->firstname ?></dd>
              <dt>Last name:</dt>
              <dd><?=$this->user->lastname ?></dd>
              <dt>Email:</dt>
              <dd><?=$this->user->email ?></dd>
            </dl>
          </div>
        </div>
      <?php else: ?>
        <div class="alert alert-warning text-center">
          <?=$this->translate('message_no_user_logged_in') ?>
        </div>
      <?php endif; ?>
    </div>
  </div>
  <!-- /user data -->

  <!-- ziskej data -->
  <?php if (!empty($this->data)): ?>
    <div>
      <!-- Nav tabs -->
      <ul class="nav nav-tabs" role="tablist">
        <?php $i = 1; ?>
        <?php foreach ($this->data as $eppn => $row): ?>
          <li role="presentation" class="<?php if ($i === 1): ?>active<?php endif; ?>">
            <a href="#tab_<?=$i ?>" role="tab" data-toggle="tab"><?=$eppn ?></a>
          </li>
          <?php $i++; ?>
        <?php endforeach; ?>
      </ul>
      <!-- Tab panes -->
      <div class="tab-content">
        <?php $i = 1; ?>
        <?php foreach ($this->data as $eppn => $row): ?>
          <div class="tab-pane <?php if ($i === 1): ?>active<?php endif; ?>" id="tab_<?=$i ?>">
            <?php if ($row['library_in_ziskej']): ?>
              <?php
              /** @var Mzk\ZiskejApi\ResponseModel\Reader $reader */
              $reader = !empty($row['reader']) ? $row['reader'] : null;
              ?>
              <?php if ($reader): ?>
                <?php if (!$reader->isActive()): ?>
                  <div class="alert alert-warning text-center">
                    Reader is in Ziskej, but is not active
                  </div>
                <?php endif; ?>
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h3 class="panel-title">Reader</h3>
                  </div>
                  <div class="panel-body">
                    <div class="row">
                      <div class="col-md-6">
                        <dl class="dl-horizontal">
                          <dt>Is active</dt>
                          <dd><?=$reader->isActive() ? 'Yes' : 'No' ?></dd>
                          <dt>Eppn:</dt>
                          <dd><?=$eppn ?></dd>
                          <dt>Sigla</dt>
                          <dd><?=$reader->getSigla() ?></dd>
                        </dl>
                      </div>
                      <div class="col-md-6">
                        <dl class="dl-horizontal">
                          <dt>First name:</dt>
                          <dd><?=$reader->getFirstName() ?></dd>
                          <dt>Last name:</dt>
                          <dd><?=$reader->getLastName() ?></dd>
                          <dt>Email:</dt>
                          <dd><?=$reader->getEmail() ?></dd>
                        </dl>
                      </div>
                    </div>
                  </div>
                </div>
                <?php if ($reader->isActive()): ?>
                  <?php
                  /** @var array $tickets */
                  $tickets = $row['tickets'];
                  ?>
                  <div class="panel panel-default">
                    <div class="panel-heading">
                      <h3 class="panel-title">Tickets <span class="badge"><?=count($tickets) ?></span></h3>
                    </div>
                    <div class="panel-body">
                      <?php if (count($tickets)): ?>
                        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                          <?php
                          /** @var \Mzk\ZiskejApi\ResponseModel\Ticket $ticket */
                          foreach ($tickets as $ticketDuo):
                            $ticket = $ticketDuo['ticket'];
                            ?>
                            <div class="panel panel-default">
                              <div class="panel-heading" role="tab">
                                <h4 class="panel-title">
                                  <a role="button" data-toggle="collapse" href="#ticket_<?=$ticket->getHid() ?>">
                                    <?=$this->Datetime()->convertToDisplayDateAndTime('U', $ticket->getCreatedAt()->getTimestamp()) ?>
                                    | <?=$ticket->getId() ?>
                                    <span class="pull-right">
                                      <?php if (count($ticketDuo['messages'])): ?>
                                        <span class="badge"><?=count($ticketDuo['messages']) ?> messages</span>
                                      <?php endif; ?>
                                    </span>
                                  </a>
                                </h4>
                              </div>
                              <div id="ticket_<?=$ticket->getHid() ?>" class="panel-collapse collapse out" role="tabpanel">
                                <div class="panel-body">
                                  <div class="row">
                                    <div class="col-md-6">
                                      <dl class="dl-horizontal">
                                        <dt>ID:</dt>
                                        <dd><?=$ticket->getId() ?></dd>
                                        <dt>HID:</dt>
                                        <dd><?=$ticket->getHid() ?></dd>
                                        <dt>is_open:</dt>
                                        <dd><?=$ticket->isOpen() ?></dd>
                                        <dt>doc_id:</dt>
                                        <dd><?=$ticket->getDocumentId() ?></dd>
                                        <dt>sigla:</dt>
                                        <dd><?=$ticket->getSigla() ?></dd>
                                        <dt>status_reader :</dt>
                                        <dd><?=$ticket->getStatus() ?></dd>
                                      </dl>
                                    </div>
                                    <div class="col-md-6">
                                      <dl class="dl-horizontal">
                                        <dt>date_created:</dt>
                                        <dd><?=$this->Datetime()->convertToDisplayDateAndTime('U', $ticket->getCreatedAt()->getTimestamp()) ?></dd>
                                        <dt>date_requested:</dt>
                                        <dd>
                                          <?=!empty($ticket->getRequestedAt())
                                            ? $this->Datetime()->convertToDisplayDate('U', $ticket->getRequestedAt()->getTimestamp())
                                            : ''
                                          ?>
                                        </dd>
                                        <dt>date_return:</dt>
                                        <dd>
                                          <?=!empty($ticket->getReturnAt())
                                            ? $this->Datetime()->convertToDisplayDate('U', $ticket->getReturnAt()->getTimestamp())
                                            : ''
                                          ?>
                                        </dd>
                                      </dl>
                                    </div>
                                  </div>
                                  <hr>
                                </div>
                              </div>
                            </div>
                          <?php endforeach; ?>
                        </div>
                      <?php else: ?>
                        <div class="alert alert-info text-center">
                          No tickets
                        </div>
                      <?php endif; ?>
                    </div>
                  </div>
                <?php endif; ?>
              <?php else: ?>
                <div class="alert alert-warning text-center">
                  No reader in Ziskej
                </div>
              <?php endif; ?>
            <?php else: ?>
              <div class="alert alert-warning text-center">
                Library not in Ziskej
              </div>
            <?php endif ?>
          </div>
          <?php $i++; ?>
        <?php endforeach; ?>
      </div>
    </div>
  <?php endif; ?>
  <!-- /ziskej data -->

<?php endif; ?>
