<?
// Set page title.
$this->headTitle('Ziskej Alpha');

// Disable search box
$this->layout()->searchbox = false;
?>

<?= $this->flashmessages() ?>

<!-- ziskej select mode -->
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Získej mode</h3>
  </div>
  <div class="panel-body">
    <form action="<?= $this->url('ziskej') ?>" id="ziskejForm" method="post" name="ziskejForm">
    <div class="form-group">
        <label for="ziskejSelect">Mode: </label>
      <select name="ziskej" class="form-control" id="ziskejSelect">
          <? foreach ($this->ziskejModes as $mode): ?>
            <option value="<?= $this->escapeHtmlAttr($mode) ?>"
                    <? if ($mode == $this->ziskejCurrentMode): ?>selected="selected"<? endif; ?>>
              <?= $this->translate(sprintf('Ziskej_%s', $mode)) ?>
            </option>
          <? endforeach; ?>
      </select>
    </div>
    <div class="form-group">
      <input class="btn btn-primary" type="submit" name="submitZiskej" title="<?= $this->translate('Set') ?>"
             value="<?= $this->translate('Set') ?>">
    </div>
  </form>
</div>
</div>
<!-- /ziskej select mode -->

<? if ($this->ziskejCurrentMode !== 'disabled'): ?>

  <!-- user data -->
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Logged user</h3>
    </div>
    <div class="panel-body">
      <? if (!empty($this->userData)): ?>
        <div class="row">
          <div class="col-md-6">
            <dl class="dl-horizontal">
              <dt>Username:</dt>
              <dd><?= $this->userData['username']; ?></dd>
              <dt>Home library:</dt>
              <dd><?= $this->userData['home_library']; ?></dd>
            </dl>
          </div>
          <div class="col-md-6">
            <dl class="dl-horizontal">
              <dt>First name:</dt>
              <dd><?= $this->userData['firstname']; ?></dd>
              <dt>Last name:</dt>
              <dd><?= $this->userData['lastname']; ?></dd>
              <dt>Email:</dt>
              <dd><?= $this->userData['email']; ?></dd>
            </dl>
          </div>
        </div>
      <? else: ?>
        <div class="alert alert-warning text-center">
          No user logged in
        </div>
      <? endif; ?>
    </div>
  </div>
  <!-- /user data -->

  <!-- ziskej data -->
  <? if (!empty($this->ziskejData)): ?>
    <div>
      <!-- Nav tabs -->
      <ul class="nav nav-tabs" role="tablist">
        <? $i = 1; ?>
        <? foreach ($this->ziskejData as $eppn => $row): ?>
          <li role="presentation" class="<? if ($i === 1): ?>active<? endif; ?>">
            <a href="#tab_<?= $i; ?>" role="tab" data-toggle="tab"><?= $eppn; ?></a>
          </li>
          <? $i++; ?>
        <? endforeach; ?>
      </ul>
      <!-- Tab panes -->
      <div class="tab-content">
        <? $i = 1; ?>
        <? foreach ($this->ziskejData as $eppn => $row): ?>
          <div class="tab-pane <? if ($i === 1): ?>active<? endif; ?>" id="tab_<?= $i; ?>">
            <? if ($row['library_in_ziskej']): ?>
              <?
              /** @var Mzk\ZiskejApi\ResponseModel\Reader $reader */
              $reader = !empty($row['reader']) ? $row['reader'] : null;
              ?>
              <? if ($reader): ?>
                <? if (!$reader->isActive()): ?>
                  <div class="alert alert-warning text-center">
                    Reader is in Ziskej, but is not active
                  </div>
                <? endif; ?>
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h3 class="panel-title">Reader</h3>
                  </div>
                  <div class="panel-body">
                    <div class="row">
                      <div class="col-md-6">
                        <dl class="dl-horizontal">
                          <dt>Is active</dt>
                          <dd><?= $reader->isActive() ? 'Yes' : 'No'; ?></dd>
                          <dt>Eppn:</dt>
                          <dd><?= $eppn; ?></dd>
                          <dt>Sigla</dt>
                          <dd><?= $reader->getSigla(); ?></dd>
                        </dl>
                      </div>
                      <div class="col-md-6">
                        <dl class="dl-horizontal">
                          <dt>First name:</dt>
                          <dd><?= $reader->getFirstName(); ?></dd>
                          <dt>Last name:</dt>
                          <dd><?= $reader->getLastName(); ?></dd>
                          <dt>Email:</dt>
                          <dd><?= $reader->getEmail(); ?></dd>
                        </dl>
                      </div>
                    </div>
                  </div>
                </div>
                <? if ($reader->isActive()): ?>
                  <?
                  /** @var array $tickets */
                  $tickets = $row['tickets'];
                  ?>
                  <div class="panel panel-default">
                    <div class="panel-heading">
                      <h3 class="panel-title">Tickets <span class="badge"><?= count($tickets); ?></span></h3>
                    </div>
                    <div class="panel-body">
                      <? if (count($tickets)): ?>
                        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                          <? foreach ($tickets as $ticket): ?>
                            <div class="panel panel-default">
                              <div class="panel-heading" role="tab" id="headingOne">
                                <h4 class="panel-title">
                                  <a role="button" data-toggle="collapse" href="#ticket_<?= $ticket['ticket_id']; ?>">
                                    <?= $ticket['date_created']; ?> | <?= $ticket['ticket_id']; ?>
                                    <span class="pull-right">
                              <? if (count($ticket['messages'])): ?>
                                <span class="badge"><?= count($ticket['messages']); ?> messages</span>
                              <? endif; ?>
                            </span>
                                  </a>
                                </h4>
                              </div>
                              <div id="ticket_<?= $ticket['ticket_id']; ?>" class="panel-collapse collapse out"
                                   role="tabpanel">
                                <div class="panel-body">
                                  <div class="row">
                                    <div class="col-md-6">
                                      <dl class="dl-horizontal">
                                        <dt>is_open:</dt>
                                        <dd><?= $ticket['is_open']; ?></dd>
                                        <dt>doc_id:</dt>
                                        <dd><?= $ticket['doc_id']; ?></dd>
                                        <dt>sigla:</dt>
                                        <dd><?= $ticket['sigla']; ?></dd>
                                        <dt>status_reader :</dt>
                                        <dd><?= $ticket['status_reader']; ?></dd>
                                      </dl>
                                    </div>
                                    <div class="col-md-6">
                                      <dl class="dl-horizontal">
                                        <dt>date_created:</dt>
                                        <dd><?= $ticket['date_created']; ?></dd>
                                        <dt>date_requested:</dt>
                                        <dd><?= $ticket['date_requested']; ?></dd>
                                        <dt>date_return:</dt>
                                        <dd><?= $ticket['date_return']; ?></dd>
                                      </dl>
                                    </div>
                                  </div>
                                  <hr>
                                  <? if (count($ticket['messages'])): ?>
                                    <h4>Messages</h4>
                                    <div>
                                      <? foreach ($ticket['messages'] as $message): ?>
                                        <div>
                                          <dl class="dl-horizontal">
                                            <dt>date:</dt>
                                            <dd><?= $message['date']; ?></dd>
                                            <dt>sender:</dt>
                                            <dd><?= $message['sender']; ?></dd>
                                            <dt>text:</dt>
                                            <dd><?= $message['text']; ?></dd>
                                            <dt>unread :</dt>
                                            <dd><?= $message['unread']; ?></dd>
                                          </dl>
                                        </div>
                                      <? endforeach; ?>
                                    </div>
                                  <? endif; ?>
                                </div>
                              </div>
                            </div>
                          <? endforeach; ?>
                        </div>
                      <? else: ?>
                        <div class="alert alert-info text-center">
                          No tickets
                        </div>
                      <? endif; ?>
                    </div>
                  </div>
                <? endif; ?>
              <? else: ?>
                <div class="alert alert-warning text-center">
                  No reader in Ziskej
                </div>
              <? endif; ?>
            <? else: ?>
              <div class="alert alert-warning text-center">
                Library not in Ziskej
              </div>
            <? endif ?>
          </div>
          <? $i++; ?>
        <? endforeach; ?>
      </div>
    </div>
  <? endif; ?>
  <!-- /ziskej data -->

<? endif; ?>
