<?php
?>

<div class='clearfix'>

    <div class="col-md-8 record-mvs-description">
      <div class="row">
        <h3>Informace o uzivateli</h3>
        <p>Jmeno a prijmeni:  <?= $this->user['firstname'] ?> <?= $this->user['lastname'] ?></p>
        <p>Adresa</p>
      </div>
    </div>
    <div class="col-md-4">
      <form class="form " action="">
        <fieldset class="form-group">
          <label for="">Where to deliver</label>
          <select name="eppn" id="">
            <? if ($this->user): ?>
              <? foreach ($this->user->getSource() as $eppn): ?>
                <option>test</option> <!-- @TODO ?  -->
              <? endforeach;?>
            <? endif; ?>
          </select>
        </fieldset>
        <fieldset class="form-group">
          <label for="">Date requested</label>
          <input type="date" class="form-control" name="" id="" required>
        </fieldset>
        <fieldset class="form-group">
          <label for=""><?= $this->translate('Describe problem') ?></label>
          <textarea id=""
                    name='text'
                    class='form-control'
                    required><?= ($this->text) ? htmlspecialchars($this->text) : '' ?></textarea>
        </fieldset>
        <fieldset class="form-group">
          <input id="captcha_submit"
                 type='submit'
                 name="submitted"
                 class='btn btn-primary'
                 value='<?= $this->translate('Submit') ?>'
                 disabled>
        </fieldset>
      </form>
    </div>
</div>
