<?
// Set page title.
$this->headTitle('Ziskej');

// Disable search box
$this->layout()->searchbox = false;
?>

<div align="center">
  <form action="/ziskej" id="ziskejForm" method="post" name="ziskejForm">
    <div class="form-group">
      <label for="ziskejSelect">ZISKEJ</label>
      <select name="ziskej" class="form-control" id="ziskejSelect">
        <option value="off"><?= $this->translate('Ziskej_do_not_show') ?></option>
        <option value="prod"><?= $this->translate('Ziskej_prod') ?></option>
        <option value="demo"><?= $this->translate('Ziskej_demo') ?></option>
        <option value="test"><?= $this->translate('Ziskej_test') ?></option>
        <option value="dev"><?= $this->translate('Ziskej_dev') ?></option>
      </select>
    </div>
    <div class="form-group">
      <input class="btn btn-primary" type="submit" name="submitZiskej" title="<?= $this->translate('Set') ?>"
             value="<?= $this->translate('Set') ?>">
    </div>
  </form>
  <? if ($this->setting): ?>
    <div>
      <p><?= $this->translate('Configured') ?>: <strong><?= $this->setting ?></strong></p>
    </div>
  <? endif; ?>
</div>
