<?
// Set page title.
$this->headTitle('Ziskej Alpha');

// Disable search box
$this->layout()->searchbox = false;
?>

<div align="center">
  <form action="/ziskejalpha" id="ziskejForm" method="post" name="ziskejForm">
    <div class="form-group">
      <label for="ziskejSelect">ZISKEJ</label>
      <select name="ziskej" class="form-control" id="ziskejSelect">
          <? foreach ($this->ziskejConfig as $type): ?>
            <option
                value="<?= $this->escapeHtmlAttr($type) ?>"
                <?= $type == $this->setting ? 'selected' : '' ?>><?= $this->translate(sprintf('Ziskej_%s', $type)) ?></option>
          <? endforeach; ?>
      </select>
    </div>
    <div class="form-group">
      <input class="btn btn-primary" type="submit" name="submitZiskej" title="<?= $this->translate('Set') ?>"
             value="<?= $this->translate('Set') ?>">
    </div>
    <div>
<!--      --><?// if($this->redirect): ?>
<!--        <p>Your library is not registered in Ziskej or you not logged in<p>-->
<!--        <a href="--><?//=$this->redirect?><!--">-->
<!--            --><?//= $this->translate('Please register via this link or log in') ?>
<!--        </a>-->
<!--      --><?// endif; ?>
<!--      <p>--><?//= $this->messages ?><!--</p>-->
    </div>
  </form>
  <div>
    <p></p>
  </div>
</div>
