<?
  // Set page title.
  $this->headTitle('Ziskej Alpha');

  // Disable search box
  $this->layout()->searchbox = false;
?>

<div align="center">
  <div class="row">
    <div class="<? if ($this->reader): ?>col-md-6<? else: ?> col-md-12 <? endif; ?>">
      <form action="<?= $this->url('ziskej') ?>" id="ziskejForm" method="post" name="ziskejForm">
        <div class="form-group">
          <label for="ziskejSelect">ZISKEJ</label>
          <select name="ziskej" class="form-control" id="ziskejSelect">
            <? foreach ($this->ziskejConfig as $type): ?>
              <option value="<?= $this->escapeHtmlAttr($type) ?>"
                      <? if ($type == $this->setting): ?>selected="selected"<? endif; ?>><?= $this->translate(sprintf('Ziskej_%s',
                  $type)) ?></option>
            <? endforeach; ?>
          </select>
        </div>
        <div class="form-group">
          <input class="btn btn-primary" type="submit" name="submitZiskej" title="<?= $this->translate('Set') ?>"
                 value="<?= $this->translate('Set') ?>">
        </div>
      </form>
    </div>
    <? if ($this->setting != 'disabled'): ?>
      <? if ($this->reader): ?>
        <div class="col-md-6">
          <form action="<?= $this->url('ziskej-createticket') ?>"
                id="createZiskejTicket"
                method="post"
                name="createZiskejTicket">
            <div class="form-group" id="createTicketZiskejForm">
              <label for="recordId">Record ID</label>
              <input type="text" id="recordId" class="form-control" name="recordId" required>
            </div>
            <div class="form-group">
              <div id="ziskejErrMsg"></div>
              <input class="btn btn-primary"
                     type="submit"
                     name="submitTicket"
                     title="<?= $this->translate('Create') ?>"
                     value="<?= $this->translate('Create') ?>">
            </div>
          </form>
          <?= $this->flashmessages() ?>
        </div>
        </div>
        <div class="row">
          <div class="clearfix well border table-core">
            <div class="col-sm-12">
              <table class="table">
                  <tbody>
                  <? if ($this->reader['is_gdpr_data']): ?>
                    <tr>
                      <th class="col-md-3">First Name</th>
                      <td><?= $this->escapeHtml($this->reader['first_name']) ?></td>
                    </tr>
                    <tr>
                      <th class="col-md-3">Last Name</th>
                      <td><?= $this->escapeHtml($this->reader['last_name']) ?></td>
                    </tr>
                    <tr>
                      <th class="col-md-3">Email</th>
                      <td><?= $this->escapeHtml($this->reader['email']) ?></td>
                    </tr>
                  <? else: ?>
                    <tr>
                      <th>NEJSOU SOUHLASY S ULOZENIM DAT</th>
                    </tr>
                  <? endif; ?>
                  </tbody>
                </table>
            </div>
          </div>
          <? if ( ! empty($this->ticketDetails)): ?>
            <? foreach ($this->ticketDetails as $ticketDetail): ?>
              <div class="row">
                <div class="col-md-4" id="myList">
                  <div class="list-group">
                    <a href="#tab_<?= $this->escapeHtmlAttr($ticketDetail['ticket_id']) ?>"
                       id="<?= $this->escapeHtmlAttr($ticketDetail['ticket_id']) ?>"
                       class="list-group-item"><?= $this->escapeHtml($ticketDetail['doc_id']) ?></a>
                  </div>
                </div>
                <div class="col-md-8">
                  <div class="tab-content" id="nav-tabContent">
                    <div class="tab hidden" id="tab_<?= $this->escapeHtmlAttr($ticketDetail['ticket_id']) ?>">
                      <div class="clearfix well border table-core">
                        <table class="table">
                          <tbody>
                            <tr>
                              <th class="col-md-3">sigla</th>
                              <td><?= $this->escapeHtml($ticketDetail['sigla']) ?></td>
                            </tr>
                            <tr>
                              <th class="col-md-3">link</th>
                              <td><a href="/Record/<?= $ticketDetail['doc_id'] ?>"><?= $ticketDetail['doc_id'] ?></a></td>
                            </tr>
                            <tr>
                              <th class="col-md-3">is open</th>
                              <td><? if ($ticketDetail['is_open']): ?>Yes<? else: ?>No<? endif; ?></td>
                            </tr>
                            <tr>
                              <th class="col-md-3">date requested</th>
                              <td><?= $this->escapeHtml($ticketDetail['date_requested']) ?></td>
                            </tr>
                            <tr>
                              <th class="col-md-3">date created</th>
                              <td><?= $this->escapeHtml($ticketDetail['date_created']) ?></td>
                            </tr>
                            <tr>
                              <th class="col-md-3">ticket id</th>
                              <td><?= $this->escapeHtml($ticketDetail['ticket_id']) ?></td>
                            </tr>
                            <tr>
                              <th class="col-md-3">count messages</th>
                              <td><?= $this->escapeHtml($ticketDetail['count_messages']) ?></td>
                            </tr>
                            <tr>
                              <th class="col-md-3">status</th>
                              <td><?= $this->escapeHtml($ticketDetail['status_label']) ?></td>
                            </tr>
                            <tr>
                              <th class="col-md-3">Write message</th>
                              <td>
                                <form action=""
                                      method="post"
                                      name="ticketMessages"
                                      id="ticketMessages_<?= $this->escapeHtmlAttr($ticketDetail['ticket_id']) ?>">
                                  <div class="form-group">
                                    <label for="ticketMessage_<?= $this->escapeHtmlAttr($ticketDetail['ticket_id']) ?>"></label>
                                    <textarea class="form-control"
                                              id="ticketMessage_<?= $this->escapeHtmlAttr($ticketDetail['ticket_id']) ?>"
                                              rows="3"
                                              name="ticketMessage"
                                              required></textarea>
                                    <div align="center">
                                      <input class="btn btn-primary"
                                             type="submit"
                                             name="submitMessage"
                                             title="<?= $this->translate('Send Message') ?>"
                                             value="<?= $this->translate('Send Message') ?>">
                                    </div>
                                  </div>
                                </form>
                              </td>
                            </tr>
                            <? if ($ticketDetail['count_messages'] > 0): ?>
                              <tr>
                                <th class="col-md-3">Messages</th>
                                <td>
                                  <ul class="list-group"
                                      id="messages_<?= $this->escapeHtmlAttr($ticketDetail['ticket_id']) ?>">
                                    <? foreach ($ticketDetail['messages'] as $message): ?>
                                      <li class="list-group-item"><?= $this->escapeHtml($message['text']) ?></li>
                                    <? endforeach; ?>
                                  </ul>
                                </td>
                              </tr>
                            <? endif; ?>
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            <? endforeach; ?>
          <? else: ?>
            <p>Nejsou zadne objednavky</p>
          <? endif; ?>
      <? elseif ($this->redirect): ?>
        <p>Jste ne zaregestrovany v Ziskej</p>
        <div class="col-md-12">
          <?= $this->flashmessages() ?>
          <form action="<?= $this->url('ziskej-registration') ?>"
                id="registrationZiskej"
                name="registrationZiskej"
                method="post">
            <div class="control-group">
              <div class="checkbox">
                <label>
                <input type="checkbox" name="is_gdpr_reg" id="souhlasReg" required>
                  Souhlas s registraci
                </label>
              </div>
              <div class="checkbox">
                <label>
                <input type="checkbox" name="is_gdpr_data" id="souhlasDat">
                  Souhlas s ulozenim dat
                </label>
              </div>
              <div class="checkbox">
                <label>
                <input type="checkbox" name="notification_enabled" id="notification">
                  Posilat notifikace?
                </label>
              </div>
              <input class="btn btn-primary"
                     type="submit"
                     name="submit"
                     title="<?= $this->translate('Registration') ?>"
                     value="<?= $this->translate('Registration') ?>">
            </div>
          </form>
        </div>
      <? elseif ($this->libNotInZiskej): ?>
            <p>Vase knihovna nejsou v seznamu knihoven Ziskej</p>
      <? else: ?>
            <p>Pro testivani je nutne se prihlasit</p>
      <? endif; ?>
      </div>
    <? else: ?>
      <p>Zsikej disabled</p>
    <? endif; ?>
</div>
<style>
  #nav-tabContent {
    position: absolute;
    z-index: 999;
  }
</style>

<script>
  $( '#myList a' ).on( 'click', function (e) {
    e.preventDefault();
    let activeElem = $( '#myList a.active' );
    let activeId = activeElem.attr( 'id' );
    let id = $( this ).attr( 'id' );

    if (!$( this ).hasClass( 'active' )) {
      activeElem.toggleClass( 'active' );
      $( '#tab_' + activeId ).toggleClass( 'hidden' );
    }

    $( this ).toggleClass( 'active' );
    $( '#tab_' + id ).toggleClass( 'hidden' );
  } );

  function getCookie (cname) {
    let name = cname + '=';
    let decodedCookie = decodeURIComponent( document.cookie );
    let ca = decodedCookie.split( ';' );
    for (let i = 0; i < ca.length; i++) {
      let c = ca[i];
      while (c.charAt( 0 ) === ' ') {
        c = c.substring( 1 );
      }
      if (c.indexOf( name ) === 0) {
        return c.substring( name.length, c.length );
      }
    }
    return 'disabled';
  }

  function createZiskejMessage (message, id, cookie) {
    return $.ajax( {
      dataType: 'json',
      async: true,
      method: 'POST',
      url: '/AJAX/JSON?method=createZiskejMessage',
      data: {
        message: message,
        ticketId: id,
        ziskejCookie: cookie,
      },
    } );
  }

  $( 'form[name=ticketMessages]' ).submit( function (e) {
    e.preventDefault();
    let id = $( '#myList a.active' ).attr( 'id' );
    let message = $( 'textarea#ticketMessage_' + id ).val().trim();
    if (message !== '') {
      createZiskejMessage( message, id, getCookie( 'ziskej' ) ).done( function (data) {
        $( 'textarea#ticketMessage_' + id ).val( '' );
        let messagesList = $( '#messages_' + id + ' li:first' );
        if (messagesList.length !== 0) {
          messagesList.before( '<li class="list-group-item">' + data.items[0].text + '</li>' );
        }
        else {
          $( 'div#tab_' + id + ' table.table tbody' ).append(
            '<tr>' +
            '<th class="col-md-3">Messages</th>' +
            '<td><ul class="list-group" id="messages_' + id + '">' +
            '<li class="list-group-item">' + data.items[0].text + '</li></ul></td></tr>',
          );
        }
      } ).error( function (data) {
      } );
    }
    else {
      console.log( 'message is empty' );
    }

  } );

</script>