<? $list = $this->params->getSortList(); if (!empty($list)): ?>
  <form class="form-inline" action="<?=$this->currentPath()?>" method="get" name="sort">
    <?=$this->results->getUrlQuery()->asHiddenFields(array('sort' => '/.*/'));?>
    <label class='dropdown-select-label'>
    <select id="sort_options_1" name="sort" class="form-control dropdown-select ajax-update-sort">
      <? foreach ($list as $sortType => $sortData):
            if ( ! (isset($sortData['selected']) && is_bool($sortData['selected'])))
                $sortData['selected'] = ($sortType == $this->sort) ? true : false;
      ?>
        <option value="<?=$this->escapeHtmlAttr($sortType)?>"<?=$sortData['selected']?' selected="selected"':''?>><?=$this->transEsc($sortData['desc'])?></option>
      <? endforeach; ?>
    </select>
    </label>
    <noscript><input type="submit" class="btn btn-default" value="<?=$this->transEsc("Set")?>" /></noscript>
  </form>
<? endif; ?>
