<? // This is a text-only email template; do not include HTML! ?>
Dobrý den,

rádi bychom Vás informovali, že Vaše NCIP či Aleph API brána pod označením "<?=$this->source?>" je momentálně nedostupná pro uživatele Knihovny.cz, alias Centrálního portálu knihoven.

Uživatele jsme o nedostupnosti Vašeho API také informovali touto chybovou hláškou:
<?=$this->message ?>


--
S přátelským pozdravem,
vývojový tým Centrálního portálu knihoven.<? if (isset($this->failureTimes)): ?>


P.S. Pokus o připojení od počátků těchto problémů selhal celkem <?=$this->failureTimes?>x<? endif; ?>