<? $account = $this->auth()->getManager(); ?>
<nav class="navbar header">
  <div class="navbar-header">

    <ul class="nav navbar-nav pull-left">
      <li class="header-logo">
        <a href="<?=$this->url('home')?>"><img src="<?=$this->imageLink('cb-logo-cistbrno.png') ?>"></img></a>
      </li>
    </ul>

    <ul class="nav navbar-nav pull-right">
      <? if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
        <? foreach ($this->layout()->allLangs as $langCode => $langName): ?>
          <?
            $langImg = 'lang/' . $langCode . '.png';
            $queryParams = array('lng' => $langCode);
            parse_str($_SERVER['QUERY_STRING'], $params);
            $queryParams = array_merge($params, $queryParams);
          ?>
          <li>
            <a class="modal-link" href="<?=$this->url(null, array(), array('query' => $queryParams), true);?>">
              <img class="langFlag" src="<?=$this->imageLink($langImg)?>" alt="<?=$langName?>">
            </a>
          </li>
        <? endforeach; ?>
      <? endif; ?>
      
      <? if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
        <li class="header-login">
          <? $cart = $this->cart(); if ($cart->isActive()): ?>
            <span id="cartSummary">
              <? $cart = $this->cart(); if ($cart->isActive()): ?>
              <span id="cartSummary">
                <a id="cartItems" class="modal-link" title="<?=$this->transEsc('View Book Bag')?>" href="<?=$this->url('cart-home')?>">
                  <?=$this->transEsc('Number of items in book bag')?>:
                  <strong><?=count($cart->getItems())?></strong>
                  <?=$cart->isFull() ? ' (' .  $this->transEsc('bookbag_full') . ')' : ''?>
                </a>
              </span>
              <span class="muted">&nbsp;/&nbsp;</span>
            <? endif; ?>
              
            </span>
          <? endif; ?>
          <span class="logoutOptions<? if(!$account->isLoggedIn()): ?> hide<? endif ?>">
            <a href="<?=$this->url('myresearch-home')?>" class="modal-link" title="<?=$this->transEsc("My Profile")?>"><?=$this->transEsc("My Profile")?></a>
            <span class="muted">&nbsp;/&nbsp;</span> 
            <i class="icon-signout"></i><a href="<?=$this->url('myresearch-logout')?>" class="modal-link" title="<?=$this->transEsc("Log Out")?>"><?=$this->transEsc("Log Out")?></a>
          </span>
          <span id="loginOptions"<? if($account->isLoggedIn()): ?> class="hide"<? endif ?>>
            <i class="icon-signin"></i> 
            <? if ($sessionInitiator = $account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
              <a href="<?=$this->escapeHtml($sessionInitiator)?>"><?=$this->transEsc("Login")?></a>
            <? else: ?>
              <a href="<?=$this->url('myresearch-home')?>" class="modal-link" title="<?=$this->transEsc("Login")?>"><?=$this->transEsc("Login")?></a>
            <? endif; ?>
          </span>
        </li>
      <? endif; ?>
      
    </ul>

    <div class="header-finisher"></div>

  </div>
</nav>
