  <div class="col-md-4 widget" id='conspectus'>
    <div class='header'>
      <h2><?=$this->translate('Conspectus')?></h2>
    </div>
    <div class="list-group">
	<? foreach ($conspectus as $category => $subCategories): ?>
          <div class='category list-group-item clearfix'>
            <a href='#' title='<?=$this->translate('Expand category')?>' class='expand-category'>
              <i class='fa fa-plus'> </i>&nbsp;&nbsp;
            </a>
            <a href='/Search/Results?filter[]=conspectus_str_mv:"0/<?=$this->escapeHtml($category)?>/"' title='<?=$this->escapeHtml($category)?>' class='category-text'>
              <?=$this->escapeHtml($category)?>
            </a>
            <div class='expanded-category hidden' style='padding-left: 40px;'>
    			<? foreach ($subCategories as $subCategory): ?>
    			<div class='subcategory'>
        			<a href='#' title='<?=$this->translate('Expand category')?>' class='expand-category'></a>
        			<a href='/Search/Results?filter[]=conspectus_str_mv:"1/<?=$this->escapeHtml($category)?>/<?=$this->escapeHtml($subCategory)?>/"' title='<?=$this->escapeHtml($subCategory)?>'>
        				<?=$this->escapeHtml($subCategory)?>
        			</a>
            	</div>
    			<? endforeach; ?>
            </div>
          </div>
        <? endforeach; ?>
    </div>
  </div>

<script>
jQuery( document ).ready( function( $ ) {

	/* Expand subcategories on click */
	$( '#conspectus' ).on( 'click', '.expand-category', function( event ){

		event.preventDefault();

		var expandedCategoryElement = $( this ).parent().find( '.expanded-category' );
		if( expandedCategoryElement.hasClass( 'hidden' ) ) {
			expandedCategoryElement.removeClass( 'hidden' );
			expandedCategoryElement.parent().find( 'i.fa' ).removeClass( 'fa-plus' ).addClass( 'fa-minus' );
		} else {
			expandedCategoryElement.addClass( 'hidden' );
			expandedCategoryElement.parent().find( 'i.fa' ).removeClass( 'fa-minus' ).addClass( 'fa-plus' );
		}
	});

});
</script>