  <div class="col-md-4 favorite_authors widget">
    <div class='header'>
      <h2><?=$this->transEsc('favorite_authors')?></h2>
    </div>
    <div class="list-group">
      <? foreach ($this->favoriteAuthors as $author): ?>
      <a href="/Record/<?=$author['authority_id']?>" class="list-group-item clearfix">
        <div class='row'>
          <?
          $recordId =  preg_replace("/\./", "", $author['authority_id']);
          $recordId =  preg_replace("/:/", "", $recordId);
          $formats = $author['driver']->getFormats();
          ?>
          <div class="col-xs-3 cover_<?=$recordId?>">

                <? if ($bibinfo = $this->record($author['driver'])->getObalkyKnihJSONV3()): ?>
                    <script type="text/javascript">
                        obalky.display_thumbnail_without_links(".cover_<?=$recordId?>", <?=$bibinfo?>, <?=json_encode($author['authority_name'])?>);
                    </script>
                <? endif;?>

                <? if (! empty($formats)): ?>
                    <div class="iconlabel"><i style='font-size: 300%; color: #CCCCCC;' class="pr-format-<?=$this->record($author['driver'])->getFormatClass($formats[0])?>"></i></div>
                <? elseif ($summThumb = $this->record($author['driver'])->getThumbnail('small')): ?>
                    <img class="recordcover" src="<?=$this->escapeHtmlAttr($summThumb)?>" alt="<?=$this->transEsc('Cover Image')?>"/>
                <? else: ?>
                    <img class="recordcover" src="<?=$this->url('cover-unavailable')?>" alt="<?=$this->transEsc('No Cover Image')?>"/>
                <? endif; ?>

          </div>
          <div class="col-xs-9 content">
            <h4 class="list-group-item-heading"><?=$author['authority_name']?></h4>
            <p class="list-group-item-text"><?=$author['short_note_cs']?></p>
          </div>
        </div>
      </a>
      <? endforeach; ?>
	  <a href='/Search/Results?lookFor0[]=&type0[]=AllFields&bool0[]=AND&join=AND&searchTypeTemplate=basic&page=1&keepEnabledFilters=true&filter[]=inspiration:"favorite_authors"' class="list-group-item clearfix" title='<?=$this->translate('Show all favorite authors')?>'>
	    <div class='row more-info'>
	      <div class='col-sm-10'>
	      	<?=$this->translate('Show all favorite authors')?>
	      </div>
	      <div class='col-sm-2' style='text-align: right;'>
		    <i class="pr-interface-arrowright"></i>
	      </div>
	    </div>
	  </a>
    </div>
  </div>