  <div class="col-md-4 infobox widget">
  	<div class='header'>
    	<h2><?=$this->transEsc('You know that')?></h2>
    </div>
    <div class="list-group">
      <? foreach($this->infobox as $item): ?>
      <div class="list-group-item clearfix">
        <div class='row'>
          <div class="col-xs-12 content">
            <a href=""><h4><?=$item['title_cs']?></h4></a>
            <p class="list-group-item-text"><?=$item['text_cs']?></p>
          </div>
        </div>
      </div>
      <? endforeach; ?>
    </div>
  </div>