  <div class="col-md-4 infobox widget">
  	<div class='header'>
    	<h2><?=$this->transEsc('frontpage-news')?></h2>
    </div>
    <div class="list-group">
      <div class="list-group-item clearfix">
        <div class='row'>
          <div class="col-xs-12 content">
            <a href=""><h4>Narodil se nový spisovatel</h4></a>
            <span style='color: #777;'>2. 2. 2016</span>
            <p class="list-group-item-text">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</p>
            <div class='pull-right'><a href=""><?=$this->translate('Read more')?></a></div>
          </div>
        </div>
      </div>
      <div class="list-group-item clearfix">
        <div class='row'>
          <div class="col-xs-12 content">
            <a href=""><h4>Narodil se nový spisovatel</h4></a>
            <span style='color: #777;'>2. 2. 2016</span>
            <p class="list-group-item-text">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</p>
            <div class='pull-right'><a href=""><?=$this->translate('Read more')?></a></div>
          </div>
        </div>
      </div>
      <div class="list-group-item clearfix">
        <div class='row'>
          <div class="col-xs-12 content">
            <a href=""><h4>Narodil se nový spisovatel</h4></a>
            <span style='color: #777;'>2. 2. 2016</span>
            <p class="list-group-item-text">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</p>
            <div class='pull-right'><a href=""><?=$this->translate('Read more')?></a></div>
          </div>
        </div>
      </div>

	  <a href='#' class="list-group-item clearfix" title='<?=$this->translate('Older news')?>'>
	    <div class='row more-info'>
	      <div class='col-sm-10'>
	      	<?=$this->translate('Older news')?>
	      </div>
	      <div class='col-sm-2' style='text-align: right;'>
		    <i class="pr-interface-arrowright"></i>
	      </div>
	    </div>
	  </a>
    </div>
  </div>