  <div class="col-md-4 most-wanted widget">
    <div class='header'>
      <h2><?=$this->transEsc('frontpage-most-wanted')?></h2>
    </div>
    <div class="list-group">
      <? foreach ($this->mostWanted as $book): ?>
      <a href="/Record/<?=$book->getValue()?>" class="list-group-item clearfix">
        <div class='row'>
          <?
          $recordId =  preg_replace("/\./", "", $book->getValue());
          $recordId =  preg_replace("/:/", "", $recordId);
          $formats = $book->getRecordDriver()->getFormats();
          ?>
          <div class="col-xs-3 cover_<?=$recordId?>" id="<?=$recordId?>">

                <? if ($bibinfo = $this->record($book->getRecordDriver())->getObalkyKnihJSONV3()): ?>
                    <script type="text/javascript">
                        obalky.display_thumbnail_without_links(".cover_<?=$recordId?>", <?=$bibinfo?>, <?=json_encode($book->getRecordDriver()->getTitle())?>);
                    </script>
                <? endif;?>

                <? if (! empty($formats)): ?>
                    <div class="iconlabel"><i style='font-size: 300%; color: #CCCCCC;' class="pr-format-<?=$this->record($book->getRecordDriver())->getFormatClass($formats[0])?>"></i></div>
                <? elseif ($summThumb = $this->record($book->getRecordDriver())->getThumbnail('small')): ?>
                    <img class="recordcover" src="<?=$this->escapeHtmlAttr($summThumb)?>" alt="<?=$this->transEsc('Cover Image')?>"/>
                <? else: ?>
                    <img class="recordcover" src="<?=$this->url('cover-unavailable')?>" alt="<?=$this->transEsc('No Cover Image')?>"/>
                <? endif; ?>

          </div>
          <div class="col-xs-9 content">
            <h4 class="list-group-item-heading"><?=$book->getRecordDriver()->getTitle()?></h4>
            <p class="list-group-item-text"><?=$book->getRecordDriver()->getDeduplicatedAuthors()['main']?></p>
          </div>
        </div>
      </a>
      <? endforeach; ?>
	  <a href='/Search/Results?lookFor0[]=&type0[]=AllFields&bool0[]=AND&join=AND&searchTypeTemplate=basic&page=1&keepEnabledFilters=true&filter[]=inspiration:"top_results"' class="list-group-item clearfix" title='<?=$this->translate('Show all most wanted')?>'>
	    <div class='row more-info'>
	      <div class='col-sm-10'>
	      	<?=$this->translate('Show all most wanted')?>
	      </div>
	      <div class='col-sm-2' style='text-align: right;'>
		    <i class="pr-interface-arrowright"></i>
	      </div>
	    </div>
	  </a>
    </div>
  </div>