<?php
    $this->headScript()->appendFile('components/widgets.js');
?>
<div class='col-md-4 widget' id='conspectus'>

  <div class='header'>
    <h2><?=$this->translate('Conspectus')?></h2>
  </div>

  <div class='list-group'>
    <? foreach ($conspectus as $category => $subCategories): ?>
      <div class='category list-group-item clearfix'>

        <a href='#' title='<?=$this->translate('Expand or collapse')?>' class='expand-category'>
          <i class='pr-institution-arrow collapsed'> </i>
        </a>

        <a href='<?=$this->conspectusBaseUrl.$this->compressUrlParam('conspectus_str_mv:"0/'.$category.'/"')?>'
           title='<?=$this->escapeHtml($category)?>'
           class='category-text'>
          <?=$this->escapeHtml($category)?>
        </a>

        <div class='expanded-category hidden'>
          <? foreach ($subCategories as $subCategory): ?>
            <div class='subcategory'>
              <a href='#' title='<?=$this->translate('Expand category')?>' class='expand-category'></a>
              <a href='<?=$this->conspectusBaseUrl.$this->compressUrlParam(
                  'conspectus_str_mv:"1/'.$category.'/'.$subCategory.'/"'
              )?>'
                 title='<?=$this->escapeHtml($subCategory)?>'>
                <?=$this->escapeHtml($subCategory)?>
              </a>
            </div>
          <? endforeach; ?>
        </div>

      </div>
    <? endforeach; ?>
  </div>

</div>