  <div class="col-md-4 events widget">
    <div class='header'>
    	<h2><?=$this->transEsc('frontpage-events')?></h2>
    </div>
    <div class="list-group">
      <div class="list-group-item clearfix">
        <div class='row'>
          <div class="col-xs-9 content">
            <a href="">
              <h4>Autorské čtení Romana Vaňka</h4>
            </a>
            <p class="list-group-item-text">Moravská zemská knihovna v Brně</p>
          </div>
          <div class="number pull-right">
             2.2.
          </div>
        </div>
      </div>
      <div class="list-group-item clearfix">
        <div class='row'>
          <div class="col-xs-9 content">
            <a href="">
              <h4>Autorské čtení Romana Vaňka</h4>
            </a>
            <p class="list-group-item-text">Moravská zemská knihovna v Brně</p>
          </div>
          <div class="number pull-right">
             2.2.
          </div>
        </div>
      </div>
      <div class="list-group-item clearfix">
        <div class='row'>
          <div class="col-xs-9 content">
            <a href="">
              <h4>Autorské čtení Romana Vaňka</h4>
            </a>
            <p class="list-group-item-text">Moravská zemská knihovna v Brně</p>
          </div>
          <div class="number pull-right">
             2.2.
          </div>
        </div>
      </div>
      <div class="list-group-item clearfix">
        <div class='row'>
          <div class="col-xs-9 content">
            <a href="">
              <h4>Autorské čtení Romana Vaňka</h4>
            </a>
            <p class="list-group-item-text">Moravská zemská knihovna v Brně</p>
          </div>
          <div class="number pull-right">
             2.2.
          </div>
        </div>
      </div>
      <div class="list-group-item clearfix">
        <div class='row'>
          <div class="col-xs-9 content">
            <a href="">
              <h4>Autorské čtení Romana Vaňka</h4>
            </a>
            <p class="list-group-item-text">Moravská zemská knihovna v Brně</p>
          </div>
          <div class="number pull-right">
             2.2.
          </div>
        </div>
      </div>

	  <a href='#' class="list-group-item clearfix" title='<?=$this->translate('All planned events')?>'>
	    <div class='row more-info'>
	      <div class='col-sm-10'>
	      	<?=$this->translate('All planned events')?>
	      </div>
	      <div class='col-sm-2' style='text-align: right;'>
		    <i class="pr-interface-arrowright"></i>
	      </div>
	    </div>
	  </a>
    </div>
  </div>