<table class="recordSet">
  <tr>
    <th></th>
    <th><?= $this->transEsc('Main Author') ?></th>
    <th><?= $this->transEsc('Title') ?></th>
    <th><?= $this->transEsc('Published') ?></th>
    <th><?= $this->transEsc('Availability') ?></th>
  </tr>
  <? $i = 0; foreach ($this->results->getResults() as $current): ?>
  <tr id="result<?=$i ?>" class="result<?=(++$i % 2 == 0) ? ' alt' : ''?>">
    <td><? if ($this->cart()->isActive()): ?><?=$this->record($current)->getCheckbox()?><? endif; ?></td>
    <?=$this->record($current)->getSearchResult('table')?>
  </tr>
  <? endforeach; ?>
</table>