<?
  $this->headScript()->appendFile('ol/OpenLayers.js');
  $this->headScript()->appendFile('map_selection.js');
  $geoField = $this->recommend->getGeoField();
  $coordinates = $this->recommend->getSelectedCoordinates();
  $useWKT = $this->recommend->isUseWKT();
  $showSelection = true;
  if ($coordinates == null) {
    $coordinates = $this->recommend->getDefaultCoordinates();
    $showSelection = false;
  }
  $height = $this->recommend->getHeight();
  $searchParams = $this->recommend->getSearchParams();
  $jsParams = json_encode([
    'geoField'      => $geoField,
    'boundingBox'   => array_map('doubleval', $coordinates),
    'searchParams'  => $searchParams,
    'showSelection' => $showSelection,
    'useWKT'        => $useWKT,
  ]);
  $jsLoad = "loadMapSelection(" . $jsParams . ");";
  $addSearchOption = <<<EOF
    $('.search-query-options>.advanced').after('&nbsp;&nbsp;<a href="#" class="advanced" onclick=\\'{$jsLoad} $(this).remove(); return false;\\'>{$this->translate('Geographical search')}</a>');
EOF;

?>
<div class="authorbox">
  <div id="geo_search" style="display: none;">
    <div id="geo_search_modes" class="form-inline">
      <input id="geo_search_move" type="radio" name="mode" value="move" />
      <label for="geo_search_move"><?=$this->transEsc('Move map')?></label>
      <input id="geo_search_bbox" type="radio" name="mode" value="dragBox" checked="checked" />
      <label for="geo_search_bbox"><?=$this->transEsc('Select rectangle')?></label>
    </div>
    <div id="geo_search_map" style="height: <?=$height?>px;"></div>
  </div>
  <? if ($showSelection) :?>
    <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $jsLoad, 'SET');?>
  <? else: ?>
    <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $addSearchOption, 'SET');?>
  <? endif; ?>
</div>
