<?=$this->doctype('HTML5')?>
<html lang="<?=$this->layout()->userLang?>">
  <head>
    <?$this->headThemeResources()?>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
    <?=$this->headMeta()?>
    <?=$this->headTitle()?>
    <?
      // Set up OpenSearch link:
      $this->headLink(
        array(
          'href' => $this->url('search-opensearch') . '?method=describe',
          'type' => 'application/opensearchdescription+xml',
          'title' => $this->transEsc('Library Catalog Search'),
          'rel' => 'search'
        )
      );
    ?>
    <!-- RTL styling -->
    <? if ($this->layout()->rtl) {
      $this->headLink()->appendStylesheet('vendor/bootstrap-rtl.min.css');
    } ?>
    <?=$this->headLink()?>
    <?=$this->headStyle()?>
    <?
      if (!isset($this->renderingError)) {
        // Add translation strings
        $this->jsTranslations()->addStrings(
          array(
            'add_tag_success' => 'add_tag_success',
            'bulk_email_success' => 'bulk_email_success',
            'bulk_noitems_advice' => 'bulk_noitems_advice',
            'bulk_save_success' => 'bulk_save_success',
            'close' => 'close',
            'libphonenumber_invalid' => 'libphonenumber_invalid',
            'libphonenumber_invalidcountry' => 'libphonenumber_invalidcountry',
            'libphonenumber_invalidregion' => 'libphonenumber_invalidregion',
            'libphonenumber_notanumber' => 'libphonenumber_notanumber',
            'libphonenumber_toolong' => 'libphonenumber_toolong',
            'libphonenumber_tooshort' => 'libphonenumber_tooshort',
            'libphonenumber_tooshortidd' => 'libphonenumber_tooshortidd',
            'loading' => 'Loading',
            'sms_success' => 'sms_success',
            'number_thousands_separator' => ['number_thousands_separator', null, ',']
          )
        );
        // Add libphonenumber.js strings
        $this->jsTranslations()->addStrings(
          array(
            "'Phone number invalid'" => 'libphonenumber_invalid',
            "'Invalid country calling code'" => 'libphonenumber_invalidcountry',
            "'Invalid region code'" => 'libphonenumber_invalidregion',
            "'The string supplied did not seem to be a phone number'" => 'libphonenumber_notanumber',
            "'The string supplied is too long to be a phone number'" => 'libphonenumber_toolong',
            "'The string supplied is too short to be a phone number'" => 'libphonenumber_tooshort',
            "'Phone number too short after IDD'" => 'libphonenumber_tooshortidd'
          )
        );
        // Deal with cart stuff:
        $cart = $this->cart();
            $this->jsTranslations()->addStrings(array('loading' => 'Loading'));
        if ($cart->isActive()) {
          $this->headScript()->appendFile("vendor/cookies.js");
          $this->headScript()->appendFile("cart.js");
          $domain = $cart->getCookieDomain();
          $this->headScript()->appendScript(
            'var cartCookieDomain = ' . (!empty($domain) ? "'$domain'" : 'false') . ';'
          );
          $this->jsTranslations()->addStrings(
            array(
              'addBookBag' => 'Add to Book Bag',
              'bookbagFull' => 'bookbag_full_msg',
              'bookbagMax' => $cart->getMaxSize(),
              'bookbagStatusFull' => 'bookbag_full',
              'confirmDelete' => 'confirm_delete',
              'confirmEmpty' => 'bookbag_confirm_empty',
              'itemsAddBag' => 'items_added_to_bookbag',
              'itemsInBag' => 'items_already_in_bookbag',
              'removeBookBag' => 'Remove from Book Bag',
              'viewBookBag' => 'View Book Bag'
            )
          );
            }
            $this->headScript()->appendScript($this->jsTranslations()->getScript());
            $this->headScript()->appendScript(
                            'var userIsLoggedIn = ' . ($this->auth()->isLoggedIn() ? 'true' : 'false') . ';'
            );

            // Session keep-alive
            if ($this->KeepAlive()) {
                $this->headScript()->appendScript('var keepAliveInterval = '. $this->KeepAlive());
                $this->headScript()->appendFile("keep_alive.js");
            }

        }
        $this->headScript()->appendScript(
          'var userIsLoggedIn = ' . ($this->auth()->isLoggedIn() ? 'true' : 'false') . ';'
        );
    ?>

    <?=$this->headScript()?>
    <script>
      var VuFind = new VuFindNamespace(
        '<?=rtrim($this->url('home'), '/') ?>',
        <?=$this->jsTranslations()->getJSON() ?>
      );
    </script>
  </head>
  <body class="<?=$this->layoutClass('offcanvas-row')?><? if ($this->layout()->rtl): ?> rtl<? endif; ?>">
    <?=$this->googleanalytics()?>
    <div class="<?=($this->layout()->frontpage == true)?'frontpage':'header'?>">
      <div class="container">
        <div id="header" class="clearfix hidden-print">
          <?// Set up the search box -- there are three possible cases:
            // 1. No search box was set; we should default to the normal box
            // 2. It was set to false; we should display nothing
            // 3. It is set to a custom string; we should display the provided version
            // Set up default search box if no data was provided from the template;
            // this covers case 1.  Cases 2 and 3 are then covered by logic below.
            if (!isset($this->layout()->searchbox)) {
              $this->layout()->searchbox = $this->render('search/searchbox.phtml');
            }
          ?>
          <?=$this->render('header.phtml')?>
        </div>
      </div>
    </div>
    <? if((!isset($this->layout()->showBreadcrumbs) || $this->layout()->showBreadcrumbs == true)
      && !empty($this->layout()->breadcrumbs)
      && $this->layout()->breadcrumbs !== false
    ): ?>
    <div class="breadcrumb-background">
      <ul class="breadcrumb hidden-print container">
          <? if(is_array($this->layout()->breadcrumbs)): ?>
            <? if(count($this->layout()->breadcrumbs) > 1): ?>
              <?=$this->render('breadcrumbs/multi.phtml', array(
                  'parents' => $this->layout()->breadcrumbs,
                  'title'   => $this->layout()->title,
                  'end'     => $this->layout()->breadcrumbEnd,
                  'from'    => $this->layout()->from
                )) ?>
            <? else: ?>
              <?=$this->render('breadcrumbs/default.phtml', array(
                  'parents' => $this->layout()->breadcrumbs,
                  'title'   => $this->layout()->title
                )) ?>
            <? endif; ?>
          <? else: ?>
            <li><a href="<?=$this->url('search-home')?>"><?=$this->transEsc('Online catalog')?></a></li>
            <?=$this->layout()->breadcrumbs ?>
          <? endif; ?>

      </ul>
    </div>
    <? endif; ?>
    <div role="main" class="container template-dir-<?=$this->templateDir?> template-name-<?=$this->templateName?>">
      <div class="main row">
        <?=$this->layout()->content?>
      </div>
      <div class="footer hidden-print">
        <?=$this->render('footer.phtml')?>
        <?=$this->layout()->poweredBy?>
      </div>
    </div>
    <!-- MODAL IN CASE WE NEED ONE -->
    <div id="modal" class="modal fade hidden-print" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 id="modalTitle" class="modal-title">&nbsp;</h4>
          </div>
          <div class="modal-body"><?=$this->transEsc('Loading') ?>...</div>
        </div>
      </div>
    </div>
    <div class="offcanvas-toggle" data-toggle="offcanvas"><i class="fa"></i></div>
    <div class="offcanvas-overlay" data-toggle="offcanvas"></div>
  </body>
</html>
