<?=$this->doctype('HTML5')?>
<html lang="<?=$this->layout()->userLang?>">
  <head>
    <?$this->headThemeResources()?>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
    <?=$this->headMeta()?>
    <?=$this->headTitle()?>
    <?
      // Set up OpenSearch link:
      $this->headLink(
        array(
          'href' => $this->url('search-opensearch') . '?method=describe',
          'type' => 'application/opensearchdescription+xml',
          'title' => $this->transEsc('Library Catalog Search'),
          'rel' => 'search'
        )
      );
    ?>
    <?=$this->headLink()?>
    <?=$this->headStyle()?>
    <?
        // Set global path for Javascript code:
        $this->headScript()->prependScript("path = '" . rtrim($this->url('home'), '/') . "';");

        // Deal with cart stuff:
        if (!isset($this->renderingError)) {
            $cart = $this->cart();
            $this->jsTranslations()->addStrings(array('loading' => 'Loading'));
            if ($cart->isActive()) {
                $this->headScript()->appendFile("vendor/cookies.js");
                $this->headScript()->appendFile("cart.js");
                $domain = $cart->getCookieDomain();
                $this->headScript()->appendScript(
                                'var cartCookieDomain = ' . (!empty($domain) ? "'$domain'" : 'false') . ';'
                );
                $this->jsTranslations()->addStrings(
                    array(
                        'bulk_noitems_advice' => 'bulk_noitems_advice',
                        'confirmEmpty' => 'bookbag_confirm_empty',
                        'viewBookBag' => 'View Book Bag',
                        'addBookBag' => 'Add to Book Bag',
                        'removeBookBag' => 'Remove from Book Bag',
                        'itemsAddBag' => 'items_added_to_bookbag',
                        'itemsInBag' => 'items_already_in_bookbag',
                        'bookbagMax' => $cart->getMaxSize(),
                        'bookbagFull' => 'bookbag_full_msg',
                        'bookbagStatusFull' => 'bookbag_full',
                    )
                );
            }
            $this->headScript()->appendScript($this->jsTranslations()->getScript());
            $this->headScript()->appendScript(
                            'var userIsLoggedIn = ' . ($this->auth()->isLoggedIn() ? 'true' : 'false') . ';'
            );

            // Session keep-alive
            if ($this->KeepAlive()) {
                $this->headScript()->appendScript('var keepAliveInterval = '. $this->KeepAlive());
                $this->headScript()->appendFile("keep_alive.js");
            }

        }
        $this->headScript()->prependScript("var obalky = obalky || {}; obalky.cacheUrl = " . json_encode($this->obalkyKnih()->getCacheUrl()));
    ?>

    <?=$this->headScript()?>
  </head>
  <body class="<?=$this->layoutClass('offcanvas-row')?>">
    <?=$this->googleanalytics()?>
    <div class="<?=($this->layout()->frontpage == true)?'frontpage':'header'?>">
      <div class="container">
        <div id="header" class="clearfix noprint">
          <?// Set up the search box -- there are three possible cases:
            // 1. No search box was set; we should default to the normal box
            // 2. It was set to false; we should display nothing
            // 3. It is set to a custom string; we should display the provided version
            // Set up default search box if no data was provided from the template;
            // this covers case 1.  Cases 2 and 3 are then covered by logic below.
            if (!isset($this->layout()->searchbox)) {
              $this->layout()->searchbox = $this->render('search/searchbox.phtml');
            }
          ?>
          <?=$this->render('header.phtml')?>
        </div>
      </div>
    </div>
    <? if((!isset($this->layout()->showBreadcrumbs) || $this->layout()->showBreadcrumbs == true)
      && !empty($this->layout()->breadcrumbs)
      && $this->layout()->breadcrumbs !== false
    ): ?>
    <div class="breadcrumb-background">
      <ul class="breadcrumb hidden-print container">
          <? if(is_array($this->layout()->breadcrumbs)): ?>
            <? if(count($this->layout()->breadcrumbs) > 1): ?>
              <?=$this->render('breadcrumbs/multi.phtml', array(
                  'parents' => $this->layout()->breadcrumbs,
                  'title'   => $this->layout()->title,
                  'end'     => $this->layout()->breadcrumbEnd,
                  'from'    => $this->layout()->from
                )) ?>
            <? else: ?>
              <?=$this->render('breadcrumbs/default.phtml', array(
                  'parents' => $this->layout()->breadcrumbs,
                  'title'   => $this->layout()->title
                )) ?>
            <? endif; ?>
          <? else: ?>
            <li><a href="<?=$this->url('search-home')?>"><?=$this->transEsc('Online catalog')?></a></li>
            <?=$this->layout()->breadcrumbs ?>
          <? endif; ?>

      </ul>
    </div>
    <? endif; ?>
    <div role="main" class="container template-dir-<?=$this->templateDir?> template-name-<?=$this->templateName?>">
      <div class="main row">
        <?=$this->layout()->content?>
      </div>
      <div class="footer noprint">
        <?=$this->render('footer.phtml')?>
        <?=$this->layout()->poweredBy?>
      </div>
    </div>
    <!-- MODAL IN CASE WE NEED ONE -->
    <div id="modal" class="modal hide fade">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3></h3>
      </div>
      <div class="modal-body"><?=$this->transEsc('Loading') ?>...</div>
    </div>
    <div class="offcanvas-toggle" data-toggle="offcanvas"><i class="fa"></i></div>
    <div class="offcanvas-overlay" data-toggle="offcanvas"></div>
  </body>
</html>
