<?
    $id = $this->driver->getUniqueID();
    $recordSource = $source = explode(".", $id)[0];
    $maxSubjectsInCore = $config['Record']['max_subjects_in_core'];
?>

<div class="well">
<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <div class="col-sm-3">
    <div class="text-center #cover" id="cover">
        <img src="<?=$this->url('cover-unavailable')?>" class="recordcover" alt="<?=$this->transEsc('No Cover Image')?>"/>
        <script type="text/javascript">
            obalky.display_authority_cover("#cover", <?=$bibinfo?>, <?=json_encode($this->record($this->driver)->getObalkyKnihAdvert("record"))?>);
        </script>
        <? /* Display qrcode if appropriate: */ ?>
      <? $QRCode = $this->record($this->driver)->getQRCode("core"); ?>
      <? if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <? endif; ?>
    </div>

    <? // if you have a preview tab but want to move or remove the preview link
       // from this area of the record view, this can be split into
       // getPreviewData() (should stay here) and
       // getPreviewLink() (can go in your desired tab) ?>
    <?=$this->record($this->driver)->getPreviews()?>
  </div>

  <div class="col-sm-9">
    <h2 class='record-title' property="name"><strong><?=$this->escapeHtml($this->driver->getTitle())?></strong></h2>
    <?/* Display Main Details */?>
    <table class="table" summary="<?=$this->transEsc('Bibliographic Details')?>">
      <? $details = $this->driver->getBibliographicDetails(); ?>
      <? if (! empty($details)): ?>
      <tr>
        <th class="col-md-3"><?=$this->transEsc('Bibliographic Details')?>: </th>
        <td>
          <div><?=$details?></div>
        </td>
      </tr>
      <? endif; ?>

      <? $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
      <tr>
         <th class="col-md-3"><?=$this->transEsc('Format')?>: </th>
         <td><?=$this->record($this->driver)->getFormatList()?></td>
      </tr>
      <? endif; ?>

    </table>
    <?/* End Main Details */?>
  </div>
</div>
</div>
