<?
    $id = $this->driver->getUniqueID();
    $recordSource = $source = explode(".", $id)[0];
    $maxSubjectsInCore = $config['Record']['max_subjects_in_core'];

    $formats = $this->driver->getFormats();
?>

<div class="well">
<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <div class="col-sm-3">
    <div class="text-center #cover" id="cover">

        <? if (! empty($formats)): ?>
            <div class="iconlabel"><i style="font-size: 70px; color: #cccccc;" class="pr-format-<?=$this->record($this->driver)->getFormatClass($formats[0])?>"></i></div>
        <? elseif ($summThumb = $this->record($this->driver)->getThumbnail()): ?>
            <img class="recordcover" src="<?=$this->escapeHtmlAttr($summThumb)?>" alt="<?=$this->transEsc('Cover Image')?>"/>
        <? else: ?>
            <img class="recordcover" src="<?=$this->url('cover-unavailable')?>" alt="<?=$this->transEsc('No Cover Image')?>"/>
        <? endif; ?>

        <script type="text/javascript">
            obalky.display_authority_cover("#cover", <?=$bibinfo?>, <?=json_encode($this->record($this->driver)->getObalkyKnihAdvert("record"))?>);
        </script>
        <? /* Display qrcode if appropriate: */ ?>
      <? $QRCode = $this->record($this->driver)->getQRCode("core"); ?>
      <? if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <? endif; ?>
    </div>

    <? // if you have a preview tab but want to move or remove the preview link
       // from this area of the record view, this can be split into
       // getPreviewData() (should stay here) and
       // getPreviewLink() (can go in your desired tab) ?>
    <?=$this->record($this->driver)->getPreviews()?>
  </div>

  <div class="col-sm-9">
    <h2 class='record-title' property="name"><strong><?=$this->escapeHtml($this->driver->getTitle())?></strong></h2>
      <? /* Display Main Details */ ?>
    <table class="table">
        <?php
        $items = [
            'alternative_term' => $this->driver->getAlternatives(),
            'english_term' => $this->driver->getEnglish(),
            'explanation_term' => $this->driver->getExplanation(),
            'relative_term' => $this->driver->getRelatives(),
            'source_term' => $this->driver->getSource(),
            'term_author' => $this->driver->getTermAuthors(),
            'Format' => $this->record($this->driver)->getFormatList(),
        ];
        foreach ( $items as $itemName => $itemValue ):
            //empty string or no array items passed, skip round
            if ( empty($itemValue) )
                continue;
            //is array of values
            if ( is_array($itemValue) )
                $itemValue = implode('<br/>', $itemValue);
            ?>
          <tr id="row-<?= $itemName ?>">
            <th class="col-md-3"><?= $this->transEsc($itemName) ?>
              :
            </th>
            <td><?= $itemValue ?></td>
          </tr>
        <?
        endforeach;
        ?>

    </table>
      <? /* End Main Details */ ?>
  </div>
</div>
</div>
