<?
    $id = $this->driver->getUniqueID();
    $recordSource = $source = explode(".", $id)[0];
    $maxSubjectsInCore = $config['Record']['max_subjects_in_core'];

    $formats = $this->driver->getFormats();
?>

<div class="well">
<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <div class="col-sm-3">
    <div class="text-center #cover" id="cover">

        <? if (! empty($formats)): ?>
            <div class="iconlabel"><i style="font-size: 70px; color: #cccccc;" class="pr-format-<?=$this->record($this->driver)->getFormatClass($formats[0])?>"></i></div>
        <? elseif ($summThumb = $this->record($this->driver)->getThumbnail()): ?>
            <img class="recordcover" src="<?=$this->escapeHtmlAttr($summThumb)?>" alt="<?=$this->transEsc('Cover Image')?>"/>
        <? else: ?>
            <img class="recordcover" src="<?=$this->url('cover-unavailable')?>" alt="<?=$this->transEsc('No Cover Image')?>"/>
        <? endif; ?>

        <script type="text/javascript">
            obalky.display_authority_cover("#cover", <?=$bibinfo?>, <?=json_encode($this->record($this->driver)->getObalkyKnihAdvert("record"))?>);
        </script>
        <? /* Display qrcode if appropriate: */ ?>
      <? $QRCode = $this->record($this->driver)->getQRCode("core"); ?>
      <? if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <? endif; ?>
    </div>

    <? // if you have a preview tab but want to move or remove the preview link
       // from this area of the record view, this can be split into
       // getPreviewData() (should stay here) and
       // getPreviewLink() (can go in your desired tab) ?>
    <?=$this->record($this->driver)->getPreviews()?>
  </div>

  <div class="col-sm-9">
    <h2 class='record-title' property="name"><strong><?=$this->escapeHtml($this->driver->getTitle())?></strong></h2>
    <?/* Display Main Details */?>
    <table class="table">

      <? $alternatives = $this->driver->getAlternatives(); if (!empty($alternatives)): ?>
      <tr>
         <th class="col-md-3"><?=$this->transEsc('alternative_term')?>: </th>
         <td>
             <? foreach ($alternatives as $alternative): ?>
                 <?=$alternative?><br/>
             <? endforeach; ?>
         </td>
      </tr>
      <? endif; ?>

      <? $english = $this->driver->getEnglish(); if (!empty($english)): ?>
      <tr>
         <th class="col-md-3"><?=$this->transEsc('english_term')?>: </th>
         <td><?=$english?></td>
      </tr>
      <? endif; ?>

      <? $explanation = $this->driver->getExplanation(); if (!empty($explanation)): ?>
      <tr>
         <th class="col-md-3"><?=$this->transEsc('explanation_term')?>: </th>
         <td><?=$explanation?></td>
      </tr>
      <? endif; ?>

      <? $relatives = $this->driver->getRelatives(); if (!empty($relatives)): ?>
      <tr>
         <th class="col-md-3"><?=$this->transEsc('relative_term')?>: </th>
         <td>
             <? foreach ($relatives as $relative): ?>
                 <?=$relative?><br/>
             <? endforeach; ?>
         </td>
      </tr>
      <? endif; ?>

      <? $source = $this->driver->getSource(); if (!empty($source)): ?>
      <tr>
         <th class="col-md-3"><?=$this->transEsc('source_term')?>: </th>
         <td><?=$source?></td>
      </tr>
      <? endif; ?>

      <? if (!empty($formats)): ?>
      <tr>
         <th class="col-md-3"><?=$this->transEsc('Format')?>: </th>
         <td><?=$this->record($this->driver)->getFormatList()?></td>
      </tr>
      <? endif; ?>

    </table>
    <?/* End Main Details */?>
  </div>
</div>
</div>
