<?
  // Get source of the record to print it to h3 header
  $id = $this->driver->getUniqueID();
  $source = explode(".", $id)[0];
  $parentRecordId = $this->driver->tryMethod('getParentRecordID');

  // Set up standard record scripts:
  $this->headScript()->appendFile("record.js");
  $this->headScript()->appendFile("check_save_statuses.js");

  // Activate Syndetics Plus if necessary:
  if ($this->syndeticsPlus()->isActive()) {
    echo $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
  }

  // Add RDF header link if applicable:
  if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
    $this->headLink()->appendAlternate($this->recordLink()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
  }

  $this->layout()->title = $this->driver->getShortTitle();
?>

<script>
    dataLayer.push({
        'page': {
            'type': 'detail'
        }
    });
</script>

<? if($source != "library"): ?>
    <script>
        dataLayer.push({
            'page': {
                'category': 'record'
            }
        });
    </script>
    <? if($source != "auth"): ?>
        <script>
            dataLayer.push({
                'page': {
                    'library': '<?=$source?>'
                }
            });
        </script>
    <? endif; ?>
<? else: ?>
    <script>
        dataLayer.push({
            'page': {
                'category': 'library'
            }
        });
    </script>
<? endif; ?>

<a id="back-to-search-link-ID" class='back-to-search-link' href="" title='<?=$this->translate('Back to search results')?>'>
    <i class="pr-interface-arrowleft"> </i> <?=$this->translate('Back to search results')?>
</a>
<script>
    if (document.referrer.search("/Search/") !== -1){
        document.getElementById("back-to-search-link-ID").classList.remove("hide");
        document.getElementById("back-to-search-link-ID").setAttribute("href",document.referrer);
    } else {
        document.getElementById("back-to-search-link-ID").classList.add("hide");
    }
</script>

<? if (isset($this->scrollData) && ($this->scrollData['previousRecord'] || $this->scrollData['nextRecord'])): ?>
  <ul class="pager hidden-print">
    <? if ($this->scrollData['previousRecord']): ?>
      <li>
        <a href="<?=$this->recordLink()->getUrl($this->scrollData['previousRecord'])?>" title="<?=$this->transEsc('Previous Search Result')?>">&laquo; <?=$this->transEsc('Prev')?></a>
      </li>
    <? else: ?>
      <li class="disabled"><a href="#">&laquo; <?=$this->transEsc('Prev')?></a></li>
    <? endif; ?>
    #<?=$this->localizedNumber($this->scrollData['currentPosition']) . ' ' . $this->transEsc('of') . ' ' . $this->localizedNumber($this->scrollData['resultTotal']) . ' ' . $this->transEsc('results') ?>
    <? if ($this->scrollData['nextRecord']): ?>
      <li>
        <a href="<?=$this->recordLink()->getUrl($this->scrollData['nextRecord'])?>" title="<?=$this->transEsc('Next Search Result')?>"><?=$this->transEsc('Next')?> &raquo;</a>
      </li>
    <? else: ?>
      <li class="disabled"><a href="#"><?=$this->transEsc('Next')?> &raquo;</a></li>
    <? endif; ?>
  </ul>
<? endif; ?>

<div class="clearfix">
  <div class="col-sm-9">
    <div class="record source<?=$this->escapeHtmlAttr($this->driver->getResourceSource())?>">
      <input type="hidden" value="<?=$this->escapeHtmlAttr($id)?>" class="hiddenId" />
      <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getResourceSource()) ?>" class="hiddenSource" />
      <input type="hidden" value="<?=$this->escapeHtmlAttr($parentRecordId ?? $id)?>" class="hiddenParentRecordId" >
      <?=$this->flashmessages()?>

    <!-- Modal -->
    <div class="modal fade" id="citationsModal" tabindex="-1" role="dialog" aria-labelledby="citationsLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="citationsLabel"><?=$this->translate('Citations')?></h4>
          </div>
          <div class="modal-body">
              <div class='citation-loader row'>
                <div class='col-sm-12 text-center'>
              	  <i class="fa fa-2x fa-spinner fa-spin"></i>
              	</div>
              </div>
              <? if (isset($this->availableCitationStyles)) :?>
			    <div id='citation-placeholder'></div>
			    <div id='citation-style-selector'>
			      <select class='style' id='record_<?=$id?>'>
                    <? foreach($this->availableCitationStyles as $style): ?>
			          <option value='<?=$style['value']?>'<?= ($style['value'] == $this->selectedCitationStyle) ? 'selected="selected"' : '' ?>><?=$style['description']?></option>
			        <? endforeach; ?>
			      </select>
			      <a href="http://www.citacepro.com/nacist-dokument-sysno/<?=$id?>?katalog=cpk" target="_blank">
			        <img src="/themes/bootstrap3/images/logoCitacePROkatalog.png" alt="Citace PRO">
			      </a>
			    </div>
			  <? endif; ?>
		  </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal"><?=$this->translate('close')?></button>
          </div>
        </div>
      </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="shareModal" tabindex="-1" role="dialog" aria-labelledby="shareLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="shareLabel"><?=$this->translate('Share this')?></h4>
          </div>
          <div class="modal-body">
		<center>
	  	<div style="display:inline-block;" class="fb-share-button" data-href="<?=htmlspecialchars("https://".$_SERVER['SERVER_NAME']."/Record/".$id)?>" data-layout="button" data-size="large" data-mobile-iframe="false"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=<?=htmlspecialchars("https://".$_SERVER['SERVER_NAME']."/Record/".$id)?>&src=sdkpreparse"><img alt="Facebook - Knihovny.cz" class="social-icon" width="64" src="https://cdn0.iconfinder.com/data/icons/flat-social-media-icons-set-round-style-1/550/facebook-128.png"></a></div>
		<div style="display:inline-block;margin-left:30px;">
	<a target="_blank" href="https://plus.google.com/share?url=<?=htmlspecialchars("https://".$_SERVER['SERVER_NAME']."/Record/".$id)?>"><img src="https://cdn1.iconfinder.com/data/icons/logotypes/32/circle-google-plus-128.png" width="60"></a>
	  	</div>
		<div style="display:inline-block;margin-left:30px;">
		<a target="_blank" href="https://twitter.com/intent/tweet?url=<?=htmlspecialchars("https://".$_SERVER['SERVER_NAME']."/Record/".$id)?>">
			<img src="https://cdn1.iconfinder.com/data/icons/logotypes/32/circle-twitter-128.png" width="60">
		</a>
		</div>
		</center>
	  </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal"><?=$this->translate('close')?></button>
          </div>
        </div>
      </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="permalinkModal" tabindex="-1" role="dialog" aria-labelledby="permalinkLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="permalinkLabel"><?=$this->translate('Permalink')?></h4>
          </div>
          <div class="modal-body">
            <? if ($this->driver instanceof VuFind\RecordDriver\EDS): ?>
              <input class='selectOnClick form-control' value='<?=htmlspecialchars("https://".$_SERVER['SERVER_NAME']."/EdsRecord/".$id)?>'>
            <? else: ?>
              <input class='selectOnClick form-control' value='<?=htmlspecialchars("https://".$_SERVER['SERVER_NAME']."/Record/".$id)?>'>
            <? endif; ?>
		  </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal"><?=$this->translate('close')?></button>
          </div>
        </div>
      </div>
    </div>
			<?=$this->record($this->driver)->getCoreMetadata()?>
            <? if ($this->driver instanceof CPK\RecordDriver\SolrMarc && !($this->driver instanceof CPK\RecordDriver\SolrAuthority) && $source != "library"): ?>
                <div class='row records-in-groups-container' id='records-in-groups-container'>
                  <div class='col-md-12 col-lg-2 text-center'>
                    <h3 id='records-in-groups'><strong><?=$this->translate('Select institution')?></strong>: </h3>
                  </div>
                  <? if($this->libraryID): ?>
                  <div class='col-xs-12 col-lg-8'>
                  <? else: ?>
                  <div class='col-xs-12 col-lg-8'>
                  <? endif; ?>
                    <?= $this->render('RecordDriver/SolrDefault/records-in-groups.phtml'); ?>
                  </div>
                  <? if($this->libraryID): ?>
                  <div class='col-xs-12 col-lg-2 information'>
                    <a href='/Record/library.<?=$this->libraryID?>' target='_blank' title='<?=$this->translate('Information about library')?>'>
                      <div class='row'>
                        <div class='col-xs-1 col-xs-offset-4 col-lg-3 col-lg-offset-0'>
                          <i class='cpk-icon information-about-library'>i</i>
                        </div>
                        <div class='col-xs-6 col-lg-9'>
                          <span><?=$this->translate('Information about library')?></span>
                        </div>
                      </div>
                    </a>
                  </div>
                  <? endif; ?>
                </div>
            <? endif; ?>
			<div>
            <? if (count($this->tabs) > 0): ?>
            <div class='row'>
              <div class='col-md-12'>

                  <a name="tabnav"></a>
                  <ul class="recordTabs nav nav-tabs">

                    <? foreach ($this->tabs as $tab => $obj): ?>
                    <? // add current tab to breadcrumbs if applicable:
                      $desc = $obj->getDescription();
                      $tab_classes = array();
                      if (0 === strcasecmp($this->activeTab, $tab)) {
                        $tab_classes[] = 'active';
                        $tab_classes[] = 'initiallyActive';
                        $this->layout()->breadcrumbs .= '<li class="active">' . $this->transEsc($desc) . '</li>';
                        $activeTabObj = $obj;
                      }
                      if (!$obj->isVisible()) { $tab_classes[] = 'hidden'; }
                      if (!$obj->supportsAjax()) { $tab_classes[] = 'noajax'; }
                    ?>
                    <? if ($desc !== 'Buy'): /* temporary hide Buy tab */ ?>
                    <li<?=count($tab_classes) > 0 ? ' class="' . implode(' ', $tab_classes) . '"' : ''?>>
                      <a id="<?=strtolower($tab) ?>" href="<?=$this->recordLink()->getTabUrl($this->driver, $tab)?><?="?referer=".$this->referer?>#tabnav">
                          <? $titleHtml = ($desc=='Holdings') ? $this->transEsc('Borrow') : $this->transEsc($desc) ?>
                          <?= $this->help()->getElementHelp('element_help_record_tab_'.$desc, $titleHtml) ?>

                      </a>
                    </li>
                    <? endif; ?>
                    <? endforeach; ?>
                  </ul>
              </div>
            </div>
           	<? endif; ?>

                <div class="tab-content well border" id="record-tabs">
                  <div class="tab-pane active" id="<?=$this->activeTab ?>-tab">
                    <?=isset($activeTabObj) ? $this->record($this->driver)->getTab($activeTabObj) : '' ?>
                  </div>
                </div>

                <?=$this->driver->supportsCoinsOpenURL()?'<span class="Z3988" title="'.$this->escapeHtmlAttr($this->driver->getCoinsOpenURL()).'"></span>':''?>
            </div>


            <!-- Modal -->
                <div class="modal fade" id="subjectsModal" tabindex="-1" role="dialog" aria-labelledby="subjectsLabel">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="subjectsLabel"><?=$this->translate('Subjects')?></h4>
                      </div>
                      <div class="modal-body">
                        <div class='subjects-scrollable'>
                          <? $subjects = $this->driver->getAllSubjectHeadings(); if (!empty($subjects)): ?>
                              <? foreach ($subjects as $field): ?>
                              <div class="subjectLine" property="keywords">
                                <? $subject = ''; ?>
                                <? if(count($field) == 1) $field = explode('--', is_array($field) ? $field[0] : $field); ?>
                                <? $i = 0; foreach ($field as $subfield): ?>
                                  <?=($i++ == 0) ? '' : ' &gt; '?>
                                  <? $subject = trim($subfield); ?>
                                  <a title="<?=$this->escapeHtmlAttr($subject)?>" href="<?=$this->record($this->driver)->getLink('subject', $subject)?>"><?=trim($this->escapeHtml($subfield))?></a>
                                <? endforeach; ?>
                              </div>
                              <? endforeach; ?>
                          <? endif; ?>
                        </div>
            		  </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal"><?=$this->translate('close')?></button>
                      </div>
                    </div>
                  </div>
                </div>

             <!-- Modal -->
                <div class="modal fade" id="mailRecordModal" tabindex="-1" role="dialog" aria-labelledby="mailRecordLabel">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="mailRecordLabel"><?=$this->translate('Email this Search')?></h4>
                      </div>
                      <div class="modal-body">
                        <?=$this->context($this)->renderInContext('record/email.phtml', [])?>
            		  </div>
                    </div>
                  </div>
                </div>

            <script src="/themes/bootstrap3/js/ajax-record-tabs.js"></script>
            <script>

            /**
             * Removes active state from Buy Link when there are no buyLinks
             *
             * @param {array} buyLinks
             * @return {void}
             */
            function disableBuyTab( buyLinks )
            {
            	if ( buyLinks.data[0]['buyLinksCount'] === 0 )
            		$( '#buy' ).parent().removeClass( 'active' ).addClass( 'disabled' );
            }

            /**
             * Disables tab
             *
             * @param tabId Id tab which will be disabled
             */
            function disableTab(tabId) {
                //disable redirect event on click to eversion link
                tabId.click(function (event) {
                    event.preventDefault();
                });
                tabId.parent().removeClass( 'active' ).addClass( 'disabled' );
            }

            jQuery( document ).ready( function( $ ) {

                // Disable eversion tab
                <?if($this->eVersionLinksCount):?>
                    var eVersionLinksCount = <?=$this->eVersionLinksCount?>;
                <?endif;?>
                if (typeof eVersionLinksCount === 'undefined' || !eVersionLinksCount) {
                    disableTab($( '#eversion' ));
                    //hide table inside the tab
                    $( "#e-version-table" ).addClass( 'hidden' );
                }

                // Disable holdings tab
                var holdingsCount = <?= count($holdings = $this->driver->getRealTimeHoldings()) ?>;
                if (!holdingsCount) {
                    disableTab($( '#holdings' ));
                }

                // Disable AddInfo tab
                <?   $addInfoItemsCount = 1;
                if(method_exists($this->driver, "AddInfoItemsCount"))
                    $addInfoItemsCount = $this->driver->AddInfoItemsCount();
                ?>
                var addInfoItemsCount = <?=$addInfoItemsCount?>;
                if (!addInfoItemsCount) {
                    disableTab($( '#addinfo' ));
                }

                // Disable Contacts tab
                <?   $ContactsItemsCount = 1;
                if(method_exists($this->driver, "ContactsItemsCount"))
                    $ContactsItemsCount = $this->driver->ContactsItemsCount();
                ?>
                var ContactsItemsCount = <?=$ContactsItemsCount?>;
                if (!ContactsItemsCount) {
                    disableTab($( '#contacts' ));
                }

                // Disable Services tab
                <?   $ServicesItemsCount = 1;
                if(method_exists($this->driver, "ServicesItemsCount"))
                    $ServicesItemsCount = $this->driver->ServicesItemsCount();
                ?>
                var ServicesItemsCount = <?=$ServicesItemsCount?>;
                if (!ServicesItemsCount) {
                    disableTab($( '#services' ));
                }

                // Disable Branches tab
                <?   $BranchesItemsCount = 1;
                if(method_exists($this->driver, "BranchesItemsCount"))
                    $BranchesItemsCount = $this->driver->BranchesItemsCount();
                ?>
                var BranchesItemsCount = <?=$BranchesItemsCount?>;
                if (!BranchesItemsCount) {
                    disableTab($( '#branches' ));
                }

                <? if(!$this->isZiskej): ?>
                    disableTab($( '#ziskej' ));
                    // $( "#ziskej-tab" ).addClass( 'hidden' );
                    var elem = document.querySelector('#ziskej-tab');
                    elem.parentNode.removeChild(elem);
                <? endif; ?>

                var recordID = '<?= $this->driver->getUniqueID() ?>';
                var parentRecordID = '<?= method_exists($this->driver, "getParentRecordID") ? $this->driver->getParentRecordID() : null ?>';

            	var source = "<?= $source ?>";

            	// select default record group
            	$( '#record-group li a' ).each( function() {

            		var title = $( this ).attr( 'title' );
            		if ( $( this ).attr( 'id' ).toLowerCase().indexOf( source.toLowerCase() ) >= 0 ) {
            			$( '#first-record-group' ).text( title );
            		}

            	});

            	$( '#subjects-tr' ).on('click', '#show-all-subjects', function(){
            		$( '#subjectsModal' ).modal( 'show' );
            	});

            	$( 'body' ).on('click', '.want-it', function(){
            		$( 'html,body' ).animate( {
            	        scrollTop: $( '#records-in-groups-container' ).offset().top
            	    }, 1000);
            	});

                $( 'body' ).on('click', '.eds-want-it', function(){
                    $( 'html,body' ).animate( {
                        scrollTop: $( '#edsavailability' ).offset().top
                    }, 1000);
                });

            });
            </script>
		</div>

    </div>
    <div class='col-sm-3'>
      <?= $this->render('RecordDriver/SolrDefault/record-sidebar.phtml'); ?>
    </div>
</div>

</div>

<?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, '$(document).ready(recordDocReady);', 'SET'); ?>

