<? if (empty($_COOKIE['eu-cookies'])): ?>
<div class="eu-cookies">

    <?=$this->translate('cookies_agreement')?>

    <button class="btn btn-default" onclick='cookies_agreed(true)'><?=$this->translate('All right')?></button>
    <a href="https://www.google.com/policies/technologies/cookies/"><?=$this->translate('More information')?></a>
    <noscript><style>.eu-cookies { display:none }</style></noscript>
</div>
<? endif; ?>