
<div class="eu-cookies" n:if="empty($_COOKIE[eu-cookies])">

    Tento web používá k poskytování služeb a analýze návštěvnosti soubory cookie. Používáním tohoto webu s tím souhlasíte.

    <button onclick='$(".eu-cookies").remove();'>V pořádku</button>
    <a href="https://www.google.com/policies/technologies/cookies/">Další informace</a>
    <noscript><style>.eu-cookies { display:none }</style></noscript>
</div>