<?
    $portalPages = $this->portalPages()->getAllPages();
?>
<div class="row">
  <div class="col-sm-3">
    <h2><?=$this->transEsc('Search Options')?></h2>
    <ul>
      <li><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></li>
      <?
      if(isset($_SERVER['REDIRECT_URL'])) :
          $redirectUrl = $_SERVER['REDIRECT_URL'];
          $redirectUrlArray = explode("/", $redirectUrl);
          $controller = $redirectUrlArray[1];
          $action = (isset($redirectUrlArray[2])) ? $redirectUrlArray[2] : '';
      ?>
      <? endif; ?>
     <? if (count($portalPages)): ?>
        <? foreach ($portalPages as $page): ?>
          <? if ($page['placement'] === 'footer' && $page['position'] === 'left'): ?>
            <li><a href='/Portal/Page/<?=$page['pretty_url']?>' title='<?=$page['title']?>'><?=$page['title']?></a></li>
          <? endif; ?>
        <? endforeach; ?>
      <? endif; ?>
    </ul>
  </div>
  <div class="col-sm-3">
    <h2 id='aboutPortalHeader'><?=$this->transEsc('About portal knihovny.cz')?></h2>
    <ul>
      <? if (count($portalPages)): ?>
        <? foreach ($portalPages as $page): ?>
          <? if ($page['placement'] === 'footer' && $page['position'] === 'middle-left'): ?>
            <li><a href='/Portal/Page/<?=$page['pretty_url']?>' title='<?=$page['title']?>'><?=$page['title']?></a></li>
          <? endif; ?>
        <? endforeach; ?>
      <? endif; ?>
    </ul>
  </div>
  <div class="col-sm-3">
    <h2 id='aboutPortalHeader'><?=$this->transEsc('About libraries')?></h2>
    <ul>
      <? if (count($portalPages)): ?>
        <? foreach ($portalPages as $page): ?>
          <? if ($page['placement'] === 'footer' && $page['position'] === 'middle-right'): ?>
            <li><a href='/Portal/Page/<?=$page['pretty_url']?>' title='<?=$page['title']?>'><?=$page['title']?></a></li>
          <? endif; ?>
        <? endforeach; ?>
      <? endif; ?>
    </ul>
  </div>
  <div class="col-sm-3">
    <h2><?=$this->transEsc('Need Help?')?></h2>
    <ul>
      <li><a target="_blank" href="https://docs.google.com/a/mzk.cz/document/d/1pc1F4tQkkV1-SmnxuBztdfcVAINIfv7TMrkTOIEP5QI/edit?usp=sharing"><?=$this->transEsc('Hint')?></a></li>
      <li><a href="http://www.ptejteseknihovny.cz/"><?=$this->transEsc('Ask a Librarian')?></a></li>
      <? if (count($portalPages)): ?>
        <? foreach ($portalPages as $page): ?>
          <? if ($page['placement'] === 'footer' && $page['position'] === 'right'): ?>
            <li><a href='/Portal/Page/<?=$page['pretty_url']?>' title='<?=$page['title']?>'><?=$page['title']?></a></li>
          <? endif; ?>
        <? endforeach; ?>
      <? endif; ?>
    </ul>
  </div>
</div>
<div class='row'>
  <div class='col-sm-6' style='padding-right: 20px;'>
	<h4><?=$this->translate('Footer header')?></h4>
	<p>
	Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
	 Duis condimentum augue id magna semper rutrum. Fusce tellus.
	 Mauris metus. Nam sed tellus id magna elementum tincidunt.
	  Integer malesuada. Aenean fermentum risus id tortor. Nam quis nulla.
	  Maecenas sollicitudin. Class aptent taciti sociosqu ad litora torquent
	  per conubia nostra, per inceptos hymenaeos. Nam quis nulla. Phasellus
	  faucibus molestie nisl. Duis ante orci, molestie vitae vehicula venenatis,
	   tincidunt ac pede.
	</p>
  </div>
  <div class='col-sm-3'>
    <h4><?=$this->translate('Developer')?></h4>
	 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img height='40' src='https://www.mzk.cz/sites/mzk.cz/themes/mzk/logo.png'>
	 <h4><?=$this->translate('Founder')?></h4>
	 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img height='60' src='http://nzm.cz/multimedia/uploads/2016/03/logo-mkcr-300x97.png'>
  </div>
  <div class='col-sm-3'>
    <br>
	<img width='64' src='https://cdn0.iconfinder.com/data/icons/flat-social-media-icons-set-round-style-1/550/facebook-128.png'>
	<img width='64' src='https://cdn0.iconfinder.com/data/icons/flat-social-media-icons-set-round-style-1/550/youtube-128.png'>
	<img width='64' src='https://cdn0.iconfinder.com/data/icons/flat-social-media-icons-set-round-style-1/550/github-128.png'>
  </div>

</div>
<br>
