<div class="navbar-header">
  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#header-collapse">
    <span class="sr-only">Toggle navigation</span>
    <i class="fa fa-bars"></i>
  </button>
  <a class="navbar-brand lang-<?=$this->layout()->userLang ?>" href="<?=$this->url('home')?>" style="padding: 0px;">
    <div href="#"><i class="fa knihovny-logo"></i></div>
	</a>
  <a class="beta-logo" title="<?=$this->translate('Changelog')?>"
    data-toggle="tooltip" data-placement="top"
    href="<?=$this->translate('beta_changelog_link')?>">
    <?=$this->translate('beta_tag')?>
  </a>
</div>
<? if (!isset($this->layout()->renderingError)): ?>
  <div class="collapse navbar-collapse" id="header-collapse">
    <ul class="nav navbar-nav">
        <li class="active"><a href="<?=$this->url('home')?>"><?=$this->translate('Catalog')?><span class="sr-only">(current)</span></a></li>
        <li><a href="http://info.knihovny.cz/libraries"><?=$this->translate('Libraries')?></a></li>
        <li><a href="http://info.knihovny.cz/events"><?=$this->translate('Events')?></a></li>
      </ul>
    <nav>
      <ul class="nav navbar-nav navbar-right flip">
        <? if ($this->feedback()->tabEnabled()): ?>
          <li>
            <a id="feedbackLink" class="modal-link" href="<?=$this->url('feedback-home') ?>"><i class="fa fa-envelope"></i> <?=$this->transEsc("Feedback")?></a>
          </li>
        <? endif; ?>
        <? $cart = $this->cart(); if ($cart->isActive()): ?>
          <li id="cartSummary">
            <a id="cartItems" class="modal-link" title="<?=$this->transEsc('View Book Bag')?>" href="<?=$this->url('cart-home')?>"><i class="fa fa-suitcase"></i> <strong><?=count($cart->getItems())?></strong> <?=$this->transEsc('items')?><?=$cart->isFull() ? ' (' .  $this->transEsc('bookbag_full') . ')' : ''?></a>
          </li>
        <? endif; ?>

        <? if ($notificationsEnabled): ?>
          <?=$this->render('notifications.phtml', [ 'user' => $user, 'libraryCards' => $libraryCards])?>
        <? endif; ?>

        <? if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
		  <? if($user): ?>
            <li class="dropdown">
            <? if (!empty($user->firstname) || !empty($user->lastname)) {
                $fullname = $user->firstname . ' ' . $user->lastname;
            } else {
                $fullname = $this->transEsc("Your Account");
            } ?>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$fullname?> <b
					class="caret"></b></a>
				<ul class="dropdown-menu">
					<li class="myAccountOptions"><a
						href="<?=$this->url('myresearch-home', array(), array('query' => array('redirect' => 0)))?>"
						class="modal-link" title="<?=$this->transEsc("Your Account")?>"><i
							class="fa fa-home"></i> <?=$this->transEsc("Your Account")?></a>
					</li>
					<li class="myAccountOptions">
					  <a href="<?=$this->url('myresearch-favorites')?>"
		                class="modal-link" title="<?=$this->transEsc('Your Favorites')?>"><i
		                class="icon-oblibene"></i> <?=$this->transEsc('Your Favorites')?></a>
					</li>
				</ul>
			</li>
		  <? else: ?>
		    <li>
		      <a href="<?=$this->url('myresearch-favorites')?>"
		        class="modal-link" title="<?=$this->transEsc('Your Favorites')?>"><i
		        class="icon-oblibene"></i> <?=$this->transEsc('Your Favorites')?></a>
		    </li>
		  <? endif ?>
        <? endif; ?>

        <? if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
          <li class="dropdown">
            <form method="post" name="themeForm" id="themeForm">
              <input type="hidden" name="ui"/>
            </form>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Theme")?> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <? foreach ($this->layout()->themeOptions as $current): ?>
                <li<?=$current['selected'] ? ' class="active"' : ''?>><a href="#" onClick="document.themeForm.ui.value='<?=$this->escapeHtmlAttr($current['name'])?>';document.themeForm.submit()"><?=$this->transEsc($current['desc'])?></a></li>
              <? endforeach; ?>
            </ul>
          </li>
        <? endif; ?>

        <? if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
          <form method="post" name="langForm" id="langForm" style="float: left;">
            <input type="hidden" name="mylang"/>
          </form>
          <? foreach ($this->layout()->allLangs as $langCode => $langName): ?>
            <? if ($this->layout()->userLang != $langCode): ?>
              <li<?=$this->layout()->userLang == $langCode ? ' class="active"' : ''?>><a href="#" onClick="document.langForm.mylang.value='<?=$langCode?>';document.langForm.submit()"><?=$this->displayLanguageOption($langName)?></a></li>
            <? endif; ?>
        <? endforeach; ?>
        <? endif; ?>

        <? if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
        <? if($user): ?>
			<li id="logoutOptions">
              <a href="<?=$this->url('myresearch-logout')?>"
                class="modal-link" title="<?=$this->transEsc("Log Out")?>">
                <i class="icon-odhlasit"></i> <?=$this->transEsc("Log Out")?></a>
			<? else: ?>
			<li id="loginOptions">
              <? if ($sessionInitiator = $account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
                <a href="#" onclick='$("div#loginModal").modal("show")'><i
				  class="pr-user-passwordlock"></i> <?=$this->transEsc("Institutional Login")?></a>
              <? else: ?>
                <a href="#" onclick='$("div#loginModal").modal("show")'
                  class="modal-link" title="<?=$this->transEsc("Login")?>"><i
                  class="pr-user-passwordlock"></i> <?=$this->transEsc("Login")?></a>
              <? endif; ?>
            <? endif; ?>
            </li>
		<? endif; ?>
      </ul>
    </nav>
  
    <!-- Modal for login -->
    <div class="modal fade" id="loginModal" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content" ng-controller="FederativeLoginController as fedLoginCtrl">
          <div class="modal-header" ng-show='fedLoginCtrl.hasLastIdps()'>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"><?=$this->translate('login_last_used')?></h4>
          </div>
          <div class="modal-body" ng-last-used ng-show='fedLoginCtrl.hasLastIdps()'>
		  </div>
		  <div class="modal-header link" ng-click="fedLoginCtrl.showHelpContent()" style="cursor: pointer">
		    <? $portalPage = $this->portalPages()->getPage('napoveda-pro-prihlaseni-a-registraci'); ?>
		    <h4 class="modal-title"><?=$portalPage['title']?></h4>
		  </div>
		  <div class="modal-body" ng-help-content hidden="hidden">
		    <?=$portalPage['content'] ?>
		  </div>
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"><?=$this->translate('login_with')?></h4>
          </div>
          <div class="modal-body">
          	<?=$this->render('login/identity-providers.phtml', [
          	    'idps' => $this->identityProviders()->getLibraries()
          	]) ?>
		  </div>
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"><?=$this->translate('login_other')?></h4>
          </div>
          <div class="modal-body">
          	<?=$this->render('login/identity-providers.phtml', [
          	    'idps' => $this->identityProviders()->getOthers()
          	]) ?>
		  </div>    	
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal"><?=$this->translate('close')?></button>
          </div>
        </div>
      </div>
    </div>
  </div>
<? endif; ?>
