<div class="navbar-header">
  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#header-collapse">
    <span class="sr-only">Toggle navigation</span>
    <i class="fa fa-bars"></i>
  </button>
  <a class="navbar-brand lang-<?=$this->layout()->userLang ?>" href="<?=$this->url('home')?>" style="padding: 0px;">
    <div href="#"><i class="fa knihovny-logo"></i></div>
	</a>
</div>
<? if (!isset($this->layout()->renderingError)): ?>
  <div class="collapse navbar-collapse" id="header-collapse">
    <ul class="nav navbar-nav">
        <li class="active"><a href="<?=$this->url('home')?>">Katalog<span class="sr-only">(current)</span></a></li>
        <li><a href="http://info.knihovny.cz/libraries">Knihovny</a></li>
        <li><a href="http://info.knihovny.cz/events">Akce</a></li>
      </ul>
    <nav>
      <ul class="nav navbar-nav navbar-right flip">
        <? if ($this->feedback()->tabEnabled()): ?>
          <li>
            <a id="feedbackLink" class="modal-link" href="<?=$this->url('feedback-home') ?>"><i class="fa fa-envelope"></i> <?=$this->transEsc("Feedback")?></a>
          </li>
        <? endif; ?>
        <? $cart = $this->cart(); if ($cart->isActive()): ?>
          <li id="cartSummary">
            <a id="cartItems" class="modal-link" title="<?=$this->transEsc('View Book Bag')?>" href="<?=$this->url('cart-home')?>"><i class="fa fa-suitcase"></i> <strong><?=count($cart->getItems())?></strong> <?=$this->transEsc('items')?><?=$cart->isFull() ? ' (' .  $this->transEsc('bookbag_full') . ')' : ''?></a>
          </li>
        <? endif; ?>

        <? if ($notificationsEnabled): ?>
          <?=$this->render('notifications.phtml', [ 'user' => $user, 'libraryCards' => $libraryCards])?>
        <? endif; ?>

        <? if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
		  <? if($user): ?>
            <li class="dropdown">
            <? if (!empty($user->firstname) || !empty($user->lastname)) {
                $fullname = $user->firstname . ' ' . $user->lastname;
            } else {
                $fullname = $this->transEsc("Your Account");
            } ?>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$fullname?> <b
					class="caret"></b></a>
				<ul class="dropdown-menu">
					<li class="myAccountOptions"><a
						href="<?=$this->url('myresearch-home', array(), array('query' => array('redirect' => 0)))?>"
						class="modal-link" title="<?=$this->transEsc("Your Account")?>"><i
							class="fa fa-home"></i> <?=$this->transEsc("Your Account")?></a>
					</li>
					<li class="myAccountOptions">
					  <a href="<?=$this->url('myresearch-favorites')?>"
		                class="modal-link" title="<?=$this->transEsc('Your Favorites')?>"><i
		                class="icon-oblibene"></i> <?=$this->transEsc('Your Favorites')?></a>
					</li>
				</ul>
			</li>
		  <? else: ?>
		    <li>
		      <a href="<?=$this->url('myresearch-favorites')?>"
		        class="modal-link" title="<?=$this->transEsc('Your Favorites')?>"><i
		        class="icon-oblibene"></i> <?=$this->transEsc('Your Favorites')?></a>
		    </li>
		  <? endif ?>
        <? endif; ?>

        <? if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
          <li class="dropdown">
            <form method="post" name="themeForm" id="themeForm">
              <input type="hidden" name="ui"/>
            </form>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Theme")?> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <? foreach ($this->layout()->themeOptions as $current): ?>
                <li<?=$current['selected'] ? ' class="active"' : ''?>><a href="#" onClick="document.themeForm.ui.value='<?=$this->escapeHtmlAttr($current['name'])?>';document.themeForm.submit()"><?=$this->transEsc($current['desc'])?></a></li>
              <? endforeach; ?>
            </ul>
          </li>
        <? endif; ?>

        <? if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
          <form method="post" name="langForm" id="langForm" style="float: left;">
            <input type="hidden" name="mylang"/>
          </form>
          <? foreach ($this->layout()->allLangs as $langCode => $langName): ?>
            <? if ($this->layout()->userLang != $langCode): ?>
              <li<?=$this->layout()->userLang == $langCode ? ' class="active"' : ''?>><a href="#" onClick="document.langForm.mylang.value='<?=$langCode?>';document.langForm.submit()"><?=$this->displayLanguageOption($langName)?></a></li>
            <? endif; ?>
        <? endforeach; ?>
        <? endif; ?>

        <? if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
        <? if($user): ?>
			<li id="logoutOptions">
              <a href="<?=$this->url('myresearch-logout')?>"
                class="modal-link" title="<?=$this->transEsc("Log Out")?>">
                <i class="icon-odhlasit"></i> <?=$this->transEsc("Log Out")?></a>
			<? else: ?>
			<li id="loginOptions">
              <? if ($sessionInitiator = $account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
                <a href="<?=$this->escapeHtmlAttr($sessionInitiator)?>"><i
				  class="icon-prihlasit"></i> <?=$this->transEsc("Institutional Login")?></a>
              <? else: ?>
                <a href="<?=$this->url('myresearch-userlogin')?>"
                  class="modal-link" title="<?=$this->transEsc("Login")?>"><i
                  class="icon-prihlasit"></i> <?=$this->transEsc("Login")?></a>
              <? endif; ?>
            <? endif; ?>
            </li>
		<? endif; ?>
      </ul>
    </nav>
  </div>
<? endif; ?>
