<? $haveBlocks = is_array($blocks) && count($blocks) > 0;
if ($haveBlocks): ?>
  <? foreach($blocks as $key => $block): ?>
    <li class="notification">
      <span class="label label-warning"><?=$block ?></span>
    </li>
  <? endforeach; ?>
<? else: // No blocks were found ?>
  <li class="notification">
    <span class="label label-success"><?=$this->transEsc('no_blocks_found')?></span>
  </li>
<? endif; ?>