<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" id="notif_icon">
    <i style="font-size: 20px; color: #fff;" class="fa fa-fw fa-bell"></i>
    <i class="fa fa-warning notificationWarning" id="notif-warning" style="display: none"></i>
  </a>
  <ul id='notificationsList' class="dropdown-menu">
  	<li>
  	  <div class="notif-header"> <?=$this->translate('source_cpk', null, 'Knihovny.cz')?>
  	    <img height="20" class="pull-right" alt="knihovny.cz" src="<?=$this->imageLink('knihovny-logo.png') ?>"/>
  	  </div>
	  <div data-type="global" class="identity-notifications" <?=$this->globalNotifications()->isEnabled() || ! $user ? '' : 'hidden="hidden"' ?>>
	    <?=$this->globalNotifications()->renderAll() ?>
	  </div>
	  <? if ($user): ?>
      <div class="notif-default" data-type="loader">
	    <i class="fa fa-spinner fa-spin"></i>
	    <span class="label label-primary"><?=$this->transEsc('Loading')?> ...</span>
      </div>
      <? endif; ?>
	</li>
  <? if ($user): foreach ($libraryCards as $libraryCard):
	   $source = explode('.', $libraryCard['cat_username'])[0];
  ?>
	<li hidden="hidden">
	   <div class="notif-header"> <?=$this->translate('source_' . $source, null, $source)?>
	     <img height="20" class="pull-right" src="<?=$this->logos()->getLogo($source) ?>"/>
	   </div>
	   <div data-type="institution" data-source="<?=$source?>" data-id="<?=$libraryCard['cat_username'] ?>" class="identity-notifications"></div>
	</li>
     <? endforeach; endif;?>
  </ul>
</li>