<?php
    // Set up page title:
    $this->headTitle($this->translate('Statistics'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/Search">' . $this->transEsc('Main page') . '</a></li> '.
                                   '<li><a href="'.$this->url('myresearch-home').'">'.$this->translate('Your Account').'</a></li>' 
    							  .'<li><a href="'.$this->url('statistics-dashboard').'">' . $this->translate('Statistics') . '</a></li>'
    							  .'<li class="active">' . $this->translate('Payments') . '</li>';
    
    echo $this->render('statistics/menu.phtml');
    
    echo $this->render('statistics/calendar.phtml');
?>

<div class="row">
	<div class="<?=$this->layoutClass('mainbody')?>">

		<div class="row">
			<div class="col-lg-3 col-md-6">
				<div class="panel panel-primary">
					<div class="panel-heading">
						<div class="row">
							<div class="col-xs-3">
								<i class="fa fa-user-plus fa-4x"></i>
		 					</div>
							<div class="col-xs-9 text-right">
		 						<div class="huge">20 543</div>
								<div><?= $this->translate('Registrations'); ?></div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-3 col-md-6">
				<div class="panel panel-green">
					<div class="panel-heading">
						<div class="row">
							<div class="col-xs-3">
								<i class="fa fa-clock-o fa-4x"></i>
		 					</div>
							<div class="col-xs-9 text-right">
		 						<div class="huge"><?= number_format(32580, 0, ',', ' ') ?></div>
								<div><?= $this->translate('Prolongations'); ?></div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-3 col-md-6">
				<div class="panel panel-yellow">
					<div class="panel-heading">
						<div class="row">
							<div class="col-xs-3">
								<i class="fa fa-bookmark fa-4x"></i>
		 					</div>
							<div class="col-xs-9 text-right">
		 						<div class="huge"><?= number_format(12520, 0, ',', ' ') ?></div>
								<div><?= $this->translate('Reservatons'); ?></div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-3 col-md-6">
				<div class="panel panel-red">
					<div class="panel-heading">
						<div class="row">
							<div class="col-xs-3">
								<i class="fa fa-warning fa-4x"></i>
		 					</div>
							<div class="col-xs-9 text-right">
		 						<div class="huge"><?= number_format(13589, 0, ',', ' ') ?></div>
								<div><?= $this->translate('Fines'); ?></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- /.row -->
		
		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
				    <div class="panel-heading">
				        <h3 class="panel-title">
				            <i class="fa fa-clock-o fa-fw"></i>
				             <?= $this->translate('Payments in time') ?>
				        </h3>
				    </div>
				    <div class="panel-body">
				    	<div id="payments-in-time"></div>
				    </div>
				</div>
			</div>
		</div>
		<!-- /.row -->

	</div>
	<div class="<?=$this->layoutClass('sidebar')?>">
    	<?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'statistics'))?>
	</div>
</div>
<!-- /.row -->

<? $this->headScript()->appendFile("raphael.min.js"); ?>
<? $this->headScript()->appendFile("morris-0.4.1.min.js"); ?>
<? $this->headScript()->appendFile("jquery-ui.min.js"); ?>
<script>
	jQuery( document ).ready( function( $ ) {
		
		// Sets menu item as active
		$( ".statistics-payments" ).addClass( "active" );

		// Initializes area chart for visits in time
	    Morris.Area(	{
	        element: 'payments-in-time',
	        data: [
			   	{
		            period: '2012-01',
		            registrace: 620,
		            prolongace: 680,
		            rezervace: 1500,
		    		upominky: 1300
		        }, {
		            period: '2012-02',
		            registrace: 520,
		            prolongace: 780,
		            rezervace: 1400,
		    		upominky: 1300
		        }, {
		            period: '2012-03',
		            registrace: 320,
		            prolongace: 280,
		            rezervace: 1700,
		    		upominky: 1800
		        }, {
		            period: '2012-04',
		            registrace: 680,
		            prolongace: 620,
		            rezervace: 1300,
		    		upominky: 1100
		        }, {
		            period: '2012-05',
		            registrace: 610,
		            prolongace: 680,
		            rezervace: 1600,
		    		upominky: 1600
		        }, {
		            period: '2012-06',
		            registrace: 680,
		            prolongace: 480,
		            rezervace: 1500,
		    		upominky: 2300
		        }, {
		            period: '2012-07',
		            registrace: 520,
		            prolongace: 640,
		            rezervace: 2500,
		    		upominky: 1800
		        }, {
		            period: '2012-08',
		            registrace: 720,
		            prolongace: 580,
		            rezervace: 1200,
		    		upominky: 1400
		        }, {
		            period: '2012-09',
		            registrace: 650,
		            prolongace: 650,
		            rezervace: 1500,
		    		upominky: 1300
		        }, {
		            period: '2012-10',
		            registrace: 620,
		            prolongace: 680,
		            rezervace: 1600,
		    		upominky: 1700
		        }, {
		            period: '2012-11',
		            registrace: 625,
		            prolongace: 685,
		            rezervace: 2100,
		    		upominky: 900
		        }, {
		            period: '2012-12',
		            registrace: 693,
		            prolongace: 644,
		            rezervace: 1358,
		    		upominky: 1454
		        }
	        ],
	        xkey: 'period',
	        ykeys: [ 'registrace', 'prolongace', 'rezervace', 'upominky' ],
	        labels: [ '<?= $this->translate('Registrations'); ?>', '<?= $this->translate('Prolongations'); ?>', '<?= $this->translate('Reservations'); ?>', '<?= $this->translate('Fines'); ?>' ],
	        lineColors: ['#0F5693', '#389438', '#B57213', '#A6201C'],
	        fillOpacity: 0.9,
	        behaveLikeLine: true,
	        pointSize: 2,
	        hideHover: 'auto'
	      });
		
	});
</script>