<?php
    // Set up page title:
    $this->headTitle($this->translate('Statistics'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/Search">' . $this->transEsc('Main page') . '</a></li> '.
    '<li><a href="'.$this->url('myresearch-home').'">'.$this->translate('Your Account').'</a></li>'
    							  .'<li><a href="'.$this->url('statistics-dashboard').'">' . $this->translate('Statistics') . '</a></li>'
    							  .'<li class="active">' . $this->translate('Visits') . '</li>';

    echo $this->render('statistics/menu.phtml');

    echo $this->render('statistics/calendar.phtml');

    $libCard = null;

    if (isset($this->urlGetParams['libCard']))
        $libCard  = $this->urlGetParams['libCard'];
?>

<div class="row">
	<div class="<?=$this->layoutClass('mainbody')?>">

		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
				    <div class="panel-heading">
				        <h3 class="panel-title">
				            <i class="fa fa-clock-o fa-fw"></i>
				             <?= $this->translate('Visits in time') ?>
				        </h3>
				    </div>
				    <div class="panel-body">
				    	<div id="visits-in-time"></div>
				    </div>
				</div>
			</div>
		</div>
		<!-- /.row -->

		<div class="row">
			<div class="col-lg-4">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title">
							<i class="fa fa-user fa-fw"></i>
		 					<?= $this->translate('All Visitors') ?>
						</h3>
					</div>
					<div class="panel-body">
						<div id="visits-comparision"></div>
					</div>
				</div>
			</div>

			<? if ( ($libCard && $libCard === 'all') || (! $libCard)) : ?>
			<div class="col-lg-4">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title">
							<i class="fa fa-user fa-fw"></i>
		 					<?= $this->translate('Anonymous Visitors') ?>
						</h3>
					</div>
					<div class="panel-body">
						<div id="visits-comparision-anonymous"></div>
					</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title">
							<i class="fa fa-user fa-fw"></i>
		 					<?= $this->translate('Authenticated Visitors') ?>
						</h3>
					</div>
					<div class="panel-body">
						<div id="visits-comparision-authenticated"></div>
					</div>
				</div>
			</div>
			<? endif; ?>

		</div>
		<!-- /.row -->

		<div class='row'>
			<div class="col-lg-6">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title">
							<i class="fa fa-users fa-fw"></i>
							<?= $this->translate('Dashboard') ?>
						</h3>
					</div>
					<div class="panel-body">
		  				<div class="table-responsive">
							<table class="table table-hover table-striped">
								<tbody>
									<tr>
										<td>
											<?= $this->translate('Total visits') ?>
										</td>
										<td>
											<?= number_format($this->totalVisits, 0, ',', ' ') ?>
										</td>
									</tr>
									<!--<tr>
										<td>
											<?= $this->translate('Total time') ?>
										</td>
										<td>
											<?= $this->totalTimeOnSite ?>
										</td>
									</tr>-->
									<tr>
										<td>
											<?= $this->translate('Average visit time') ?>
										</td>
										<td>
											<?= $this->avgTimeOnSite ?>
										</td>
									</tr>
									<tr>
										<td>
											<?= $this->translate('Actions') ?>
										</td>
										<td>
											<?= number_format($this->nbActions, 0, ',', ' ') ?>
										</td>
									</tr>
									<tr>
										<td>
											<?= $this->translate('Actions per visit') ?>
										</td>
										<td>
											<?= number_format($this->nbActionPerVisit, 1, ',', ' ') ?>
										</td>
									</tr>
									<tr>
										<td>
											<?= $this->translate('Online borrowers') ?>
										</td>
										<td>
											<?= number_format($this->nbOnlineUsers, 0, ',', ' ') ?>
										</td>
									</tr>
									<? if (($libCard) && ($libCard === 'all')) : ?>
									<tr><td><?= $this->translate('Returning anonymous visitors') ?></td><td><?= number_format($this->returningAnonymeVisitorsCount, 0, ',', ' ') ?></td></tr>
									<tr><td><?= $this->translate('Returning authenticated visitors') ?></td><td><?= number_format($this->returningAuthenticatedVisitorsCount, 0, ',', ' ') ?></td></tr>
									<tr><td><?= $this->translate('New anonymous visitors') ?></td><td><?= number_format($this->newAnonymeVisitorsCount, 0, ',', ' ') ?></td></tr>
									<tr><td><?= $this->translate('New authenticated visitors') ?></td><td><?= number_format($this->newAuthenticatedVisitorsCount, 0, ',', ' ') ?></td></tr>
									<? endif; ?>
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- /.row -->

	</div>
	<div class="<?=$this->layoutClass('sidebar')?>">
    	<?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'statistics'))?>
	</div>
</div>
<!-- /.row -->

<? $this->headScript()->appendFile("raphael.min.js"); ?>
<? $this->headScript()->appendFile("morris-0.4.1.min.js"); ?>
<? $this->headScript()->appendFile("jquery-ui.min.js"); ?>
<script>
	jQuery( document ).ready( function( $ ) {

		// Sets menu item as active
		$( ".statistics-visits" ).addClass( "active" );

		// Initializes donut charts for visitors comparision
	    Morris.Donut( {
	        element: 'visits-comparision',
	        data: [
	        	{ label: "<?= $this->translate('Returning readers'); ?>",
		          value: <?= number_format($this->returningVisitorsCount, 0, ',', ' ') ?>
		        },
			    { label: "<?= $this->translate('New readers'); ?>",
				  value: <?= number_format($this->newVisitorsCount, 0, ',', ' ') ?>
				},
			],
	        resize: true
	    });
	    <? if ( ($libCard && $libCard === 'all') || (! $libCard)) : ?>
	    Morris.Donut( {
	        element: 'visits-comparision-anonymous',
	        data: [
	        	{ label: "<?= $this->translate('Returning readers'); ?>",
		          value: <?= number_format($this->returningAnonymeVisitorsCount, 0, ',', ' ') ?>
		        },
			    { label: "<?= $this->translate('New readers'); ?>",
				  value: <?= number_format($this->newAnonymeVisitorsCount, 0, ',', ' ') ?>
				},
			],
	        resize: true
	    });

	    Morris.Donut( {
	        element: 'visits-comparision-authenticated',
	        data: [
	        	{ label: "<?= $this->translate('Returning readers'); ?>",
		          value: <?= number_format($this->returningAuthenticatedVisitorsCount, 0, ',', ' ') ?>
		        },
			    { label: "<?= $this->translate('New readers'); ?>",
				  value: <?= number_format($this->newAuthenticatedVisitorsCount, 0, ',', ' ') ?>
				},
			],
	        resize: true
	    });
		<? endif; ?>

	 	// Initializes area chart for visits in time
	    Morris.Area( {
	        element: 'visits-in-time',
	        data: [
	   	    	<?php
	   	    		$data = "";
	   	    		foreach ($this->visitsInTime as $key => $value) {
						$data .= "{ period: '$key', novi: ".$value["newVisits"].", vracejici: ".$value["returningVisits"]." },";
	   	    		}
	   	    		echo rtrim($data, ",");
				?>
	        ],
	        xkey: 'period',
	        ykeys: [ 'novi', 'vracejici' ],
	        labels: [ '<?= $this->translate('New visits'); ?>', '<?= $this->translate('Returning visits'); ?>' ],
	        pointSize: 2,
	        parseTime: false,
	        hideHover: 'auto'
	      });

	});
</script>