<?
  // Set page title.
  $this->headTitle($this->translate('Search Home'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
  }

  // Load search actions and settings (if any):
  $options = $this->searchOptions($this->searchClassId);
  $basicSearch = $options->getSearchAction();
  $advSearch = $options->getAdvancedSearchAction();
  
  $this->layout()->breadcrumbs = false;
  
  $userLang = $this->layout()->userLang;
  $projectPage = "http://projekt.narodnifonoteka.cz/";
  if ($userLang != 'cs') {
      $projectPage .= 'homeeng';
  }
?>
<div class="row clearfix">
  <div class="col-md-6">
    <a href="<?=$projectPage?>"><img src="<?=$this->imageLink("fonoteka-deska-$userLang.png") ?>"></img></a>
  </div>
  <div class="col-md-6 centering">
    <div class="searchbox">
      <?=$this->render("search/searchbox-mainpage.phtml")?>
    </div>
    <div class="row clearfix">
      <div class="col-md-4">
        <p><strong><?=$this->transEsc('Search Options')?></strong></p>
        <ul>
          <li><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></li>
          <li><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></li>
        </ul>
      </div>
      <div class="col-md-4">
        <p><strong><?=$this->transEsc('Find More')?></strong></p>
        <ul>
          <li><a href="<?=$this->url('browse-home')?>"><?=$this->transEsc('Browse the Catalog')?></a></li>
          <li><a href="<?=$this->url('alphabrowse-home')?>"><?=$this->transEsc('Browse Alphabetically')?></a></li>
        </ul>
      </div>
    </div>
    <div>
    <p class="homepage-citation">
    <?=$this->transEsc('vnf-homepage-citation')?><b><?=$this->transEsc('vnf-homepage-citation-bold')?></b>
    
     </p>
     <p class="homepage-citation-author">
     Karel Čapek
     </p>
     <p>
       <a href="<?=$projectPage?>"><?=$this->transEsc('About the project')?></a>
     </p>
     </div>
     <div>
       <?=$this->transEsc('vnf-homepage-annex')?>
     </div>
  </div>
  <div class="col-md-12 institutions">
    <div class="row">Poskytovatelé dat</div>
    <img src="<?=$this->imageLink("institutions/01 prispevatele dat/fonoteka-logo-02.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/01 prispevatele dat/fonoteka-logo-05.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/01 prispevatele dat/fonoteka-logo-audioteka.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/01 prispevatele dat/fonoteka-logo-cr.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/01 prispevatele dat/fonoteka-logo-ervis.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/01 prispevatele dat/fonoteka-logo-esta.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/01 prispevatele dat/fonoteka-logo-khfb.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/01 prispevatele dat/fonoteka-logo-kkv.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/01 prispevatele dat/fonoteka-logo-kladno.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/01 prispevatele dat/fonoteka-logo-kutnahora.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/01 prispevatele dat/fonoteka-logo-liberec.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/01 prispevatele dat/fonoteka-logo-mahena.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/01 prispevatele dat/fonoteka-logo-mek.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/01 prispevatele dat/fonoteka-logo-mkhk.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/01 prispevatele dat/fonoteka-logo-mkp.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/01 prispevatele dat/fonoteka-logo-mzk2.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/01 prispevatele dat/fonoteka-logo-nkp.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/01 prispevatele dat/fonoteka-logo-nm.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/01 prispevatele dat/fonoteka-logo-osa.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/01 prispevatele dat/fonoteka-logo-pehlrimov.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/01 prispevatele dat/fonoteka-logo-radioteka.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/01 prispevatele dat/fonoteka-logo-supraphon.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/01 prispevatele dat/fonoteka-logo-vko.png") ?>"/>
  </div>
  <div class="col-md-12 institutions">
    <div class="row">Mediální partneři</div>
    <img src="<?=$this->imageLink("institutions/02 medialni partneri/fonoteka-logo-cr.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/02 medialni partneri/fonoteka-logo-ervis.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/02 medialni partneri/fonoteka-logo-inflow.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/02 medialni partneri/fonoteka-logo-kisk2.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/02 medialni partneri/fonoteka-logo-naposlech.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/02 medialni partneri/fonoteka-logo-osa.png") ?>"/>
  </div>
</div>
