<?
  // Set page title.
  $this->headTitle($this->translate('Search Home'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
  }

  // Load search actions and settings (if any):
  $options = $this->searchOptions($this->searchClassId);
  $basicSearch = $options->getSearchAction();
  $advSearch = $options->getAdvancedSearchAction();
  
  $this->layout()->breadcrumbs = false;
  
  $userLang = $this->layout()->userLang;
  $projectPage = "http://projekt.narodnifonoteka.cz/";
  if ($userLang != 'cs') {
      $projectPage .= 'homeeng';
  }
?>
<div class="row clearfix">
  <div class="col-md-6">
    <a href="<?=$projectPage?>"><img src="<?=$this->imageLink("fonoteka-deska-$userLang.png") ?>"></img></a>
  </div>
  <div class="col-md-6 centering">
    <div class="searchbox">
      <?=$this->render("search/searchbox-mainpage.phtml")?>
    </div>
    <div class="row clearfix">
      <div class="col-md-4">
        <p><strong><?=$this->transEsc('Search Options')?></strong></p>
        <ul>
          <li><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></li>
          <li><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></li>
        </ul>
      </div>
      <div class="col-md-4">
        <p><strong><?=$this->transEsc('Find More')?></strong></p>
        <ul>
          <li><a href="<?=$this->url('browse-home')?>"><?=$this->transEsc('Browse the Catalog')?></a></li>
          <li><a href="<?=$this->url('alphabrowse-home')?>"><?=$this->transEsc('Browse Alphabetically')?></a></li>
        </ul>
      </div>
    </div>
    <div>
    <p class="homepage-citation">
    <?=$this->transEsc('vnf-homepage-citation')?><b><?=$this->transEsc('vnf-homepage-citation-bold')?></b>
    
     </p>
     <p class="homepage-citation-author">
     Karel Čapek
     </p>
     <p>
       <a href="<?=$projectPage?>"><?=$this->transEsc('About the project')?></a>
     </p>
     </div>
     <div>
       <?=$this->transEsc('vnf-homepage-annex')?>
     </div>
  </div>
  <div class="col-md-12 institutions">
    <div class="row"><?=$this->transEsc('Data providers')?></div>
    <a href="http://www.mzk.cz/" target="_blank"><img src="/themes/vnf3/images/institutions/01 prispevatele dat/fonoteka-logo-mzk2.png" title="<?=$this->transEsc('vnf-homepage-ins-alt-mzk')?>"/></a>
    <a href="http://www.nkp.cz/" target="_blank"><img src="/themes/vnf3/images/institutions/01 prispevatele dat/fonoteka-logo-nkp.png" title="<?=$this->transEsc('vnf-homepage-ins-alt-nkp')?>"/></a>
    <a href="http://www.nm.cz/" target="_blank"><img src="/themes/vnf3/images/institutions/01 prispevatele dat/fonoteka-logo-nm.png" title="<?=$this->transEsc('vnf-homepage-ins-alt-nm')?>"/></a>
    <a href="http://www.rozhlas.cz/" target="_blank"><img src="/themes/vnf3/images/institutions/01 prispevatele dat/fonoteka-logo-cr.png" title="<?=$this->transEsc('vnf-homepage-ins-alt-cr')?>"/></a>
    <a href="http://www.supraphon.cz/" target="_blank"><img src="/themes/vnf3/images/institutions/01 prispevatele dat/fonoteka-logo-supraphon.png" title="<?=$this->transEsc('vnf-homepage-ins-alt-supraphon')?>"/></a>
    <a href="http://www.mlp.cz/" target="_blank"><img src="/themes/vnf3/images/institutions/01 prispevatele dat/fonoteka-logo-mkp.png" title="<?=$this->transEsc('vnf-homepage-ins-alt-mkp')?>"/></a>
    <a href="http://www.cbvk.cz/" target="_blank"><img src="/themes/vnf3/images/institutions/01 prispevatele dat/fonoteka-logo-02.png" title="<?=$this->transEsc('vnf-homepage-ins-alt-02')?>"/></a>
    <a href="http://www.ktn.cz/" target="_blank"><img src="/themes/vnf3/images/institutions/01 prispevatele dat/fonoteka-logo-05.png" title="<?=$this->transEsc('vnf-homepage-ins-alt-05')?>"/></a>
    <a href="http://www.svkkl.cz/" target="_blank"><img src="/themes/vnf3/images/institutions/01 prispevatele dat/fonoteka-logo-kladno.png" title="<?=$this->transEsc('vnf-homepage-ins-alt-kladno')?>"/></a>
    <a href="http://www.kvkli.cz/" target="_blank"><img src="/themes/vnf3/images/institutions/01 prispevatele dat/fonoteka-logo-liberec.png" title="<?=$this->transEsc('vnf-homepage-ins-alt-liberec')?>"/></a>
    <a href="http://www.vkol.cz/" target="_blank"><img src="/themes/vnf3/images/institutions/01 prispevatele dat/fonoteka-logo-vko.png" title="<?=$this->transEsc('vnf-homepage-ins-alt-vko')?>"/></a>
    <a href="http://www.kfbz.cz/" target="_blank"><img src="/themes/vnf3/images/institutions/01 prispevatele dat/fonoteka-logo-khfb.png" title="<?=$this->transEsc('vnf-homepage-ins-alt-khfb')?>"/></a>
    <a href="http://www.kkvysociny.cz/" target="_blank"><img src="/themes/vnf3/images/institutions/01 prispevatele dat/fonoteka-logo-kkv.png" title="<?=$this->transEsc('vnf-homepage-ins-alt-kkv')?>"/></a>
    <a href="http://www.knihovnahk.cz/" target="_blank"><img src="/themes/vnf3/images/institutions/01 prispevatele dat/fonoteka-logo-mkhk.png" title="<?=$this->transEsc('vnf-homepage-ins-alt-mkhk')?>"/></a>
    <a href="http://www.kjm.cz/" target="_blank"><img src="/themes/vnf3/images/institutions/01 prispevatele dat/fonoteka-logo-mahena.png" title="<?=$this->transEsc('vnf-homepage-ins-alt-mahena')?>"/></a>
    <a href="http://www.knihovna-kh.cz/" target="_blank"><img src="/themes/vnf3/images/institutions/01 prispevatele dat/fonoteka-logo-kutnahora.png" title="<?=$this->transEsc('vnf-homepage-ins-alt-kutnahora')?>"/></a>
    <a href="http://www.knihovnaprerov.cz/" target="_blank"><img src="/themes/vnf3/images/institutions/01 prispevatele dat/fonoteka-logo-mek.png" title="<?=$this->transEsc('vnf-homepage-ins-alt-mek')?>"/></a>
    <a href="http://www.knih-pe.cz/" target="_blank"><img src="/themes/vnf3/images/institutions/01 prispevatele dat/fonoteka-logo-pehlrimov.png" title="<?=$this->transEsc('vnf-homepage-ins-alt-pelhrimov')?>"/></a>
    <a href="http://www.radioteka.cz/" target="_blank"><img src="/themes/vnf3/images/institutions/01 prispevatele dat/fonoteka-logo-radioteka.png" title="<?=$this->transEsc('vnf-homepage-ins-alt-radioteka')?>"/></a>
    <a href="http://www.radioservis-as.cz/" target="_blank"><img src="/themes/vnf3/images/institutions/01 prispevatele dat/fonoteka-logo-ervis.png" title="<?=$this->transEsc('vnf-homepage-ins-alt-ervis')?>"/></a>
    <a href="http://www.audioteka.cz/" target="_blank"><img src="/themes/vnf3/images/institutions/01 prispevatele dat/fonoteka-logo-audioteka.png" title="<?=$this->transEsc('vnf-homepage-ins-alt-audioteka')?>"/></a>
    <a href="http://projekt.narodnifonoteka.cz/home/publikace-1" target="_blank"><img src="/themes/vnf3/images/institutions/01 prispevatele dat/fonoteka-logo-esta.png" title="<?=$this->transEsc('vnf-homepage-ins-alt-esta')?>"/></a>
  </div>
  <div class="col-md-12 institutions">
    <div class="row"><?=$this->transEsc('Media partnerships')?></div>
    <a href="http://www.rozhlas.cz/" target="_blank"><img src="/themes/vnf3/images/institutions/02 medialni partneri/fonoteka-logo-cr.png" title="<?=$this->transEsc('vnf-homepage-ins-alt-cr')?>"/></a>
    <a href="http://www.inflow.cz/" target="_blank"><img src="/themes/vnf3/images/institutions/02 medialni partneri/fonoteka-logo-inflow.png" title="<?=$this->transEsc('vnf-homepage-ins-alt-inflow')?>"/></a>
    <a href="http://www.naposlech.cz/" target="_blank"><img src="/themes/vnf3/images/institutions/02 medialni partneri/fonoteka-logo-naposlech.png" title="<?=$this->transEsc('vnf-homepage-ins-alt-naposlech')?>"/></a>
  </div>
</div>
