<?
    // Set page title.
    $this->headTitle($this->translate('request_place_text') . ': ' . $this->driver->getBreadcrumb());
    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li>' . $this->getLastSearchLink($this->transEsc('Search'), '', '<span class="divider">&gt;</span> </li>')
        . '<li>' . $this->recordLink()->getBreadcrumb($this->driver) . '<span class="divider">&gt;</span> </li>'
        . '<li class="active">' . $this->transEsc('request_place_text') . '</li>';
?>
<h2><?=$this->transEsc('request_place_text')?></h2>
<? if ($this->helpText): ?>
<p class="helptext"><?=$this->helpText?></p>
<? endif; ?>

<?=$this->flashmessages()?>
<div class="hold-form">
  <form action="" class="form-horizontal" method="post" name="placeHold">

  <table class="table">
    <?foreach ($this->slots as $date => $slotsInDay):?>
    <tr>
      <td>
        <?=$date?>
      </td>
      <?foreach ($slotsInDay as $slot):?>
        <?if ($slot['available']):?>
          <td style='background-color:lightgreen;'>
            <input type="checkbox"></input>
            <?=$slot['start_time'] . ' - ' . $slot['end_time']?>
          </td>
        <?else:?>
          <td style='background-color:#FF9EC0;'>
          </td>
        <?endif;?>
      <?endforeach;?>
    </tr>
    <?endforeach;?>
  </table>
  <input type="submit"></input>

  </form>
</div>
