<?
$title = $this->translate('Feedback') . ' | ' . $this->translate('Central Library Portal');
$this->headTitle($title);

//Hide feedback modal window in Feedback page (uses in layout.phtml to render modal)
$this->feedback()->hideFeedbackModalButton = true;
?>
<div class='clearfix portal-page'>
  <div class="title">
    <h1><?=$this->translate('Feedback') ?></h1>
  </div>

  <p><?= $this->translate('FAQ_first', [
          '%s1' => "<a href='/Portal/Page/faq'>",
          '%s2' => "</a>"
      ]) ?>
  </p>

    <? if (explode("-", $this->layout()->userLang)[0] == 'cs'): ?>
      <p><?= $this->translate('FAQ_first_for_libs', [
              '%s1' => "<a href='/Portal/Page/faq-pro-knihovny'>",
              '%s2' => "</a>"
          ]) ?>
      </p>
    <? endif; ?>

    <? if ($this->captchaError): ?>
      <div class="alert alert-danger">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <?= $this->translate($this->captchaError) ?>
      </div>
    <? endif; ?>

  <form action='/Portal/Feedback' class='form feedback-form' method='post'>
    <div class='row'>
      <fieldset class="form-group">
        <label for="feedback_text"><?= $this->translate('Describe problem') ?></label>
        <textarea id="feedback_text"
                  name='text'
                  class='form-control'
                  required><?= ($this->text) ? htmlspecialchars($this->text) : '' ?></textarea>
      </fieldset>
    </div>
    <div class='row'>
      <fieldset class="form-group">
        <label for="feedback_name"><?= $this->translate('Your name') ?></label>
          <? if ($this->userFullName || $this->name): ?>
            <input id="feedback_name" type='text' name='name' class='form-control'
                   value='<?= ($this->name) ? htmlspecialchars($this->name) : htmlspecialchars($this->userFullName) ?: '' ?>'
                   required>
          <? else: ?>
            <input id="feedback_name" type='text' name='name' class='form-control' required>
          <? endif; ?>
      </fieldset>
    </div>

    <div class='row'>
      <fieldset class="form-group">
        <label for="feedback_email"><?= $this->translate('Your email') ?></label>
          <? if ($this->userEmail || $this->email): ?>
            <input id="feedback_email" type='email' name='email'
                   class='form-control'
                   value='<?= ($this->email) ? htmlspecialchars($this->email) : htmlspecialchars($this->userEmail) ?: '' ?>'
                   required>
          <? else: ?>
            <input id="feedback_email" type='email' name='email' class='form-control' required>
          <? endif; ?>
      </fieldset>
    </div>

    <div id='RecaptchaField'></div>

    <input type="hidden" name="page_path" value="<?= $this->feedback()->actualLink ?>">

    <fieldset class="form-group">
      <input type='submit'
             name="submitted"
             class='btn btn-primary'
             value='<?= $this->translate('Send form') ?>'>
    </fieldset>
  </form>
</div>
<script src="https://www.google.com/recaptcha/api.js?onload=CaptchaCallback&amp;render=explicit" async defer></script>
<script>
  var CaptchaCallback = function () {
    grecaptcha.render('RecaptchaField', {
      'sitekey': '<?=$this->feedback()->siteKey?>'
    });
  };
</script>