<?
  $title = $page['title'].' | '.$this->translate('Central Library Portal');
  $this->layout()->title = $title;
  $this->headTitle($title);
  $this->layout()->searchbox = false;
?>
<script>
  dataLayer.push({
    'page': {
      'category': 'info',
    }
  });
</script>
<div class='white-box clearfix portal-page'>
  <div class="title">
    <h1><?=$page['title']?></h1>
  </div>
  <div class='content'>
    <?=$page['content']?>
  </div>
</div> 
