<?
  // Set page title.
  $this->headTitle($this->translate('Search history and saved searches'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/Search">' . $this->transEsc('Main page') . '</a></li> '
      .'<li><a href="' .  $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'
    . '<li class="active">' . $this->transEsc('History') . '</li>';

  $saveSupported = $this->accountCapabilities()->getSavedSearchSetting() === 'enabled';
?>
<!--<ul class="breadcrumb hidden-print"><?=$this->layout()->breadcrumbs ?></ul>-->
<div class="row">
  <? if ($this->auth()->isLoggedIn()): ?>
    <div class="<?=$this->layoutClass('mainbody')?>">
  <? else: ?>
    <div class="col-sm-12">
  <? endif; ?>
    <? if ($saveSupported && !empty($this->saved)): ?>
      <h2><?=$this->transEsc("history_saved_searches")?></h2>
      <?=$this->context()->renderInContext('search/history-table.phtml', array('showSaved' => true, 'tableClass' => 'history-saved-searches'));?>
    <? endif; ?>

    <h2><?=$this->transEsc("history_recent_searches")?></h2>
    <? if (!empty($this->unsaved)): ?>
      <?=$this->context()->renderInContext('search/history-table.phtml', array('showSaved' => false, 'tableClass' => 'history-recent-searches'));?>
      <a href="?purge=true"><i class="fa fa-remove"></i> <?=$this->transEsc("history_purge")?></a>
    <? else: ?>
      <?=$this->transEsc("history_no_searches")?>
    <? endif; ?>
  </div>

  <? if ($this->auth()->isLoggedIn()): ?>
      <? if ($saveSupported): ?>
        <div class="<?=$this->layoutClass('sidebar')?>">
          <?=$this->context($this)->renderInContext(
              "myresearch/menu.phtml",
              // Only activate search history in account menu if user is logged in.
              $this->auth()->isLoggedIn() ? array('active' => 'history') : array()
           );
           ?>
        </div>
      <? endif; ?>
  <? endif; ?>
</div>

    <script type="text/javascript">
        jQuery(document).ready(function( $ ) {
            $('.history-saved-searches').on('click', '.history-item.edit, .history-item.savetitle', function( event ) {
                event.preventDefault();
                var dad = $(this).closest('tr');
                var label = $(dad).find('div.control-group > label');
                var edit = $(dad).find('.edit-input');
                if ($(label).is(":visible") == true) {
                    $(edit).val($(label).text());
                }
                else {
                    $(label).text(edit.val());
                }
                $(dad).find('.history-item.edit').toggle();
                $(dad).find('.history-item.savetitle').toggle();
                $(label).toggle();
                $(edit).toggle();
                $(edit).focus();
            }),
                $('.history-saved-searches').on('click', '.history-item.savetitle', function() {
                    var dad = $(this).closest('tr');
                    var edit = $(dad).find('.edit-input');
                    var id = $(dad).find('div.control-group').attr('id');
                    window.location.href='/MyResearch/ChangeTitle?save=' + id + '&mode=history&title=' + $(edit).val();
                }),
                $('.history-saved-searches .edit-input').keypress(function( event ) {
                    if (event.which == 13) {
                        var dad = $(this).closest('tr');
                        var edit = $(dad).find('.edit-input');
                        var id = $(dad).find('div.control-group').attr('id');
                        window.location.href='/MyResearch/ChangeTitle?save=' + id + '&mode=history&title=' + $(edit).val();
                    }
                });
        });
    </script>