<?
  // Set page title.
  //$this->headTitle($this->translate('Knihovny.cz'));
  $title = (!empty($this->themeConfiguration()->themeConfig['title'])? $this->themeConfiguration()->themeConfig['title'] : "Knihovny.cz");
  $this->headTitle($this->translate($title));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;
  $this->layout()->frontpage = true;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
  }

  // Load search actions and settings (if any):
  $options = $this->searchOptions($this->searchClassId);
  $basicSearch = $options->getSearchAction();
  $advSearch = $options->getAdvancedSearchAction();

  $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/">' . $this->transEsc('Main page') . '</a></li> ';
?>
<div class="searchHomeContent">
  <? if ($this->ils()->getOfflineMode() == "ils-offline"): ?>
    <div class="alert alert-warning">
      <h2><?=$this->transEsc('ils_offline_title')?></h2>
      <p><strong><?=$this->transEsc('ils_offline_status')?></strong></p>
      <p><?=$this->transEsc('ils_offline_home_message')?></p>
      <? $supportEmail = $this->escapeHtmlAttr($this->systemEmail()); ?>
      <p><a href="mailto:<?=$supportEmail?>"><?=$supportEmail?></a></p>
    </div>
  <? endif; ?>
  <script>
    dataLayer.push({
      'page': {
        'category': 'frontpage'
      }
    });
  </script>
  <? foreach ($this->widgets as $widgetsList): foreach ($widgetsList as $widget): ?>
    <? if ($widget->getName() == 'infobox') : ?>
      <?=$this->render('widgets/infobox.phtml', ['widget' => $widget, 'language' => $language])?>
    <? elseif ($widget->getName() == 'Document_Types_Widget'): ?>
      <?=$this->render('widgets/document_types_widget.phtml', [
          'widget' => $widget,
          'documentTypesWidget' => $documentTypesWidget
      ])?>
    <? else: ?>
      <?=$this->render('widgets/widget.phtml', ['widget' => $widget, 'language' => $language])?>
    <? endif; ?>
  <? endforeach; ?><? endforeach; ?>

</div>
