<?
  // Set page title.
  $this->headTitle($this->translate('Knihovny.cz'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;
  $this->layout()->frontpage = true;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
  }

  // Load search actions and settings (if any):
  $options = $this->searchOptions($this->searchClassId);
  $basicSearch = $options->getSearchAction();
  $advSearch = $options->getAdvancedSearchAction();

  $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/">' . $this->transEsc('Main page') . '</a></li> ';
?>
<? if($this->loggedOut): ?>
  <div class="alert alert-info">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong><?=$this->translate('authentication_error_loggedout')?>.</strong> <?=$this->translate('Please log in again')?>
  </div>
<? endif; ?>
<div class="searchHomeContent">
  <? if ($this->ils()->getOfflineMode() == "ils-offline"): ?>
    <div class="alert alert-warning">
      <h2><?=$this->transEsc('ils_offline_title')?></h2>
      <p><strong><?=$this->transEsc('ils_offline_status')?></strong></p>
      <p><?=$this->transEsc('ils_offline_home_message')?></p>
      <? $supportEmail = $this->escapeHtmlAttr($this->systemEmail()); ?>
      <p><a href="mailto:<?=$supportEmail?>"><?=$supportEmail?></a></p>
    </div>
  <? endif; ?>

  <? foreach ($this->widgets as $widgetsList): foreach ($widgetsList as $widget): ?>
    <? if ($widget->getName() == 'infobox') : ?>
	  <?=$this->render('widgets/infobox.phtml', ['widget' => $widget, 'language' => $language])?>
    <? else: ?>
      <?=$this->render('widgets/widget.phtml', ['widget' => $widget, 'language' => $language])?>
    <? endif; ?>
  <? endforeach; ?><? endforeach; ?>

</div>
