<?
  // Set page title.
  $title = "Inspiration";
  $this->headTitle($this->translate('Inspiration'));
  $this->layout()->title = $title;
  $this->headTitle($title);
  $this->layout()->headerType = "inspiration";

?>
<div class="row">
    <? $row = 0; ?>
    <? for ($i = 1; $i <= $lastInspirationsWidgetsPosition; $i++): $inspirationsWidget = isset($sortedInspirationsWidgets[$i]) ? $sortedInspirationsWidgets[$i] : false;?>

        <? if (($row % 3) == 0): ?>
            </div><div class='row'>
        <? endif; ?>

        <? if ($inspirationsWidget): ?>
            <? if ($inspirationsWidget->getName() == 'infobox') : ?>
                <?=$this->render('widgets/infobox.phtml', ['widget' => $inspirationsWidget, 'language' => $language])?>
            <? elseif ($inspirationsWidget->getName() == 'conspectus'): ?>
                <?=$this->render('widgets/conspectus.phtml')?>
            <? else: ?>
                <?=$this->render('widgets/widget.phtml', ['widget' => $inspirationsWidget, 'language' => $language])?>
            <? endif; ?>
        <? else: ?>
            <div class="col-md-4">
            </div>
        <? endif; ?>

    <? $row++; ?>
    <? endfor; ?>
</div>
