<? $account = $this->auth()->getManager(); ?>
<? $sessionInitiator = $account->getSessionInitiator($this->serverUrl($this->url('myresearch-home'))); ?>
<a href="<?=$this->escapeHtmlAttr($sessionInitiator)?>"><?=$this->transEsc("Institutional Login")?></a>
<? if ($this->enableRedirect):?>
  <script type="text/javascript">
    setTimeout(function() {
      window.location = "<?=$sessionInitiator?>";
      },
    2000);
  </script>
<? endif; ?>