<meta property="og:url"
      content="https://tech.knihovny.cz/" />
<meta property="og:title"
      content="Oborová brána TECH" />
<meta property="og:description"
      content="Oborová brána TECH - informace z technických a přírodních věd pro vás na jednom místě." />
<meta property="og:image"
      content="https://www.knihovny.cz/themes/bootstrap3/images/screenshot_20190620.png" />
<meta property="og:image:secure_url"
      content="https://www.knihovny.cz/themes/bootstrap3/images/screenshot_20190620.png" />
<meta property="og:image:type"
      content="image/png" />
<meta name="referrer"
      content="unsafe-url" />
<link href="/themes/bootstrap3/images/logos/logo-tech.png" rel="icon" type="image/png">
