<?=$this->doctype('HTML5')?>
<html lang="<?=explode("-", $this->layout()->userLang)[0]?>">
  <head>
    <?$this->headThemeResources()?>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
    <?=$this->headMeta()?>
    <meta property="og:url"                content="https://knihovny.cz/" />
    <meta property="og:title"              content="Knihovny.cz" />
    <meta property="og:description"  content="Knihovny pod jednou střechou. Využijte komfort a jednoduchost prohledávání fondů desítek českých knihoven současně. Využijte služeb knihoven, objednávejte, stahujte - kdykoliv a kdekoliv." />
    <meta property="og:image"              content="https://knihovny.cz/themes/bootstrap3/images/screenshot.png" />
    <meta property="og:image:secure_url"   content="https://knihovny.cz/themes/bootstrap3/images/screenshot.png" />
    <meta name="referrer" content="unsafe-url" />
    <?=$this->headTitle()?>
    <?
      // Set up OpenSearch link:
      $this->headLink(
        array(
          'href' => $this->url('search-opensearch') . '?method=describe',
          'type' => 'application/opensearchdescription+xml',
          'title' => $this->transEsc('Library Catalog Search'),
          'rel' => 'search'
        )
      );
    ?>
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
          new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
          j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
          'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
      })(window,document,'script','dataLayer','GTM-TXJ544');</script>
    <!-- End Google Tag Manager -->

    <!-- RTL styling -->
    <? if ($this->layout()->rtl) {
      $this->headLink()->appendStylesheet('vendor/bootstrap-rtl.min.css');
    } ?>
    <?=$this->headLink()?>
    <?=$this->render("layout/fonts.phtml")?>
    <?=$this->headStyle()?>
    <?
      if (!isset($this->renderingError)) {
        // Add translation strings
        $this->jsTranslations()->addStrings(
          array(
            'bulk_email_success' => 'bulk_email_success',
            'bulk_noitems_advice' => 'bulk_noitems_advice',
            'bulk_save_success' => 'bulk_save_success',
            'close' => 'close',
            'go_to_list' => 'go_to_list',
            'libphonenumber_invalid' => 'libphonenumber_invalid',
            'libphonenumber_invalidcountry' => 'libphonenumber_invalidcountry',
            'libphonenumber_invalidregion' => 'libphonenumber_invalidregion',
            'libphonenumber_notanumber' => 'libphonenumber_notanumber',
            'libphonenumber_toolong' => 'libphonenumber_toolong',
            'libphonenumber_tooshort' => 'libphonenumber_tooshort',
            'libphonenumber_tooshortidd' => 'libphonenumber_tooshortidd',
            'loading' => 'Loading',
            'sms_success' => 'sms_success',
            'number_thousands_separator' => ['number_thousands_separator', null, ','],
            'in_titles' => 'in_titles',
            'in_authors' => 'in_authors',
            'in_subjects' => 'in_subjects',
            'citation_set_permanently' => 'citation_set_permanently',
            'records_per_page_set_permanently' => 'records_per_page_set_permanently',
            'default_sorting_set_permanently' => 'default_sorting_set_permanently',
            'Source' => 'Source',
            'Reserve' => 'Reserve',
            'show_others' => 'show_others',
            'hide_others' => 'hide_others',
            'unknown status' => 'status_Unknown Status',
            'Basic Search' => 'Basic Search',
            'Advanced Search' => 'Advanced Search',
            'Geo Error' => 'Geo Error',
            'Request timeout' => 'Request timeout',
            'Position unavailable' => 'Position unavailable',
            'Permission denied' => 'Permission denied',
            'Geolocation is not supported by this browser' => 'Geolocation is not supported by this browser',
            'without_notifications' => 'V této instituci nemáte žádné zprávy.',
            'The most commonly occurring' => 'The most commonly occurring',
            'Save search' => 'Save search',
            'search_save_success' => 'search_save_success',
            'Delete saved search' => 'Delete saved search',
            'search_unsave_success' => 'search_unsave_success',
            'reload_or_save_again' => 'reload_or_save_again',
            'login_to_use_this' => 'login_to_use_this',
            'Enter email' => 'Enter email',
            'Wrong email format' => 'Wrong email format',
            'caslin_tab_link' => 'caslin_tab_link',
            'Expand or collapse' => 'Expand or collapse',
            'Do not forget to update search results' => 'Do not forget to update search results'
          )
        );
        // Add libphonenumber.js strings
        $this->jsTranslations()->addStrings(
          array(
            "'Phone number invalid'" => 'libphonenumber_invalid',
            "'Invalid country calling code'" => 'libphonenumber_invalidcountry',
            "'Invalid region code'" => 'libphonenumber_invalidregion',
            "'The string supplied did not seem to be a phone number'" => 'libphonenumber_notanumber',
            "'The string supplied is too long to be a phone number'" => 'libphonenumber_toolong',
            "'The string supplied is too short to be a phone number'" => 'libphonenumber_tooshort',
            "'Phone number too short after IDD'" => 'libphonenumber_tooshortidd'
          )
        );

        // Fix some IE issues
        if (USES_IE) {
            $this->headScript()->appendFile('vendor/es6-promise.min.js');
        }

        $cacheUrl = $this->ObalkyKnih()->getCacheUrl();
        $this->headScript()->appendScript("obalky.setCacheUrl(\"{$cacheUrl}\");");

        // Deal with cart stuff:
        $cart = $this->cart();
        if ($cart->isActive()) {
          $this->headScript()->appendFile("vendor/cookies.js");
          $this->headScript()->appendFile("cart.js");
          $domain = $cart->getCookieDomain();
          $this->headScript()->appendScript(
            'var cartCookieDomain = ' . (!empty($domain) ? "'$domain'" : 'false') . ';'
          );
          $this->jsTranslations()->addStrings(
            array(
              'bulk_noitems_advice' => 'bulk_noitems_advice',
              'confirmDelete' => 'confirm_delete',
              'confirmEmpty' => 'bookbag_confirm_empty',
              'viewBookBag' => 'View Book Bag',
              'addBookBag' => 'Add to Book Bag',
              'removeBookBag' => 'Remove from Book Bag',
              'itemsAddBag' => 'items_added_to_bookbag',
              'itemsInBag' => 'items_already_in_bookbag',
              'bookbagMax' => $cart->getMaxSize(),
              'bookbagFull' => 'bookbag_full_msg',
              'bookbagStatusFull' => 'bookbag_full',
              'no_tags' => 'No Tags'
            )
          );
        }
        $this->headScript()->appendScript(
          'var userIsLoggedIn = ' . ($this->auth()->isLoggedIn() ? 'true' : 'false') . ';'
        );
      }

      // data-ng-app translations ..
      $this->jsTranslations()->addStrings(
          array(
              'you_have_unsaved_favorites' => 'you_have_unsaved_favorites'
          )
      );

      // Prompt 'offline' favorites to push to the server
      if(isSeT($_ENV['justLoggedIn'])) {
          $this->headScript()->appendScript('var sendMeFavs=()=>true');
      }

      // Session keep-alive
      if ($this->KeepAlive()) {
          $this->headScript()->appendScript('var keepAliveInterval = '
            . $this->KeepAlive());
          $this->headScript()->appendFile("keep_alive.js");
      }


        /*
         * Will we show the notifications ??
         */
        $authManager = $this->auth()->getManager();
        $user = $authManager->isLoggedIn();

        $libraryCards = [];

        //variables for purposes of google analytics
        $hashedUserId = null;
        $listOfIdentityProviders = null;
        $loggedIn = "Ne";

        $notificationsEnabled = false;

        if ($authManager instanceof \CPK\Auth\Manager) {
            $notificationsEnabled = $authManager->isNotificationSystemEnabled();
        }

        if ($user) {
            $loggedIn = "Ano";
            $libraryCards = $user->getLibraryCards(false);
            $hashedUserId = $user->getHashedId();
            $listOfIdentityProviders = $user->getStringOfConnectedInstitutions();
        }

        $headerParams = [
            'account' => $authManager,
            'user' => $user,
            'libraryCards' => $libraryCards,
            'notificationsEnabled' => $notificationsEnabled,
        ];
    ?>
    <?
      $root = rtrim($this->url('home'), '/');
      $translations = $this->jsTranslations()->getJSON();
      $dsb = DEFAULT_SEARCH_BACKEND;
      $setupJS = "var VuFind = new VuFindNamespace('{$root}', {$translations}, '{$dsb}');";
      $this->headScript()->appendScript($setupJS);
    ?>
    <?=$this->headScript()->appendFile("geolocation.js");?>
  </head>
  <body data-ng-app="cpk" data-ng-controller="GlobalController as ctrl" class="<?=$this->layoutClass('offcanvas-row')?><? if ($this->layout()->rtl): ?> rtl<? endif; ?>">
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TXJ544"
                      height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->
    <script>
      dataLayer.push({
        'page': {
          'title': '<?=$this->headTitle()->renderTitle()?>',
          'language': '<?=$this->layout()->userLang?>',
          'category': undefined,
          'type': undefined,
          'library': undefined
        },
        'user': {
          'loggedIn': '<?=$loggedIn ?>',
          'userId': <?= empty($hashedUserId) ? "undefined" :  "'".$hashedUserId."'" ?>,
          'loginType': <?= empty($listOfIdentityProviders) ? "undefined" :  "'".$listOfIdentityProviders."'" ?>
        }

      });
    </script>
    <?=$this->render('cookies-agreement.phtml')?>
    <?=$this->render('info.phtml')?>
    <? // Set up the search box -- there are three possible cases:
      // 1. No search box was set; we should default to the normal box
      // 2. It was set to false; we should display nothing
      // 3. It is set to a custom string; we should display the provided version
      // Set up default search box if no data was provided from the template;
      // this covers case 1.  Cases 2 and 3 are then covered by logic below.
      if (!isset($this->layout()->searchbox)) {
        $this->layout()->searchbox = $this->render('search/searchbox.phtml');
      }
    ?>
    <header class="hidden-print header-container <?=($this->layout()->frontpage == true)?'frontpage':''?>">
      <div class="container navbar">
	<a class="sr-only" href="#content"><?=$this->transEsc('Skip to content') ?></a>
        <?=$this->render('header.phtml', $headerParams)?>
      </div>
      <div class="container">
          <? if ($this->layout()->frontpage == true): ?>
            <h1><?=$this->transEsc("frontpage-header-text")?></h1>
            <? $docCount = $this->layout()->docCount; ?>
            <? if (empty($docCount)): ?>
              <h4><?=$this->transEsc("frontpage-text")?></h4>
            <? else: ?>
              <h4><?=$this->transEsc("frontpage-text", ['10 000 000' => $this->localizedNumber($docCount)])?></h4>
            <? endif; ?>
            <div class="clearfix">
               <div class='container'>
                 <?=$this->render('search/searchbox.phtml'); ?>
                 <?=$this->render('shib-assertion.phtml')?>
                 <a href="/Search/Inspiration" class="pull-left arrow-link"><i class="pr-interface-arrowleft"></i> <?=$this->transEsc("frontpage-left-arrow-link")?></a>
                 <a href="/Libraries/List/" class="pull-right arrow-link">
                   <? $titleHtml = $this->transEsc("frontpage-right-arrow-link") ."<i class=\"pr-interface-arrowright\"></i>"; ?>
                   <?= $this->help()->getElementHelp('element_help_frontpage_right_arrow', $titleHtml, "mzk") ?>
                 </a>
               </div>
            </div>
          <? else: ?>
            <? if ($this->layout()->headerType == "libraries"): ?>
              <?=$this->render('libraries/header.phtml')?>
            <? endif; ?>
          <? endif; ?>
      </div>
    </header>

    <div role="main" class="main template-dir-<?=$this->templateDir?> template-name-<?=$this->templateName?>">
      <div class="container">
        <? if ($this->layout()->frontpage != true): ?>
          <? if ($this->layout()->headerType != "libraries"): ?>
            <div class="clearfix">
              <div class='container'>
                <?=$this->layout()->searchbox ?>
                <?=$this->render('shib-assertion.phtml')?>
              </div>
            </div>
            <hr/>
          <? endif; ?>
        <? endif; ?>
        <?=$this->layout()->content ?>
      </div>
    </div>
    <footer class="hidden-print header-container">
      <div class="container">
        <?=$this->render('footer.phtml', ['user' => $user])?>
        <?=$this->layout()->poweredBy ?>
      </div>
    </footer>
    <!-- MODAL IN CASE WE NEED ONE -->
    <div id="modal" class="modal fade hidden-print" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 id="modalTitle" class="modal-title" data-ng-modal="global.header">&nbsp;</h4>
          </div>
          <div class="modal-body" data-ng-modal="global.body"><?=$this->transEsc('Loading') ?>...</div>
        </div>
      </div>
    </div>
    <? if (! $user): ?>
    <!-- Modal for login -->
    <div class="modal fade" id="loginModal" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content" data-ng-controller="FederativeLoginController as fedLoginCtrl">
          <div class="modal-header" data-ng-show='fedLoginCtrl.hasLastIdps()'>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"><?=$this->translate('login_last_used')?></h4>
          </div>
          <div class="modal-body last-idps" data-ng-last-used data-ng-show='fedLoginCtrl.hasLastIdps()'>
		  </div>
		  <div class="modal-header link" data-ng-click="fedLoginCtrl.showHelpContent()" style="cursor: pointer">
		    <? $portalPage = $this->portalPages()->getPage('moznosti-prihlaseni-a-registrace', explode("-", $this->layout()->userLang)[0]); ?>
		    <h4 class="modal-title"><?=$portalPage['title']?></h4>
		  </div>
		  <div class="modal-body" id="preregistration" data-ng-help-content hidden="hidden">
		    <?=$portalPage['content'] ?>
            <script>
              $(document).ready(function () {
                $('#preregistration a').on('click', function () {
                  dataLayer.push({
                    'event': 'action.account',
                    'actionContext': {
                      'eventCategory': 'account',
                      'eventAction': 'register',
                      'eventLabel': $(this).attr('href'),
                      'eventValue': undefined,
                      'nonInteraction': false
                    }
                  });
                })
              });
            </script>
		  </div>
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"><?=$this->translate('login_with')?></h4>
          </div>
          <div class="modal-body">
          	<?=$this->render('login/identity-providers.phtml', [
          	    'idps' => $this->identityProviders()->getLibraries()
          	]) ?>
		  </div>
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"><?=$this->translate('login_other')?></h4>
          </div>
          <div class="modal-body">
          	<?=$this->render('login/identity-providers.phtml', [
          	    'idps' => $this->identityProviders()->getOthers()
          	]) ?>
		  </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal"><?=$this->translate('close')?></button>
          </div>
        </div>
      </div>
    </div>
    <? endif; ?>
    <? if (! $user && isset($_GET['AcceptTermsOfUse'])):
      $agreeUrl = $this->url('myresearch-home').'?auth_method=Shibboleth&terms_of_use_accepted=yes'?>
    <!-- Modal for terms of use -->
    <script type="text/javascript">$(function(){$('#termsOfUseModal').modal('show').unbind('click');});</script>
    <div class="modal fade" id="termsOfUseModal" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title"><?=$this->translate('terms_of_use')?></h4>
          </div>
          <div class="modal-body">
          	<? $termsOfUsePage = $this->portalPages()->getPage('terms-of-use', explode("-", $this->layout()->userLang)[0]);?>
          	<?=isset($termsOfUsePage['content']) ? $termsOfUsePage['content'] : 'Terms of use are unavailable, please contact the administrator at cpk-dev@mzk.cz' ?>
		  </div>
          <div class="modal-footer">
            <div class="btn-group">
              <button type="button" title="<?=$this->translate('terms_of_use_agree') ?>" class="btn btn-default" onclick="location='<?=$agreeUrl?>'"><?=$this->translate('i_agree')?></button>
              <button type="button" title="<?=$this->translate('terms_of_use_disagree') ?>" class="btn btn-default" onclick="$('#termsOfUseModal').modal('hide');"><?=$this->translate('i_disagree')?></button>
            </div>
          </div>
        </div>
      </div>
    </div>
    <? endif; ?>
  </body>
</html>
