<?=$this->doctype('HTML5')?>
<html lang="<?=explode("-", $this->layout()->userLang)[0]?>">
  <head>
    <?$this->headThemeResources()?>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
    <?=$this->headMeta()?>
    <?=$this->render('layout/head.phtml');?>
    <?=$this->headTitle()?>
    <?
      // Set up OpenSearch link:
      $this->headLink(
        array(
          'href' => $this->url('search-opensearch') . '?method=describe',
          'type' => 'application/opensearchdescription+xml',
          'title' => $this->transEsc('Library Catalog Search'),
          'rel' => 'search'
        )
      );
    ?>
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
          new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
          j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
          'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
      })(window,document,'script','dataLayer','GTM-TXJ544');</script>
    <!-- End Google Tag Manager -->

    <!-- RTL styling -->
    <? if ($this->layout()->rtl) {
      $this->headLink()->appendStylesheet('vendor/bootstrap-rtl.min.css');
    } ?>
    <?=$this->headLink()?>
    <?=$this->headStyle()?>
    <?
      if (!isset($this->renderingError)) {
        // Add translation strings
        $this->jsTranslations()->addStrings(
          array(
            'bulk_email_success' => 'bulk_email_success',
            'bulk_noitems_advice' => 'bulk_noitems_advice',
            'bulk_save_success' => 'bulk_save_success',
            'close' => 'close',
            'go_to_list' => 'go_to_list',
            'libphonenumber_invalid' => 'libphonenumber_invalid',
            'libphonenumber_invalidcountry' => 'libphonenumber_invalidcountry',
            'libphonenumber_invalidregion' => 'libphonenumber_invalidregion',
            'libphonenumber_notanumber' => 'libphonenumber_notanumber',
            'libphonenumber_toolong' => 'libphonenumber_toolong',
            'libphonenumber_tooshort' => 'libphonenumber_tooshort',
            'libphonenumber_tooshortidd' => 'libphonenumber_tooshortidd',
            'loading' => 'Loading',
            'sms_success' => 'sms_success',
            'number_thousands_separator' => ['number_thousands_separator', null, ','],
            'in_titles' => 'in_titles',
            'in_authors' => 'in_authors',
            'in_subjects' => 'in_subjects',
            'in_lib_names' => 'in_lib_names',
            'in_towns' => 'in_towns',
            'citation_set_permanently' => 'citation_set_permanently',
            'records_per_page_set_permanently' => 'records_per_page_set_permanently',
            'default_sorting_set_permanently' => 'default_sorting_set_permanently',
            'Source' => 'Source',
            'Reserve' => 'Reserve',
            'show_others' => 'show_others',
            'hide_others' => 'hide_others',
            'unknown status' => 'status_Unknown Status',
            'Basic Search' => 'Basic Search',
            'Advanced Search' => 'Advanced Search',
            'Geo Error' => 'Geo Error',
            'Request timeout' => 'Request timeout',
            'Position unavailable' => 'Position unavailable',
            'Permission denied' => 'Permission denied',
            'Geolocation is not supported by this browser' => 'Geolocation is not supported by this browser',
            'without_notifications' => 'V této instituci nemáte žádné zprávy.',
            'The most commonly occurring' => 'The most commonly occurring',
            'Save search' => 'Save search',
            'search_save_success' => 'search_save_success',
            'Delete saved search' => 'Delete saved search',
            'search_unsave_success' => 'search_unsave_success',
            'reload_or_save_again' => 'reload_or_save_again',
            'login_to_use_this' => 'login_to_use_this',
            'Enter email' => 'Enter email',
            'Wrong email format' => 'Wrong email format',
            'caslin_tab_link' => 'caslin_tab_link',
            'Expand or collapse' => 'Expand or collapse',
            'Do not forget to update search results' => 'Do not forget to update search results',
            'warning_safety_login' => 'warning_safety_login',
            'page' => 'page',
            'record' => 'record',
            'Select widget' => 'Select widget',
            'Do you really want to delete this page?' => 'Do you really want to delete this page?',
            'Do you really want to remove permissions to this user?' => 'Do you really want to remove permissions to this user?',
            'Informace o dokumentu' => 'Informace o dokumentu'
          )
        );
        // Add libphonenumber.js strings
        $this->jsTranslations()->addStrings(
          array(
            "'Phone number invalid'" => 'libphonenumber_invalid',
            "'Invalid country calling code'" => 'libphonenumber_invalidcountry',
            "'Invalid region code'" => 'libphonenumber_invalidregion',
            "'The string supplied did not seem to be a phone number'" => 'libphonenumber_notanumber',
            "'The string supplied is too long to be a phone number'" => 'libphonenumber_toolong',
            "'The string supplied is too short to be a phone number'" => 'libphonenumber_tooshort',
            "'Phone number too short after IDD'" => 'libphonenumber_tooshortidd'
          )
        );
        // Add translation for sorting
        $this->jsTranslations()->addStrings(
          array(
            'date_newest' => 'date_newest',
            'date_oldest' => 'date_oldest',
            'sort_relevance' => 'sort_relevance',
          )
        );

        // Fix some IE issues
        if (USES_IE) {
            $this->headScript()->appendFile('vendor/es6-promise.min.js');
        }

        $cacheUrl = $this->ObalkyKnih()->getCacheUrl();
        $this->headScript()->appendScript("obalky.setCacheUrl(\"{$cacheUrl}\");");

        // Deal with cart stuff:
        $cart = $this->cart();
        if ($cart->isActive()) {
          $this->headScript()->appendFile("vendor/cookies.js");
          $this->headScript()->appendFile("cart.js");
          $domain = $cart->getCookieDomain();
          $this->headScript()->appendScript(
            'var cartCookieDomain = ' . (!empty($domain) ? "'$domain'" : 'false') . ';'
          );
          $this->jsTranslations()->addStrings(
            array(
              'bulk_noitems_advice' => 'bulk_noitems_advice',
              'confirmDelete' => 'confirm_delete',
              'confirmEmpty' => 'bookbag_confirm_empty',
              'viewBookBag' => 'View Book Bag',
              'addBookBag' => 'Add to Book Bag',
              'removeBookBag' => 'Remove from Book Bag',
              'itemsAddBag' => 'items_added_to_bookbag',
              'itemsInBag' => 'items_already_in_bookbag',
              'bookbagMax' => $cart->getMaxSize(),
              'bookbagFull' => 'bookbag_full_msg',
              'bookbagStatusFull' => 'bookbag_full',
              'no_tags' => 'No Tags'
            )
          );
        }
        $this->headScript()->appendScript(
          'var userIsLoggedIn = ' . ($this->auth()->isLoggedIn() ? 'true' : 'false') . ';'
        );
      }

      // data-ng-app translations ..
      $this->jsTranslations()->addStrings(
          array(
              'you_have_unsaved_favorites' => 'you_have_unsaved_favorites'
          )
      );

      // Prompt 'offline' favorites to push to the server
      if(isSeT($_ENV['justLoggedIn'])) {
          $this->headScript()->appendScript('var sendMeFavs=()=>true');
      }

      // Session keep-alive
      if ($this->KeepAlive()) {
          $this->headScript()->appendScript('var keepAliveInterval = '
            . $this->KeepAlive());
          $this->headScript()->appendFile("keep_alive.js");
      }


        /*
         * Will we show the notifications ??
         */
        $authManager = $this->auth()->getManager();
        $user = $authManager->isLoggedIn();

        //variables for purposes of google analytics
        $hashedUserId = null;
        $listOfIdentityProviders = null;
        $loggedIn = "Ne";

        $notificationsEnabled = false;

        if ($authManager instanceof \CPK\Auth\Manager) {
            $notificationsEnabled = $authManager->isNotificationSystemEnabled();
        }

        if ($user) {
            $loggedIn = "Ano";
            $hashedUserId = $user->getHashedId();
            $listOfIdentityProviders = $user->getStringOfConnectedInstitutions();
        }

        $headerParams = [
            'account' => $authManager,
            'user' => $user,
            'notificationsEnabled' => $notificationsEnabled,
        ];
    ?>
    <?
      $root = rtrim($this->url('home'), '/');
      $translations = $this->jsTranslations()->getJSON();
      $dsb = DEFAULT_SEARCH_BACKEND;
      $setupJS = "var VuFind = new VuFindNamespace('{$root}', {$translations}, '{$dsb}');";
      $this->headScript()->appendScript($setupJS);
    ?>
    <?=$this->headScript()->appendFile("geolocation.js");?>
  </head>
  <body data-ng-app="cpk" data-ng-controller="GlobalController as ctrl" class="<?=$this->layoutClass('offcanvas-row')?><? if ($this->layout()->rtl): ?> rtl<? endif; ?> ziskej-mode-<?=$this->Ziskej()->getCurrentMode()?>">

  <!-- Facebook Pixel Code -->
  <script>
      !function(f,b,e,v,n,t,s)
      {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
          n.callMethod.apply(n,arguments):n.queue.push(arguments)};
          if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
          n.queue=[];t=b.createElement(e);t.async=!0;
          t.src=v;s=b.getElementsByTagName(e)[0];
          s.parentNode.insertBefore(t,s)}(window,document,'script',
          'https://connect.facebook.net/en_US/fbevents.js');
      fbq('init', '822054034585908');
      fbq('track', 'PageView');
  </script>
  <noscript>
      <img height="1" width="1" src="https://www.facebook.com/tr?id=822054034585908&amp;ev=PageView&amp;noscript=1"/>
  </noscript>
  <!-- End Facebook Pixel Code -->

    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TXJ544"
                      height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->
    <script>
      dataLayer.push({
        'page': {
          'title': '<?=$this->headTitle()->renderTitle()?>',
          'language': '<?=$this->layout()->userLang?>',
          'category': undefined,
          'type': undefined,
          'library': undefined
        },
        'user': {
          'loggedIn': '<?=$loggedIn ?>',
          'userId': <?= empty($hashedUserId) ? "undefined" :  "'".$hashedUserId."'" ?>,
          'loginType': <?= empty($listOfIdentityProviders) ? "undefined" :  "'".$listOfIdentityProviders."'" ?>
        }

      });
    </script>

  <?=$this->render('cookies-agreement.phtml')?>
    <?=$this->render('info.phtml')?>
    <? // Set up the search box -- there are three possible cases:
      // 1. No search box was set; we should default to the normal box
      // 2. It was set to false; we should display nothing
      // 3. It is set to a custom string; we should display the provided version
      // Set up default search box if no data was provided from the template;
      // this covers case 1.  Cases 2 and 3 are then covered by logic below.
      if (!isset($this->layout()->searchbox)) {
        $this->layout()->searchbox = $this->render('search/searchbox.phtml');
      }
    ?>
    <? if($this->help()->showBrowserSuggest()): ?>
      <?= $this->render('SuggestedBrowsers/suggested-browsers.phtml')?>
    <? endif; ?>
    <header class="hidden-print header-container <?=($this->layout()->frontpage == true)?'frontpage':''?>">
	    <? if (!$this->themeConfiguration()->themeConfig['hide_navbar']): ?>
		    <div class="container navbar">
			    <a class="sr-only" href="#content"><?= $this->transEsc('Skip to content') ?></a>
			    <?= $this->render('header.phtml', $headerParams) ?>
		    </div>
	    <? endif; ?>
        <div class="container">
            <? if ($this->layout()->frontpage == true): ?>
                <h1><?=$this->transEsc("frontpage-header-text")?></h1>
                <? $docCount = $this->layout()->docCount; ?>
                <h4><?=$this->transEsc("frontpage-text")?></h4>
                <div class="clearfix">
                    <div class='container'>
                        <?=$this->render('search/searchbox.phtml'); ?>
                        <?=$this->render('shib-assertion.phtml')?>
                        <? if(!$this->themeConfiguration()->themeConfig['hide_inspirations_arrow_link']): ?>
                            <a href="/Search/Inspiration" class="pull-left arrow-link">
                                <i class="pr-interface-arrowleft"></i>
                                <?=$this->transEsc("frontpage-left-arrow-link")?>
                            </a>
                        <? endif; ?>
                        <? if(!$this->themeConfiguration()->themeConfig['hide_library_search_arrow_link']): ?>
                            <a href="/Search/Results/?lookfor0[]=&amp;type0[]=Libraries&amp;bool0[]=AND&amp;filter=&amp;daterange=&amp;publishDatefrom=&amp;publishDateto=&amp;limit=10&amp;sort=relevance&amp;page=1&amp;searchTypeTemplate=basic&amp;keepFacetsEnabled=true&amp;join=AND" class="pull-right arrow-link">
                                <? $titleHtml = $this->transEsc("frontpage-right-arrow-link") ."<i class=\"pr-interface-arrowright\"></i>"; ?>
                                <?= $this->help()->getElementHelp('element_help_frontpage_right_arrow', $titleHtml, "mzk") ?>
                            </a>
                        <? endif; ?>
                    </div>
                </div>
            <? else: ?>
                <? if ($this->layout()->headerType == "libraries"): ?>
                    <?=$this->render('libraries/header.phtml')?>
                <? endif; ?>
            <? endif; ?>
        </div>
    </header>

    <? if (!$this->themeConfiguration()->themeConfig['hide_header_panel'] && $this->layout()->frontpage): ?>
      <section class="header-panel">
        <h2 class="text-center hidden"><?=$this->transEsc('header_panel_heading')?></h2>
        <div class="container">
          <div class="row">
            <div class="col-md-4 text-center">
              <div class="panel">
                <div class="panel-body">
                  <h3>
                    <a href="<?= $this->themeConfiguration()->themeConfig['header_panel_second_column_link'] ?>"
                       title="<?= $this->transEsc('header_panel_1_description') ?>">
                      <i class="fa fa-university"></i>
                      <?= $this->transEsc('header_panel_1_heading') ?>
                    </a>
                  </h3>
                  <p><?= $this->transEsc('header_panel_1_description') ?></p>
                </div>
              </div>
            </div>
            <div class="col-md-4 text-center">
              <div class="panel">
                <div class="panel-body">
                  <h3>
                    <a href="<?= $this->themeConfiguration()->themeConfig['header_panel_third_column_link'] ?>"
                       title="<?= $this->transEsc('header_panel_2_description') ?>">
                      <i class="fa fa-globe"></i>
                      <?= $this->transEsc('header_panel_2_heading') ?>
                    </a>
                  </h3>
                  <p><?= $this->transEsc('header_panel_2_description') ?></p>
                </div>
              </div>
            </div>
            <div class="col-md-4 text-center">
              <div class="panel">
                <div class="panel-body">
                  <h3>
                    <a href="<?= $this->themeConfiguration()->themeConfig['header_panel_fourth_column_link'] ?>"
                       title="<?= $this->transEsc('header_panel_3_description') ?>">
                      <i class="fa fa-tablet"></i>
                      <?= $this->transEsc('header_panel_3_heading') ?>
                    </a>
                  </h3>
                  <p><?= $this->transEsc('header_panel_3_description') ?></p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    <? endif; ?>

    <div role="main" class="main template-dir-<?=$this->templateDir?> template-name-<?=$this->templateName?>">
      <div class="container">
        <? if ($this->layout()->frontpage != true): ?>
          <div class="clearfix">
            <div class='container'>
              <?=$this->layout()->searchbox ?>
              <?=$this->render('shib-assertion.phtml')?>
            </div>
          </div>
          <br/>
        <? endif; ?>
        <?=$this->layout()->content ?>
      </div>
    </div>

    <footer class="hidden-print">
      <div class="container">
          <?=$this->render('footer.phtml', ['user' => $user])?>
          <?=$this->layout()->poweredBy ?>
      </div>
    </footer>

    <!-- MODAL IN CASE WE NEED ONE -->
    <div id="modal" class="modal fade hidden-print" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 id="modalTitle" class="modal-title" data-ng-modal="global.header">&nbsp;</h4>
          </div>
          <div class="modal-body" data-ng-modal="global.body"><?=$this->transEsc('Loading') ?>...</div>
        </div>
      </div>
    </div>

    <? if (!$this->feedback()->hideFeedbackModalButton): ?>
      <!-- Float feedback button -->
      <div class="feedback-link">
        <a class="pr-communication-bubblehelpquestionsupport2" href="/Portal/Feedback"
              title="<?= $this->transEsc('Feedback') ?>" target="_blank"></a>
      </div>
      <!--/ End float feedback button -->
    <? endif; ?>

    <? if (! $user): ?>
    <!-- Modal for login -->
    <div class="modal fade" id="loginModal" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content" data-ng-controller="FederativeLoginController as fedLoginCtrl">
          <div class="modal-header" data-ng-show='fedLoginCtrl.hasLastIdps()'>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"><?=$this->translate('login_last_used')?></h4>
          </div>
          <div class="modal-body last-idps" data-ng-last-used data-ng-show='fedLoginCtrl.hasLastIdps()'>
		  </div>
		  <div class="modal-header link" data-ng-click="fedLoginCtrl.showHelpContent()" style="cursor: pointer">
		    <? $portalPage = $this->portalPages()->getPage('moznosti-prihlaseni-a-registrace', explode("-", $this->layout()->userLang)[0]); ?>
		    <h4 class="modal-title"><?=$portalPage['title']?></h4>
		  </div>
		  <div class="modal-body" id="preregistration" data-ng-help-content hidden="hidden">
		    <?=$portalPage['content'] ?>
            <script>
              $(document).ready(function () {
                $('#preregistration a').on('click', function () {
                  dataLayer.push({
                    'event': 'action.account',
                    'actionContext': {
                      'eventCategory': 'account',
                      'eventAction': 'register',
                      'eventLabel': $(this).attr('href'),
                      'eventValue': undefined,
                      'nonInteraction': false
                    }
                  });
                })
              });
            </script>
		  </div>
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"><?=$this->translate('login_with')?></h4>
          </div>
          <div class="modal-body">
          	<?=$this->render('login/identity-providers.phtml', [
          	    'idps' => $this->identityProviders()->getLibraries()
          	]) ?>
		  </div>
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"><?=$this->translate('login_other')?></h4>
          </div>
          <div class="modal-body">
          	<?=$this->render('login/identity-providers.phtml', [
          	    'idps' => $this->identityProviders()->getOthers()
          	]) ?>
		  </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal"><?=$this->translate('close')?></button>
          </div>
        </div>
      </div>
    </div>
    <? endif; ?>

    <?php if(($this->Ziskej()->isEnabled() && !$this->Ziskej()->isProduction()) ||
             ($this->ZiskejEdd()->isEnabled() && !$this->ZiskejEdd()->isProduction())): ?>
      <div class="bar-ziskej">
        <i class="fa fa-fw fa-exclamation-triangle" aria-hidden="true"></i>
        <?php if($this->Ziskej()->isEnabled() && !$this->Ziskej()->isProduction()): ?>
          <?=$this->translate('ziskej_bar_info', ['%%mode%%' => $this->Ziskej()->getCurrentMode()])?>
        <?php endif; ?>
        <?php if($this->ZiskejEdd()->isEnabled() && !$this->ZiskejEdd()->isProduction()): ?>
          <?=$this->translate('ziskej_bar_info_edd', ['%%mode%%' => $this->ZiskejEdd()->getCurrentMode()])?>
        <?php endif; ?>
        <a href="<?=$this->url('ziskej')?>" title="<?=$this->translate('ziskej_bar_change_mode_title')?>"><?=$this->translate('ziskej_bar_change_mode')?></a>
      </div>
    <?php endif; ?>
  </body>
</html>
