<?
  // Set page title.
  $this->headTitle($this->translate('request_for_digitalization') . ': ' . $this->driver->getBreadcrumb());

  // Set up breadcrumbs:
  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li>' . $this->getLastSearchLink($this->transEsc('Search'), '', '</li>')
      . '<li>' . $this->recordLink()->getBreadcrumb($this->driver) . '</li>'
      . '<li class="active">' . $this->transEsc('request_for_digitalization') . '</li>';
?>
<p class="lead"><?=$this->transEsc("request_for_digitalization") ?> <?=$this->escapeHtml($this->driver->getBreadcrumb())?> </p>
<div class="hold-form">
  <p>Vážený pane, vážená paní,</p>
  <p>děkujeme za Váš návrh na digitalizaci dokumentu.</p>
  <p>
    V případě, že to fyzický stav dokumentu dovolí a pokud již nebylo dílo digitalizováno jinou knihovnou, budeme ho v nejbližší době digitalizovat a zveřejníme v digitální knihovně MZK.
    <b>Vzhledem k zákonným omezením v ní budou volně (s možností prohlížení mimo budovu MZK) zpřístupněna jen díla, na která se nevztahují autorská ani nakladatelská práva.</b>
    Autorská práva se vztahují na dokumenty, u kterých osoby s podílem na jejich vzniku (autoři, překladatelé, ilustrátoři apod.) zemřely před méně než <b>70 lety</b>.
    Nakladatelská práva umožňují zveřejnění díla nejdříve <b>50 let</b> po jejich vydání. Chráněná díla mohou být podle zákonné úpravy zveřejněna pouze v
    budově knihovny na počítačích, které neumožňují stažení digitální kopie.
  </p>
  <p>
    Pokud máte zájem získat informaci o výsledku digitalizace, vyplňte prosím svou e-mailovou adresu.
  </p>
  <p>
    Za MZK Michal Indrák, Odbor digitalizace
  </p>
  <form id="edit-save-form" class="form-horizontal" method="post" action="<?=$this->recordLink()->getActionUrl($this->driver, 'DigiRequest')?>" name="saveRecord">
    <input type="hidden" name="submit" value="1" />
    <input type="hidden" name="id" value="<?=$this->escapeHtml($this->driver->getUniqueId()) ?>" />
    <input type="hidden" name="source" value="<?=$this->escapeHtml($this->driver->getResourceSource())?>" />
    <div class="form-group">
      <label class="control-label" for="add_mytags"><?=$this->transEsc('request_for_digitalization_email') ?></label>
      <div class="controls">
        <input class="input-xlarge" id="email" type="text" name="email" value="<?=$this->escapeHtml(isset($this->email) ? $this->email : '')?>"/>
      </div>
    </div>
    <div class="form-group">
      <label class="control-label" for="add_mytags"><?=$this->transEsc('request_for_digitalization_reason') ?></label>
      <div class="controls">
        <input class="input-xlarge" id="reason" type="text" name="reason" value="<?=$this->escapeHtml(isset($this->reason) ? $this->reason : '')?>"/>
      </div>
    </div>
    <div class="form-group">
      <div class="controls">
        <input class="btn btn-primary" type="submit" value="<?=$this->transEsc('request_for_digitalization_submit') ?>"/>
      </div>
    </div>
  </form>
</div>
