<?
  // Set page title.
  $this->headTitle($this->translate('configurations_approval'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/Search">' . $this->transEsc('Main page') . '</a></li> ' .
      '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'.
      '<li class="active"><a href="/Admin/ConfigurationsApproval">'.$this->transEsc('configurations_approval').'</a></li> ';
  $this->layout()->title = $this->translate('configurations_approval');
  $this->layout()->templateName = 'configurations/approval';
?>
<div class="row clearfix">
  <ul class="breadcrumb hidden-print"><?=$this->layout()->breadcrumbs ?></ul>

  <div class="col-sm-3">
    <?=$this->render("admin/menu.phtml")?>
  </div>
  <div class="col-sm-9 well" ng-controller='ApprovalController as approvalCtrl'>
    <h2><?=$this->transEsc('configurations_approval')?></h2>
    <?=$this->flashmessages() ?>
    <? $hasRequests = false;
      foreach($configs as $source => $config):

        $transRequested = $config['requested'];
        $transActive = $config['active'];

        $isAleph = isset($transRequested['Catalog']['dlfport']);

        $template = $isAleph ? $alephTemplate : $ncipTemplate;

        $defs = $template['Definitions'];
        unset($template['Definitions']);

        $hidden = $defs['hidden'];

        // These two cannot be changed by anyone - they're generated
        unset($transRequested['IdResolver']['prefix']);
        unset($transRequested['Catalog']['requester']);

        if (! empty($transRequested)):
          $hasRequests = true;
    ?>
      <div class='well'>
        <form action='/Admin/ConfigurationsApproval' method='POST'>
        <table class="table table-striped col-sm-12">
          <thead>
            <tr><td colspan="2"><h3><?=$this->transEsc('source_' . $source)?><img class="pull-right" src="<?=$this->logos()->getLogo($source) ?>" height="32"></h3></td></tr>
          </thead>
          <tbody>
         <? foreach($transRequested as $section => $keys):
         if(! empty($keys) && array_search($section, $hidden) === false): ?>
            <tr><td colspan="2"><b>[<?=$section ?>]</b></td></tr>
            <? foreach($keys as $key => $value): if (array_search($section . ':' . $key, $hidden) === false):
                $isChanged = isset($transActive[$section][$key]) && $value != $transActive[$section][$key];
                $isRequired = ! in_array($section . ':' . $key, $defs['optional']);
                $isCheckbox = $defs[$section][$key] === 'checkbox'; ?>
            <tr title='<?=($isRequired ? $this->transEsc('This field is required') . ' - ' : '')  . $this->transEsc($template[$section][$key]) ?>'>
              <td class="col-sm-3"><?=$key . (($isRequired) ? ' *' : '') ?></td>
                <td class="col-sm-9" ng-dblclick="approvalCtrl.edit($event)">
                <div>
                <? if ($isChanged): ?>
                  <? if (! empty($transActive[$section][$key])): ?>
                    <del style="color: red"><?=$transActive[$section][$key] ?></del>
                    <br>
                  <? endif; ?>
                  <ins style="color: green"><?=$value ?></ins>
                <? else: ?>
                  <?=$value ?>
                <? endif; ?>
                </div>
                <input class="form-control hidden" ng-keydown="approvalCtrl.inputKeyDown($event)" ng-blur="approvalCtrl.inputBlurred($event)"
                	type="<?=$defs[$section][$key] ?>"
                	<? if( $isCheckbox ): ?>
                	  <?=( $value ) ? 'checked="checked"' : ''; ?>
                	<? else: ?>
                	  value="<?=$value?>"
                	<? endif; ?>
                	placeholder="<?=$this->transEsc($template[$section][$key]) ?>"
                	title="<?=$this->transEsc($template[$section][$key])?>"
                	name="<?=$section . '[' . $key . ']' ?>"
                	<?=$isRequired ? 'required' : ''?>/>
              </td>
            </tr>
            <? endif; endforeach; ?>
          <? endif; endforeach; ?>
          </tbody>
        </table>
        <textarea class="col-sm-12" name="message" placeholder="<?=$this->transEsc('approval_description')?>" title="<?=$this->transEsc('approval_description')?>"></textarea>
        <div class="btn-group">
          <input class="btn btn-primary" type="submit" name="approved" value="<?=$this->transEsc('approve_config_change') ?>" ng-submit-approval/>
          <input class="btn btn-primary" type="submit" name="denied" value="<?=$this->transEsc('deny_config_change') ?>" formnovalidate/>
        </div>
        <input type='hidden' name='source' value='<?=$source ?>'/>
        </form>
      </div>
      <? endif; endforeach; ?>
      <? if (! $hasRequests): ?>
        <div class='well'>
          <?=$this->transEsc('approve_no_requests') ?>
        </div>
      <? endif ?>
  </div>
</div>