<?
  // Set page title.
  $this->headTitle($this->translate('configurations'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/Search">' . $this->transEsc('Main page') . '</a></li> ' .
      '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'.
      '<li class="active"><a href="/Admin/Configurations">'.$this->transEsc('configurations').'</a></li> ';
  $this->layout()->title = $this->translate('configurations');
  $this->layout()->templateName = 'configurations/main';
?>
<div class="row clearfix">
  <ul class="breadcrumb hidden-print"><?=$this->layout()->breadcrumbs ?></ul>

  <div class="col-sm-3">
    <?=$this->render("admin/menu.phtml")?>
  </div>
  <div class="col-sm-9 well">
    <h2><?=$this->transEsc('configurations')?></h2>
    <?=$this->flashmessages() ?>
    <? foreach($configs as $source => $configs):
        $template = $configs['template'];
        $config = $configs['data'];

        $defs = $template['Definitions'];
        unset($template['Definitions']);

        $hidden = $defs['hidden'];
        ?>
      <div class='well'>
        <form action='/Admin/Configurations' method='POST'>
        <table class="table table-striped col-sm-12">
          <thead>
            <tr><td colspan="2"><h3><?=$this->transEsc('source_' . $source)?><img class="pull-right" src="<?=$this->logos()->getLogo($source) ?>" height="32"></h3></td></tr>
          </thead>
          <tbody>
         <? foreach($template as $section => $keys): if(! empty($keys) && array_search($section, $hidden) === false): ?>
            <tr><td colspan="2"><b>[<?=$section ?>]</b></td></tr>
            <? foreach($keys as $key => $value): if (array_search($section . ':' . $key, $hidden) === false):
                    $isRequired = ! in_array($section . ':' . $key, $defs['optional']);
                    $isCheckbox = $defs[$section][$key] === 'checkbox';?>
            <tr title='<?=($isRequired ? $this->transEsc('This field is required') . ' - ' : '')  . $this->transEsc($value) ?>'>
              <td class="col-sm-3"><?=$key . (($isRequired) ? ' *' : '') ?></td>
              <td class="col-sm-9">
                <? if($defs[$section][$key] == "select"):?>
                  <select class="form-control"
                          name="<?=$section . '[' . $key . ']' ?>"
                          title="<?=$this->transEsc($value)?>"
                          <?=$isRequired ? 'required' : ''?>>
                    <option value=""></option>
                    <? foreach ($ncipTypes['type'] as $type): ?>
                      <option value="<?= $type ?>"
                              <?= (isset($config[$section][$key]) && $config[$section][$key] == $type)
                                  ? 'selected="selected"'
                                  : ''?>>
                          <?= $type ?>
                      </option>
                    <? endforeach; ?>
                  </select>
                <? else: ?>
                  <input class="form-control"
                    type="<?=$defs[$section][$key] ?>"
                    <? if( $isCheckbox ): ?>
                      <?=( isset($config[$section][$key]) && $config[$section][$key] ) ? 'checked="checked"' : ''; ?>
                    <? else: ?>
                      value="<?=isset($config[$section][$key]) ? $config[$section][$key] : ''?>"
                    <? endif; ?>
                    placeholder="<?=$this->transEsc($value)?>"
                    title="<?=$this->transEsc($value)?>"
                    name="<?=$section . '[' . $key . ']' ?>"
                    <?=$isRequired ? 'required' : ''?>/>
                <? endif; ?>
              </td>
            </tr>
            <? endif; endforeach; ?>
          <? endif; endforeach; ?>
          </tbody>
        </table>
        <div class="btn-group">
          <input class="btn btn-primary" name="requestChange" type="submit" value="<?=$this->transEsc('submit_config_changes') ?>"/>
        </div>
        <input type='hidden' name='source' value='<?=$source ?>'/>
        </form>
      </div>
      <? endforeach; ?>
  </div>
</div>
