<?php
function getSheduleOfPeriodics($holding) {
    if (isset($holding['d'])) {
        return $holding['d'];
    }
    $result = '';
    if (isset($holding['y'])) {
        $result .= $holding['y'];
    }
    if (isset($holding['v']) && $holding['v'] != $holding['y']) {
        $result .= " " . $holding['v'];
    }
    if (isset($holding['i'])) {
        $result .= " " . $holding['i'];
    }
    return $result;
}

function getStatusDescription($status) {
    if ($status == "A") {
        return "Holding Status Absent";
    }
    if ($status == "P") {
        return "Holding Status Present";
    }
}
?>

<? $holdings = $this->driver->getHoldings(); ?>

<table class="table table-striped" summary="<?=$this->transEsc('Holdings details from')?> <?=$this->transEsc($holding['location'])?>">
  <tr>
      <td><?=$this->transEsc('Branch')?></td>
      <td><?=$this->transEsc('Second Level Branch')?></td>
      <td><?=$this->transEsc('Barcode')?></td>
      <td><?=$this->transEsc('Schedule of Periodics')?></td>
      <td><?=$this->transEsc('Signature 1')?></td>
      <td><?=$this->transEsc('Signature 2')?></td>
      <td><?=$this->transEsc('Status')?></td>
  </tr>

<? foreach ($holdings as $holding): ?>
  <tr>
    <td><? if (isset($holding['l'])):?><?=$holding['l']?><? endif; ?></td>
    <td><? if (isset($holding['r'])):?><?=$holding['r']?><? endif; ?></td>
    <td><? if (isset($holding['b'])):?><?=$holding['b']?><? endif; ?></td>
    <td><?=getSheduleOfPeriodics($holding)?></td>
    <td><? if (isset($holding['c'])):?><?=$holding['c']?><? endif; ?></td>
    <td><? if (isset($holding['h'])):?><?=$holding['h']?><? endif; ?></td>
    <td><? if (isset($holding['s'])):?><?=$this->transEsc(getStatusDescription($holding['s']))?><? endif; ?></td>
  </tr>
<? endforeach;?>
</table>


