<?php
function getSheduleOfPeriodics($holding) {
    $result = '';
    if (isset($holding['r'])) {
        $result .= $holding['r'];
    }
    if (isset($holding['e'])) {
        $result .= " " . $holding['e'];
    }
    if (isset($holding['w'])) {
        $result .= " " . $holding['w'];
    }
    return $result;
}
?>

<?php
$holdings = array();

$branchValues = array();
$sheduleOfPeriodicsValues = array();
$signatureValues = array();
$signature2Values = array();
$barcodeValues = array();

$hasSheduleOfPeriodics = true;

foreach ($this->driver->getHoldings() as $holding) {
    if ($holding['q'] == '0') {
        continue;
    }
    $holding_entry = array();
    $holding_entry['branch'] = isset($holding['~']) ? $holding['~'] : '';
    $holding_entry['sheduleOfPeriodics'] = getSheduleOfPeriodics($holding);
    $holding_entry['signature1'] = isset($holding['k']) ? $holding['k'] : '';
    $holding_entry['signature2'] = isset($holding['g']) ? $holding['g'] : '';
    $holding_entry['barcode'] = isset($holding['b']) ? $holding['b'] : '';
    
    $branchValues[] = $holding_entry['branch'];
    $sheduleOfPeriodicsValues[] = $holding_entry['sheduleOfPeriodics'];
    $signatureValues[] = $holding_entry['signature1'];
    $signature2Values[] = $holding_entry['signature2'];
    $barcodeValues[] = $holding_entry['barcode'];
    
    $hasSheduleOfPeriodics &= !empty($holding_entry['sheduleOfPeriodics']);
    
    $holdings[] = $holding_entry;
}
if ($hasSheduleOfPeriodics) {
    array_multisort(
        $sheduleOfPeriodicsValues, SORT_ASC, SORT_NUMERIC,
        $branchValues, SORT_ASC, SORT_LOCALE_STRING,
        $signatureValues, SORT_ASC, SORT_NUMERIC,
        $signature2Values, SORT_ASC, SORT_NUMERIC,
        $barcodeValues, SORT_ASC, SORT_NUMERIC,
        $holdings
    );
} else {
    array_multisort(
        $branchValues, SORT_ASC, SORT_LOCALE_STRING,
        $signatureValues, SORT_ASC, SORT_NUMERIC,
        $signature2Values, SORT_ASC, SORT_NUMERIC,
        $barcodeValues, SORT_ASC, SORT_NUMERIC,
        $holdings
    );
}

?>
<table class="table table-striped" summary="<?=$this->transEsc('Holdings details from')?> <?=$this->transEsc($holding['location'])?>">
  <tr>
      <td><?=$this->transEsc('Branch')?></td>
      <td><?=$this->transEsc('Schedule of Periodics')?></td>
      <td><?=$this->transEsc('Signature 1')?></td>
      <td><?=$this->transEsc('Signature 2')?></td>
      <td><?=$this->transEsc('Barcode')?></td>
  </tr>

<? foreach ($holdings as $holding): ?>
  <? if ($holding['q'] != "0"): ?>
    <tr>
      <td><?=$holding['branch']?></td>
      <td><?=$holding['sheduleOfPeriodics']?></td>
      <td><?=$holding['signature1']?></td>
      <td><?=$holding['signature2']?></td>
      <td><?=$holding['barcode']?></td>
    </tr>
  <? endif; ?>
<? endforeach;?>
</table>


