<?
  // Set page title.
  $this->headTitle($this->translate('Knihovny.cz'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

?>

<div class="statusContent well">
  <h1><?=$this->transEsc("Status")?></h1>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th><?=$this->transEsc("Status")?></th>
        <th><?=$this->transEsc("ms")?></th>
        <th><?=$this->transEsc("Name")?></th>
        <th><?=$this->transEsc("Address")?></th>
        <th><?=$this->transEsc("Last response")?></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>active</td>
        <td>11ms</td>
        <td>obalky1</td>
        <td>http://cache.obalkyknih.cz/api/runtime/alive</td>
        <td>Tue Dec  1 11:21:48 CET 2015</td>
      </tr>
    </tbody>
  </table>


</div>
