<?
  // Set page title.
  $this->headTitle($this->translate('Search Home'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
  }

  // Load search actions and settings (if any):
  $options = $this->searchOptions($this->searchClassId);
  $basicSearch = $options->getSearchAction();
  $advSearch = $options->getAdvancedSearchAction();
  
  $this->layout()->breadcrumbs = false;
?>
<div class="row clearfix">
  <div class="span6">
    <?$userLang = $this->layout()->userLang?>
    <img src="<?=$this->imageLink("fonoteka-deska-$userLang.png") ?>"></img>
  </div>
  <div class="span6 centering">
    <div class="searchbox">
      <?=$this->render("search/searchbox-mainpage.phtml")?>
    </div>
    <div class="row clearfix">
      <div class="span4">
        <p><strong><?=$this->transEsc('Search Options')?></strong></p>
        <ul>
          <li><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></li>
          <li><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></li>
        </ul>
      </div>
      <div class="span4">
        <p><strong><?=$this->transEsc('Find More')?></strong></p>
        <ul>
          <li><a href="<?=$this->url('browse-home')?>"><?=$this->transEsc('Browse the Catalog')?></a></li>
          <li><a href="<?=$this->url('alphabrowse-home')?>"><?=$this->transEsc('Browse Alphabetically')?></a></li>
        </ul>
      </div>
    </div>
    <div>
    <p class="homepage-citation">
    "...aby každý stát soustředil a uchoval v nějaké národní diskotéce cenné desky obsahující jednak národní folklór,
     jednak vynikající díla domácích skladatelů nebo výkonných umělců a uměleckých souborů, pokud jsou nahrána na
     gramofonových deskách. Tak by vznikl skutečný archív národní hudby v autentickém a vrcholném provedení, archív 
     sloužící k mezinárodní propagaci domácího umění, k rozšiřování rádiem, k vědeckému studiu atd. – <b>věc jistě žádoucí.</b>"
     </p>
     <p class="homepage-citation-author">
     Karel Čapek
     </p>
     </div>
  </div>
</div>
