<?
  // Set page title.
  $this->headTitle($this->translate('Search Home'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
  }

  // Load search actions and settings (if any):
  $options = $this->searchOptions($this->searchClassId);
  $basicSearch = $options->getSearchAction();
  $advSearch = $options->getAdvancedSearchAction();
  
  $this->layout()->breadcrumbs = false;

  $projectPage = "http://projekt.narodnifonoteka.cz/";
?>
<div class="row clearfix">
  <div class="span6">
    <?$userLang = $this->layout()->userLang?>
    <a href="<?=$projectPage?>"><img src="<?=$this->imageLink("fonoteka-deska-$userLang.png") ?>"></img></a>
  </div>
  <div class="span6 centering">
    <div class="searchbox">
      <?=$this->render("search/searchbox-mainpage.phtml")?>
    </div>
    <div class="row clearfix">
      <div class="span4">
        <p><strong><?=$this->transEsc('Search Options')?></strong></p>
        <ul>
          <li><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></li>
          <li><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></li>
        </ul>
      </div>
      <div class="span4">
        <p><strong><?=$this->transEsc('Find More')?></strong></p>
        <ul>
          <li><a href="<?=$this->url('browse-home')?>"><?=$this->transEsc('Browse the Catalog')?></a></li>
          <li><a href="<?=$this->url('alphabrowse-home')?>"><?=$this->transEsc('Browse Alphabetically')?></a></li>
        </ul>
      </div>
    </div>
    <div>
    <p class="homepage-citation">
    <?=$this->transEsc('vnf-homepage-citation')?><b><?=$this->transEsc('vnf-homepage-citation-bold')?></b>
    
     </p>
     <p class="homepage-citation-author">
     Karel Čapek
     </p>
     <p>
       <a href="<?=$projectPage?>"><?=$this->transEsc('About the project')?></a>
     </p>
     </div>
  </div>
  <div class="span12 institutions">
    <img src="<?=$this->imageLink("institutions/mzk.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/sup.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/mkp.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/nkp.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/cbvk.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/svkk.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/vkol.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/kkfb.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/ktn.png") ?>"/>
    <img src="<?=$this->imageLink("institutions/mkuo.png") ?>"/>
  </div>
</div>
