<table>
<tbody>
<? foreach($idps as $idp):
$json = json_encode([
    'href' => $idp['href'],
    'logo' => $idp['logo'],
    'name_cs' => $idp['name_cs'],
    'name_en' => $idp['name_en']
]);
?>
  <tr class="link" ng-click="fedLoginCtrl.login('<?=htmlentities($json)?>')">
    <td class="col-sm-4">
      <? if($idp['logo']):?>
        <img height='30' src="<?=$idp['logo']?>">
      <? endif; ?>
    </td>
    <td>
      <a href="#"><?=$idp['name']?></a>
    </td>
  </tr>
<? endforeach; ?>
</tbody>
</table>