<table class="table table-striped">
    <colgroup>
       <col span="1" style="width: 30%;">
       <col span="1" style="width: 40%;">
       <col span="1" style="width: 15%;">
       <col span="1" style="width: 15%;">
    </colgroup>
	<tr>
		<th align="center"><?=$this->transEsc('Author')?></th>
		<th align="center"><?=$this->transEsc('Title')?></th>
		<th align="center"><?=$this->transEsc('Playing Time')?></th>
		<th align="center"><?=$this->transEsc('Link')?></th>
	</tr>
	<? foreach ($this->driver->getTOC() as $current): ?>
	<tr>
		<td><?=$this->escapeHtml(isset($current['r']) ? $current['r'] : '')?>
		</td>
		<td><?=$this->escapeHtml($current['t'])?>
		</td>
		<td><?=$this->tab->convertFootage($current['g'])?>
		</td>
		<td>
		  <a href="<?=$this->recordLink()->related(array(
		      'type' => 'bib', 
		      'value' => $current['x']))?>">
		      link
		  </a>
		</td>
	</tr>
	<?endforeach;?>
</table>
