<?
    // Set page title.
    $this->headTitle($this->translate('Table of Contents') . ': ' . $this->driver->getBreadcrumb());

    $toc = $this->driver->getTOC();
?>
<? if (!empty($toc)): ?>
  <? if (is_array($toc) && is_array($toc[0])):?>
    <?=$this->render('RecordTab/supraphonrecordtab.phtml'); ?>
  <? else: ?>
    <strong><?=$this->transEsc('Table of Contents')?>: </strong>
    <ul class="toc">
      <? foreach ($toc as $line): ?>
        <li><?=$this->escapeHtml($line)?></li>
      <? endforeach; ?>
     </ul>
  <? endif;?>
<? else: ?>
  <?=$this->transEsc("Table of Contents unavailable")?>.
<? endif; ?>