<?
    // Set up page title:
    $this->headTitle($this->translate('Checked Out Items'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a> <span class="divider">&gt;</span></li>'
        . '<li class="active">' . $this->transEsc('Checked Out Items') . '</li>';
?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <h2><?=$this->transEsc('Your Checked Out Items')?></h2>
  <?=$this->flashmessages()?>

  <? if (count($this->view['views']) > 1): ?>
    <div class="pull-right row">
      <? $first = true; ?>
      <? foreach ($this->view['views'] as $name => $view): ?>
        <span class="span5 <?= !$first ? 'offset2' : '' ?>">
        <? if(!$view['selected']): ?>
          <a href="<?=$view['uri'] ?>" title="<?=$this->transEsc('Switch view to')?> <?=$this->transEsc(ucfirst($name))?>" >
        <? endif; ?>
          <img src="<?=$this->imageLink("view_$name.png") ?>"<? if($view['selected']): ?> title="<?=$this->transEsc(ucfirst($name))?> <?=$this->transEsc('view already selected') ?>" <? endif ?> alt="<?=$this->transEsc(ucfirst($name))?>"/>
        <? if(!$view['selected']): ?>
          </a>
        <? endif; ?>
        </span>
        <? $first = false; ?>
      <? endforeach; ?>
    </div>
    <br/><br/>
  <? endif; ?>

  <? if (!empty($this->transactions)): ?>
    <? if ($this->renewForm): ?>
    <form name="renewals" action="" method="post" id="renewals">
      <div class="toolbar">
        <input type="submit" class="btn" name="renewSelected" value="<?=$this->transEsc("renew_selected")?>" />
        <input type="submit" class="btn" name="renewAll" value="<?=$this->transEsc('renew_all')?>" />
      </div>
    <? endif; ?>

    <?= $this->render("myresearch/checkedout-" . $this->view['selected'] . ".phtml"); ?>

    <? if ($this->renewForm): ?></form><? endif; ?>
  <? else: ?>
    <?=$this->transEsc('You do not have any items checked out')?>.
  <? endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'checkedout'))?>
</div>