<?php require_once(__DIR__.'/../system/common.php'); ?>
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>CPK Diagnostics</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/simple-sidebar.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Sidebar -->
        <?php require_once(__DIR__.'/menu.phtml');?>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <h1>Summary</h1>

						<!--<div class="alert alert-danger" role="alert">
						  <a href="#" class="alert-link">Too low disc space!</a>
						</div>

						<div class="alert alert-warning" role="alert">
						  <a href="#" class="alert-link">Solr is a bit slow</a>
						</div>
							
						<div class='row'>
							<div class='col-md-6'>
								<div id="storage-usage" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto"></div>	
							</div>
							<div class='col-md-6'>
								<div id="solr-usage" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto"></div>
							</div>
						</div>-->
						<?php					
    						$xml = new DOMDocument;
    						$xml->load(__DIR__.'/data/unitTestsResults.xml');
    						$xpath = new DOMXpath($xml);

    						$total = $xpath->query("/testsuites/testsuite[@name='AllTests']/@tests")[0]->value;
    						$done = $total - $xpath->query("/testsuites/testsuite/@failures")[0]->value;
    						
    						$green = ($done * 100) / $total;
    						$red = 100 - $green;
    						
						?>
						<h4>
							Unit tests
							<span class='pull-right'><?=$done?> / <?=$total?> - <?=$green?>% success</span>
						</h4>
                        <div class="progress">
							<div class="progress-bar progress-bar-success" style="width: <?=$green?>%">
								<span class="sr-only"><?=$green?>% Complete (success)</span>
							</div>

							<div class="progress-bar progress-bar-danger" style="width: <?=$red?>%">
								<span class="sr-only"><?=$red?>% Complete (danger)</span>
							</div>
						</div>
						<?php				
    						$file = file_get_contents(__DIR__ . "/../selenium_cpk_tests/target/surefire-reports/Command-line-suite/Command-line-test.html");
    						$regex = "/[0-9]{1}\/[0-9]{1}\/[0-9]{1}/";
    						preg_match($regex, $file, $match);
    						$seleniumTestsResults = explode("/", $match[0]);
    						$passed = $seleniumTestsResults[0];
    						$failed = $seleniumTestsResults[1];
    						$skipped = $seleniumTestsResults[2];
    						$total = $seleniumTestsResults[0]+$seleniumTestsResults[1]+$seleniumTestsResults[2];
						?>
						<h4>
							System tests
							<span class='pull-right'><?=$passed?>/<?=$total?> - <?=$passed*100/$total?>% success</span>
						</h4>
						<div class="progress">
							<div class="progress-bar progress-bar-success" style="width: <?=$passed*100/$total?>%">
								<span class="sr-only"><?=$passed*100/$total?>% Complete (success)</span>
							</div>

							<div class="progress-bar progress-bar-danger" style="width: <?=$failed*100/$total?>%">
								<span class="sr-only"><?=$failed*100/$total?>% Complete (danger)</span>
							</div>
							
							<div class="progress-bar progress-bar-warning" style="width: <?=$skipped*100/$total?>%">
								<span class="sr-only"><?=$skipped*100/$total?>% Complete (warning)</span>
							</div>
						</div>
						<?php 
    						$log = fgets(fopen(__DIR__.'/data/error.log', 'r'));
                            if ($log === 'Log is clean') {
                                $red = 0;
                                $green = 100;
                            } else {
                                $red = 100;
                                $green = 0;
                            }
						?>
						<h4>
							Logs
							<span class='pull-right'><?=$green?>% success</span>
						</h4>
						<div class="progress">
							<div class="progress-bar progress-bar-success" style="width: <?=$green?>%">
								<span class="sr-only"><?=$green?>% Complete (success)</span>
							</div>

							<div class="progress-bar progress-bar-danger" style="width: <?=$red?>%">
								<span class="sr-only"><?=$red?>% Complete (danger)</span>
							</div>
						</div>

						<!--<h4>
							NCIP tests
							<span class='pull-right'>25/100 - 25% success</span>
						</h4>
						<div class="progress">
							<div class="progress-bar progress-bar-success" style="width: 100%">
								<span class="sr-only">35% Complete (success)</span>
							</div>

							<div class="progress-bar progress-bar-danger" style="width: 0%">
								<span class="sr-only">65% Complete (danger)</span>
							</div>
						</div>-->
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>
    <script src="http://code.highcharts.com/highcharts.js"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    
    $('#storage-usage').highcharts({
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false,
            type: 'pie'
        },
        title: {
            text: 'Storage usage'
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    }
                }
            }
        },
        series: [{
            name: "Storage usage",
            colorByPoint: true,
            data: [{
                name: "Free",
                y: 25,
                sliced: true,
                selected: true
            }, {
                name: "Used",
                y: 75
            }]
        }]
    });
    
    $('#solr-usage').highcharts({
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false,
            type: 'pie'
        },
        title: {
            text: 'SOLR usage'
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    }
                }
            }
        },
        series: [{
            name: "Storage usage",
            colorByPoint: true,
            data: [{
                name: "Free",
                y: 65,
                sliced: true,
                selected: true
            }, {
                name: "Used",
                y: 35
            }]
        }]
    });
    </script>
   

</body>

</html>
