<div id="sidebar-wrapper">
    <ul class="sidebar-nav">
        <li class="sidebar-brand">
            <a href="index.phtml">
                CPK Diagnostics
            </a>
        </li>
        <li>
            <a href="index.phtml">Summary</a>
        </li>
        <li>
            <a href="unit-tests.phtml">Unit tests</a>
        </li>
        <li>
            <a href="system-tests.phtml">System tests</a>
        </li>
        <li>
            <a href="logs.phtml">Logs</a>
        </li>
        <li>
            <a href="ncip-tests.phtml">NCIP tests</a>
        </li>
        <li>
            <a href="accessibility.phtml">Accessibility</a>
        </li>
    </ul>
</div>
