<?php require_once(__DIR__.'/../system/common.php'); ?>
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>CPK tests</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/simple-sidebar.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Sidebar -->
        <?php require_once(__DIR__.'/menu.phtml');?>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <h1>System-tests</h1>

						<table class='table' data-toggle="table" data-url="data1.json" data-cache="false" data-height="299">
							<thead>
								<tr>
									<th>Stránka</th>
									<th>Funkce</th>
									<th>Status</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>Homepage</td>
									<td>Header je modrý</td>
									<td><span class="label label-success">Success</span></td>
								</tr>
								<tr>
									<td>Homepage</td>
									<td>Jazyk je CS</td>
									<td><span class="label label-success">Success</span></td>
								</tr>
								<tr>
									<td>Homepage</td>
									<td>Neco je takové</td>
									<td><span class="label label-success">Success</span></td>
								</tr>
								<tr>
									<td class='warning'>Search</td>
									<td class='warning'>Autocomplete funguje</td>
									<td class='warning'><span class="label label-danger">Failed</span></td>
								</tr>
								
								<tr>
									<td>Search</td>
									<td>Neco je takové</td>
									<td><span class="label label-success">Success</span></td>
								</tr>
								<tr>
									<td class='warning'>Search</td>
									<td class='warning'>Neco je takové</td>
									<td class='warning'><span class="label label-danger">Failed</span></td>
								</tr>
								<tr>
									<td>Search</td>
									<td>Neco je takové</td>
									<td><span class="label label-success">Success</span></td>
								</tr>
								<tr>
									<td>Úplný záznam</td>
									<td>Neco je zas makové</td>
									<td><span class="label label-success">Success</span></td>
								</tr>
								<tr>
									<td>Úplný záznam</td>
									<td>Neco je zas makové</td>
									<td><span class="label label-success">Success</span></td>
								</tr>
								<tr>
									<td>Úplný záznam</td>
									<td>Neco je zas makové</td>
									<td><span class="label label-success">Success</span></td>
								</tr>
								<tr>
									<td class='warning'>Úplný záznam</td>
									<td class='warning'>Neco je zas makové</td>
									<td class='warning'><span class="label label-danger">Failed</span></td>
								</tr>
								<tr>
									<td class='warning'>Úplný záznam</td>
									<td class='warning'>Neco je zas makové</td>
									<td class='warning'><span class="label label-danger">Failed</span></td>
								</tr>
								<tr>
									<td>Úplný záznam</td>
									<td>Neco je zas makové</td>
									<td><span class="label label-success">Success</span></td>
								</tr>
								<tr>
									<td>Úplný záznam</td>
									<td>Neco je zas makové</td>
									<td><span class="label label-success">Success</span></td>
								</tr>
							</body>
						</table>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

</body>

</html>
