<?php require_once(__DIR__.'/../system/common.php'); ?>
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>CPK tests</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/simple-sidebar.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
	<style>
	   #mainResults thead tr th, #mainResults tbody tr td  {
	       text-align: center;
	   }
	</style>
</head>

<body>

    <div id="wrapper">

        <!-- Sidebar -->
        <?php require_once(__DIR__.'/menu.phtml');?>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <h1>Unit-tests</h1>
						
								<?php
    								$xml = new DOMDocument;
            						$xml->load(__DIR__.'/data/unitTestsResults.xml');
            						
            						$xsl = new DOMDocument;
            						$xsl->load(__DIR__.'/../system/unitTestsToHTML.xsl');
            						
            						$proc = new XSLTProcessor;
            						$proc->importStyleSheet($xsl);
            						
            						echo $proc->transformToXML($xml);
						          ?>						
						
						<h3>Details</h3>
						<?= '<pre>'.xml_highlight(file_get_contents(__DIR__.'/data/unitTestsResults.xml')).'</pre>' ?>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

</body>

</html>
