<h4><?=$this->transEsc('Your Account')?></h4>
<ul class="nav nav-list">
  <li<?=$this->active == 'history' ? ' class="active"' : ''?>><a href="<?=$this->url('search-history')?>?require_login"><?=$this->transEsc('history_saved_searches')?> <i class="pull-right"></i></a></li>
</ul>
  <? if ($user = $this->auth()->isLoggedIn()): ?>
    <h4 class="list"><?=$this->transEsc('Your Lists')?></h4>
    <ul class="nav nav-list">
      <li<?=$this->active == 'favorites' ? ' class="active"' : ''?>><a href="<?=$this->url('myresearch-favorites')?>"><?=$this->transEsc('Your Favorites')?> <i class="pull-right"></i></a></li>
      <? $lists = $user->getLists() ?>
      <? foreach ($lists as $list): ?>
          <li<?=$this->active == 'list' . $list['id'] ? ' class="active"' : ''?>> <a href="<?=$this->url('userList', array('id' => $list['id']))?>"><?=$this->escapeHtml($list['title'])?> <span class="pull-right"><?=$list->cnt?></span></a></li>
      <? endforeach; ?>
      <li><a href="<?=$this->url('editList', array('id'=>'NEW'))?>" title="<?=$this->transEsc('Create a List') ?>"><?=$this->transEsc('Create a List') ?> <span class="pull-right"></span></a></li>
    </ul>
  <? endif ?>
