<?
  // Set page title.
  $this->headTitle($this->translate('Administration'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = 
      '<li><a title="' . $this->transEsc('Main page') . '" href="/">' .$this->transEsc('Main page') . '</a></li>' .
      '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'.
      '<li><a href="/Admin/Home">'.$this->transEsc('Administration').'</a></li>'.
      '<li><a href="/Admin/PermissionsManager">'.$this->transEsc('Permissions manager').'</a></li>'.
      '<li class="active">'.$this->translate('Add user').'</li>';

  $this->layout()->title = $this->translate('Add user');
  $this->headScript()->appendFile('admin/add-user-with-permissions.js');
?>

<div class='row clearfix'>
  <ul class='breadcrumb hidden-print'><?=$this->layout()->breadcrumbs ?></ul>

  <div class='col-sm-3'>
    <?=$this->render('admin/menu.phtml')?>
  </div>

  <div class='col-sm-9'>
    <h2><?=$this->translate('Add user')?></h2>
    <div class='well'>
      <div>
        <form action='/Admin/PermissionsManager/Save' method='post'>
          <input type='hidden' name='userId' value='<?=$this->user['id']?>'>
          <fieldset class='form-group'>
            <div class='col-xs-8'>
              <label>
                <?=$this->translate('User')?>
                <span class='cursor-help' data-toggle='tooltip' title='EduPersonPrincipalName'>
                  (eppn)
                </span>
              </label>
              <input class='form-control'
                     name='eppn'
                     type='text'
                     placeholder='<?=$this->translate('Enter users eppn')?>'>
            </div>
          </fieldset>
          <fieldset class='form-group'>
            <div class='col-xs-3'>
              <label><?=$this->translate('Major permissions')?></label>
              <input type='text' class='form-control' name='major' placeholder='<?=$this->translate('Enter value')?>'>
            </div>
          </fieldset>
          <fieldset class='form-group'>
            <input type='submit' class='btn btn-lg btn-primary pull-right' value='<?=$this->translate('Save')?>'>
          </fieldset>
        </form>
      </div>
    </div>
  </div>
</div>