<?
  // Set page title.
  $this->headTitle($this->translate('Portal pages | Administration'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = ''.
      '<li><a href="/Search" title="'.$this->transEsc('Main page').'">'.$this->transEsc('Main page').'</a></li> '.
      '<li>'.
        '<a href="'.$this->url('myresearch-home').'" title="'.$this->transEsc('Your Account').'">'.
          $this->transEsc('Your Account').
        '</a>'.
      '</li>'.
      '<li>'.
        '<a href="/Admin/Home" title="'.$this->transEsc('Administration').'">'.
          $this->transEsc('Administration').
        '</a>'.
      '</li>'.
      '<li>'.
        '<a href="/Admin/PortalPages" title="'.$this->transEsc('Portal pages').'">'.
          $this->transEsc('Portal pages').
        '</a>'.
      '</li>'.
      '<li>'.
        '<a href="/Admin/PortalPages/Edit/'.$this->page['id'].'" 
            title="'.$this->translate('Edit').': '.$this->escapeHtml($this->page['title']).'">'.
          $this->translate('Edit').': '.$this->escapeHtml($this->page['title']).
        '</a>'.
      '</li>'.
      '<li class="active">'.$this->transEsc('Edit specific contents').'</li>';

  $this->layout()->title = $this->transEsc('Portal pages');

  $this->headScript()->appendFile('vendor/ckeditor/ckeditor.js');
  $this->headScript()->appendFile('admin/portal-pages/specific-contents.js');
?>

<div class='row clearfix'>
  <ul class='breadcrumb hidden-print'><?=$this->layout()->breadcrumbs?></ul>

  <div class='col-sm-3'>
    <?=$this->render('admin/menu.phtml')?>
  </div>

  <div class='col-sm-9'>
    <h2><?=$this->translate('Edit').': '.$this->escapeHtml($this->page['title'])?></h2>
    <div class='well'>
      <div>
        <? if (! empty($this->page)): ?>
        <form action='/Admin/PortalPages/SaveSpecificContents' method='post'>

          <input type='hidden' name='pageId' value='<?=$this->page['id']?>'>
          <input type='hidden' name='pageGroup' value='<?=$this->page['group']?>'>
          <input type='hidden' name='language' value='<?=$this->page['language_code']?>'>

          <fieldset class='form-group'>
            <div class='col-xs-3'>
              <label><?=$this->translate('Language')?></label>
              <input type='text' value='<?=$this->page['language_code']?>' disabled>
            </div>
          </fieldset>

          <div id='sources'>
            <div class='panel list-group'>
              <? foreach($this->sources as $source): ?>
                <a href='#'
                   class='list-group-item'
                   data-toggle='collapse'
                   data-target='#modal_for_<?=$source?>'
                   data-parent='#sources'>
                  <?=$this->translate('source_'.$source)?>
                </a>
                <div id='modal_for_<?=$source?>' class='sublinks collapse'>
                  <textarea rows='15' class='form-control editor ckeditor' name='content[]'>
                    <?=isset($specificContents[$source]) ? $specificContents[$source] : ''?>
                  </textarea>
                  <input type='hidden' name='source[]' value='<?=$source?>'>
                </div>
              <? endforeach; ?>
            </div>
          </div>

          <fieldset class='form-group'>
            <input type='submit' class='btn btn-lg btn-primary pull-right' value='<?=$this->translate('Save')?>'>
          </fieldset>
        </form>
        <? endif; ?>
      </div>
    </div>
  </div>
</div>