<aside class="well list-group">
  <a href="/Admin/Configurations" class="list-group-item<?=strtolower($this->layout()->templateName) == "configurations/main" ? ' active' : ''?>"><?=$this->transEsc('configurations')?></a>

  <? if ($isPortalAdmin): ?>
    <a href="/Admin/ConfigurationsApproval" class="list-group-item<?=strtolower($this->layout()->templateName) == "configurations/approval" ? ' active' : ''?>"><?=$this->transEsc('configurations_approval')?></a>
    <a href="/Admin/PortalPages" class="list-group-item<?=strtolower($this->layout()->templateName) == "portalpages" ? ' active' : ''?>"><?=$this->transEsc('Portal pages')?></a>
    <a href="/Admin/Widgets" class="list-group-item<?=strtolower($this->layout()->templateName) == "widgets/main" ? ' active' : ''?>"><?=$this->transEsc('Widgets')?></a>
    <div style=" margin-left: 15px; ">
    	<a href="/Admin/Infobox" class="list-group-item<?=strtolower($this->layout()->templateName) == "widgets/infobox/list" ? ' active' : ''?>"><?=$this->transEsc('Infobox')?></a>
    	<? foreach($this->widgetsForMenu as $widget): ?>
    	  <? if (! in_array($widget->getName(), ['infobox'])): // these are already printed, because they have different templates?>
		    <a href="/Admin/Widget/<?=$widget->getId()?>" class="list-group-item<?=strtolower($this->layout()->templateName) == "widgets/widget/list" ? ' active' : ''?>"><?=$widget->getTitleCs()?></a>
		  <? endif; ?>
    	<? endforeach; ?>
    </div>
    <a href="/Admin/PermissionsManager" class="list-group-item<?=strtolower($this->layout()->templateName) == "permissions-manager" ? ' active' : ''?>"><?=$this->transEsc('Permissions manager')?></a>
  <? endif; ?>
</aside>
