<?php
    $this->headLink()->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css');
    $this->headScript()->appendFile('./admin/menu.js');
    $this->headScript()->appendFile('//cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js');
?>
<aside class='well list-group aside-menu'>
  <a href='/Admin/Configurations' class='list-group-item<?=strtolower($this->layout()->templateName) == 'configurations/main' ? ' active' : ''?>'><?=$this->transEsc('configurations')?></a>

  <? if ($isPortalAdmin): ?>
    <a href='/Admin/ConfigurationsApproval' class='list-group-item<?=strtolower($this->layout()->templateName) == 'configurations/approval' ? ' active' : ''?>'><?=$this->transEsc('configurations_approval')?></a>
    <a href='/Admin/PortalPages' class='list-group-item<?=strtolower($this->layout()->templateName) == 'portalpages' ? ' active' : ''?>'><?=$this->transEsc('Portal pages')?></a>
    <a href='/Admin/PermissionsManager' class='list-group-item<?=strtolower($this->layout()->templateName) == 'permissions-manager' ? ' active' : ''?>'><?=$this->transEsc('Permissions manager')?></a>
    <a href='/Admin/Widgets' class='list-group-item<?=strtolower($this->layout()->templateName) == 'widgets/main' ? ' active' : ''?>'><?=$this->transEsc('Widgets')?></a>

    <select id='menu-widgets-list'>
      <option value='-1'></option>
      <?= sprintf('<option value="/Admin/Infobox">%s</option>', $this->transEsc('Infobox')); ?>
      <?php foreach($this->widgetsForMenu as $widget): ?>
        <?= sprintf('<option value="/Admin/Widget/%s">%s</option>', $widget->getId(), $widget->getTitleCs()); ?>
      <?php endforeach; ?>
    </select>
  <? endif; ?>
</aside>
