<?php
    $this->headLink()->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css');
    $this->headScript()->appendFile('./admin/menu.js');
    $this->headScript()->appendFile('//cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js');
    $templateName = strtolower($this->layout()->templateName);
?>
<aside class='well list-group aside-menu admin-menu'>
  <a href='/Admin/Configurations'
     class='list-group-item<?=$templateName == 'configurations/main' ? ' active' : ''?>'>
    <?=$this->transEsc('configurations')?>
  </a>

  <? if ($isPortalAdmin): ?>
    <a href='/Admin/PortalPages'
       class='list-group-item<?=$templateName == 'portalpages' ? ' active' : ''?>'>
      <?=$this->transEsc('Portal pages')?>
    </a>

    <a href='/Admin/PermissionsManager'
       class='list-group-item<?=$templateName == 'permissions-manager' ? ' active' : ''?>'>
      <?=$this->transEsc('Permissions manager')?>
    </a>

    <a href='/Admin/Widgets'
       class='list-group-item<?=$templateName == 'widgets/main' ? ' active' : ''?>'>
      <?=$this->transEsc('Widgets')?>
    </a>

    <select id='menu-widgets-list'>
      <option value='-1'></option>
      <option value='/Admin/Infobox'><?=$this->transEsc('Infobox')?></option>
      <?php foreach($this->widgetsForMenu as $widget): ?>
        <option value='/Admin/Widget/<?=$widget->getId()?>'>
          <?=$widget->getTitleCs()?>
        </option>
      <?php endforeach; ?>
    </select>
  <? endif; ?>
</aside>
