<div class='calendar form-inline' >
	
	<?= $this->transEsc('Period') ?>
	<span class='period-picker'>
		<select id='period' class="form-control">
			<option value='day'><?= $this->transEsc('Choose Day') ?></option>
			<option value='range'><?= $this->transEsc('Select Range') ?></option>
			<option value='today'><?= $this->transEsc('Today') ?></option>
			<option value='month' selected><?= $this->transEsc('This Month') ?></option>
			<option value='year'><?= $this->transEsc('This Year') ?></option>
		</select>
	</span>


	<span id='day-calendar'>
		<span class='date-picker-caption'><?= $this->transEsc('Select day') ?></span>
		<span class="input-group">
			<span class="input-group-addon"><i class="fa fa-calendar fa-fw"></i></span>
			<input class="form-control" type="text" id="day-datepicker">
		</span>
	</span>
	
	<span id='range-calendar'>
		<span class='date-picker-caption'><?= $this->transEsc('From') ?></span>
		<span class="input-group">
			<span class="input-group-addon"><i class="fa fa-calendar fa-fw"></i></span>
			<input class="form-control" type="text" id="range-datepicker-from">
		</span>
		
		<span class='date-picker-caption'><?= $this->transEsc('To') ?></span>
		<span class="input-group">
			<span class="input-group-addon"><i class="fa fa-calendar fa-fw"></i></span>
			<input class="form-control" type="text" id="range-datepicker-to">
		</span>
	</span>
	
	<span class='update-stats'>
		<button class='btn btn-primary' id='update-stats'><?= $this->transEsc('Update stats') ?></button>
	</span>
	
	<span class='selected-date-range pull-right'></span>
	
</div>


<script>
			jQuery( document ).ready( function( $ ) {
				
				// Initializes calendars
				$( '#day-datepicker, #range-datepicker-from, #range-datepicker-to' ).datepicker( {
			    	changeMonth: true,
			    	changeYear: true,
			    	dateFormat: "yy-mm-dd",
			    	setDate: new Date()
				});

				// Set default dates
				$( '#day-datepicker' ).datepicker('setDate', new Date());
				$( '#range-datepicker-from' ).datepicker('setDate', '2015-01-01');
				$( '#range-datepicker-to' ).datepicker('setDate', '2015-12-31');

				var dateFrom = $( '#range-datepicker-from' ).val();
				var dateTo = $( '#range-datepicker-to' ).val();
				$( '.selected-date-range' ).html( dateFrom + '-' + dateTo);
				//
				
				$( '#day-datepicker' ).on(' change ', function() {
					var day = $(this).val();
					$( '.selected-date-range' ).html(day);
				})
				
				$( '#range-datepicker-from, #range-datepicker-to' ).on( 'change ', function() {
					var dateFrom = $( '#range-datepicker-from' ).val();
					var dateTo = $( '#range-datepicker-to' ).val();
					$( '.selected-date-range' ).html( dateFrom + '-' + dateTo);
				})

				$( '#period' ).on( 'change', function( event ){

					event.preventDefault();

					var period = $(this).val();

					console.log('Period changed to: '+period);
					
					if ( period == 'day' ) {
						$( '#day-calendar' ).show();
						$( '#range-calendar' ).hide();
					} else if ( period == 'range' ){
						$( '#day-calendar' ).hide();
						$( '#range-calendar' ).show();
					} else {
						$( '#day-calendar' ).hide();
						$( '#range-calendar' ).hide();
					}
					
					
				});

			});
		</script>