<?php
    // Set up page title:
    $this->headTitle($this->translate('Statistics'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/Search">' . $this->transEsc('Main page') . '</a></li> '.
    '<li><a href="'.$this->url('myresearch-home').'">'.$this->translate('Your Account').'</a></li>' 
    							  .'<li><a href="'.$this->url('statistics-dashboard').'">' . $this->translate('Statistics') . '</a></li>'
    							  .'<li class="active">' . $this->translate('Circulations') . '</li>';
    
    echo $this->render('statistics/menu.phtml');
    
    echo $this->render('statistics/calendar.phtml');
?>

<div class="row">
	<div class="<?=$this->layoutClass('mainbody')?>">

		<div class="row">
			<div class="col-lg-6">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title">
							<i class="fa fa-user fa-fw"></i>
		 					<?= $this->translate('Readers') ?>
						</h3>
					</div>
					<div class="panel-body">
						<div id="readers-comparision"></div>
					</div>
				</div>
			</div>
			<div class="col-lg-6">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title">
							<i class="fa fa-user fa-fw"></i>
		 					<?= $this->translate('Circulations') ?>
						</h3>
					</div>
					<div class="panel-body">
						<div id="circulations-comparision"></div>
					</div>
				</div>
			</div>
		</div>
		<!-- /.row -->
		
		<div class="row">
			<div class="col-lg-12">
				<h2><?= $this->translate('EIZ usage') ?></h2>
				<div class="table-responsive">
		    		<table class="table table-hover table-striped">
		        		<thead>
		        			<tr>
		        				<th><?= $this->translate('Source') ?></th>
		        				<th><?= $this->translate('Time spent using') ?></th>
		        				<th class='text-center'><?= $this->translate('Number of actions done') ?></th>
		        				<th class='text-center'><?= $this->translate('Records viewed') ?></th>
		        				<th><?= $this->translate('Usage by readers') ?></th>
		        			</tr>
		        		</thead>
		        		<tbody>
				            <tr>
				                <td>Ebsco</td>
				                <td>15 dní, 6h 30min 25sek</td>
				                <td class='text-center'><?= number_format(3560, 0, ',', ' ') ?></td>
				                <td class='text-center'><?= number_format(3112, 0, ',', ' ') ?></td>
				                <td>159 readers (10%)</td>
							</tr>
							<tr>
				                <td>Ebsco</td>
				                <td>15 dní, 6h 30min 25sek</td>
				                <td class='text-center'><?= number_format(3560, 0, ',', ' ') ?></td>
				                <td class='text-center'><?= number_format(3112, 0, ',', ' ') ?></td>
				                <td>159 readers (10%)</td>
							</tr>
							<tr>
				                <td>Ebsco</td>
				                <td>15 dní, 6h 30min 25sek</td>
				                <td class='text-center'><?= number_format(3560, 0, ',', ' ') ?></td>
				                <td class='text-center'><?= number_format(3112, 0, ',', ' ') ?></td>
				                <td>159 readers (10%)</td>
							</tr><tr>
				                <td>Ebsco</td>
				                <td>15 dní, 6h 30min 25sek</td>
				                <td class='text-center'><?= number_format(3560, 0, ',', ' ') ?></td>
				                <td class='text-center'><?= number_format(3112, 0, ',', ' ') ?></td>
				                <td>159 readers (10%)</td>
							</tr><tr>
				                <td>Ebsco</td>
				                <td>15 dní, 6h 30min 25sek</td>
				                <td class='text-center'><?= number_format(3560, 0, ',', ' ') ?></td>
				                <td class='text-center'><?= number_format(3112, 0, ',', ' ') ?></td>
				                <td>159 readers (10%)</td>
							</tr>
							<tr>
				                <td>Ebsco</td>
				                <td>15 dní, 6h 30min 25sek</td>
				                <td class='text-center'><?= number_format(3560, 0, ',', ' ') ?></td>
				                <td class='text-center'><?= number_format(3112, 0, ',', ' ') ?></td>
				                <td>159 readers (10%)</td>
							</tr><tr>
				                <td>Ebsco</td>
				                <td>15 dní, 6h 30min 25sek</td>
				                <td class='text-center'><?= number_format(3560, 0, ',', ' ') ?></td>
				                <td class='text-center'><?= number_format(3112, 0, ',', ' ') ?></td>
				                <td>159 readers (10%)</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>	
		<!-- /.row -->
		
	</div>
	<div class="<?=$this->layoutClass('sidebar')?>">
    	<?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'statistics'))?>
	</div>
</div>
<!-- /.row -->

<? $this->headScript()->appendFile("raphael.min.js"); ?>
<? $this->headScript()->appendFile("morris-0.4.1.min.js"); ?>
<? $this->headScript()->appendFile("jquery-ui.min.js"); ?>
<script>
	jQuery( document ).ready( function( $ ) {
		
		// Sets menu item as active
		$( ".statistics-circulations" ).addClass( "active" );

		// Initializes donut chart for readers comparision
	    Morris.Donut( {
	        element: 'readers-comparision',
	        data: [
	        	{ label: "<?= $this->translate('Registrations'); ?>", 
		          value: <?= number_format(20, 0, ',', ' ') ?>
		        },
			    { label: "<?= $this->translate('Prolongations'); ?>", 
				  value: <?= number_format(30, 0, ',', ' ') ?> 
				},
			],
	        resize: true
	    });

	 	// Initializes donut chart for circulations comparision
	    Morris.Donut( {
	        element: 'circulations-comparision',
	        data: [
	        	{ label: "<?= $this->translate('Reserved'); ?>", 
		          value: <?= number_format(20, 0, ',', ' ') ?> 
		        },
			    { label: "<?= $this->translate('Prolonged'); ?>", 
				  value: <?= number_format(30) ?>
				},
				{ label: "<?= $this->translate('Ordered'); ?>", 
				  value: <?= number_format(10, 0, ',', ' ') ?>
				},
			],
	        resize: true
	    });
		
	});
</script>