<?php
    // Set up page title:
    $this->headTitle($this->translate('Statistics'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="'.$this->url('myresearch-home').'">'.$this->transEsc('Your Account').'</a></li>' 
    							  .'<li><a href="'.$this->url('statistics-dashboard').'">' . $this->transEsc('Statistics') . '</a></li>'
    							  .'<li class="active">' . $this->transEsc('Circulations') . '</li>';
    
    echo $this->render('statistics/menu.phtml');
    
    echo $this->render('statistics/calendar.phtml');
?>

<div class="row">
	<div class="<?=$this->layoutClass('mainbody')?>">

		<div class="row">
			<div class="col-lg-6">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title">
							<i class="fa fa-user fa-fw"></i>
		 					<?= $this->transEsc('Readers') ?>
						</h3>
					</div>
					<div class="panel-body">
						<div id="readers-comparision"></div>
					</div>
				</div>
			</div>
			<div class="col-lg-6">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title">
							<i class="fa fa-user fa-fw"></i>
		 					<?= $this->transEsc('Circulations') ?>
						</h3>
					</div>
					<div class="panel-body">
						<div id="circulations-comparision"></div>
					</div>
				</div>
			</div>
		</div>
		<!-- /.row -->
		
		<div class="row">
			<div class="col-lg-12">
				<h2><?= $this->transEsc('EIZ usage') ?></h2>
				<div class="table-responsive">
		    		<table class="table table-hover table-striped">
		        		<thead>
		        			<tr>
		        				<th><?= $this->transEsc('Source') ?></th>
		        				<th><?= $this->transEsc('Time spent using') ?></th>
		        				<th class='text-center'><?= $this->transEsc('Number of actions done') ?></th>
		        				<th class='text-center'><?= $this->transEsc('Records viewed') ?></th>
		        				<th><?= $this->transEsc('Usage by readers') ?></th>
		        			</tr>
		        		</thead>
		        		<tbody>
				            <tr>
				                <td>Ebsco</td>
				                <td>15 dní, 6h 30min 25sek</td>
				                <td class='text-center'>3 560</td>
				                <td class='text-center'>3 112</td>
				                <td>159 readers (10%)</td>
							</tr>
							<tr>
				                <td>Ebsco</td>
				                <td>15 dní, 6h 30min 25sek</td>
				                <td class='text-center'>3 560</td>
				                <td class='text-center'>3 112</td>
				                <td>159 readers (10%)</td>
							</tr>
							<tr>
				                <td>Ebsco</td>
				                <td>15 dní, 6h 30min 25sek</td>
				                <td class='text-center'>3 560</td>
				                <td class='text-center'>3 112</td>
				                <td>159 readers (10%)</td>
							</tr>
							<tr>
				                <td>Ebsco</td>
				                <td>15 dní, 6h 30min 25sek</td>
				                <td class='text-center'>3 560</td>
				                <td class='text-center'>3 112</td>
				                <td>159 readers (10%)</td>
							</tr>
							<tr>
				                <td>Ebsco</td>
				                <td>15 dní, 6h 30min 25sek</td>
				                <td class='text-center'>3 560</td>
				                <td class='text-center'>3 112</td>
				                <td>159 readers (10%)</td>
							</tr>
							<tr>
				                <td>Ebsco</td>
				                <td>15 dní, 6h 30min 25sek</td>
				                <td class='text-center'>3 560</td>
				                <td class='text-center'>3 112</td>
				                <td>159 readers (10%)</td>
							</tr>
							<tr>
				                <td>Ebsco</td>
				                <td>15 dní, 6h 30min 25sek</td>
				                <td class='text-center'>3 560</td>
				                <td class='text-center'>3 112</td>
				                <td>159 readers (10%)</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>	
		<!-- /.row -->
		
	</div>
	<div class="<?=$this->layoutClass('sidebar')?>">
    	<?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'statistics'))?>
	</div>
</div>
<!-- /.row -->

<script src="js/raphael.min.js"></script>
<script src="vendor/jquery.min.js"></script>
<script src="js/morris-0.4.1.min.js"></script>
<script src="js/jquery-ui.min.js"></script>
<script>
	jQuery( document ).ready( function( $ ) {
		
		// Sets menu item as active
		$( ".statistics-circulations" ).addClass( "active" );

		// Initializes donut chart for readers comparision
	    Morris.Donut( {
	        element: 'readers-comparision',
	        data: [
	        	{ label: "<?= $this->transEsc('Registrations'); ?>", 
		          value: 20
		        },
			    { label: "<?= $this->transEsc('Prolongations'); ?>", 
				  value: 30 
				},
			],
	        resize: true
	    });

	 	// Initializes donut chart for circulations comparision
	    Morris.Donut( {
	        element: 'circulations-comparision',
	        data: [
	        	{ label: "<?= $this->transEsc('Reserved'); ?>", 
		          value: 20 
		        },
			    { label: "<?= $this->transEsc('Prolonged'); ?>", 
				  value: 30
				},
				{ label: "<?= $this->transEsc('Ordered'); ?>", 
				  value: 10
				},
			],
	        resize: true
	    });
		
	});
</script>