<?php
    // Set up page title:
    $this->headTitle($this->translate('Statistics'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/Search">' . $this->transEsc('Main page') . '</a></li> '.
    '<li><a href="'.$this->url('myresearch-home').'">'.$this->translate('Your Account').'</a></li>' 
    							  .'<li class="active">' . $this->translate('Statistics') . '</li>';
    
    echo $this->render('statistics/menu.phtml');
    
    echo $this->render('statistics/calendar.phtml');
?>
<ul class="breadcrumb hidden-print"><?=$this->layout()->breadcrumbs ?></ul>
<div class="row">
	<div class="<?=$this->layoutClass('mainbody')?>">
	
		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title">
							<i class="icon-hledani"></i>
							<?= $this->translate('Top referrers'); ?> 
						</h3>
					</div>
					<div class="panel-body">
						<div class="table-responsive">
							<table class="table table-hover table-striped">
								<thead>
									<tr>
										<th><?= $this->translate('Referrers') ?></th>
		            					<th class='text-center'><?= $this->translate('Visits') ?></th>
		            				</tr>
		            			</thead>
		            			<tbody>
		            				<?php
		            					$searchesHtml = "";
		
		            					foreach ($this->referrers as $key => $value) {
		            						$searchesHtml .= "\t\t\t\t\t\t\t<tr>\n";
		            						$searchesHtml .= "\t\t\t\t\t\t\t\t<td>\n";
		            						$searchesHtml .= "\t\t\t\t\t\t\t\t\t".$value['referrer']."\n";
		            						$searchesHtml .= "\t\t\t\t\t\t\t\t</td>\n";
		            						$searchesHtml .= "\t\t\t\t\t\t\t\t<td class='text-center'>\n";
		            						$searchesHtml .= "\t\t\t\t\t\t\t\t\t".number_format($value['count'], 0, ',', ' ')."\n";
		            						$searchesHtml .= "\t\t\t\t\t\t\t\t</td>\n";
		            						$searchesHtml .= "\t\t\t\t\t\t\t<tr>\n";
		            					}
		            					
		            					echo $searchesHtml;
		            				?>
		            			</tbody>
		            		</table>
		            	</div>
						<div class="text-right">
							<a id='download-referrers'><?= $this->translate('Download full list in CSV'); ?> <i class="fa fa-cloud-download"></i></a>
						</div>
					</div>
				</div>
			 </div>
		</div>
		<!-- /.row -->
		
		<div class="row">
			<div class="col-lg-6">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title">
							<i class="fa fa-user fa-fw"></i>
		 					<?= $this->translate('Referred types') ?>
						</h3>
					</div>
					<div class="panel-body">
						<div id="referred-types"></div>
					</div>
				</div>
			</div>
		</div>
		<!-- /.row -->
		
	</div>
	<div class="<?=$this->layoutClass('sidebar')?>">
		<?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'statistics'))?>
	</div>
</div>

<? $this->headScript()->appendFile("raphael.min.js"); ?>
<? $this->headScript()->appendFile("morris-0.4.1.min.js"); ?>
<? $this->headScript()->appendFile("jquery-ui.min.js"); ?>
<script>
	jQuery( document ).ready( function( $ ) {
		// Sets menu item as active
		$( ".statistics-dashboard" ).addClass( "active" );

		// download found keywords
		$( "#download-referrers" ).click( function() {
			console.log( "download-referrers initialized" );
			window.open( '<?= $this->referrersLink ?>' );
		});

	    Morris.Donut( {
	        element: 'referred-types',
	        data: [

				<?
					foreach ($this->referredVisits as $val) :
				?>
					
				{ 
					label: "<?= $this->translate($val['referrerType']) ?>", 
			        value: <?= number_format($val['count'], 0, ',', ' ') ?> 
			    },
			    
				<?
					endforeach;
				?>
			],
	        resize: true
	    });
	    
	});
</script>