<?php

    $libCard = null;

    if (isset($this->urlGetParams['libCard']))
	   $libCard  = $this->urlGetParams['libCard'];

	$params = $this->urlGetParams;
	$options = [
		'query' => array(
			'period'   => (! empty($params['period']))   ? $params['period'] : 'month',
			'dateFrom' => (! empty($params['dateFrom'])) ? $params['dateFrom'] : date('Y-m-01'),
			'dateTo'   => (! empty($params['dateTo']))   ? $params['dateTo'] : date('Y-m-t'),
		),
	];
	if ($libCard)
		$options['query']['libCard']  = (! empty($params['libCard']))  ? $params['libCard'] : 'all';

?>

<ul class='nav nav-tabs nav-justified statistics-menu'>
	<li class='statistics-dashboard'><a href='<?= $this->url('statistics-dashboard', array(), $options) ?>'><?= $this->translate('Dashboard') ?></a></li>
	<li class='statistics-visits'><a href='<?= $this->url('statistics-visits', array(), $options) ?>'><?= $this->translate('Visits and visitors') ?></a></li>
	<li class='statistics-searches'><a href='<?= $this->url('statistics-searches', array(), $options) ?>'><?= $this->translate('Searches and catalog') ?></a></li>
	<li class='statistics-payments'><a href='<?= $this->url('statistics-payments', array(), $options) ?>'><?= $this->translate('Payments and orders') ?></a></li>
	<li class='statistics-circulations'><a href='<?= $this->url('statistics-circulations', array(), $options) ?>'><?= $this->translate('Readers and circulations') ?></a></li>
</ul>