<ul class='nav nav-tabs nav-justified'>
	<li class='active'><a href='<?= $this->url('statistics-dashboard') ?>'><?= $this->transEsc('Dashboard') ?></a></li>
	<li><a href='<?= $this->url('statistics-visits') ?>'><?= $this->transEsc('Visits and visitors') ?></a></li>
	<li><a href='<?= $this->url('statistics-searches') ?>'><?= $this->transEsc('Searches and catalog') ?></a></li>
	<li><a href='<?= $this->url('statistics-payments') ?>'><?= $this->transEsc('Payments and orders') ?></a></li>
	<li><a href='<?= $this->url('statistics-circulations') ?>'><?= $this->transEsc('Reservations and prolongs') ?></a></li>
</ul>