<?php
    // Set up page title:
    $this->headTitle($this->translate('Statistics'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="'.$this->url('myresearch-home').'">'.$this->translate('Your Account').'</a></li>' 
    							  .'<li><a href="'.$this->url('statistics-dashboard').'">' . $this->translate('Statistics') . '</a></li>'
    							  .'<li class="active">' . $this->translate('Searches') . '</li>';
    
    echo $this->render('statistics/menu.phtml');
    
    echo $this->render('statistics/calendar.phtml');
?>

<div class="row">
	<div class="<?=$this->layoutClass('mainbody')?>">

		<div class="row">
			<div class="col-lg-4">
				<div class="widget lazur-bg p-lg text-center">
					<div class="m-b-md">
						<i class="fa fa-check fa-4x"></i>
						<h1 class="m-xs"><?= number_format($this->nbSuccessedSearches, 0, ',', ' ') ?></h1>
						<h3 class="font-bold no-margins">
							<?= $this->translate('Found') ?>
		                </h3>
		        		<small>
		            		<?= $this->translate('Number of searches with found results') ?>
		        		</small>
		    		</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="widget red-bg p-lg text-center">
					<div class="m-b-md">
						<i class="fa fa-close fa-4x"></i>
						<h1 class="m-xs"><?= number_format($this->nbFailedSearches, 0, ',', ' ') ?></h1>
						<h3 class="font-bold no-margins">
							<?= $this->translate('Not found') ?>
		                </h3>
		        		<small>
		            		<?= $this->translate('Number of searches with no results') ?>
		        		</small>
		    		</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="widget yellow-bg p-lg text-center">
					<div class="m-b-md">
						<i class="fa fa-sitemap fa-4x"></i>
						<h1 class="m-xs"><?= number_format($this->catalogAccessCount, 0, ',', ' ') ?></h1>
						<h3 class="font-bold no-margins">
							<?= $this->translate('Catalog') ?>
		                </h3>
		        		<small>
		            		<?= $this->translate('Number of catalog browsings') ?>
		        		</small>
		    		</div>
				</div>
			</div>
		</div>
		<!-- /.row -->
		
		<div class="row">
			<div class="col-lg-6">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title">
							<i class="fa fa-search fa-fw"></i> 
							<?= $this->translate('Top keywords'); ?> 
							<span style='float: right;' class="badge"><?= number_format($this->nbFoundKeywords, 0, ',', ' ') ?></span>
						</h3>
					</div>
					<div class="panel-body">
						<div class="table-responsive">
							<table class="table table-hover table-striped">
								<thead>
									<tr>
										<th><?= $this->translate('Search term') ?></th>
		            					<th class='text-center'><?= $this->translate('Search count') ?></th>
		            				</tr>
		            			</thead>
		            			<tbody>
		            				<?php
		            					$searchesHtml = "";
		
		            					foreach ($this->topSearches as $key => $value) {
		            						$searchesHtml .= "\t\t\t\t\t\t\t<tr>\n";
		            						$searchesHtml .= "\t\t\t\t\t\t\t\t<td>\n";
		            						$searchesHtml .= "\t\t\t\t\t\t\t\t\t".$value['keyword']."\n";
		            						$searchesHtml .= "\t\t\t\t\t\t\t\t</td>\n";
		            						$searchesHtml .= "\t\t\t\t\t\t\t\t<td class='text-center'>\n";
		            						$searchesHtml .= "\t\t\t\t\t\t\t\t\t".number_format($value['count'], 0, ',', ' ')."\n";
		            						$searchesHtml .= "\t\t\t\t\t\t\t\t</td>\n";
		            						$searchesHtml .= "\t\t\t\t\t\t\t<tr>\n";
		            					}
		            					
		            					echo $searchesHtml;
		            				?>
		            			</tbody>
		            		</table>
		            	</div>
						<div class="text-right">
							<a id='download-found-keywords'><?= $this->translate('Download full list in CSV'); ?> <i class="fa fa-cloud-download"></i></a>
						</div>
					</div>
				</div>
			 </div>
			 <div class="col-lg-6">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title">
							<i class="fa fa-search fa-fw"></i> 
							<?= $this->translate('Top not found keywords'); ?> 
							<span style='float: right;' class="badge"><?= number_format($this->nbNoResultKeywords, 0, ',', ' ') ?></span>
						</h3>
					</div>
					<div class="panel-body">
						<div class="table-responsive">
							<table class="table table-hover table-striped">
								<thead>
									<tr>
										<th><?= $this->translate('Search term') ?></th>
		            					<th class='text-center'><?= $this->translate('Search count') ?></th>
		            				</tr>
		            			</thead>
		            			<tbody>
		            				<?php
		            					$failedSearchesHtml = "";
		            					
		            					foreach ($this->topFailedSearches as $key => $value) {
		            						$failedSearchesHtml .= "\t\t\t\t\t\t\t<tr>\n";
		            						$failedSearchesHtml .= "\t\t\t\t\t\t\t\t<td>\n";
		            						$failedSearchesHtml .= "\t\t\t\t\t\t\t\t\t".$value['keyword']."\n";
		            						$failedSearchesHtml .= "\t\t\t\t\t\t\t\t</td>\n";
		            						$failedSearchesHtml .= "\t\t\t\t\t\t\t\t<td class='text-center'>\n";
		            						$failedSearchesHtml .= "\t\t\t\t\t\t\t\t\t".number_format($value['count'], 0, ',', ' ')."\n";
		            						$failedSearchesHtml .= "\t\t\t\t\t\t\t\t</td>\n";
		            						$failedSearchesHtml .= "\t\t\t\t\t\t\t<tr>\n";
		            					}
		            					
		            					echo $failedSearchesHtml;
		            				?>
		            			</tbody>
		            		</table>
		            	</div>
						<div class="text-right">
							<a id='download-no-result-keywords'><?= $this->translate('Download full list in CSV'); ?> <i class="fa fa-cloud-download"></i></a>
						</div>
					</div>
				</div>
			 </div>
		</div>
		<!-- /.row -->

		<div class="row">
			<div class="col-lg-6">
				<div class="widget blue-bg p-lg text-center">
					<div class="m-b-md">
						<h1 class="m-xs"><?= number_format($this->nbViewedItems, 0, ',', ' ') ?></h1>
		        		<p>
		            		<?= $this->translate('Number of viewed items') ?>
		        		</p>
		    		</div>
				</div>
			</div>
			<div class="col-lg-6">
				<div class="widget blue-bg p-lg text-center">
					<div class="m-b-md">
						<h1 class="m-xs"><?= number_format($this->nbItemViews, 0, ',', ' ') ?></h1>
		        		<p>
		            		<?= $this->translate('Number of item views') ?>
		        		</p>
		    		</div>
				</div>
			</div>
		</div>
		<!-- /.row -->
		
	</div>
	<div class="<?=$this->layoutClass('sidebar')?>">
    	<?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'statistics'))?>
	</div>
</div>
<!-- /.row -->

<? $this->headScript()->appendFile("jquery-ui.min.js"); ?>
<script>
	jQuery( document ).ready( function( $ ) {
		
		// Sets menu item as active
		$( ".statistics-searches" ).addClass( "active" );

		// download found keywords
		$( "#download-found-keywords" ).click( function() {
			console.log( "download-found-keywords initialized" );
			window.open( '<?= $this->foundKeywordsUrl ?>' );
		});

		// download no result keywords
		$( "#download-no-result-keywords" ).click( function() {
			console.log( "download-no-result-keywords initialized" );
			window.open( '<?= $this->noResultKeywordsUrl ?>' );
		});
		
	});
</script>