<?php
    // Set up page title:
    $this->headTitle($this->translate('Statistics'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="'.$this->url('myresearch-home').'">'.$this->transEsc('Your Account').'</a></li>' 
    							  .'<li><a href="'.$this->url('statistics-dashboard').'">' . $this->transEsc('Statistics') . '</a></li>'
    							  .'<li class="active">' . $this->transEsc('Searches') . '</li>';
    
    echo $this->render('statistics/menu.phtml');
    
    echo $this->render('statistics/calendar.phtml');
?>

<?php 
/*
 echo "<pre>";
 print_r($this->searches);
 echo "</pre>";
 */
?>
<div class="row">
	<div class="col-lg-4">
		<div class="widget lazur-bg p-lg text-center">
			<div class="m-b-md">
				<i class="fa fa-check fa-4x"></i>
				<h1 class="m-xs"><?= $this->nbSuccessedSearches ?></h1>
				<h3 class="font-bold no-margins">
					<?= $this->transEsc('Found') ?>
                </h3>
        		<small>
            		<?= $this->transEsc('Number of searches with found results') ?>
        		</small>
    		</div>
		</div>
	</div>
	<div class="col-lg-4">
		<div class="widget red-bg p-lg text-center">
			<div class="m-b-md">
				<i class="fa fa-close fa-4x"></i>
				<h1 class="m-xs"><?= $this->nbFailedSearches ?></h1>
				<h3 class="font-bold no-margins">
					<?= $this->transEsc('Not found') ?>
                </h3>
        		<small>
            		<?= $this->transEsc('Number of searches with no results') ?>
        		</small>
    		</div>
		</div>
	</div>
	<div class="col-lg-4">
		<div class="widget yellow-bg p-lg text-center">
			<div class="m-b-md">
				<i class="fa fa-sitemap fa-4x"></i>
				<h1 class="m-xs"><?= $this->catalogAccessCount ?></h1>
				<h3 class="font-bold no-margins">
					<?= $this->transEsc('Catalog') ?>
                </h3>
        		<small>
            		<?= $this->transEsc('Number of catalog browsings') ?>
        		</small>
    		</div>
		</div>
	</div>
</div>
<!-- /.row -->

<div class="row">
	<div class="col-lg-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">
					<i class="fa fa-search fa-fw"></i> 
					<?= $this->transEsc('Top keywords'); ?> 
					<span style='float: right;' class="badge"><?= $this->nbFoundKeywords ?></span>
				</h3>
			</div>
			<div class="panel-body">
				<div class="table-responsive">
					<table class="table table-hover table-striped">
						<thead>
							<tr>
								<th><?= $this->transEsc('Search term') ?></th>
            					<th><?= $this->transEsc('Search count') ?></th>
            				</tr>
            			</thead>
            			<tbody>
            				<?php
            					$searchesHtml = "";

            					foreach ($this->topSearches as $key => $value) {
            						$searchesHtml .= "\t\t\t\t\t\t\t<tr>\n";
            						$searchesHtml .= "\t\t\t\t\t\t\t\t<td>\n";
            						$searchesHtml .= "\t\t\t\t\t\t\t\t\t".$value['keyword']."\n";
            						$searchesHtml .= "\t\t\t\t\t\t\t\t</td>\n";
            						$searchesHtml .= "\t\t\t\t\t\t\t\t<td>\n";
            						$searchesHtml .= "\t\t\t\t\t\t\t\t\t".$value['count']."\n";
            						$searchesHtml .= "\t\t\t\t\t\t\t\t</td>\n";
            						$searchesHtml .= "\t\t\t\t\t\t\t<tr>\n";
            					}
            					
            					echo $searchesHtml;
            				?>
            			</tbody>
            		</table>
            	</div>
				<div class="text-right">
					<a href="#"><?= $this->transEsc('Download full list in CSV'); ?> <i class="fa fa-cloud-download"></i></a>
				</div>
			</div>
		</div>
	 </div>
	 <div class="col-lg-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">
					<i class="fa fa-search fa-fw"></i> 
					<?= $this->transEsc('Top not found keywords'); ?> 
					<span style='float: right;' class="badge"><?= $this->nbNoResultKeywords ?></span>
				</h3>
			</div>
			<div class="panel-body">
				<div class="table-responsive">
					<table class="table table-hover table-striped">
						<thead>
							<tr>
								<th><?= $this->transEsc('Search term') ?></th>
            					<th><?= $this->transEsc('Search count') ?></th>
            				</tr>
            			</thead>
            			<tbody>
            				<?php
            					$failedSearchesHtml = "";
            					
            					foreach ($this->topFailedSearches as $key => $value) {
            						$failedSearchesHtml .= "\t\t\t\t\t\t\t<tr>\n";
            						$failedSearchesHtml .= "\t\t\t\t\t\t\t\t<td>\n";
            						$failedSearchesHtml .= "\t\t\t\t\t\t\t\t\t".$value['keyword']."\n";
            						$failedSearchesHtml .= "\t\t\t\t\t\t\t\t</td>\n";
            						$failedSearchesHtml .= "\t\t\t\t\t\t\t\t<td>\n";
            						$failedSearchesHtml .= "\t\t\t\t\t\t\t\t\t".$value['count']."\n";
            						$failedSearchesHtml .= "\t\t\t\t\t\t\t\t</td>\n";
            						$failedSearchesHtml .= "\t\t\t\t\t\t\t<tr>\n";
            					}
            					
            					echo $failedSearchesHtml;
            				?>
            			</tbody>
            		</table>
            	</div>
				<div class="text-right">
					<a href="#"><?= $this->transEsc('Download full list in CSV'); ?> <i class="fa fa-cloud-download"></i></a>
				</div>
			</div>
		</div>
	 </div>
</div>
<!-- /.row -->

<div class="row">
	<div class="col-lg-6">
		<div class="widget lazur-bg p-lg text-center">
			<div class="m-b-md">
				<h1 class="m-xs"><?= $this->nbViewedItems ?></h1>
        		<p>
            		<?= $this->transEsc('Number of viewed items') ?>
        		</p>
    		</div>
		</div>
	</div>
	<div class="col-lg-6">
		<div class="widget lazur-bg p-lg text-center">
			<div class="m-b-md">
				<h1 class="m-xs"><?= $this->nbItemViews ?></h1>
        		<p>
            		<?= $this->transEsc('Number of item views') ?>
        		</p>
    		</div>
		</div>
	</div>
</div>
<!-- /.row -->

<script src="js/raphael.min.js"></script>
<script src="vendor/jquery.min.js"></script>
<script src="js/morris-0.4.1.min.js"></script>
<script src="js/jquery-ui.min.js"></script>
<script>
	jQuery( document ).ready( function( $ ) {
		// Sets menu item as active
		$(".statistics-searches").addClass("active");
	});
</script>