<?php
    // Set up page title:
    $this->headTitle($this->translate('Statistics'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="'.$this->url('myresearch-home').'">'.$this->transEsc('Your Account').'</a></li>' 
    							  .'<li><a href="'.$this->url('statistics-dashboard').'">' . $this->transEsc('Statistics') . '</a></li>'
    							  .'<li class="active">' . $this->transEsc('Visits') . '</li>';
    
    echo $this->render('statistics/menu.phtml');
    
    echo $this->render('statistics/calendar.phtml');
?>

<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
		    <div class="panel-heading">
		        <h3 class="panel-title">
		            <i class="fa fa-clock-o fa-fw"></i>
		             <?= $this->transEsc('Visits in time') ?>
		        </h3>
		    </div>
		    <div class="panel-body">
		    	<div id="visits-in-time"></div>
		    </div>
		</div>
	</div>
</div>
<!-- /.row -->

<div class="row">
	<div class="col-lg-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">
					<i class="fa fa-user fa-fw"></i>
 					<?= $this->transEsc('Visitors') ?>
				</h3>
			</div>
			<div class="panel-body">
				<div id="visits-comparision"></div>
			</div>
		</div>
	</div>
	<div class="col-lg-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">
					<i class="fa fa-users fa-fw"></i> 
					<?= $this->transEsc('Dashboard') ?>
				</h3>
			</div>
			<div class="panel-body">
  				<div class="table-responsive">
					<table class="table">
						<tbody>
							<tr>
								<td>
									<button class="btn array-danger m-r-sm" type="button"><?= $this->totalVisits ?></button>
									<?= $this->transEsc('Total visits') ?>
								</td>
							</tr>
							<tr>
								<td>
									<button class="btn array-default m-r-sm" type="button"><?= $this->totalTimeOnSite ?></button>
									<?= $this->transEsc('Total time') ?>
								</td>
							</tr>
							<tr>
								<td>
									<button class="btn array-info m-r-sm" type="button"><?= $this->avgTimeOnSite ?></button>
									<?= $this->transEsc('Average visit time') ?>
								</td>
							</tr>
							<tr>
								<td>
									<button class="btn array-primary m-r-sm" type="button"><?= $this->nbActions ?></button>
									<?= $this->transEsc('Actions') ?>
								</td>
							</tr>
							<tr>
								<td>
									<button class="btn array-warning m-r-sm" type="button"><?= $this->nbActionPerVisit ?></button>
									<?= $this->transEsc('Actions per visit') ?>
								</td>
							</tr>
							<tr>
								<td>
									<button class="btn array-success m-r-sm" type="button"><?= $this->nbOnlineUsers ?></button>
									<?= $this->transEsc('Online borrowers') ?>
								</td>
							</tr>
							<tr>
								<td>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- /.row -->

<script src="js/raphael.min.js"></script>
<script src="vendor/jquery.min.js"></script>
<script src="js/morris-0.4.1.min.js"></script>
<script src="js/jquery-ui.min.js"></script>
<script>
	jQuery( document ).ready( function( $ ) {

		// Initializes donut chart for visitors comparision
	    Morris.Donut( {
	        element: 'visits-comparision',
	        data: [
	        	{ label: "<?= $this->transEsc('Returning readers'); ?>", 
		          value: <?= $this->returningVisitorsCount ?> 
		        },
			    { label: "<?= $this->transEsc('New readers'); ?>", 
				  value: <?= $this->newVisitorsCount ?> 
				},
			],
	        resize: true
	    });

	 	// Initializes area chart for visits in time
	    Morris.Area( {
	        element: 'visits-in-time',
	        data: [
	   	    	<?php 
	   	    		$data = "";
	   	    		foreach ($this->visitsInTime as $key => $value) {
						$data .= "{ period: '$key', novi: ".$value["newVisits"].", vracejici: ".$value["returningVisits"]." },";
	   	    		}	   
	   	    		echo rtrim($data, ",");	   
				?>
	        ],
	        xkey: 'period',
	        ykeys: [ 'novi', 'vracejici' ],
	        labels: [ '<?= $this->transEsc('New visits'); ?>', '<?= $this->transEsc('Returning visits'); ?>' ],
	        pointSize: 2,
	        hideHover: 'auto'
	      });

	 	// Sets menu item as active
		$( ".statistics-visits" ).addClass( "active" );
		
	});
</script>