<?php
    // Set up page title:
    $this->headTitle($this->translate('Statistics'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="'.$this->url('myresearch-home').'">'.$this->transEsc('Your Account').'</a></li>' 
    							  .'<li><a href="'.$this->url('statistics-dashboard').'">' . $this->transEsc('Statistics') . '</a></li>'
    							  .'<li class="active">' . $this->transEsc('Visits') . '</li>';
    
    echo $this->render('statistics/menu.phtml');
    
    echo $this->render('statistics/calendar.phtml');
    
    $libCard  = $this->urlGetParams['libCard'];
?>

<div class="row">
	<div class="<?=$this->layoutClass('mainbody')?>">

		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
				    <div class="panel-heading">
				        <h3 class="panel-title">
				            <i class="fa fa-clock-o fa-fw"></i>
				             <?= $this->transEsc('Visits in time') ?>
				        </h3>
				    </div>
				    <div class="panel-body">
				    	<div id="visits-in-time"></div>
				    </div>
				</div>
			</div>
		</div>
		<!-- /.row -->
		
		<div class="row">
			<div class="col-lg-4">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title">
							<i class="fa fa-user fa-fw"></i>
		 					<?= $this->transEsc('All Visitors') ?>
						</h3>
					</div>
					<div class="panel-body">
						<div id="visits-comparision"></div>
					</div>
				</div>
			</div>
			
			<? if (($libCard) && ($libCard === 'all')) : ?>
			<div class="col-lg-4">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title">
							<i class="fa fa-user fa-fw"></i>
		 					<?= $this->transEsc('Anonymous Visitors') ?>
						</h3>
					</div>
					<div class="panel-body">
						<div id="visits-comparision-anonymous"></div>
					</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title">
							<i class="fa fa-user fa-fw"></i>
		 					<?= $this->transEsc('Authenticated Visitors') ?>
						</h3>
					</div>
					<div class="panel-body">
						<div id="visits-comparision-authenticated"></div>
					</div>
				</div>
			</div>
			<? endif; ?>
			
		</div>
		<!-- /.row -->
		
		<div class='row'>
			<div class="col-lg-6">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title">
							<i class="fa fa-users fa-fw"></i> 
							<?= $this->transEsc('Dashboard') ?>
						</h3>
					</div>
					<div class="panel-body">
		  				<div class="table-responsive">
							<table class="table table-hover table-striped">
								<tbody>
									<tr>
										<td>
											<?= $this->transEsc('Total visits') ?>
										</td>
										<td>
											<?= $this->totalVisits ?>
										</td>
									</tr>
									<!--<tr>
										<td>
											<?= $this->transEsc('Total time') ?>
										</td>
										<td>
											<?= $this->totalTimeOnSite ?>
										</td>
									</tr>-->
									<tr>
										<td>
											<?= $this->transEsc('Average visit time') ?>
										</td>
										<td>
											<?= $this->avgTimeOnSite ?>
										</td>
									</tr>
									<tr>
										<td>
											<?= $this->transEsc('Actions') ?>
										</td>
										<td>
											<?= $this->nbActions ?>
										</td>
									</tr>
									<tr>
										<td>
											<?= $this->transEsc('Actions per visit') ?>
										</td>
										<td>
											<?= $this->nbActionPerVisit ?>
										</td>
									</tr>
									<tr>
										<td>
											<?= $this->transEsc('Online borrowers') ?>
										</td>
										<td>
											<?= $this->nbOnlineUsers ?>
										</td>
									</tr>
									<? if (($libCard) && ($libCard === 'all')) : ?>
									<tr><td><?= $this->translate('Returning anonymous visitors') ?></td><td><?= $this->returningAnonymeVisitorsCount ?></td></tr>
									<tr><td><?= $this->translate('Returning authenticated visitors') ?></td><td><?= $this->returningAuthenticatedVisitorsCount ?></td></tr>
									<tr><td><?= $this->translate('New anonymous visitors') ?></td><td><?= $this->newAnonymeVisitorsCount ?></td></tr>
									<tr><td><?= $this->translate('New authenticated visitors') ?></td><td><?= $this->newAuthenticatedVisitorsCount ?></td></tr>
									<? endif; ?>
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- /.row -->
		
	</div>
	<div class="<?=$this->layoutClass('sidebar')?>">
    	<?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'statistics'))?>
	</div>
</div>
<!-- /.row -->

<script src="js/raphael.min.js"></script>
<script src="vendor/jquery.min.js"></script>
<script src="js/morris-0.4.1.min.js"></script>
<script src="js/jquery-ui.min.js"></script>
<script>
	jQuery( document ).ready( function( $ ) {

		// Sets menu item as active
		$( ".statistics-visits" ).addClass( "active" );

		// Initializes donut charts for visitors comparision
	    Morris.Donut( {
	        element: 'visits-comparision',
	        data: [
	        	{ label: "<?= $this->transEsc('Returning readers'); ?>", 
		          value: <?= $this->returningVisitorsCount ?> 
		        },
			    { label: "<?= $this->transEsc('New readers'); ?>", 
				  value: <?= $this->newVisitorsCount ?> 
				},
			],
	        resize: true
	    });
	    <? if (($libCard) && ($libCard === 'all')) : ?>
	    Morris.Donut( {
	        element: 'visits-comparision-anonymous',
	        data: [
	        	{ label: "<?= $this->transEsc('Returning readers'); ?>", 
		          value: <?= $this->returningAnonymeVisitorsCount ?> 
		        },
			    { label: "<?= $this->transEsc('New readers'); ?>", 
				  value: <?= $this->newAnonymeVisitorsCount ?> 
				},
			],
	        resize: true
	    });

	    Morris.Donut( {
	        element: 'visits-comparision-authenticated',
	        data: [
	        	{ label: "<?= $this->transEsc('Returning readers'); ?>", 
		          value: <?= $this->returningAuthenticatedVisitorsCount ?> 
		        },
			    { label: "<?= $this->transEsc('New readers'); ?>", 
				  value: <?= $this->newAuthenticatedVisitorsCount ?> 
				},
			],
	        resize: true
	    });
		<? endif; ?>
	    
	 	// Initializes area chart for visits in time
	    Morris.Area( {
	        element: 'visits-in-time',
	        data: [
	   	    	<?php 
	   	    		$data = "";
	   	    		foreach ($this->visitsInTime as $key => $value) {
						$data .= "{ period: '$key', novi: ".$value["newVisits"].", vracejici: ".$value["returningVisits"]." },";
	   	    		}	   
	   	    		echo rtrim($data, ",");	   
				?>
	        ],
	        xkey: 'period',
	        ykeys: [ 'novi', 'vracejici' ],
	        labels: [ '<?= $this->transEsc('New visits'); ?>', '<?= $this->transEsc('Returning visits'); ?>' ],
	        pointSize: 2,
	        parseTime: false,
	        hideHover: 'auto'
	      });
		
	});
</script>