<div id="microsoft_browser_warning" class="hidden">
    <button id="close_browser_suggest" class="close">X</button>
    <?=$this->translate("microsoft-browser-warning")?>
    <label for="browser_more_info"><?=$this->translate("more_info")?></label>
    <input type="checkbox" id="browser_more_info">
    <div id="suggest_browser">
        <p class="tryBrowser"><?=$this->translate("try_browser")?></p><br>
        <ul>
            <li class="col-xs-3">
                <a href="https://www.google.com/intl/cs/chrome/" target="_blank">
                    <img src="/themes/bootstrap3/images/suggestedBrowsers/chrome.png" alt="Google Chrome">
                    <p><?=$this->translate("google_chrome")?></p>
                </a>
            </li>
            <li class="col-xs-3">
                <a href="https://www.opera.com/cs" target="_blank">
                    <img src="/themes/bootstrap3/images/suggestedBrowsers/opera.png" alt="Opera">
                    <p><?=$this->translate("opera")?></p>
                </a>
            </li>
            <li class="col-xs-3">
                <a href="https://www.mozilla.org/cs/firefox/new/" target="_blank">
                    <img src="/themes/bootstrap3/images/suggestedBrowsers/mozilla.png" alt="Mozilla Firefox">
                    <p><?=$this->translate("firefox")?></p>
                </a>
            </li>
            <li class="col-xs-3">
                <a href="https://support.apple.com/downloads/safari" target="_blank">
                    <img src="/themes/bootstrap3/images/suggestedBrowsers/safari.png" alt="Safari">
                    <p><?=$this->translate("safari")?></p>
                </a>
            </li>
        </ul>
        <p class="browsersFree"><?=$this->translate("browsers_free")?></p>
    </div>
</div>
<script>
  /* Work with browser suggest lightbox */
  var browserSuggest = document.getElementById( 'microsoft_browser_warning' );
  document.getElementById( 'close_browser_suggest' ).onclick = function () {
    browserSuggest.classList.add( 'hidden' );
    localStorage.setItem( 'browserSuggestClosed', true );
  };
  if ( /(MSIE|Trident\/)/i.test( navigator.userAgent ) && !localStorage.getItem( 'browserSuggestClosed' ) ) {
    browserSuggest.classList.remove( 'hidden' );
  }
</script>