<div id="microsoft_browser_warning" class="hidden">
    <?=$this->translate("microsoft-browser-warning")?>
    <label for="browser_more_info"><?=$this->translate("more_info")?></label>
    <input type="checkbox" id="browser_more_info">
    <div id="suggest_browser">
        <p class="tryBrowser"><?=$this->translate("try_browser")?></p><br>
        <ul>
            <li class="col-xs-3">
                <a href="https://www.google.com/chrome/">
                    <img src="/themes/bootstrap3/images/suggestedBrowsers/chrome.png" alt="Google Chrome">
                    <p><?=$this->translate("google_chrome")?></p>
                </a>
            </li>
            <li class="col-xs-3">
                <a href="https://www.opera.com/">
                    <img src="/themes/bootstrap3/images/suggestedBrowsers/opera.png" alt="Opera">
                    <p><?=$this->translate("opera")?></p>
                </a>
            </li>
            <li class="col-xs-3">
                <a href="https://www.mozilla.org/en-US/firefox/new/">
                    <img src="/themes/bootstrap3/images/suggestedBrowsers/mozilla.png" alt="Mozilla Firefox">
                    <p><?=$this->translate("firefox")?></p>
                </a>
            </li>
            <li class="col-xs-3">
                <a href="https://support.apple.com/downloads/safari">
                    <img src="/themes/bootstrap3/images/suggestedBrowsers/safari.png" alt="Safari">
                    <p><?=$this->translate("safari")?></p>
                </a>
            </li>
        </ul>
        <p class="browsersFree"><?=$this->translate("browsers_free")?></p>
        <div>Icons made by
            <a href="https://www.freepik.com/" title="Freepik">Freepik</a>
            from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by
            <a href="http://creativecommons.org/licenses/by/3.0/"
               title="Creative Commons BY 3.0"
               target="_blank">CC 3.0 BY</a>
        </div>
    </div>
</div>