<?
  // Set page title.
  $this->headTitle($this->translate('Email this Search'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li>' . $this->getLastSearchLink($this->transEsc('Search'), '', ' <span class="divider">&gt;</span></li>') .
    '<li class="active">' . $this->transEsc('Email this Search') . '</li>';
?>
<?=$this->flashmessages()?>
<form class="form-horizontal"  method="post"  name="emailSearch">
  <input type="hidden" name="url" value="<?=$this->escapeHtmlAttr($this->url)?>" />
  <div class="control-group">
    <label class="control-label" for="email_to"><?=$this->transEsc('To')?>:</label>
    <div class="controls">
      <input class="input-xlarge" id="email_to" type="email" name="to" value="<?=isset($this->to) ? $this->to : ''?>"/>
    </div>
  </div>
  <? if (!$this->disableFrom): ?>
    <div class="control-group">
      <label class="control-label" for="email_from"><?=$this->transEsc('From')?>:</label>
      <div class="controls">
        <input class="input-xlarge" id="email_from" type="email" name="from" value="<?=isset($this->from) ? $this->from : ''?>"/>
      </div>
    </div>
  <? endif; ?>
  <? if ($this->export && is_array($this->export)): ?>
  <div class="control-group">
    <label class="control-label" for="export_format"><?=$this->transEsc('Send As')?>:</label>
    <div class="controls">
      <select name="export_format" class="jumpMenu">  
        <? foreach ($this->export as $format => $value): ?>
          <? if ($value): ?>
            <option value="<?=$this->escapeHtml(str_replace(' ', '', $format))?>"><?=$this->transEsc($format)?></option>
          <? endif; ?>
        <? endforeach; ?>
      </select>
    </div>
  </div>
  <? endif; ?>
  <div class="control-group">
    <label class="control-label" for="email_message"><?=$this->transEsc('Message')?>:</label>
    <div class="controls">
      <textarea class="input-xlarge" id="email_message" name="message" rows="3"><?=isset($this->message) ? $this->message : ''?></textarea>
    </div>
  </div>
  <?=$this->recaptcha()->html($this->useRecaptcha) ?>
  <div class="control-group">
    <div class="controls">
      <input class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEsc('Send Email')?>"/>
    </div>
  </div>
   <? if ($this->ids): ?>
    <input type="hidden" name="exportIDs" value="<?=implode(';', $this->ids);?>">
  <? endif; ?>
</form>
