<?
  // Set up standard record scripts:
  $this->headScript()->appendFile("record.js");
  $this->headScript()->appendFile("check_save_statuses.js");
  // Activate Syndetics Plus if necessary:
  if ($this->syndeticsPlus()->isActive()) {
    echo $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
  }

  // Add RDF header link if applicable:
  if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
    $this->headLink()->appendAlternate($this->recordLink()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
  }

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li>' . $this->getLastSearchLink($this->transEsc('Search'), '', '</li> ') .
    '<li class="active">' . $this->recordLink()->getBreadcrumb($this->driver) . '</li> ';
  $this->layout()->title = $this->driver->getShortTitle();
?>

<? if (isset($this->scrollData) && ($this->scrollData['previousRecord'] || $this->scrollData['nextRecord'])): ?>
  <ul class="pager hidden-print">
    <? if ($this->scrollData['previousRecord']): ?>
      <li>
        <a href="<?=$this->recordLink()->getUrl($this->scrollData['previousRecord'])?>" title="<?=$this->transEsc('Previous Search Result')?>">&laquo; <?=$this->transEsc('Prev')?></a>
      </li>
    <? else: ?>
      <li class="disabled"><a href="#">&laquo; <?=$this->transEsc('Prev')?></a></li>
    <? endif; ?>
    #<?=$this->localizedNumber($this->scrollData['currentPosition']) . ' ' . $this->transEsc('of') . ' ' . $this->localizedNumber($this->scrollData['resultTotal']) . ' ' . $this->transEsc('results') ?>
    <? if ($this->scrollData['nextRecord']): ?>
      <li>
        <a href="<?=$this->recordLink()->getUrl($this->scrollData['nextRecord'])?>" title="<?=$this->transEsc('Next Search Result')?>"><?=$this->transEsc('Next')?> &raquo;</a>
      </li>
    <? else: ?>
      <li class="disabled"><a href="#"><?=$this->transEsc('Next')?> &raquo;</a></li>
    <? endif; ?>
  </ul>
<? endif; ?>

<div class="row">
  <div class="<?=$this->layoutClass('mainbody')?>">
    <div class="record recordId source<?=$this->escapeHtmlAttr($this->driver->getResourceSource())?>" id="record">
      <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" class="hiddenId" id="record_id" />
      <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getResourceSource()) ?>" class="hiddenSource" />
      <?=$this->flashmessages()?>
        <div class="well">
      <?=$this->record($this->driver)->getCoreMetadata()?></div>
    </div>
	
	<?
	 //echo $this->record($this->driver)->getWantIt() 
	?>
	<div class="well">
    <? if (count($this->tabs) > 0): ?>
      <a name="tabnav"></a>
      <ul class="recordTabs nav nav-tabs">
        <? foreach ($this->tabs as $tab => $obj): ?>
        <? // add current tab to breadcrumbs if applicable:
          $desc = $obj->getDescription();
          $tab_classes = array();
          if (0 === strcasecmp($this->activeTab, $tab)) {
            $tab_classes[] = 'active';
            $this->layout()->breadcrumbs .= '<li class="active">' . $this->transEsc($desc) . '</li>';
            $activeTabObj = $obj;
          }
          if (!$obj->isVisible()) { $tab_classes[] = 'hidden'; }
          if (!$obj->supportsAjax()) { $tab_classes[] = 'noajax'; }
        ?>
        <li<?=count($tab_classes) > 0 ? ' class="' . implode(' ', $tab_classes) . '"' : ''?>>
          <a id="<?=strtolower($tab) ?>" href="<?=$this->recordLink()->getTabUrl($this->driver, $tab)?>#tabnav"><?=$this->transEsc($desc)?></a>
        </li>
        <? endforeach; ?>
      </ul>
    <? endif; ?>

    <div class="tab-content" id="record-tabs">
      <div class="tab-pane active" id="<?=$this->activeTab ?>-tab">
        <?=isset($activeTabObj) ? $this->record($this->driver)->getTab($activeTabObj) : '' ?>
      </div>
    </div>
</div>
    <span class="Z3988" title="<?=$this->escapeHtmlAttr($this->driver->getOpenURL())?>"></span>
  </div>

  <div class="<?=$this->layoutClass('sidebar')?>">
      <div class="well">
      <?=$this->record($this->driver)->getToolbar()?>
      </div>
      <div class="well">

	      <div>
		  	<h4><?= $this->translate('Records in group') ?></h4>
		  	
		  	<?php   	
			  	$dedupedRecords = $this->tabs['DedupedRecords']->getRecordsInGroup();
			  	
			  	$recordGroup = array();
				foreach ($dedupedRecords as $record) {
					if(! array_key_exists($record['source'], $recordGroup)) {
						$recordGroup[$record['source']] = array($record['id']);
					} else {
						$recordGroup[$record['source']][] = $record['id'];
					}
				}
		  	?>
	
			  	<div class="dropdown">
				  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
				  	<span id='first-record-group'>
					    <?
					    	reset($recordGroup);
					    	echo $this->translate(key($recordGroup));
					    ?>
				    </span>
				    <span class="caret"></span>
				  </button>
				  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1" id='record-group'>
				  	<? 
				  		foreach (array_keys($recordGroup) as $key) {
				  			if (count($recordGroup[$key]) === 1) {
				  				$link = $recordGroup[$key][0];
				  				echo "<li><a href='".$this->url('record', array('id' => $link))."' id='$link' title='".$this->translate($key)."'>".$this->translate($key)."</a></li>";
				  			} else {
				  				echo "<li><a href='#' class='multiple-records' id='".implode("|", $recordGroup[$key])."' title='".$this->translate($key)."'>".$this->translate($key)."</a></li>";
				  			}
				  		}
				  	?>
				  </ul>
				</div>
		
				<div class="dropdown hidden" id='recordsDropdown'>
				  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
				    <span id='first-record'><?= $this->translate('Choose record') ?></span>
				    <span class="caret"></span>
				  </button>
				  <ul class="dropdown-menu" aria-labelledby="dropdownMenu2" id='records-in-group'>
				  </ul>
				</div>
	
		  </div>
		  <?
		  	$recordID = $this->driver->getUniqueId();
		  	$recordSource = explode(".", $recordID)[0];
		  ?>
		  <script>
			jQuery( document ).ready( function( $ ) {
				
				var source = "<?= $recordSource ?>";
				var recordID = "<?= $recordID ?>";

				// select default record group
				$( '#record-group li a' ).each( function() {
					
					var title = $( this ).attr( 'title' );
					if ( $( this ).attr( 'id' ).toLowerCase().indexOf( source.toLowerCase() ) >= 0 ) {
						$( '#first-record-group' ).text( title );
					}

				});

				// initial records in dropdown menu
				$( '#record-group li a.multiple-records' ).each( function() {
					
					var records = $( this ).attr( 'id' );
					var recordsArr = records.split( "|" );

					if (recordsArr.length > 1) {

						if ( records.toLowerCase().indexOf( source.toLowerCase() ) >= 0 ) {
							
							var optionsHTML = "";
							
							recordsArr.forEach( function( record ) {
								
								optionsHTML += getRecordsForGroup( record );
	
							});
							
							$( '#recordsDropdown' ).removeClass( 'hidden' );
							$( '#records-in-group' ).html( optionsHTML );
							optionsHTML = null;
							
						}
	
						// set initial record
						if ( $( '#records-in-group li a[href*="'+recordID+'"]' ).text().length > 0) {
							var textValue = $( '#records-in-group li a[href*="'+recordID+'"]' ).text();
							$( '#first-record' ).text( textValue );
							$( this ).css('font-weight', 'bold');
						}

					}
						
				});

				// ajax records in selected group generator
				$( '#record-group' ).on( "click", ".multiple-records", function( event ) {
	
					event.preventDefault();
	
					$( '#first-record-group' ).text( $( this ).attr( 'title' ) );
					
					var group = $( this ).attr( 'title' );
					var recordsArr = $( this ).attr( 'id' ).split( "|" );
					var optionsHTML = "";
	
					recordsArr.forEach( function( record ) {
	
						optionsHTML += getRecordsForGroup( record );

					});
					
					$( '#recordsDropdown' ).removeClass( 'hidden' );
					$( '#records-in-group' ).html( optionsHTML );
					optionsHTML = null;
				});

				function getRecordsForGroup( record ) {

					var optionsHTML = "";
					
					$.ajax({
						url: 		"getMarcArrayViaAjax",
						method: 	"POST",
						dataType: 	"json",
						async: false,
						data: { recordID: record, 
								field: '996', 
								subfields: "l,r" 
						}
					}).done( function( msg ) {

						var arr996 = (msg.arr[0] !== undefined) ? msg.arr[0] : '<?= $this->translate('record') ?>'+' '+record;
						
						var link = '/Record/'+record;
						optionsHTML += "<li><a href='"+link+"'>"+arr996+"</a></li>"; 

					}).fail( function( jqXHR, textStatus ) {
						console.log( jqXHR+' '+textStatus );
					});

					return optionsHTML;
				}
				
			});
		  </script>
	  
	  </div>
	  <div class="well">
	  
    <? foreach ($this->related()->getList($this->driver) as $current): ?>
      <?=$this->related()->render($current)?>
    <? endforeach; ?>
    </div>

  </div>
</div>
