<?
    // Get source of the record to print it to h3 header
    $id = $this->driver->getUniqueID();
    $source = explode(".", $id)[0];

  // Set up standard record scripts:
  $this->headScript()->appendFile("record.js");
  $this->headScript()->appendFile("check_save_statuses.js");
  
  // Activate Syndetics Plus if necessary:
  if ($this->syndeticsPlus()->isActive()) {
    echo $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
  }

  // Add RDF header link if applicable:
  if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
    $this->headLink()->appendAlternate($this->recordLink()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
  }

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/">' . $this->transEsc('Main page') . '</a></li> ';
  if (isset($_GET['fromSearchId'])) {
      $this->layout()->breadcrumbs .= '<li><a href="/Search/Results?saved='.htmlspecialchars($_GET['fromSearchId']).'">'.$this->transEsc('Search').'</a></li> ';
  }
  $this->layout()->breadcrumbs .= '<li class="active">' . $this->escapeHtml($this->driver->getTitle()) . '</li> ';
  $this->layout()->title = $this->driver->getShortTitle();
  
  $fromAdvancedSearchIdParam = (isset($_GET['fromAdvancedSearchId']))
    ? '?fromAdvancedSearchId='.htmlspecialchars($_GET['fromAdvancedSearchId'])
    : '';
  $fromSearchIdParam = (isset($_GET['fromSearchId']))
    ? '?fromSearchId='.htmlspecialchars($_GET['fromSearchId'])
    : '';
?>

<script>
	jQuery( document ).ready(function( $ ){
		getCitation( '<?=$this->driver->getUniqueID()?>', false, insertCitation );
	})
</script>

<? if (isset($this->scrollData) && ($this->scrollData['previousRecord'] || $this->scrollData['nextRecord'])): ?>
  <ul class="pager hidden-print">
    <? if ($this->scrollData['previousRecord']): ?>
      <li>
        <a href="<?=$this->recordLink()->getUrl($this->scrollData['previousRecord'])?>" title="<?=$this->transEsc('Previous Search Result')?>">&laquo; <?=$this->transEsc('Prev')?></a>
      </li>
    <? else: ?>
      <li class="disabled"><a href="#">&laquo; <?=$this->transEsc('Prev')?></a></li>
    <? endif; ?>
    #<?=$this->localizedNumber($this->scrollData['currentPosition']) . ' ' . $this->transEsc('of') . ' ' . $this->localizedNumber($this->scrollData['resultTotal']) . ' ' . $this->transEsc('results') ?>
    <? if ($this->scrollData['nextRecord']): ?>
      <li>
        <a href="<?=$this->recordLink()->getUrl($this->scrollData['nextRecord'])?>" title="<?=$this->transEsc('Next Search Result')?>"><?=$this->transEsc('Next')?> &raquo;</a>
      </li>
    <? else: ?>
      <li class="disabled"><a href="#"><?=$this->transEsc('Next')?> &raquo;</a></li>
    <? endif; ?>
  </ul>
<? endif; ?>

<div class="clearfix">
  <div class="col-sm-9">
    <div class="record source<?=$this->escapeHtmlAttr($this->driver->getResourceSource())?>">
      <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" class="hiddenId" />
      <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getResourceSource()) ?>" class="hiddenSource" />
      <?=$this->flashmessages()?>
      
    <!-- Modal -->
    <div class="modal fade" id="citationsModal" tabindex="-1" role="dialog" aria-labelledby="citationsLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="citationsLabel"><?=$this->translate('Citations')?></h4>
          </div>
          <div class="modal-body">
              <div class='citation-loader row'>
                <div class='col-sm-12 text-center'>
              	  <i class="fa fa-2x fa-spinner fa-spin"></i>
              	</div>
              </div>
			  <div id='citation-placeholder'></div>
			  <div id='citation-style-selector'>
			    <select class='style' id='record_<?=$id?>'>
			      <? foreach($this->availableCitationStyles as $style): ?>
			      <option value='<?=$style['value']?>'<?= ($style['value'] == $this->selectedCitationStyle) ? 'selected="selected"' : '' ?>><?=$style['description']?></option>
			      <? endforeach; ?>
			    </select>
			    <a href="http://www.citacepro.com/nacist-dokument-sysno/<?=$id?>?katalog=cpk" target="_blank">
			      <img src="/themes/cpk-devel/images/logoCitacePROkatalog.png" alt="Citace PRO">
			    </a>
			  </div>      
		  </div>    	
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal"><?=$this->translate('close')?></button>
          </div>
        </div>
      </div>
    </div>
    
    <!-- Modal -->
    <div class="modal fade" id="permalinkModal" tabindex="-1" role="dialog" aria-labelledby="permalinkLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="permalinkLabel"><?=$this->translate('Permalink')?></h4>
          </div>
          <div class="modal-body">
            <p><?=htmlspecialchars("https://".$_SERVER['SERVER_NAME']."/Record/".$id)?></p>     
		  </div>    	
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal"><?=$this->translate('close')?></button>
          </div>
        </div>
      </div>
    </div>
			<?=$this->record($this->driver)->getCoreMetadata()?>
			<?= $this->render('RecordDriver/SolrDefault/records-in-groups.phtml'); ?>
			<div class="well">
            <? if (count($this->tabs) > 0): ?>
              <a name="tabnav"></a>
              <ul class="recordTabs nav nav-tabs">
              
                <? foreach ($this->tabs as $tab => $obj): ?>
                <? // add current tab to breadcrumbs if applicable:
                  $desc = $obj->getDescription();
                  $tab_classes = array();
                  if (0 === strcasecmp($this->activeTab, $tab)) {
                    $tab_classes[] = 'active';
                    $tab_classes[] = 'initiallyActive';
                    $this->layout()->breadcrumbs .= '<li class="active">' . $this->transEsc($desc) . '</li>';
                    $activeTabObj = $obj;
                  }
                  if (!$obj->isVisible()) { $tab_classes[] = 'hidden'; }
                  if (!$obj->supportsAjax()) { $tab_classes[] = 'noajax'; }
                ?>
                <li<?=count($tab_classes) > 0 ? ' class="' . implode(' ', $tab_classes) . '"' : ''?>>
                  <a id="<?=strtolower($tab) ?>" href="<?=$this->recordLink()->getTabUrl($this->driver, $tab)?><?=$fromSearchIdParam?><?=$fromAdvancedSearchIdParam?>#tabnav"><?=$this->transEsc($desc)?></a>
                </li>
                <? endforeach; ?>
              </ul>
           	<? endif; ?>
        
                <div class="tab-content" id="record-tabs">
                  <div class="tab-pane active" id="<?=$this->activeTab ?>-tab">
                    <?=isset($activeTabObj) ? $this->record($this->driver)->getTab($activeTabObj) : '' ?>
                  </div>
                </div>
            
                <?=$this->driver->supportsCoinsOpenURL()?'<span class="Z3988" title="'.$this->escapeHtmlAttr($this->driver->getCoinsOpenURL()).'"></span>':''?>
            </div>
            
            <!-- Modal -->
                <div class="modal fade" id="subjectsModal" tabindex="-1" role="dialog" aria-labelledby="subjectsLabel">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="subjectsLabel"><?=$this->translate('Subjects')?></h4>
                      </div>
                      <div class="modal-body">
                        <div class='subjects-scrollable'>
                          <? $subjects = $this->driver->getAllSubjectHeadings(); if (!empty($subjects)): ?>
                              <? foreach ($subjects as $field): ?>
                              <div class="subjectLine" property="keywords">
                                <? $subject = ''; ?>
                                <? if(count($field) == 1) $field = explode('--', is_array($field) ? $field[0] : $field); ?>
                                <? $i = 0; foreach ($field as $subfield): ?>
                                  <?=($i++ == 0) ? '' : ' &gt; '?>
                                  <? $subject = trim($subfield); ?>
                                  <a title="<?=$this->escapeHtmlAttr($subject)?>" href="<?=$this->record($this->driver)->getLink('subject', $subject)?>"><?=trim($this->escapeHtml($subfield))?></a>
                                <? endforeach; ?>
                              </div>
                              <? endforeach; ?>
                          <? endif; ?>  
                        </div>
            		  </div>    	
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal"><?=$this->translate('close')?></button>
                      </div>
                    </div>
                  </div>
                </div>
                
             <!-- Modal -->
                <div class="modal fade" id="mailRecordModal" tabindex="-1" role="dialog" aria-labelledby="mailRecordLabel">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="mailRecordLabel"><?=$this->translate('Email this Search')?></h4>
                      </div>
                      <div class="modal-body">
                        <?=$this->context($this)->renderInContext('record/email.phtml', [])?>
            		  </div>    	
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal"><?=$this->translate('close')?></button>
                      </div>
                    </div>
                  </div>
                </div>
         
            <script src="/themes/cpk-devel/js/ajax-record-tabs.js"></script>
            <script>
            
            /**
             * Removes active state from Buy Link when there are no buyLinks
             *
             * @param {array} buyLinks
             * @return {void}
             */
            function disableBuyTab( buyLinks )
            {
            	if ( buyLinks.data[0]['buyLinksCount'] === 0 )
            		$( '#buy' ).parent().removeClass( 'active' ).addClass( 'disabled' );
            }
            
            jQuery( document ).ready( function( $ ) {
            
            	// Disable eversion tab
            	var eVersionLinksCount = <?=$this->eVersionLinksCount?>;
            	if ( eVersionLinksCount === 0 ) {
            		$( '#eversion' ).parent().removeClass( 'active' ).addClass( 'disabled' );
            		$( "#e-version-table" ).addClass( 'hidden' );
            	}
            
            	// Disable holdings tab
            	var holdingsCount = <?= count($holdings = $this->driver->getRealTimeHoldings()) ?>;
            	if ( holdingsCount === 0 ) {
            		$( '#holdings' ).parent().removeClass( 'active' ).addClass( 'disabled' );
            	}
            
            	//
            	var recordID = '<?= $this->driver->getUniqueID() ?>';
            	var parentRecordID = '<?= $this->driver->getParentRecordID() ?>';
            
            	var buyLinks = getBuyLinks( recordID, parentRecordID, disableBuyTab );
            
            	var source = "<?= $source ?>";
            
            	// select default record group
            	$( '#record-group li a' ).each( function() {
            
            		var title = $( this ).attr( 'title' );
            		if ( $( this ).attr( 'id' ).toLowerCase().indexOf( source.toLowerCase() ) >= 0 ) {
            			$( '#first-record-group' ).text( title );
            		}
            
            	});

            	$( '#subjects-tr' ).on('click', '#show-all-subjects', function(){
            		$( '#subjectsModal' ).modal( 'show' );
            	});
            
            });
            </script>
		</div>
    
    </div>
    <div class='col-sm-3'>
      <?= $this->render('RecordDriver/SolrDefault/record-sidebar.phtml'); ?>
    </div>
</div>

</div>

<?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, '$(document).ready(recordDocReady);', 'SET'); ?>

