<?
  // Set page title.
  $this->headTitle($this->translate('Portal pages | Administration'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/Search">' . $this->transEsc('Main page') . '</a></li> ' .
      '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'.
      '<li><a href="/Admin/Home">'.$this->transEsc('Administration').'</a></li>'.
      '<li class="active">'.$this->transEsc('Widgets').'</li>';

  $this->layout()->title = $this->translate('Widgets');
?>
<div class="row clearfix">
  <ul class="breadcrumb hidden-print"><?=$this->layout()->breadcrumbs ?></ul>

  <div class="col-sm-3">
    <?=$this->render("admin/menu.phtml")?>
  </div>

  <div class="col-sm-9" id='homepage-widgets'>
    <h2><?=$this->translate('Homepage widgets')?></h2>
    <div class='well'>
	  <div class='row'>
        <div class='col-md-4 text-center'>
        	<h2><?=$this->translate('First column');?></h2>
			<select id='first-homepage-widget'>
			  <? foreach($widgets as $widget): ?>
				<option value='<?=$widget->getName()?>'<?=($widget->getName()==$this->homePageWidgets['first_homepage_widget'] ? ' selected' : '')?>><?=$this->translate($widget->getName())?></option>
			  <? endforeach; ?>
			</select>
        </div>
        <div class='col-md-4 text-center'>
        	<h2><?=$this->translate('Second column');?></h2>
			<select id='second-homepage-widget'>
				<? foreach($widgets as $widget): ?>
				<option value='<?=$widget->getName()?>'<?=($widget->getName()==$this->homePageWidgets['second_homepage_widget'] ? ' selected' : '')?>><?=$this->translate($widget->getName())?></option>
			  <? endforeach; ?>
			</select>
        </div>
        <div class='col-md-4 text-center'>
        	<h2><?=$this->translate('Third column');?></h2>
			<select id='third-homepage-widget'>
				<? foreach($widgets as $widget): ?>
				<option value='<?=$widget->getName()?>'<?=($widget->getName()==$this->homePageWidgets['third_homepage_widget'] ? ' selected' : '')?>><?=$this->translate($widget->getName())?></option>
			  <? endforeach; ?>
			</select>
        </div>
      </div>
	</div>
  </div>

  <div class="col-sm-9" id='inspiration-widgets'>
    <h2><?=$this->translate('Inspiration widgets')?></h2>
    <div class='well'>
	  <div class='row'>
        <div class='col-md-4 text-center'>
        	<h2><?=$this->translate('First column');?></h2>
			<select id='first-inspiration-widget'>
			  <? foreach($widgets as $widget): ?>
				<option value='<?=$widget->getName()?>'<?=($widget->getName()==$this->inspirationWidgets['first_inspiration_widget'] ? ' selected' : '')?>><?=$this->translate($widget->getName())?></option>
			  <? endforeach; ?>
			</select>
        </div>
        <div class='col-md-4 text-center'>
        	<h2><?=$this->translate('Second column');?></h2>
			<select id='second-inspiration-widget'>
				<? foreach($widgets as $widget): ?>
				<option value='<?=$widget->getName()?>'<?=($widget->getName()==$this->inspirationWidgets['second_inspiration_widget'] ? ' selected' : '')?>><?=$this->translate($widget->getName())?></option>
			  <? endforeach; ?>
			</select>
        </div>
        <div class='col-md-4 text-center'>
        	<h2><?=$this->translate('Third column');?></h2>
			<select id='third-inspiration-widget'>
				<? foreach($widgets as $widget): ?>
				<option value='<?=$widget->getName()?>'<?=($widget->getName()==$this->inspirationWidgets['third_inspiration_widget'] ? ' selected' : '')?>><?=$this->translate($widget->getName())?></option>
			  <? endforeach; ?>
			</select>
        </div>
        <div class='col-md-4 text-center'>
        	<h2><?=$this->translate('Fourth column');?></h2>
			<select id='fourth-inspiration-widget'>
			  <? foreach($widgets as $widget): ?>
				<option value='<?=$widget->getName()?>'<?=($widget->getName()==$this->inspirationWidgets['fourth_inspiration_widget'] ? ' selected' : '')?>><?=$this->translate($widget->getName())?></option>
			  <? endforeach; ?>
			</select>
        </div>
        <div class='col-md-4 text-center'>
        	<h2><?=$this->translate('Fifth column');?></h2>
			<select id='fifth-inspiration-widget'>
				<? foreach($widgets as $widget): ?>
				<option value='<?=$widget->getName()?>'<?=($widget->getName()==$this->inspirationWidgets['fifth_inspiration_widget'] ? ' selected' : '')?>><?=$this->translate($widget->getName())?></option>
			  <? endforeach; ?>
			</select>
        </div>
        <div class='col-md-4 text-center'>
        	<h2><?=$this->translate('Sixth column');?></h2>
			<select id='sixth-inspiration-widget'>
				<? foreach($widgets as $widget): ?>
				<option value='<?=$widget->getName()?>'<?=($widget->getName()==$this->inspirationWidgets['sixth_inspiration_widget'] ? ' selected' : '')?>><?=$this->translate($widget->getName())?></option>
			  <? endforeach; ?>
			</select>
        </div>
      </div>
	</div>
  </div>

</div>

<script>
	jQuery( document ).ready( function( $ ) {
		$( '#homepage-widgets, #inspiration-widgets' ).on( 'change', 'select', function( event ) {
			event.preventDefault();

			var data = {};

			$( '#homepage-widgets select, #inspiration-widgets select' ).each(function( index, element ) {
				data[$( element ).attr( 'id' )] = $( element ).val();
			});

			$.ajax({
	            type: 'POST',
	            cache: false,
	            dataType: 'json',
	            data: data,
	            url: VuFind.getPath() + '/Admin/Widgets/SaveHomePageWidgets',
	            beforeSend: function() {
	            },
	            success: function( response ) {

	                if (response.status == 'OK') {

	                	$( '#save-widgets-confirmation' ).modal( 'show' );

	        			setTimeout( function() {
	        				$( '#save-widgets-confirmation' ).modal( 'hide' );
	        			}, 1200 );

	                } else {
	                    console.error(response.data);
	                }

	            },
	            error: function ( xmlHttpRequest, status, error ) {
	                $( '#search-results-loader' ).remove();
	                console.error(xmlHttpRequest.responseText);
	                console.error(xmlHttpRequest);
	                console.error(status);
	                console.error(error);
	            },
	            complete: function ( xmlHttpRequest, textStatus ) {
	            }
	        });
		});
	});
</script>

<div class="modal fade" id="save-widgets-confirmation" tabindex="-1" role="dialog" aria-labelledby="save-widgets-confirmation-label" style='margin-top: 150px;'>
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
               <?=$this->translate('Widgets saved')?>
            </div>
        </div>
    </div>
</div>