<meta property="og:url"
      content="https://kiv.knihovny.cz/" />
<meta property="og:title"
      content="Oborová brána KIV" />
<meta property="og:description"
      content="Oborová brána KIV - jednotný přístup k informačním zdrojům v knihovnictví a informační vědy" />
<meta property="og:image"
      content="https://www.knihovny.cz/themes/bootstrap3/images/knihovny-cz-20200919.png" />
<meta property="og:image:secure_url"
      content="https://www.knihovny.cz/themes/bootstrap3/images/knihovny-cz-20200919.png" />
<meta property="og:image:type"
      content="image/png" />
<meta name="referrer"
      content="unsafe-url" />
<link href="<?=$this->imageLink($this->themeConfiguration()->themeConfig['logo_image']) ?>" rel="icon" type="image/png">
