<meta property="og:url"
      content="https://kiv.knihovny.cz/" />
<meta property="og:title"
      content="Oborová brána KIV" />
<meta property="og:description"
      content="Oborová brána KIV - jednotný přístup k informačním zdrojům v knihovnictví a informační vědy" />
<meta property="og:image"
      content="https://www.knihovny.cz/themes/bootstrap3/images/screenshot_20171130.png" />
<meta property="og:image:secure_url"
      content="https://www.knihovny.cz/themes/bootstrap3/images/screenshot_20171130.png" />
<meta property="og:image:type"
      content="image/png" />
<meta name="referrer"
      content="unsafe-url" />
<link href="/themes/kiv/images/logo-kiv.png" rel="icon" type="image/png">
