<? if (!isset($this->hideCartControls) && $this->cart()->isActive()): ?>
  <label class="checkbox">
    <input type="checkbox" class="checkbox-select-all" name="selectAll" id="<?=$this->idPrefix?>addFormCheckboxSelectAll"/> <?=$this->transEsc('select_page')?>
  </label>
  <noscript>
    <span class="help-inline"><?=$this->transEsc('with_selected')?>:</span>
    <input id="<?=$this->idPrefix?>updateCart" type="submit" class="btn" name="add" value="<?=$this->transEsc('Add to Book Bag')?>"/>
  </noscript>
<? endif; ?>
