<?
    $query = (! is_null($params)) ? $params->getQuery() : null;
    $allGroupsOperator = (! is_null($query)) ? $query->getOperator() : 'AND';
    $groups = -1;
?>
  <div id="collapseAdvancedSearch" class="panel-collapse collapse in advanced-search-panel<?=(isset($hiddenAdvancedSearch)) ? ' hidden' : ''?>" role="tabpanel" aria-labelledby="headingAdvancedSearch">
    <div class="panel-body">
  	  <div class="searchForm">

        <div class='row'>
          <div class='col-md-12 scrollable-search-panel-options'>
            <?= $this->help()->getQuestionMarkHelp('advanced-search') ?>
    	    <a href="#" class='search-type-template-switch'><?=$this->translate("Basic Search")?></a>
    	    <? if($this->searchResults): ?>
              <span class="save-advanced-search-results">
              <? if (($account = $this->auth()->getManager()) && $account->loginEnabled() && $account->isLoggedIn()): // hide save option if login disabled or not logged in ?>
                  <? if (is_numeric($this->results->getSearchId())): ?>
                      <? if ($this->results->isSavedSearch()): ?>
                          <a class="save-search-link" id='remove-from-saved-searches' data-search-id='<?=urlencode($this->results->getSearchId())?>' title='<?=$this->translate('Delete saved search')?>'>
                              <?=$this->translate('Delete saved search')?>
                          </a>
                      <? else: ?>
                          <a class="save-search-link" id='add-to-saved-searches' data-search-id='<?=urlencode($this->results->getSearchId())?>' title='<?=$this->translate('Save search')?>'>
                              <i class="pr-web-downloadarrow"></i>
                              <span><?=$this->translate('Save search')?></span>
                          </a>
                      <? endif; ?>
                  <? endif; ?>
              <? endif; ?>
              </span>
         	<? endif; ?>
          </div>
        </div>

    	<div class='row' id='group-join-type-row'>
      	  <div class='col-md-12'>
            <select id='group-join-type' name="join" class="form-control">
              <option value="AND"<?= ($allGroupsOperator == 'AND') ? ' selected="selected"' : ''?>><?=$this->transEsc("group_AND")?></option>
              <option value="OR"<?= ($allGroupsOperator == 'OR') ? ' selected="selected"' : ''?>><?=$this->transEsc("group_OR")?></option>
            </select>
          </div>
        </div>

      </div>

      <form id='editable-advanced-search-form' name='searchForm'>
      <!-- If search consists of more than one search groups, foreach them -->

	  <? if(is_a($query, 'VuFindSearch\Query\QueryGroup')): ?>
        <? foreach ($query->getQueries() as $queryGroup): $groupOperator = $queryGroup->getOperator(); $groups++; $queries = -1;?>
        <div class='row group border' id='group_<?=$groups?>'>
          <a href="#" class="group-close hidden" title="<?=$this->transEsc("del_search")?>">&times;</a>

          <div class='col-md-3'>
            <label class='dropdown-select-label'>
              <select class="form-control group-operator dropdown-select" name='bool<?=$groups?>[]'>
                <option value="AND"<?= ($groupOperator == 'AND') ? ' selected="selected"' : ''?>><?=$this->transEsc("search_AND")?></option>
                <option value="OR"<?= ($groupOperator == 'OR') ? ' selected="selected"' : ''?>><?=$this->transEsc("search_OR")?></option>
                <option class='not-query' value="NOT"<?= ($groupOperator == 'NOT') ? ' selected="selected"' : ''?>><?=$this->transEsc("search_NOT")?></option>
              </select>
            </label>
          </div>

          <div class='col-md-9'>
            <? foreach ($queryGroup->getQueries() as $query): $queryHandler = $query->getHandler(); $queryString  = $query->getString(); $queries++;?>
            <div class='row queries' id='query_<?=$queries?>'>

              <div class='col-md-4 text-right'>
                <select class='form-control query-type' name='type<?=$groups?>[]'>
                  <? foreach ($options->getAdvancedHandlers() as $value => $description): ?>
                  <option value="<?=$this->escapeHtml($value)?>"<?= ($value == $queryHandler) ? ' selected="selected"' : ''?>>
                    <?=$this->transEsc($description)?>
                  </option>
                  <? endforeach; ?>
                </select>
              </div>

              <div class='col-md-7'>
                <input name='lookfor<?=$groups?>[]' type='text' class='form-control query-string' value='<?=$queryString != "FT Y OR FT N" ? $this->escapeHtmlAttr($queryString) : ''?>' placeholder='<?=$this->translate('enter-search-query')?>'>
              </div>

              <div class="col-md-1">
                <a href="#" class='close remove-advanced-search-query'>&times;</a>
              </div>

            </div>
            <? endforeach; ?>

            <p>
              <a href="#" class="add-search-query">
                <i class="pr-interface-plusadd"></i> <?=$this->transEsc("add_search")?>
              </a>
            </p>
          </div>

          <div class="col-md-1 close">
            <a class="help-block remove-advanced-search-group" href="#">&times;</a>
          </div>
        </div>
        <? endforeach; ?>

      <!-- If search consists of one search group -->
      <? elseif(is_a($query, 'VuFindSearch\Query\Query')): $groupOperator = 'AND'; $groups++; $queries = -1;?>

		<div class='row group' id='group_<?=$groups?>'>
          <a href="#" class="group-close hidden" title="<?=$this->transEsc("del_search")?>">&times;</a>

          <div class='col-md-3'>
            <label class='dropdown-select-label'>
              <select class="form-control group-operator dropdown-select" name='bool<?=$groups?>[]'>
                <option value="AND"<?= ($groupOperator == 'AND') ? ' selected="selected"' : ''?>><?=$this->transEsc("search_AND")?></option>
                <option value="OR"<?= ($groupOperator == 'OR') ? ' selected="selected"' : ''?>><?=$this->transEsc("search_OR")?></option>
                <option hidden class='not-query' value="NOT"<?= ($groupOperator == 'NOT') ? ' selected="selected"' : ''?>><?=$this->transEsc("search_NOT")?></option>
              </select>
            </label>
          </div>
          <div class='col-md-9'>
            <? $queryHandler = $query->getHandler(); $queryString  = $query->getString(); $queries++;?>
            <div class='row queries' id='query_<?=$queries?>'>

              <div class='col-md-4 text-right'>
                <select class='form-control query-type' name='type<?=$groups?>[]'>
                  <? foreach ($options->getAdvancedHandlers() as $value => $description): ?>
                  <option value="<?=$this->escapeHtml($value)?>"<?= ($value == $queryHandler) ? ' selected="selected"' : ''?>>
                    <?=$this->transEsc($description)?>
                  </option>
                  <? endforeach; ?>
                </select>
              </div>

              <div class='col-md-7'>
                <input name='lookfor<?=$groups?>[]' type='text' class='form-control query-string' value='<?=$queryString != "FT Y OR FT N" ? $this->escapeHtmlAttr($queryString) : ''?>' placeholder='<?=$this->translate('enter-search-query')?>'>
              </div>

              <div class="col-md-1">
                <a href="#" class='close remove-advanced-search-query'>&times;</a>
              </div>

            </div>

            <p>
              <a href="#" class="add-search-query">
                <i class="pr-interface-plusadd"></i> <?=$this->transEsc("add_search")?>
              </a>
            </p>
          </div>

          <div class="col-md-1 close">
            <a class="help-block remove-advanced-search-group" href="#">&times;</a>
          </div>
        </div>

      <? else: ?>
      	<? throw new \Exception('Unhandled Query object'); ?>
      <? endif; ?>

        <p>
          <a href="#" class="add-search-group">
            <i class="pr-interface-plusadd"></i> <?=$this->transEsc('add_search_group')?>
          </a>
        </p>

        <div class='row'>
          <div class='col-sm-12 text-right'>
            <input class="btn btn-primary pull-right flip advanced-find-button" value="<?=$this->translate('Update results')?>" id='submit-edited-advanced-search' type='submit'>
            <a href='#' class="btn btn-link" id='clearAdvancedSearchLink' title='<?= $this->transEsc('Clear')?>'>
              <?= $this->transEsc('Clear')?>
            </a>
          </div>
        </div>

      </form>
    </div>
  </div>