<? $this->headScript()->appendFile('parts/errors/404.js'); ?>
<div class='not-found-container'>
  <div class='left-page'>
    <h1><?=$this->transEsc('Page not found')?></h1>

    <p class='page-number'>403</p>
  </div>

  <div class='right-page'>
    <h2><?=$this->transEsc('You have probably clicked on invalid link or entered defunct URL')?></h2>
    <h3><?=$this->translate('Return to homepage', ['%s1' => '<a href="/" title="Knihovny.cz">', '%s2' => '</a>'])?></h3>

    <p class='page-number'>406</p>
  </div>
</div>
