<script>
  dataLayer.push({
    'page': {
      'category': 'error'
    }
  });
</script>
<div style="background-image: url(/themes/bootstrap3/images//mzk-open-book-01.png); background-repeat: no-repeat; width: 800px; height: 560px; margin: auto;">
  <div style="float: left; position:relative; padding-left: 60px; height: 500px; padding-top: 20px; width: 380px;">
    <h1><?=$this->transEsc('Page not found')?></h1>
    <p style="position:absolute; bottom:0px; padding-left: 140px;">403</p>
  </div>
  <div style="position:relative; padding-left: 410px; padding-top: 30px; width: 740px; height: 500px;">
    <h2><?=$this->transEsc('You have probably clicked on invalid link or entered defunct URL')?></h2>
    <? $hrefTags = array(
         '%s1' => '<a href="/">',
         '%s2' => '</a>'
       );
    ?>
    <h3><?=$this->translate('Return to homepage', $hrefTags)?></h3>
    <p style="position:absolute; bottom:0px; padding-left: 160px;">406</p>
  </div>
</div>
