<html>
  <head>
  	<meta charset='UTF-8'>
  	<title>Knihovny.cz</title>
  	<style>
  	 .error-body {
  	     background-color: #f6f6f6;
         color: #333;
         font-family: 'Lato', sans-serif;
         font-size: 15px;
         line-height: 1.42857;
         text-align: center;
  	 }
  	 .error-h2 {
  	     color: #e5004b;
  	 }
  	 .error-well {
  	     background-color: #fff;
  	     padding: 5px;
  	     margin: 50px auto;

  	 }
  	</style>
  	<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
      <!-- Google Tag Manager -->
      <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
              new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
              j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
              'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
          })(window,document,'script','dataLayer','GTM-TXJ544');</script>
      <!-- End Google Tag Manager -->

  </head>
  <body class='error-body'>
  <!-- Google Tag Manager (noscript) -->
  <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TXJ544"
                    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
  <!-- End Google Tag Manager (noscript) -->
  <script>
      dataLayer.push({
          'page': {
              'category': 'error'
          }
      });
  </script>
    <div class='error-well'>
        <h2 class='error-h2'>Došlo k chybě - zkuste, prosím, zopakovat svůj požadavek později.<br> Omlouváme se za nepohodlí.</h2>
        <p>V případě přetrvávajících problémů se na nás můžete obrátit prostřednictvím <a href="/Portal/Feedback#bugreport">formuláře zpětné vazby</a> nebo emailem na <a href='mailto:cpk-support@mzk.cz'>cpk-support@mzk.cz.</a></p>
        <h3>Zpět na <a href="/Search/Home">Hlavní stránku</a></h3>
    </div>

	<div class='error-well'>
    	<h2 class='error-h2'>An error has occured - please try your request again later.<br> Sorry for the inconvenience.</h2>
        <p>In case of persistent problems, you can contact us via the <a href="/Portal/Feedback#bugreport">feedback form</a> or email <a href='mailto:cpk-support@mzk.cz'>cpk-support@mzk.cz.</a></p>
        <h3>Back to <a href="/Search/Home">Main page</a></h3>
    </div>
  </body>
</html>