<?
  // Set page title.
  $this->headTitle($this->translate('translations_approval'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/">' . $this->transEsc('Main page') . '</a></li> ' .
      '<li class="active"><a href="/Admin/TranslationsApproval">'.$this->transEsc('translations_approval').'</a></li> ';
  $this->layout()->title = $this->translate('translations_approval');

  $this->layout()->templateName = 'translations/approval';
?>
<div class="row clearfix">
  <ul class="breadcrumb hidden-print"><?=$this->layout()->breadcrumbs ?></ul>

  <div class="col-sm-3">
    <?=$this->render("admin/menu.phtml")?>
  </div>
  <div class="col-sm-9 well" ng-controller='TranslationsController as transCtrl'>
    <h2><?=$this->transEsc('translations_approval')?></h2>
    <?=$this->flashmessages() ?>
    <? $hasRequests = count($translations);
        if (! $hasRequests): ?>
        <div class='well'>
          <?=$this->transEsc('approve_no_requests') ?>
        </div>
        <? else: foreach ($translations as $source => $sourceTranslations):

            unset ($sourceTranslations['hasRequested']);

            $this->newTransFormId = $source . '_newTrans';
            $this->source = $source;
            $this->sourceTranslations = $sourceTranslations;
            ?>
        <div class='well'>
        <form action='/Admin/TranslationsApproval' method='POST' data-source="<?=$source?>">
        <?=$this->render('admin/translations/table.phtml') ?>
        <div class="btn-group">
          <input class="btn btn-primary" name="approved" type="submit" value="<?=$this->transEsc('approve_translations_change') ?>" ng-click="transCtrl.submit()" ng-submit-btn/>
          <input class="btn btn-primary" name="denied" type="submit" value="<?=$this->transEsc('deny_translations_change') ?>" formnovalidate/>
        </div>
        <input type='hidden' name='source' value='<?=$source ?>'/>
        </form>
      	<form action="#<?=$source?>" id="<?=$this->newTransFormId?>"></form>
      </div>
      <? endforeach; endif; ?>
      <form action='#' id='dummy'><input type='submit' hidden='hidden'/></form>
  </div>
</div>