<?
  // Set page title.
  $this->headTitle($this->translate('translations'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/">' . $this->transEsc('Main page') . '</a></li> ' .
      '<li class="active"><a href="/Admin/Translations">'.$this->transEsc('translations').'</a></li> ';
  $this->layout()->title = $this->translate('translations');

  $this->layout()->templateName = 'translations/main';

  // Add translations for the javascript
  $this->jsTranslations()->addStrings([
      'remove_translation' => $this->translate('remove_translation'),
      'new_translation_key_already_used' => $this->translate('new_translation_key_already_used'),
      'confirm_translation_delete_of' => $this->translate('confirm_translation_delete_of'),
      'add_translation' => $this->translate('add_translation')
  ]);
?>
<div class="row clearfix">
  <ul class="breadcrumb hidden-print"><?=$this->layout()->breadcrumbs ?></ul>

  <div class="col-sm-3">
    <?=$this->render("admin/menu.phtml")?>
  </div>
  <div class="col-sm-9 well" ng-controller='TranslationsController as transCtrl'>
    <h2><?=$this->transEsc('translations')?></h2>
    <?=$this->flashmessages() ?>
    <? foreach($sourcesBeingAdmin as $source):

        if (isset($translations[$source])) {

            $this->hasRequested = $translations[$source]['hasRequested'];
            unset($translations[$source]['hasRequested']);

            $this->sourceTranslations = $translations[$source];
        } else {
            $this->hasRequested = false;
            $this->sourceTranslations = [];
        }

        $this->source = $source;
        $this->newTransFormId = $source . '_newTrans';
    ?>
      <div class='well'>
        <form action='/Admin/Translations' method='POST' data-source="<?=$source?>">
        <?=$this->render('admin/translations/table.phtml') ?>
        <div class="btn-group">
          <input class="btn btn-primary" name="requestChange" type="submit" value="<?=$this->transEsc('submit_changes') ?>" ng-click="transCtrl.submit()" ng-submit-btn/>
          <? if ($this->hasRequested): ?>
            <input class="btn btn-primary" name="requestChangeCancel" type="submit" value="<?=$this->transEsc('request_translations_change_cancel') ?>" formnovalidate/>
          <? endif; ?>
        </div>
        <input type='hidden' name='source' value='<?=$source ?>'/>
        </form>
      	<form action="#<?=$source?>" id="<?=$this->newTransFormId?>"></form>
      </div>
      <? endforeach; ?>
  </div>
</div>