<?  // Add translations for the javascript
  $this->jsTranslations()->addStrings([
      'remove_translation' => $this->translate('remove_translation'),
      'new_translation_key_already_used' => $this->translate('new_translation_key_already_used'),
      'confirm_translation_delete_of' => $this->translate('confirm_translation_delete_of'),
      'add_translation' => $this->translate('add_translation'),
      'empty_value_not_allowed' => $this->translate('empty_value_not_allowed'),
      'whitespaces_not_allowed' => $this->translate('whitespaces_not_allowed')
  ]);
  ?>
<table class="table">
  <thead>
    <tr><th id="<?=$source?>" class="blickable" colspan="4"><h3><?=$this->transEsc('source_' . $source)?><img class="pull-right" src="<?=$this->logos()->getLogo($source) ?>" height="32"></h3></th></tr>
    <? if (isset($hasRequested) && $hasRequested): ?>
      <tr><th colspan="4"><div class="alert alert-warning"><?=$this->transEsc('request_translations_change_pending') ?></div></th></tr>
    <? endif; ?>
    <tr>
      <th class="col-xs-3"><?=$this->transEsc('translation_key')?></th>
      <? foreach($supportedLanguages as $lang):?>
        <th class="col-xs-4"><?=$this->transEsc('translation_' . $lang)?></th>
      <? endforeach; ?>
      <th class="col-xs-1"><?=$this->transEsc('add_remove')?></th>
    </tr>
  </thead>
  <tbody>
  <tr ng-repeat="newTranslation in transCtrl.newTranslations['<?=$source?>']" ng-new-translation-template='<?=$source?>'>
  <? foreach($sourceTranslations as $key => $languageTranslations): ?>
    <tr>
    <? if (isset($languageTranslations['deleted'])): ?>
      <td class="col-xs-3"><del style="color: gray"><?=$key ?></del></td>
      <? foreach($supportedLanguages as $lang):?>
        <td class="col-xs-4"><del style="color: gray"><?=$languageTranslations['deleted'][$lang]?></del></td>
      <? endforeach; ?>
		<td class="col-xs-1">
			<a class="btn btn-link" href="#<?=$source?>" ng-click="transCtrl.addTranslation('<?=htmlspecialchars($languageTranslations['deleted']['JSON'])?>',$event,'json')">
			<i class="pr-interface-plusadd"></i> <?=$this->transEsc('add_translation')?></a>
		</td>
    <? else: ?>
      <td class="col-xs-3" ng-dblclick="transCtrl.editTranslation($event, 'key')">
        <div><?=$key ?></div>
        <input class="hidden" type="text" name="<?=$source . '[' . $key . ']'?>" form="dummy" required="required"
        	value="<?=$key ?>"
        	ng-keydown="transCtrl.oldTranslationKeyDown($event, 'key')"
        	ng-blur="transCtrl.oldTranslationBlurred($event, 'key')"/>
      </td>
      <? foreach($supportedLanguages as $lang):?>
        <td ng-dblclick="transCtrl.editTranslation($event)" class="col-xs-4">
          <div>
          <? if (isset($languageTranslations[$lang]['diff'])):
               $currentValue = $languageTranslations[$lang]['diff']['new'];?>
            <? if (isset($languageTranslations[$lang]['diff']['old'])): ?>
              <del style="color: red"><?=$languageTranslations[$lang]['diff']['old'] ?></del>
              <br>
            <? endif; ?>
            <ins style="color: green"><?=$languageTranslations[$lang]['diff']['new'] ?></ins>
          <? else:
            $currentValue = $languageTranslations[$lang];?>
            <?=$languageTranslations[$lang]?>
          <? endif; ?>
          </div>
        <input class="hidden" type="text" name="<?=$key . '[' . $lang . ']' ?>" required="required"
        	value="<?=$currentValue ?>"
        	ng-keydown="transCtrl.oldTranslationKeyDown($event)"
        	ng-blur="transCtrl.oldTranslationBlurred($event)"/>
        </td>
      <? endforeach; ?>
      <td class="col-xs-1">
        <a class="btn btn-link" href="#<?=$source?>" ng-click="transCtrl.removeTranslation('<?=$source?>',$event)">
        <i class="fa fa-trash-o"></i> <?=$this->transEsc('remove_translation') ?></a>
      </td>
    <? endif; // End of deleted ?>
    </tr>
  <? endforeach; ?>
  <tr ng-repeat="(translationKey, deletedTranslation) in transCtrl.deletedTranslations['<?=$source?>']" ng-deleted-translation-template>
  <tr>
  	<td class="col-xs-3">
  		<input form="<?=$newTransFormId?>" class="form-control" type="text"
  			value="" name="" ng-new-translation="key" required
  			placeholder="<?=$this->transEsc('translation_key') ?>"
  			title="<?=$this->transEsc('translation_key') ?>"/>
  	</td>
		<td class="col-xs-4">
			<input form="<?=$newTransFormId?>" class="form-control" type="text"
				value="" name="" ng-new-translation="cs" required
				placeholder="<?=$this->transEsc('translation_cs') ?>"
				title="<?=$this->transEsc('translation_cs') ?>"/>
		</td>
		<td class="col-xs-4">
			<input form="<?=$newTransFormId?>" class="form-control" type="text"
				value="" name="" ng-new-translation="en" required
				placeholder="<?=$this->transEsc('translation_en') ?>"
				title="<?=$this->transEsc('translation_en') ?>"/>
		</td>
		<td class="col-xs-1">
			<a class="btn btn-link" href="#<?=$source?>" ng-click="transCtrl.addTranslation('<?=$source?>',$event)">
			<i class="pr-interface-plusadd"></i> <?=$this->transEsc('add_translation')?></a>
			<input form="<?=$newTransFormId?>" type="submit" value="" class="hidden" ng-new-translation="submit" ng-click="transCtrl.addTranslation('<?=$source?>',$event)">
		</td>
  </tr>
  </tbody>
</table>