<?
  $this->layout()->librariesUrl = "/Search/Results/?lookfor0[]=&amp;type0[]=Libraries&amp;bool0[]=AND&amp;"
                                 ."filter=&amp;daterange=&amp;publishDatefrom=&amp;publishDateto=&amp;limit=10&amp;"
                                 ."sort=relevance&amp;page=1&amp;searchTypeTemplate=basic&amp;"
                                 ."keepFacetsEnabled=true&amp;join=AND";
?>
<div class="navbar-header">
  <? if (!$this->themeConfiguration()->themeConfig['logo_image']): ?>
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#header-collapse">
      <span class="sr-only">Toggle navigation</span>
      <i class="fa fa-bars"></i>
    </button>
    <a class="navbar-brand lang-<?= $this->layout()->userLang ?>"
       href="<?= $this->themeConfiguration()->themeConfig['logo_href'] ?>"
       title="<?= $this->translate('logo_title') ?>">
      <img class="knihovny-logo" src="<?=$this->imageLink('logo-knihovny.cz-'. $this->layout()->userLang .'.svg') ?>" alt="<?= $this->translate('logo_alt') ?>">
    </a>
  <? else: ?>
    <a href="<?= $this->themeConfiguration()->themeConfig['logo_href'] ?>" title="<?= $this->translate('logo_title') ?>">
      <img src="<?=$this->imageLink($this->themeConfiguration()->themeConfig['logo_image']) ?>"
           alt="<?= $this->translate('logo_alt') ?>">
    </a>
  <? endif; ?>
</div>

<? if (!isset($this->layout()->renderingError)): ?>
  <div class="collapse navbar-collapse" id="header-collapse">

    <!--navigation-->
    <ul class="nav navbar-nav">
      <? if (!$this->themeConfiguration()->themeConfig['hide_catalog']): ?>
        <li id="catalogSearchLink"
            class="<?= ! in_array($this->layout()->headerType, ['newlibraries', 'inspiration']) ? 'active' : '' ?>">
          <a href="<?= $this->url('home') ?>" title='<?= $this->transEsc('Catalog') ?>'>
              <?= $this->translate('Catalog') ?>
            <span class="sr-only">(current)</span>
          </a>
        </li>
      <? endif; ?>

      <? if (! $this->themeConfiguration()->themeConfig['hide_inspirations']): ?>
        <li class="<?= $this->layout()->headerType == 'inspiration' ? 'active' : '' ?>">
          <a href="/Search/Inspiration" title="<?= $this->translate('Inspiration') ?>">
            <?= $this->translate('Inspiration') ?>
          </a>
        </li>
      <? endif; ?>

      <? if (! $this->themeConfiguration()->themeConfig['hide_library_search']): ?>
        <li class="<?= $this->layout()->headerType == 'newlibraries' ? 'active' : '' ?>" id="librariesSearchLink">
          <a href="<?= $this->layout()->librariesUrl ?>">
            <?= $this->help()->getElementHelp('element_help_header_libraries', $this->translate('List of libraries')) ?>
          </a>
        </li>
      <? endif; ?>
    </ul>
    <nav>
      <ul class="nav navbar-nav navbar-right flip">
        <? if ($this->feedback()->tabEnabled()): ?>
          <li>
            <a id="feedbackLink"
               class="modal-link"
               href="<?= $this->url('feedback-home') ?>"
               title="<?= $this->transEsc("Feedback") ?>">
                <i class="fa fa-envelope"></i>
                <?= $this->transEsc("Feedback") ?>
            </a>
          </li>
        <? endif; ?>
          <? if ($this->cart()->isActive()): ?>
            <li id="cartSummary">
              <a id="cartItems"
                 class="modal-link"
                 title="<?= $this->transEsc('View Book Bag') ?>"
                 href="<?= $this->url('cart-home') ?>">
                  <i class="fa fa-suitcase"></i>
                  <strong><?= count($this->cart()->getItems()) ?></strong>
                  <?= $this->transEsc('items') ?>
                  <?= $this->cart()->isFull() ? ' (' . $this->transEsc('bookbag_full') . ')' : '' ?>
              </a>
            </li>
          <? endif; ?>

          <? if ($notificationsEnabled): ?>
            <? if ($user): ?>
              <?= $this->render('notifications.phtml', ['user' => $user, 'libraryCards' => $libraryCards]) ?>
            <? endif; ?>
          <? endif; ?>

          <? if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
            <? if ($user): ?>
              <!--dropdown menu if authorized-->
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <?= $user->firstname || $user->lastname
                      ? $user->firstname . ' ' . $user->lastname
                      : $this->transEsc("Your Account") ?>
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li class="myAccountOptions">
                    <a href="<?= $this->url('myresearch-home', [], ['query' => ['redirect' => 0]]) ?>"
                       class="modal-link"
                       title="<?= $this->transEsc("Your Account") ?>">
                        <i class="fa fa-home"></i>
                        <?= $this->transEsc("Your Account") ?>
                    </a>
                  </li>
                  <li class="myAccountOptions">
                    <a href="<?= $this->url('myresearch-favorites') ?>"
                       class="modal-link"
                       title="<?= $this->transEsc('Your Favorites') ?>">
                        <i class="icon-oblibene"></i>
                        <?= $this->transEsc('Your Favorites') ?>
                    </a>
                  </li>
                  <li>
                    <a href="<?= $this->url('search-history') ?>" title="<?= $this->transEsc('Search History') ?>">
                      <i class='pr-interface-arrowleft3'></i>
                      <?= $this->transEsc('Search History') ?>
                    </a>
                  </li>
                  <li role="separator" class="divider"></li>
                  <li id="logoutOptions">
                    <a href="<?= $this->url('myresearch-logout') ?>"
                       class="modal-link"
                       title="<?= $this->transEsc("Log Out") ?>">
                      <i class="pr-interface-logoutexit"></i>
                      <?= $this->transEsc("Log Out") ?>
                    </a>
                  </li>
                </ul>
              </li> <!--/dropdown menu-->
            <? endif ?>
          <? endif; ?>

          <? if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
            <li class="dropdown">
              <form method="post" name="themeForm" id="themeForm">
                <input type="hidden" name="ui">
              </form>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="<?= $this->transEsc("Theme") ?>">
                <?= $this->transEsc("Theme") ?>
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <? foreach ($this->layout()->themeOptions as $current): ?>
                  <li class="<?= $current['selected'] ?: 'active' ?>">
                    <a href="#"
                       title="<?= $this->transEsc($current['desc']) ?>"
                       onclick="
                          document.themeForm.ui.value='<?= $this->escapeHtmlAttr($current['name']) ?>';
                          document.themeForm.submit()">
                      <?= $this->transEsc($current['desc']) ?>
                    </a>
                  </li>
                <? endforeach; ?>
              </ul>
            </li>
          <? endif; ?>

          <? if (is_object($account) && $account->loginEnabled() && ! $user): // hide login/logout if unavailable ?>
            <li class="loginOptions">
              <div id="login-button" data-toggle="modal" data-target="#loginModal">
                <?= $this->render('Auth/Shibboleth/login.phtml') ?>
              </div>
              <div id='login-help'>
                <?= $this->help()->getQuestionMarkHelp('login') ?>
              </div>
            </li>
          <? endif; ?>

          <? if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
            <form method="post" name="langForm" id="langForm" class="pull-left">
                <input type="hidden" name="mylang">
            </form>

            <? if (!$this->themeConfiguration()->themeConfig['hide_switch_language']): ?>
              <? foreach ($this->layout()->allLangs as $langCode => $langName): ?>
                <? if ($this->layout()->userLang != $langCode): ?>
                  <li class="<?= $this->layout()->userLang == $langCode ? 'active' : '' ?>">
                    <a href="#"
                       data-lang="<?= $langCode ?>"
                       class="change-language"
                       title="<?= $this->displayLanguageOption($langName) ?>">
                      <?= $this->displayLanguageOption($langName) ?>
                    </a>
                  </li>
                <? endif; ?>
              <? endforeach; ?>
            <? endif; ?>
          <? endif; ?>
      </ul>
    </nav>
  </div>
<? endif; ?>
