<? $list = $this->params->getSortList(); if (!empty($list)): ?>
  <form class="form-inline" style="margin:0" action="<?=$this->currentPath() . $this->results->getUrlQuery()->setSort(null)?>" method="post" name="sort">
    <label for="sort_options_1" class="resultsSortOptions"><?=$this->transEsc('Sort')?></label>
    <select id="sort_options_1" name="sort" class="jumpMenu resultsSortOptions" onChange="document.sort.submit()">
      <? foreach ($list as $sortType => $sortData): ?>
        <option value="<?=$this->escapeHtml($sortType)?>"<?=$sortData['selected']?' selected="selected"':''?>><?=$this->transEsc($sortData['desc'])?></option>
      <? endforeach; ?>
    </select>
    <noscript><input type="submit" class="btn" value="<?=$this->transEsc("Set")?>" /></noscript>
  </form>
<? endif; ?>
