<?
  // Set page title.
  $this->headTitle($this->translate('Advanced Search'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/">' . $this->transEsc('Main page') . '</a></li> '.
  '<li>';
  $lastSearchLink = $this->getLastSearchLink($this->transEsc('Search'));
  $this->layout()->breadcrumbs .= !empty($lastSearchLink)
    ? $lastSearchLink : $this->transEsc('Search');
  $this->layout()->breadcrumbs .= '</li> <li class="active">' . $this->transEsc('Advanced') . '</li>';

  // Set up saved search details:
  if (isset($this->saved) && is_object($this->saved)) {
    $searchDetails = $this->saved->getParams()->getQuery();
    if ($searchDetails instanceof \VuFindSearch\Query\Query) {
        // Not an advanced query -- ignore it.
        $searchDetails = $groups = false;
    } else {
        $groups = $searchDetails->getQueries();
    }
    $hasDefaultsApplied = $this->saved->getParams()->hasDefaultsApplied();
    $searchFilters = $this->saved->getParams()->getFilterList();
  } else {
    $hasDefaultsApplied = $searchDetails = $searchFilters = $groups = false;
  }

  // Step 1: Load the javascript
  $this->headScript()->appendFile(
    isset($this->advancedSearchJsOverride) ? $this->advancedSearchJsOverride : 'advanced_search.js'
  );
  // Step 2: Build the page
  $this->headScript()->appendScript(
    $this->partial(
      isset($this->buildPageOverride) ? $this->buildPageOverride : 'search/advanced/build_page.phtml',
      ['options' => $this->options, 'searchDetails' => $searchDetails]
    )
  );

  // Collect previous search queries
  $setSearchGroups = [];
  $setGroupCount = 0;
  $setQueries = [];
  if (isset($searchDetails) && is_object($searchDetails)) {
    foreach ($searchDetails->getQueries() as $group=>$searchGroup) {
      $setSearchGroups[$group] = $searchGroup->isNegated() ? 'NOT' : $searchGroup->getOperator();
      if ($setGroupCount < $group) {
        $setGroupCount = $group;
      }
      if (!isset($setQueries[$group])) {
        $setQueries[$group] = [];
      }
      foreach ($searchGroup->getQueries() as $search) {
        $setQueries[$group][] = $search;
      }
    }
  }
?>
<?=$this->flashmessages()?>
<ul class="breadcrumb hidden-print"><?=$this->layout()->breadcrumbs ?></ul>
<div role="search">
  <form name="searchForm" id="advSearchForm" method="get" action="<?=$this->url($this->options->getSearchAction())?>">
    <div class="row">
      <div class="col-sm-12">
        <input type="hidden" name="sort" value="relevance">
        <div class="clearfix">
          <div class='row'>
          	<div class='col-sm-9 pull-left'>
          	  <div class='row'>
          	    <div class='col-sm-6 pull-left'>
                  <h2 class="flip"><?=$this->transEsc('Find')?></h2>
                </div>
                <div class='col-sm-6 pull-right'>
                  <div id="groupJoin" class="form-inline pull-right flip">
                    <label for="groupJoinOptions"><?=$this->transEsc("search_match")?>:</label>
                    <select id="groupJoinOptions" name="join" class="form-control">
                      <option value="AND"<? if($searchDetails && $searchDetails->getOperator()=='ALL'):?> selected<?endif?>><?= $this->transEsc('group_AND') ?></option>
                      <option value="OR"<? if($searchDetails && $searchDetails->getOperator()=='OR'):?> selected<?endif?>><?= $this->transEsc('group_OR') ?></option>
                    </select>
                  </div>
                </div>
              </div>
            </div>
            <div class='col-sm-3 pull-right'>
              <h2 class="flip"><?=$this->transEsc('Help')?></h2>
            </div>
          </div>
        </div>
        <div class='row'>
            <div class='col-sm-9 pull-left'>
                <? /* An empty div. This is the target for the javascript that builds this screen */ ?>
                <span id="groupPlaceHolder" class="hidden">
                  <a href="#" onClick="addGroup()"><i class="fa fa-plus-circle"></i> <?= $this->transEsc('add_search_group') ?></a>
                </span>
            	<? /* fallback to a fixed set of search groups/fields if JavaScript is turned off */ ?>
            	<div class="no-js">
        
                  <? if(!empty($this->formOverride)): ?>
                    <?=$this->formOverride ?>
                  <? else: ?>
          
                	  <? for ($group=0; (($group<1) || ($group<=$setGroupCount)); $group++): ?>
                
                      <? if($group == 0): ?>
                        <div id="new_group_template">
                      <? endif; ?>
                  	  <div id="group<?=$group ?>" class="row">
                        <div class='group col-sm-12'>
    
                          <a href="#" class="group-close hidden" title="<?=$this->transEsc("del_search")?>">&times;</a>
    
                          <div class="row">
                            <div class="col-sm-2 match">
                              <select name="bool<?=$group ?>[]" id="search_bool<?=$group ?>" class="form-control">
                                <option value="AND"<? if(isset($setSearchGroups[$group]) && 'AND' == $setSearchGroups[$group]):?> selected<?endif;?>><?=$this->transEsc("search_AND")?></option>
                                <option value="OR"<? if(isset($setSearchGroups[$group]) && 'OR' == $setSearchGroups[$group]):?> selected<?endif;?>><?=$this->transEsc("search_OR")?></option>
                                <option value="NOT"<? if(isset($setSearchGroups[$group]) && 'NOT' == $setSearchGroups[$group]):?> selected<?endif;?>><?=$this->transEsc("search_NOT")?></option>
                              </select>
                              
                            </div>
                            <div class="col-sm-10">
                              <? for($search=0; (($search<1) || (isset($setQueries[$group]) && ($search<count($setQueries[$group])))); $search++): ?>
                                <? if($group == 0 && $search == 0): ?>
                                  <div id="new_search_template">
                                <? endif; ?>
                                <div id="search<?=$group.'_'.$search ?>" class="search">
                                  <div class="row">
                                    <div class="col-sm-4 middle">
                                      <select class="type form-control" name="type<?=$group ?>[]">
                                        <? foreach ($this->options->getAdvancedHandlers() as $searchVal => $searchDesc): ?>
                                          <option value="<?=$this->escapeHtml($searchVal)?>"<?if(isset($setQueries[$group][$search]) && $searchVal == $setQueries[$group][$search]->getHandler()):?> selected<?endif;?>><?=$this->transEsc($searchDesc)?></option>
                                        <? endforeach; ?>
                                      </select>
                                    </div>
                                    <div class="col-sm-7 left">
                                      <input name="lookfor<?=$group ?>[]" id="search_lookfor<?=$group.'_'.$search ?>" class="form-control" placeholder="<?=$this->translate('enter-search-query')?>" type="text"<?if(isset($setQueries[$group][$search])):?> value="<?=$this->escapeHtml($setQueries[$group][$search]->getString())?>"<?endif;?>>
                                    </div>
                                    <div class="col-sm-1 close hidden">
                                      <a class="help-block" href="#">&times;</a>
                                    </div>
                                  </div>
                                </div>
                                <? if($group == 0 && $search == 0): ?>
                                    </div>
                                  <i class="search_place_holder hidden"></i>
                                  <a href="#" class="add_search_link hidden"><i class="fa fa-plus-circle"></i> <?=$this->transEsc("add_search")?></a>
                                <? endif; ?>
                              <? endfor; ?>
                            </div>
                          </div>
                        </div>
                      </div>
    
                      <? if($group == 0): ?>
                        </div>
                      <? endif; ?>
                      <? endfor; ?>
                  <? endif; ?>
          
          
                </div>
            </div>
          
            <div class="col-sm-3 pull-right">
                <? if ($hasDefaultsApplied): ?>
                  <input type="hidden" name="dfApplied" value="1" />
                <? endif ?>
                <? if (!empty($searchFilters)): ?>
                  <h4><?=$this->transEsc("adv_search_filters")?></h4>
                  <div class="list-group">
                    <label class="list-group-item checkbox">
                      <input type="checkbox" checked="checked" class="checkbox-select-all"/>
                      <?=$this->transEsc("adv_search_select_all")?>
                    </label>
                  </div>
                  <? foreach ($searchFilters as $field => $data): ?>
                    <div class="list-group">
                      <div class="list-group-item title"><?=$this->transEsc($field)?></div>
                      <? foreach ($data as $value): ?>
                        <label class="list-group-item checkbox"><input class="checkbox-select-item" type="checkbox" checked="checked" name="filter[]" value='<?=$this->escapeHtmlAttr($value['field'])?>:"<?=$this->escapeHtmlAttr($value['value'])?>"' /> <?=$this->escapeHtml($value['displayText'])?></label>
                      <? endforeach; ?>
                    </div>
                  <? endforeach; ?>
                <? endif; ?>
                <div class="sidegroup">
                  <div class="list-group">
                    <div class="list-group-item" style='padding: 10px 10px 5px 10px;'><i class='fa fa-info'></i> <a class="help-link" href="<?=$this->url('help-home')?>?topic=advsearch" title="<?=$this->transEsc('Help with Advanced Search')?>"><?=$this->transEsc("Help with Advanced Search")?></a></div>
                    <div class="list-group-item" style='padding: 5px 10px 10px 10px;'><i class='fa fa-info'></i> <a class="help-link" href="<?=$this->url('help-home')?>?topic=search" title="<?=$this->transEsc('Help with Search Operators')?>"><?=$this->transEsc("Help with Search Operators")?></a></div>
                  </div>
                </div>
            </div>
		</div>
      </div>

      <? if (isset($this->extraAdvancedControls)): ?>
          <?=$this->extraAdvancedControls ?>
          <br>
          <div class="clearfix">
            <input class="btn btn-lg btn-default clear-btn" type="button" value="<?= $this->transEsc('Clear')?>">
            <input class="btn btn-lg btn-primary pull-right flip" type="submit" value="<?= $this->transEsc('Find')?>">
          </div>
          <br>
        <? endif; ?>
    </div>

</div>
  </form>
</div>
