<? if (isset($this->ranges) && !empty($this->ranges)): ?>
  <? $params = $this->searchParams($this->searchClassId); $params->activateAllFacets(); ?>
  <? foreach ($this->ranges as $current): $escField = $this->escapeHtmlAttr($current['field']); ?>
    <? $extraInputAttribs = ($current['type'] == 'date') ? 'maxlength="4" ' : ''; ?>
    <div class="col-sm-12">
      <legend><?=$this->transEsc($params->getFacetLabel($current['field']))?></legend>
      <input type="hidden" name="<?=$this->escapeHtmlAttr($current['type'])?>range[]" value="<?=$escField?>"/>
      <div class="row">
        <div class="col-sm-2">
          <input type="number" name="<?=$escField?>from" id="<?=$escField?>from" value="<?=isset($current['values'][0])?$this->escapeHtmlAttr($current['values'][0]):''?>" class="form-control" <?=$extraInputAttribs?> placeholder='<?=$this->transEsc('date_from')?>'/>
        </div>
        <div class="col-sm-2">
          <input type="number" name="<?=$escField?>to" id="<?=$escField?>to" value="<?=isset($current['values'][1])?$this->escapeHtmlAttr($current['values'][1]):''?>" class="form-control" <?=$extraInputAttribs?>  placeholder='<?=$this->transEsc('date_to')?>'/>
        </div>
      </div>
      </div>
  <? endforeach; ?>
<? endif; ?>
