<? if (!empty($this->facetList) || !empty($this->checkboxFacets)): ?>
  <div class="row">
    <fieldset class="col-sm-12">
      <legend><?=$this->transEsc('Limit To')?></legend>
      <? if (!empty($this->checkboxFacets)): ?>
        <?=$this->render('search/advanced/checkbox-filters.phtml')?>
      <? endif; ?>
      <div class="row">
        <? foreach ($this->facetList as $field => $list): ?>
          <div class="col-sm-<?=floor(12/count($this->facetList)) ?>">
          <label for="limit_<?=$this->escapeHtmlAttr(str_replace(' ', '', $field))?>"><?=$this->transEsc($list['label'])?>:</label>
          <?
            $selectId = 'limit_' . $this->escapeHtmlAttr(str_replace(' ', '', $field));
            $onClick = "$('#" . $selectId . "').val('');";
          ?>  
	      <select class="col-sm-12 form-control" id="<?=$selectId?>" name="filter[]" multiple="multiple" size="10">
            <? if (is_array($this->hierarchicalFacets) && in_array($field, $this->hierarchicalFacets)): ?>
                <? foreach ($list['list'] as $value): ?>
                  <? $display = str_pad('', 4 * $value['level'] * 6, '&nbsp;', STR_PAD_LEFT) . $this->escapeHtml($value['displayText']); ?>
                  <option value="<?=$this->escapeHtmlAttr(($value['operator'] == 'OR' ? '~' : '') . $field . ':"' . $value['value'] . '"')?>"<?=(isset($value['selected']) && $value['selected'])?' selected="selected"':''?>><?=$display?></option>
                <? endforeach; ?>
              	<? else: ?>
                    <?
                    // Sort the current facet list alphabetically; we'll use this data
                    // along with the foreach below to display facet options in the
                    // correct order.
                    $sorted = array();
                    foreach ($list['list'] as $i => $value) {
                      if (!empty($value['displayText'])) {
                        $sorted[$i] = $value['displayText'];
                      }
                    }
                    asort($sorted, SORT_LOCALE_STRING);
                    $top = isset($this->preferredFacets[$field])? $this->preferredFacets[$field] : array();
                    $priors = array();
                    foreach ($list['list'] as $i => $value) {
                      $key = $value['value'];
                      if (isset($top[$key])) {
                        $priors[$top[$key]] = $value;
                      }
                    }
                    ksort($priors);
                ?>
                <? foreach ($priors as $i => $value): ?>
                  <option value="<?=$this->escapeHtmlAttr(($value['operator'] == 'OR' ? '~' : '') . $field . ':"' . $value['value'] . '"')?>"<?=(isset($value['selected']) && $value['selected'])?' selected="selected"':''?>>
                    <?=$this->escapeHtml($value['displayText'])?>
                  </option>
                <? endforeach; ?>
                <? if (!empty($top) && count($priors) != count($sorted)):?>
                  <option disabled="disabled">=================</option>
                <? endif;?>
                <? foreach ($sorted as $i => $display): ?>
              <? $value = $list['list'][$i]; if (!isset($top[$value['value']])):?>
                <option value="<?=$this->escapeHtmlAttr(($value['operator'] == 'OR' ? '~' : '') . $field . ':"' . $value['value'] . '"')?>"<?=(isset($value['selected']) && $value['selected'])?' selected="selected"':''?>>
                  <?=$this->escapeHtml($display)?>
                </option>
              <? endif;?>
            <? endforeach; ?>
            <? endif; ?>
            
          </select>

          </div>
        <? endforeach; ?>
      </div>
    </fieldset>
  </div>
<? endif; ?>
<div class="row">
  <? if (isset($this->illustratedLimit)): ?>
    <fieldset class="col-sm-4">
      <legend><?=$this->transEsc("Illustrated")?>:</legend>
      <? foreach ($this->illustratedLimit as $current): ?>
        <input id="illustrated_<?=$this->escapeHtmlAttr($current['value'])?>" type="radio" name="illustration" value="<?=$this->escapeHtmlAttr($current['value'])?>"<?=$current['selected']?' checked="checked"':''?>/>
        <label for="illustrated_<?=$this->escapeHtmlAttr($current['value'])?>"><?=$this->transEsc($current['text'])?></label><br/>
      <? endforeach; ?>
    </fieldset>
  <? endif; ?>
  <br>
  <?=$this->render('search/advanced/limit.phtml')?>
  </div>
  <br>
  <div class='row'>
  <?=$this->render('search/advanced/ranges.phtml')?>
  <br>
</div>