<?
    $id = $this->driver->getUniqueID();
    $source = explode(".", $id)[0];
    $maxSubjectsInCore = $config['Record']['max_subjects_in_core'];
?>

<? if ($bibinfo = $this->record($this->driver)->getObalkyKnihJSONV3()): ?>

<? endif; ?>

<div class="well">
<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <div class="col-sm-3">
    <div class="text-center #cover" id="cover">
        <img src="<?=$this->url('cover-unavailable')?>" class="recordcover" alt="<?=$this->transEsc('No Cover Image')?>"/>
        <script type="text/javascript">
            obalky.display_authority_cover("#cover", <?=$bibinfo?>, <?=json_encode($this->record($this->driver)->getObalkyKnihAdvert("record"))?>);
        </script>
        <? /* Display qrcode if appropriate: */ ?>
      <? $QRCode = $this->record($this->driver)->getQRCode("core"); ?>
      <? if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <? endif; ?>
    </div>

    <? // if you have a preview tab but want to move or remove the preview link
       // from this area of the record view, this can be split into
       // getPreviewData() (should stay here) and
       // getPreviewLink() (can go in your desired tab) ?>
    <?=$this->record($this->driver)->getPreviews()?>
  </div>

  <div class="col-sm-9">
    <h3 property="name"><strong><?=$this->escapeHtml($this->driver->getPersonalName())?></strong></h3>

    <?/* Display Main Details */?>
    <table class="table" summary="<?=$this->transEsc('Bibliographic Details')?>">
      <? $details = $this->driver->getBibliographicDetails(); ?>
      <? if (! empty($details)): ?>
      <tr>
        <th class="col-md-3"><?=$this->transEsc('Bibliographic Details')?>: </th>
        <td>
          <div><?=$details?></div>
        </td>
      </tr>
      <? endif; ?>

      <? $addedEntryNames = $this->driver->getAddedEntryPersonalNames(); if (!empty($addedEntryNames)): $iteration = 0; $namesCount = count($addedEntryNames);?>
      <tr>
        <th><?=$this->transEsc('Alternative names')?>: </th>
        <td>
          <? foreach ($addedEntryNames as $field): $iteration++; ?>
          <div>
            <? $name = ''; ?>
            <? if(count($field) == 1) $field = explode('--', is_array($field) ? $field[0] : $field); ?>
            <? $i = 0; foreach ($field as $subfield): ?>
              <?=($i++ == 0) ? '' : ' &gt; '?>
              <? $name = trim($subfield); ?>
              <?=trim($this->escapeHtml($name))?>
            <? endforeach; ?>
          </div>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $authoritySources = $this->driver->getSource(); if (count($authoritySources)):?>
      <tr>
        <th><?=$this->transEsc('Source')?>: </th>
        <td>
          <? foreach ($authoritySources as $source): ?>
          <div>
			<?=$source?>
          </div>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $pseudonyms = $this->driver->getPseudonyms(); if (!empty($pseudonyms)): $iteration = 0; $subjectsCount = count($pseudonyms);?>
      <tr>
        <th><?=$this->transEsc('Published also like')?>: </th>
        <td>
          <? foreach ($pseudonyms as $field): $iteration++; ?>
          <div>
            <? $pseudonym = ''; ?>
            <? if(count($field) == 1) $field = explode('--', is_array($field) ? $field[0] : $field); ?>
            <? $i = 0; foreach ($field as $subfield): ?>
              <?=($i++ == 0) ? '' : ' &gt; '?>
              <? $pseudonym = trim($subfield); ?>
              <a title="<?=$this->escapeHtmlAttr($pseudonym)?>" href="<?=$this->record($this->driver)->getLink('author', $pseudonym)?>"><?=trim($this->escapeHtml($subfield))?></a>
            <? endforeach; ?>
          </div>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <tr>
        <th><?=$this->transEsc('Format')?>: </th>
        <td><?=$this->transEsc('Authority')?></td>
      </tr>

    </table>
    <?/* End Main Details */?>
  </div>
</div>
</div>
