<?
  // Set page title.
  $this->headTitle($this->driver->getBreadcrumb());
?>

<div class="list-group">

    <div id='google-books-link' class='hidden'>
    	<a title='<?= $this->translate('Google Books') ?>' class="list-group-item" target='_blank'><?= $this->translate('Google Books') ?></a>
    </div>

    <div id='antikvariaty-link' class='hidden'>
    	<a title='<?= $this->translate('Antikvariat') ?>' class="list-group-item" target='_blank'><?= $this->translate('Antikvariat') ?></a>
    </div>

    <div id='zbozi-link' class='hidden'>
    	<a title='<?= $this->translate('Zboží.cz') ?>' class="list-group-item" target='_blank'><?= $this->translate('Zboží.cz') ?></a>
    </div>

    <script>
    	function displayBuyLinks( buyLinks )
    	{
    		if ( buyLinks.data[0]['gBooksLink'] !== '' ) {
    			$( "#google-books-link" ).removeClass( 'hidden' );
    			$( "#google-books-link a" ).attr( 'href', buyLinks.data[0]['gBooksLink'] );
    		}
    		if ( buyLinks.data[0]['zboziLink'] !== '' ) {
    			$( "#zbozi-link" ).removeClass( 'hidden' );
    			$( "#zbozi-link a" ).attr( 'href' , buyLinks.data[0]['zboziLink'] );
    		}
    		if ( buyLinks.data[0]['antikvariatyLink'] !== '' ) {
    			$( "#antikvariaty-link ").removeClass( 'hidden' );
    			$( "#antikvariaty-link a ").attr( 'href', buyLinks.data[0]['antikvariatyLink'] );
    		}
    	}

      jQuery( document ).ready( function( $ ) {
        var recordID = '<?= $this->driver->getUniqueID() ?>';
        getBuyLinks(recordID, displayBuyLinks);
      });

    </script>

</div>
