<?
  // Set page title.
  $this->headTitle($this->driver->getBreadcrumb());
  $this->headScript()->appendFile("jquery-ui.min.js");
  $issns = $this->driver->getIssns();
  $isbns = $this->driver->getIsbns();
  $publishDate = $this->driver->getPublishDate();
  $titles = $this->driver->getTitles();
  $authors = $this->driver->getAuthors();
  $sourceTitle = $this->driver->getSourceTitle();
  $volume = $this->driver->getVolume();
?>

<div class="list-group">

    <div id="eds-links">

        <h3 id="only-one-eds-link-header" style="display: none;"><?= $this->translate('Fulltext is avalable for users of this institution') ?>:</h3>
        <h3 id="many-eds-links-header" style="display: none;"><?= $this->translate('Fulltext is avalable for users of these institutions') ?>:</h3>

        <table class="table table-striped">
            <tbody>
                <div id="eds-links-placeholder">
                    <!-- Ajax Placeholder -->
                </div>
            </tbody>
        </table>

    </div>

    <script src="/themes/bootstrap3/js/ajax-record-tabs.js"></script>

    <script>
        var edsLinks = 0;
        var recordData = {
            <? if (! empty($issns)): ?> <?= "'issns': '".implode(", ", $issns)."'," ?> <? endif; ?>
            <? if (! empty($isbns)): ?> <?= "'isbns': '".implode(", ", $isbns)."'," ?> <? endif; ?>
            <? if (! empty($publishDate)): ?> <?= "'publishDate': '".$publishDate."'," ?> <? endif; ?>
            <? if (! empty($titles)): ?> <?= "'titles': \"".implode(", ", $titles)."\"," ?> <? endif; ?>
            <? if (! empty($authors)): ?> <?= "'authors': \"".implode(", ", $authors)."\"," ?> <? endif; ?>
            <? if (! empty($sourceTitle)): ?> <?= "'sourceTitle': \"".$sourceTitle."\"," ?> <? endif; ?>
            <? if (! empty($volume)): ?> <?= "'volume': '".$volume."'," ?> <? endif; ?>
        };
        jQuery( document ).ready( function( $ ) {

            $.ajax({
                method: 'POST',
                dataType: 'json',
                async: true,
                url: '/AJAX/JSON?method=getEdsFulltextLink',
                data: {
                    recordData: recordData
                },
                beforeSend: function () {
                    console.info( 'Calling getEdsFulltextLink..' );
                    $('#eds-links-placeholder').append("<div class='eds-links-loader text-center'><i class='fa fa-2x fa-refresh fa-spin'></i></div>");
                },
                success: function (response) {

                    if (response.status == 'OK') {
                        console.log( 'Eds fulltext links FOUND.' );

                        var links = response.data.links;
                        edsLinks += links.length;

                        var html = "";
                        links.forEach( function( link ) {
                            html += "<tr style='display: none;'><td>" + link + "</td></tr>";
                        });

                        if (edsLinks == 1) {
                            $( '#many-eds-links-header' ).hide( 'blind', {}, 200 );
                            $( '#only-one-eds-link-header' ).show( 'blind', {}, 200 );
                        }

                        if (edsLinks > 1) {
                            $( '#only-one-eds-link-header' ).hide( 'blind', {}, 200 );
                            $( '#many-eds-links-header' ).show( 'blind', {}, 200 );
                        }

                        $('#eds-links-placeholder').append( html );
                        $('#eds-links-placeholder tr').show( 'blind', {}, 200 );
                    }

                    if (response.status == 'NOT FOUND') {
                        console.log( 'Eds fulltext links NOT FOUND.' );
                        if (response.data.url) {
                            console.log(response.data.url);
                        }
                    }

                    if (response.status == 'FOUND INVALID LINKS') {
                        console.warn( 'Eds fulltext links FOUND but links are INVALID.' );
                        if (response.data.url) {
                            console.log(response.data.url);
                        }
                    }

                },
                complete: function () {
                    $( '.eds-links-loader' ).remove();
                },
                error: function ( jqXHR, textStatus, errorThrown ) {
                    console.error( JSON.stringify( jqXHR ) );
                    console.error( 'AJAX error: ' + textStatus + ' : ' + errorThrown );
                }
            });

        });
    </script>

</div>
