<?
  // Set page title.
  $this->headTitle($this->driver->getBreadcrumb());
?>

<div class='field856'>
	<table class='table table-striped' id='e-version-table'>
		<thead>
		<tr>
			<th><?=$this->translate('Destination');?></th>
			<th><?=$this->translate('Accessibility');?></th>
			<th><?=$this->translate('Link');?></th>
			<th><?=$this->translate('Distributor');?></th>
		</tr>
		</thead>
		<tbody>
			<? if ($this->linksFrom856): ?>
				<? foreach ($this->linksFrom856 as $linkRawString):
				    if (empty($linkRawString)) continue;
					$link = explode("|", $linkRawString);
					$anchor = ! empty($link[3]) ? $link[3] : $this->transEsc('Link');
					$destination = (substr($link[0], 0, 4) === 'kram') ? $this->translate('Digital library') : $this->translate('Web');
					$title = ! empty($link[3]) ? $link[3] : $destination;
					if ($link[1] === 'online' || $link[1] === 'dnnt' || $link[1] === 'emergency') {
						$statusClass = 'success';
					} else if ($link[1] === 'unknown') {
						$statusClass = 'warning';
					} else if ($link[1] === 'na') {
						$statusClass = 'default';
					} else {
						$statusClass = 'danger';
					}
				?>

					<tr>
						<td><?=$destination?></td>
						<? if ($link[1] === 'protected') : ?>
						 <td>
						 	<a target='_blank' data-toggle="tooltip" data-placement="top" rel='nofollow' title="<?=$this->translate('What does it mean?')?>" href='https://cs.wikipedia.org/wiki/Voln%C3%A9_d%C3%ADlo'>
						 		<span class="label label-<?=$statusClass?>"><?=$this->transEsc('link_access_status_'.$link[1])?></span>
						 	</a>
						 </td>
						<? else : ?>
						<td><span class="label label-<?=$statusClass?>"><?=$this->transEsc('link_access_status_'.$link[1])?></span></td>
						<? endif; ?>
						<td><a title='<?=$title?>' href='<?=$link[2]?>' target='_blank'><?=$anchor?></a></td>
						<td><?=$this->transEsc('source_'.$link[0])?></td>
					</tr>
				<? endforeach; ?>
			<? endif; ?>
		</tbody>
	</table>
</div>

<div id='sfx-jib-ajax-result'></div>

<script src="/themes/bootstrap3/js/ajax-record-tabs.js"></script>
<script>

	jQuery( document ).ready( function( $ ) {

		var recordUniqueID = '<?= $this->driver->getUniqueID() ?>';
		databaseTranslation = '<?=$this->translate('Database')?>';
		unknownTranslation = '<?=$this->translate('link_access_status_unknown')?>';
		var eVersionLinksCount = <?=$this->eVersionLinksCount?>;

		if ( eVersionLinksCount === 0 ) {
			$( '#eversion' ).parent().removeClass( 'active' ).addClass( 'disabled' );
			$( "#e-version-table" ).addClass( 'hidden' );
		}
		if ( eVersionLinksCount > 0 ) {
			get866( recordUniqueID, '<?= $this->driver->getParentRecordID() ?>', '<?= explode(".", $this->driver->getUniqueID())[0]?>', display866 );
		}

	});
</script>
