<?
    // Set page title.
    $this->headTitle($this->translate('Staff View') . ': ' . $this->driver->getBreadcrumb());
?>
<table class="citation table table-striped">
  <? foreach ($this->driver->getRawData() as $field => $values): ?>
    <tr>
      <th><?=$this->escapeHtml($field)?></th>
      <td>
        <? if (!is_array($values)) { $values = array($values); } ?>
        <? foreach ($values as $value): ?>
          <?
            if($this->escapeHtml(is_array($value))) {
              if ($field == 'RecordInfo') {
                  $json_output = json_encode($value, JSON_PRETTY_PRINT);
                  echo "<pre>";
                  echo $json_output;
                  echo "</pre>";
              } else {
                  foreach ($value as $key => $val) {
                      printf("<b>%s: </b>%s<br />", $key, htmlspecialchars_decode($val));
                  }
              }
            } else {
              echo $value;
            }
            echo '<br />';
            ?>
        <? endforeach; ?>
      </td>
    </tr>
  <? endforeach; ?>
</table>