<?
    // Set page title.
    $this->headTitle($this->translate('Staff View') . ': ' . $this->driver->getBreadcrumb());
?>
<table class="citation table table-striped">
  <? foreach ($this->driver->getRawData() as $field => $values): ?>
    <tr>
      <th><?=$this->escapeHtml($field)?></th>
      <td>
        <? if (!is_array($values)) { $values = array($values); } ?>
        <? foreach ($values as $value): ?>
          <? if(is_array($value)): ?>
            <? if ($field == 'RecordInfo'): ?>
              <? $json_output = json_encode($value, JSON_PRETTY_PRINT) ?>
              <pre><?=$this->escapeHtml($json_output)?></pre>
            <? else: ?>
              <? foreach ($value as $key => $val): ?>
                <b><?=$this->escapeHtml(htmlspecialchars_decode($key))?>: </b><?=$this->escapeHtml(htmlspecialchars_decode($val))?><br />
              <? endforeach; ?>
            <? endif; ?>
          <? else: ?>
            <?=$this->escapeHtml($value)?>
          <? endif; ?>
          <br />
        <? endforeach; ?>
      </td>
    </tr>
  <? endforeach; ?>
</table>