<?php if ($this->ZiskejEdd()->isEnabled()): ?>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><?=$this->translate('ziskej_edd_desc_header') ?></h3>
    </div>
    <div class="panel-body">
      <div class="col-md-10">
        <p><?=$this->translate('ziskej_edd_desc') ?></p>
      </div>
      <div class="col-md-2">
        <?php if (!empty($this->ziskejTechlibFrontUrl)): ?>
          <form action="<?=$this->ziskejTechlibFrontUrl ?>/ticket_create" id="ziskejEdd" method="post" target="_blank">
            <input type="hidden" name="service" value="edd">
            <input type="hidden" name="source_id" value="<?=$this->escapeHtmlAttr($this->serverName) ?>">
            <input type="hidden" name="user_id" value="<?=$this->escapeHtmlAttr(isset($this->eppn) ? $this->eppn : '') ?>">
            <input type="hidden" name="doc_id" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueID()) ?>">
            <input type="hidden" name="entity_id" value="<?=$this->escapeHtmlAttr(isset($this->entityId) ? $this->entityId : '') ?>">
            <?php foreach ($this->tabs['DedupedRecords']->getRecordsInGroup() as $record): ?>
              <input type="hidden" name="doc_alt_ids[]" value="<?=$this->escapeHtmlAttr($record['id']) ?>">
            <?php endforeach; ?>
            <input type="image" src="<?=$this->imageLink('logo-ziskej.png') ?>" alt="<?=$this->translate('ziskej') ?>">
          </form>
        <?php else: ?>
          <?php if (!empty($this->ziskejMinUrl)): ?>
            <a href="<?=$this->ziskejMinUrl ?>" target="_blank">
              <img src="<?=$this->imageLink('logo-ziskej.png') ?>" alt="<?=$this->translate('ziskej') ?>">
            </a>
          <?php endif; ?>
        <?php endif; ?>
      </div>
    </div>
  </div>

<?php endif; ?>
