<div class="row">
  <h2><?= $this->translate('ziskej_desc_header') ?></h2>
  <p><?= $this->translate('ziskej_desc') ?></p>
</div>
<div class="row">
  <? if ($this->user): ?>
    <div class="col-md-6">
      <h4><?= $this->translate('Vase knihovny') ?></h4>
      <? if(empty($this->connectedLibs)): ?>
          <p>Ne mate zapojene knihovny</p>
        <? else: ?>
          <ul class="list-group" >
            <? foreach ($this->connectedLibs as $source): ?>
              <li class="list-group-item" style="display: flex; justify-content: space-around">
                <span style="line-height: 50px"><?= $this->translate('source_'.$source) ?></span>
                <button class="btn btn-default ziskej-order-btn" id="<?= $this->escapeHtmlAttr($source) ?>">Objednat</button>
              </li>
            <? endforeach; ?>
          </ul>
        <? endif; ?>
      <h4><?= $this->translate('ziskej_available_header') ?></h4>
      <div class="panel panel-default">
        <? foreach ($this->ziskejLibSources as $source): ?>
          <div class="panel-heading ziskej-lib-title" id="<?=$source?>" style="cursor: pointer;"><?= $this->translate('source_'.$source) ?><i class="fa fa-arrow-down" style="float:right;"></i></div>
          <div class="panel-body hidden ziskej-hidden-content" id="<?='content_'.$source?>">
            <div class="row">
              <div class="col-md-6">
                  <?= $this->translate('source_'.$source) ?>
              </div>
              <div class="col-md-6">
                <button class="btn btn-default">Log in</button>
                <button class="btn btn-default">Register</button>
              </div>
            </div>
          </div>
        <?endforeach; ?>
      </div>

    </div>
    <div class="col-md-6 text-center" id="ziskejMinimalButton">
      <a href="<?= $this->ziskejMinUrl ?>" class="btn">
        <img src="/themes/bootstrap3/images/ziskejlogo.png" alt="<?= $this->translate('ziskej') ?>">
      </a>
    </div>
  <? else: ?>
  <div class="row">
    <div class="col-md-6">
      <div class="row">
        <h4><?= $this->translate('ziskej_available_header') ?></h4>
        <div class="panel panel-default">
          <? foreach ($this->ziskejLibSources as $source): ?>
            <div class="panel-heading ziskej-lib-title" id="<?=$source?>" style="cursor: pointer;">
                <?= $this->translate('source_'.$source) ?><i class="fa fa-arrow-down" style="float:right;"></i>
            </div>
            <div class="panel-body hidden ziskej-hidden-content" id="<?='content_'.$source?>">
              <div class="row">
                <div class="row">
                  <div>
                      <?= $this->translate('source_'.$source) ?>
                  </div>
                </div>
                <div class="row" style="float: right;">
                  <div data-toggle="modal" data-target="#ziskejTabLoginModal" class="col-md-6">
                    <button class='login-button btn-primary btn'><?=$this->transEsc("Institutional Login")?></button>
                  </div>
                  <div class="col-md-6">
                    <button class="register-button btn btn-default">Register</button>
                  </div>
                </div>
              </div>
            </div>
          <?endforeach; ?>
        </div>
      </div>
    </div>
    <div class="col-md-6 text-center" id="ziskejMinimalButton">
      <a href="<?= $this->ziskejMinUrl ?>" class="btn">
        <img src="/themes/bootstrap3/images/ziskejlogo.png" alt="<?= $this->translate('ziskej') ?>">
      </a>
    </div>
  </div>
  <? endif; ?>
</div>