<div class="row">
  <h2><?= $this->translate('ziskej_desc_header') ?></h2>
  <p><?= $this->translate('ziskej_desc') ?></p>
</div>
<div class="row">
  <div class="col-md-6">
    <h4><?= $this->translate('ziskej_available_header') ?></h4>
    <ul>
      <li><?= $this->translate('ziskej_national_lib') ?></li>
      <li><?= $this->translate('ziskej_national_medical_lib') ?></li>
      <li><?= $this->translate('ziskej_moravian_lib') ?></li>
      <li><?= $this->translate('ziskej_ceska_trebova_lib') ?></li>
    </ul>
  </div>
  <div class="col-md-6 text-center" id="ziskejMinimalButton">
    <a href="<?= $this->ziskejMinUrl ?>" class="btn btn-primary"><?= $this->translate('ziskej') ?></a>
  </div>
</div>