<?
  $links = $this->recommend->getLinks();
?>
<? if (count($links) > 0) :?>
  <div class="info">
    <?=$this->transEsc('recommend_links_text')?>
      <? foreach($links as $title => $href): $randomString = md5('CPK'.date("Y-m-d H:i:s"));?>
        <p>
        	<? if ($href === 'http://www.jib.cz') : ?>
          		<a target='_blank' href="<?=$href.'/V/'.$randomString.'-'.rand(10000, 99999).'?func=quick-1-check1&mode=simple&find_request_1='.addslashes($_GET['lookfor'])?>"><?=$this->transEsc($title)?></a>
          	<? elseif ($href === 'https://www.google.cz') : ?>
          		<a target='_blank' href="<?=$href.'?q='.addslashes($_GET['lookfor'])?>"><?=$this->transEsc($title)?></a>
          	<? else : ?>
          		<a target='_blank' href="<?=$href?>"><?=$this->transEsc($title)?></a>
          	<? endif; ?>
        </p>
      <? endforeach; ?>
  </div>
<? endif;?>