<? $results = $this->recommend->getResults(); ?>
<? if ($results->getResultTotal() > 0): ?>
  <h4><?=$this->transEsc(isset($this->overrideSideFacetCaption) ? $this->overrideSideFacetCaption : 'Narrow Search')?></h4>
<? endif; ?>
<? $checkboxFilters = $results->getParams()->getCheckboxFacets(); if (count($checkboxFilters) > 0): ?>
<?
  $html = '';
  $shown = 0;
  foreach ($checkboxFilters as $current) {
    $html .= '<label class="checkbox';
    if($results->getResultTotal() < 1 && !$current['selected'] && !$current['alwaysVisible']) {
      $html .= ' hidden';
    } else {
      $shown ++;
    }
    $html .= '"><input type="checkbox" name="filter[]" value="'.$this->escapeHtmlAttr($current['filter']).'"
      '. ($current['selected'] ? 'checked="checked"' : '') .' id="'.$this->escapeHtmlAttr(str_replace(' ', '', $current['desc'])).'"
      onclick="document.location.href=\''.($current['selected'] ? $results->getUrlQuery()->removeFilter($current['filter']) : $results->getUrlQuery()->addFilter($current['filter'])).'\';" />'.$this->transEsc($current['desc']).'</label>';
  }
?>
  <div class="checkboxFilter<?if($shown == 0):?> hidden<? endif; ?>"><?=$html ?></div>
<? endif; ?>
<? $extraFilters = isset($this->extraSideFacetFilters) ? $this->extraSideFacetFilters : array(); ?>
<? $collapsedFacets = $this->recommend->getCollapsedFacets() ?>
<? $hierarchicalFacetSortOptions = $this->recommend->getHierarchicalFacetSortOptions() ?>
<? $hierarchicalFacets = $this->recommend->getHierarchicalFacets() ?>
<?
$queryParams = $results->getUrlQuery()->getParamArray();
unset($queryParams['filter']);

$i = '?';
$removeFilterUrl = '/Search/Results';
foreach ($queryParams as $key => $value) {

    if (is_array($value)) {
        $value = $value[0];
        $key .= "[]";
    }
    $removeFilterUrl .= $i . $key . '=' . urlencode($value);

    if ($i === '?')
        $i = '&';
}


?>
 <? $filterList = array_merge($results->getParams()->getFilterList(true), $extraFilters); if (!empty($filterList)): ?>
  <div class="list-group filters">

    <a href='<?=$removeFilterUrl?>'><div class="list-group-item title"><?=$this->transEsc('Remove Filters')?></div></a>
    <? foreach ($filterList as $field => $filters): ?>
      <? if ($field !== 'Institution'): ?>
          <? foreach ($filters as $i => $filter): ?>
            <?
              $index = isset($filter['field']) ? array_search($filter['field'], $collapsedFacets) : false;
              if ($index !== false) {
                  unset($collapsedFacets[$index]); // Open if we have a match
              }
              if (isset($filter['specialType']) && $filter['specialType'] == 'keyword') {
                $removeLink = $this->currentPath().$results->getUrlQuery()->replaceTerm($filter['value'], '');
              } else {
                $removeLink = $this->currentPath().$results->getUrlQuery()->removeFacet($filter['field'], $filter['value'], true, $filter['operator']);
              }
              if ($filter['displayText'] == '[* TO *]') {
                $filter['displayText'] = $this->translate('filter_wildcard');
              }
              $dataFacet = $filter['field'].':"'.$filter['value'].'"';
            ?>
            <a class="list-group-item active facet-filter" data-facet='<?=$dataFacet?>' href="<?=$removeLink?>">
              <span class="pull-right flip"><i class="fa fa-times"></i></span>
              <? if ($filter['operator'] == 'NOT') echo $this->transEsc('NOT') . ' '; if ($filter['operator'] == 'OR' && $i > 0) echo $this->transEsc('OR') . ' '; ?><?=$this->transEsc($field)?>: 
              <? if (strpos($this->escapeHtml($filter['displayText']), "Library/") !== false)
                  echo explode("/", $this->escapeHtml($filter['displayText']))[1]; //@FIXME QuickFix, fix this problem on higher level
                else 
                  echo $this->escapeHtml($filter['displayText']);
              ?>
            </a>
          <? endforeach; ?>
      <? endif; ?>
    <? endforeach; ?>
  </div>
<? endif;
// Here starts custom code (everything else is from upstream)
?>
<? if ($this->recommend instanceof \CPK\Recommend\SideFacets && isset($myLibs) && is_array($myLibs) && count($myLibs) > 0):

    $urlParams = $results->getUrlQuery()->getParamArray();
    $newParams = array('type' => 'AllFields');
    $filtered = array();
    if (isset($urlParams['filter'])) foreach ($urlParams['filter'] as $param) {
        if (strpos($param, '~institution:') === 0) continue;
        $filtered[] = $param;
    }
    $newParams = $urlParams;
    $newParams['filter'] = $filtered;

    $firstLib = true;
    foreach ($myLibs as $myLib) {
        if ($firstLib) {
            $url = $this->currentPath().$results->getUrlQuery()->addFacet("institution",
                    $this->recommend->getInstutitionMapping($myLib), "OR", $newParams);
            $firstLib = false;
        }
        else
            $url .= '&' . urlencode('filter[]'). '=~' . urlencode('institution:"' .
                    $this->recommend->getInstutitionMapping($myLib) . '"');
    }

    ?>
    <div class="list-group facet" id="side-panel-institution">
        <div id="side-collapse-institution-member" class="collapse in">
            <ul class="jstree-container-ul">
                <li aria-selected="false" class="jstree-facet jstree jstree-2 jstree-default jstree-default-responsive">
                    <a href="<?=$url?>" class="jstree-anchor">
                        <span class="main" title="<?=$this->transEsc('Connected institutions only')?>">
                            <i class="fa fa-home"></i> <?=$this->transEsc('Connected institutions only')?>
                        </span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
<? endif;
// Here ends custom code (everything else is from upstream)
?>
<?= isset($this->sideFacetExtraControls) ? $this->sideFacetExtraControls : '' ?>
<? $sideFacetSet = $this->recommend->getFacetSet(); $rangeFacets = $this->recommend->getAllRangeFacets(); ?>
<? if (!empty($sideFacetSet) && $results->getResultTotal() > 0): ?>
  <? foreach ($sideFacetSet as $title => $cluster): ?>
    <? $allowExclude = $this->recommend->excludeAllowed($title); ?>
    <? $facets_before_more = $this->recommend->getShowMoreSetting($title); ?>
    <div class="list-group facet" id="side-panel-<?=$this->escapeHtmlAttr($title) ?>">
      <div class="list-group-item title<? if(in_array($title, $collapsedFacets)): ?> collapsed<? endif ?>" data-toggle="collapse" href="#side-collapse-<?=$this->escapeHtmlAttr($title) ?>" >
        <?=$this->transEsc($cluster['label'])?>
          <? if (isset($rangeFacets[$title])): ?>
          <? if ($rangeFacets[$title]['type'] == 'date'): ?>
          <button type="button" class="btn btn-primary btn-sm" id="showmodal"  ><?=$this->transEsc('Show timeline') ?></button>
          <? endif; ?>
          <? endif; ?>
      </div>
      <div id="side-collapse-<?=$this->escapeHtmlAttr($title) ?>" class="collapse<? if(!in_array($title, $collapsedFacets)): ?> in<? endif ?>">
        <? if (isset($rangeFacets[$title])): ?>
          <div class="list-group-item">
            <form action='' name="<?=$this->escapeHtmlAttr($title)?>Filter" id="<?=$this->escapeHtmlAttr($title)?>Filter">
              <?=$results->getUrlQuery()->asHiddenFields(array('page' => "/./", 'filter' => "/^{$title}:.*/"))?>
              <input type="hidden" name="<?=$this->escapeHtmlAttr($rangeFacets[$title]['type'])?>range[]" value="<?=$this->escapeHtmlAttr($title)?>"/>
              <div class="row">
                <? $extraInputAttribs = ($rangeFacets[$title]['type'] == 'date') ? 'maxlength="4" ' : ''; ?>
                <div class="col-sm-6">
                  <label for="<?=$this->escapeHtmlAttr($title)?>from">
                    <?=$this->transEsc('date_from')?>:
                  </label>
                  <input type="text" class="form-control" name="<?=$this->escapeHtmlAttr($title)?>from" id="<?=$this->escapeHtmlAttr($title)?>from" value="<?=isset($rangeFacets[$title]['values'][0])?$this->escapeHtmlAttr($rangeFacets[$title]['values'][0]):''?>" <?=$extraInputAttribs?>/>
                </div>
                <div class="col-sm-6">
                  <label for="<?=$this->escapeHtmlAttr($title)?>to">
                    <?=$this->transEsc('date_to')?>:
                  </label>
                  <input type="text" class="form-control" name="<?=$this->escapeHtmlAttr($title)?>to" id="<?=$this->escapeHtmlAttr($title)?>to" value="<?=isset($rangeFacets[$title]['values'][1])?$this->escapeHtmlAttr($rangeFacets[$title]['values'][1]):''?>" <?=$extraInputAttribs?>/>
                </div>
              </div>
              <? if ($rangeFacets[$title]['type'] == 'date'): ?>
                <div class="slider-container"><input type="text" class="hidden" id="<?=$this->escapeHtmlAttr($title)?><?=$this->escapeHtml($rangeFacets[$title]['type'])?>Slider"/></div>
              <? endif; ?>
              <input class="btn btn-default" type="submit" value="<?=$this->transEsc('Set')?>"/>
            </form>
          </div>
          <? if ($rangeFacets[$title]['type'] == 'date'): ?>
            <? $this->headScript()->appendFile('vendor/bootstrap-slider.js'); ?>
            <?
              $min = !empty($rangeFacets[$title]['values'][0]) ? min($rangeFacets[$title]['values'][0], 1400) : 1400;
              $future = date('Y', time()+31536000);
              $max = !empty($rangeFacets[$title]['values'][1]) ? max($future, $rangeFacets[$title]['values'][1]) : $future;
              $low  = !empty($rangeFacets[$title]['values'][0]) ? $rangeFacets[$title]['values'][0] : $min;
              $high = !empty($rangeFacets[$title]['values'][1]) ? $rangeFacets[$title]['values'][1] : $max;
              $reversed = $this->layout()->rtl ? 'true' : 'false';
              $script = <<<JS
$(document).ready(function() {
  var fillTexts = function() {
  var v = {$this->escapeHtmlAttr($title)}dateSlider.getValue();
  $('#{$this->escapeHtmlAttr($title)}from').val(v[0]);
  $('#{$this->escapeHtmlAttr($title)}to').val(v[1]);
  };
  var {$this->escapeHtmlAttr($title)}dateSlider = $('#{$this->escapeHtmlAttr($title)}dateSlider')
  .slider({
    'min':{$min},
    'max':{$max},
    'handle':"square",
    'tooltip':"hide",
    'value':[{$low},{$high}],
    'reversed': {$reversed}
  })
  .on('slide', fillTexts)
  .data('slider');
});
JS;
            ?>
            <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
          <? endif; ?>
        <? else: ?>
          <? if (in_array($title, $hierarchicalFacets)): ?>
            <? $this->headScript()->appendFile('vendor/jsTree/jstree.min.js'); ?>
            <? $this->headScript()->appendFile('facets.js'); ?>
            <? $sort = isset($hierarchicalFacetSortOptions[$title]) ? $hierarchicalFacetSortOptions[$title] : ''; ?>
            <? if (!in_array($title, $collapsedFacets)): ?>
              <?
              $script = <<<JS
$(document).ready(function() {
  initFacetTree($('#facet_{$this->escapeHtml($title)}'), true);
});
JS;
              ?>
              <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
            <? else: ?>
              <?
              $script = <<<JS
$('#side-collapse-{$this->escapeHtmlAttr($title)}').on('show.bs.collapse', function() {
  initFacetTree($('#facet_{$this->escapeHtml($title)}'), true);
});
JS;
              ?>
              <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
            <? endif; ?>
            <li id="facet_<?=$this->escapeHtml($title)?>" class="jstree-facet"
                  data-facet="<?=$this->escapeHtmlAttr($title)?>"
                  data-path="<?=$this->currentPath()?>"
                  data-exclude="<?=$allowExclude?>"
                  data-operator="<?=$this->recommend->getFacetOperator($title)?>"
                  data-exclude-title="<?=$this->transEsc('exclude_facet')?>"
                  data-sort="<?=isset($hierarchicalFacetSortOptions[$title]) ? $hierarchicalFacetSortOptions[$title] : ''?>">
            </li>
            <noscript>
          <? endif; ?>
          <? foreach ($cluster['list'] as $i=>$thisFacet): ?>
              <?
              $dataFacet = $title.':"'.$thisFacet['value'].'"';
                if(strlen($thisFacet['displayText']) == 0) {
                  $thisFacet['displayText'] = "-";
                }
              ?>
              <? $moreClass = 'narrowGroupHidden-'.$this->escapeHtmlAttr($title).' hidden'; ?>
            <? if ($i == $facets_before_more): ?>
              <a id="more-narrowGroupHidden-<?=$this->escapeHtmlAttr($title)?>" class="list-group-item narrow-toggle" href="javascript:moreFacets('narrowGroupHidden-<?=$title ?>')"><?=$this->transEsc('more')?> ...</a>
            <? endif; ?>
            <? if ($thisFacet['isApplied']): ?>
              <a class="list-group-item active<? if ($i >= $facets_before_more): ?><?=$moreClass ?><?endif ?><? if ($thisFacet['operator'] == 'OR'): ?> facetOR applied<? endif ?>" href="<?=$this->currentPath().$results->getUrlQuery()->removeFacet($title, $thisFacet['value'], true, $thisFacet['operator']) ?>">
                <? if ($thisFacet['operator'] == 'OR'): ?>
                  <i class="fa fa-check-square-o"></i>
                <? else: ?>
                  <span class="pull-right flip"><i class="fa fa-check"></i></span>
                <? endif; ?>
                <?=$this->transEsc($thisFacet['displayText'])?>
              </a>
            <? else: ?>
              <? $addURL = $this->currentPath().$results->getUrlQuery()->addFacet($title, $thisFacet['value'], $thisFacet['operator']); ?>
              <? if ($allowExclude): ?>
                <div class="list-group-item facet<?=$thisFacet['operator'] ?><? if ($i >= $facets_before_more): ?> <?=$moreClass ?><?endif ?>">
              <? else: ?>
                <a data-facet='<?=$dataFacet?>' href="<?=$addURL ?>" class="list-group-item facet-filter facet<?=$thisFacet['operator'] ?><? if ($i >= $facets_before_more): ?> <?=$moreClass ?><?endif ?>">
              <? endif; ?>
              <span class="badge">
                <?=$this->localizedNumber($thisFacet['count'])?>
                <? if ($allowExclude): ?>
                  <a href="<?=$this->currentPath().$results->getUrlQuery()->addFacet($title, $thisFacet['value'], 'NOT') ?>" title="<?=$this->transEsc('exclude_facet') ?>"><i class="fa fa-times"></i></a>
                <? endif; ?>
              </span>
              <? if ($allowExclude): ?>
                <a href="<?=$addURL ?>">
              <? endif; ?>
              <? if($thisFacet['operator'] == 'OR'): ?>
                <i class="fa fa-square-o"></i>
              <? endif; ?>
              <? if (($cluster['label'] == 'language') OR ($cluster['label'] == 'country_str')): ?>
                <?=$this->escapeHtml($thisFacet['value'])?>
              <? else: ?>
                <?=$this->transEsc($thisFacet['displayText'])?>
              <? endif; ?>
              <? if ($allowExclude): ?>
                  </a>
                </div>
              <? else: ?>
                </a>
              <? endif; ?>
            <? endif; ?>
          <? endforeach; ?>
          <? if ($i > 5): ?><a class="list-group-item narrow-toggle <?=$moreClass ?>" href="javascript:lessFacets('narrowGroupHidden-<?=$title ?>')"><?=$this->transEsc('less')?> ...</a><? endif; ?>
        <? endif; ?>
        <? if (in_array($title, $hierarchicalFacets)): ?>
          </noscript>
        <? endif; ?>
      </div>
      <? if($cluster['label'] == 'Institution'): ?>
        <button type="button" class="btn btn-primary btn-sm btn-block facet-filter institution-facet-filter-button"><?=$this->translate('Update results')?></button>
      <? endif; ?>
      <div class='facet-divider'></div>
    </div>
  <? endforeach; ?>
<? endif; ?>
<!--data-toggle="modal" data-target="#exampleModal"-->


<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="exampleModalLabel"><?=$this->transEsc('Timeline') ?></h4>
            </div>
            <div class="modal-body">
            <? foreach ($this->results->getRecommendations('top') as $current): ?>
                <div>
                    <?=$this->recommend($current)?>
                </div>
            <? endforeach; ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal"><?=$this->transEsc('Close') ?></button>
            </div>
        </div>
    </div>
</div>

<script>
$('#showmodal').click(function() {
    $('#exampleModal').modal('show');
    return false;
});
</script>
