<?
    // Set up convenience variables:
    $limitList = $this->options->getLimitOptions();

    // If a previous limit was used, make that the default; otherwise, use the "default default"
    $lastLimit = $this->options->getLastLimit();
    if (! empty($lastLimit)) { 
        $defaultLimit = $lastLimit;
    } else {
        if (! empty($this->preferredRecordsPerPage)) { 
            $defaultLimit = $this->preferredRecordsPerPage;
        } else {
            $defaultLimit = $this->options->getDefaultLimit();
        }
    }
?>
<? if (count($limitList) > 1): ?>
    <legend><?=$this->transEsc('Number of results per page')?></legend>
    <div class="col-sm-2">
    <select id="limit" name="limit" class="form-control">
      <? foreach ($limitList as $limitVal): ?>
        <option value="<?=$this->escapeHtmlAttr($limitVal)?>"<?=($limitVal == $defaultLimit) ? 'selected="selected"' : ''?>><?=$this->escapeHtml($limitVal)?></option>
      <? endforeach; ?>
    </select>
  </div>
<? endif; ?>