<? if (!empty($this->facetList) || !empty($this->checkboxFacets)): ?>
  <fieldset class="col-sm-12">
    <legend><?=$this->transEsc('Limit To')?></legend>
    <? if (!empty($this->checkboxFacets)): ?>
      <?=$this->render('search/advanced/checkbox-filters.phtml')?>
    <? endif; ?>
    <div class="row">
      <? foreach ($this->facetList as $field => $list): ?>
        <div class="col-sm-<?=floor(12/count($this->facetList)) ?>">
          <label for="limit_<?=$this->escapeHtmlAttr(str_replace(' ', '', $field))?>"><?=$this->transEsc($list['label'])?>:</label>
          <select class="col-sm-12" id="limit_<?=$this->escapeHtmlAttr(str_replace(' ', '', $field))?>" name="filter[]" multiple="multiple" size="10">
            <?
              // Sort the current facet list alphabetically; we'll use this data
              // along with the foreach below to display facet options in the
              // correct order.
              $sorted = array();
            foreach ($list['list'] as $i => $value) {
              $sorted[$i] = $value['displayText'];
            }
            asort($sorted, SORT_LOCALE_STRING);
            $top = isset($this->preferredFacets[$field])? $this->preferredFacets[$field] : array();
            $priors = array();
            foreach ($list['list'] as $i => $value) {
              $key = $value['value'];
              if (isset($top[$key])) {
                $priors[$top[$key]] = $value;
              }
            }
            ksort($priors);
            ?>
            <? foreach ($priors as $i => $value): ?>
              <option value="<?=$this->escapeHtmlAttr(($value['operator'] == 'OR' ? '~' : '') . $field . ':"' . $value['value'] . '"')?>"<?=(isset($value['selected']) && $value['selected'])?' selected="selected"':''?>>
                <?=$this->escapeHtml($value['displayText'])?>
              </option>
            <? endforeach; ?>
            <? if (!empty($top) && count($priors) != count($sorted)):?>
              <option disabled="disabled">=================</option>
            <? endif;?>
            <? foreach ($sorted as $i => $display): ?>
              <? $value = $list['list'][$i]; if (!isset($top[$value['value']])):?>
                <option value="<?=$this->escapeHtmlAttr(($value['operator'] == 'OR' ? '~' : '') . $field . ':"' . $value['value'] . '"')?>"<?=(isset($value['selected']) && $value['selected'])?' selected="selected"':''?>>
                  <?=$this->escapeHtml($display)?>
                </option>
              <? endif;?>
            <? endforeach; ?>
          </select>
        </div>
      <? endforeach; ?>
    </div>
  </fieldset>
<? endif; ?>
<div class="row">
  <? if (isset($this->illustratedLimit)): ?>
    <fieldset class="col-sm-4">
      <legend><?=$this->transEsc("Illustrated")?>:</legend>
      <? foreach ($this->illustratedLimit as $current): ?>
        <input id="illustrated_<?=$this->escapeHtmlAttr($current['value'])?>" type="radio" name="illustration" value="<?=$this->escapeHtmlAttr($current['value'])?>"<?=$current['selected']?' checked="checked"':''?>/>
        <label for="illustrated_<?=$this->escapeHtmlAttr($current['value'])?>"><?=$this->transEsc($current['text'])?></label><br/>
      <? endforeach; ?>
    </fieldset>
  <? endif; ?>
  <?=$this->render('search/advanced/limit.phtml')?>
  <?=$this->render('search/advanced/ranges.phtml')?>
</div>