<? // This is a text-only email template; do not include HTML! ?>
Dobrý den,

Vaše IdP brána s entityId "<?=$this->entityId?>" nám do portálu neposílá uživatelovo eduPersonPrincipalName, které je nutné k jeho přihlášení.

Prosíme Vás, abyste tento problém vyřešili co nejdříve.

Zda byl problém vyřešen můžete ověřit navštívením této adresy:
<?=$this->testingUrl?>


--
S přátelským pozdravem,
vývojový tým Centrálního portálu knihoven.

Adresa beta verze portálu:
https://beta.knihovny.cz/