<?
  // Set page title.
  $this->headTitle($this->translate('Infobox').' | '.$this->translate('Administration'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '' .
      '<li>'.
        '<a href="/Search" title="'.$this->transEsc('Main page').'">'.
          $this->transEsc('Main page').
        '</a>'.
      '</li>'.
      '<li>'.
        '<a href="'.$this->url('myresearch-home').'" title="'.$this->transEsc('Your Account').'">'.
          $this->transEsc('Your Account').
        '</a>'.
      '</li>'.
      '<li>'.
        '<a href="/Admin/Home" title="'.$this->transEsc('Administration').'">'.
          $this->transEsc('Administration').
        '</a>'.
      '</li>'.
      '<li><a href="/Admin/Widgets" title="'.$this->transEsc('Widgets').'">'.$this->transEsc('Widgets').'</a></li>'.
      '<li class="active">'.$this->transEsc('Infobox').'</li>'.

  $this->layout()->title = $this->transEsc('Infobox');
?>
<div class='row clearfix'>
  <ul class='breadcrumb hidden-print'><?=$this->layout()->breadcrumbs?></ul>

  <div class='col-sm-3'>
    <?=$this->render('admin/menu.phtml')?>
  </div>

  <div class='col-sm-9' id='homepage-infobox'>
    <h2><?=$this->translate('Infobox')?></h2>
    <div class='well'>
      <div class='row'>
        <div class='col-md-12 text-center'>
          <div class='admin-toolbox pull-left'>
            <a href='/Admin/Infobox/CreateItem'>
              <button class='btn btn-lg btn-primary'><?=$this->translate('Create new')?></button>
            </a>
          </div>
          <table class='table table-hover table-responsive'>
            <thead>
              <tr>
                <th><?=$this->transEsc('Title')?></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <? foreach($this->infobox as $item): ?>
              <tr>
                <td align='left'><?=$this->escapeHtml($item->getTitleCs())?></td>
                <td>
                  <div class='dropdown pull-right'>
                    <span id='actions'
                          class='actions'
                          aria-expanded='true'
                          aria-haspopup='true'
                          data-toggle='dropdown'>
                      <i class='fa fa-ellipsis-v dropdown-toggle pointer'></i>
                    </span>
                    <ul class='dropdown-menu' aria-labelledby='actions'>
                      <li>
                        <a href='/Admin/Infobox/EditItem/<?=$item->getId()?>' title='<?=$this->translate('Edit')?>'>
                          <i class='fa fa-edit'></i>
                          <?=$this->translate('Edit')?>
                        </a>
                      </li>
                    </ul>
                  </div>
                </td>
              </tr>
              <? endforeach; ?>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>