<?
    // Set up page title:
    $this->headTitle($this->translate('Interlibrary Loan Requests'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a> <span class="divider">&gt;</span></li>'
        . '<li class="active">' . $this->transEsc('Interlibrary Loan Requests') . '</li>';

?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <h2><?=$this->transEsc('Interlibrary Loan Requests') ?></h2>

  <?=$this->flashmessages()?>

  <form class="form-horizontal edit-list-form" method="post" name="test" action="">

    <?foreach($this->fields as $groupName => $elements):?>
      <h2><?=$this->transEsc($groupName)?></h2>
      <?foreach($elements as $field => $attributes):?>
        <div class="control-group">
          <label class="control-label" for="list_desc">
            <?=$this->transEsc($attributes['label'])?>
            <?=($attributes['required'])?'*':''?>
          </label>
          <div class="controls">
            <input type="text" name="<?=$this->escapeHtml($field)?>" id="<?=$this->escapeHtml($field)?>" value="<?=$this->escapeHtml($attributes['value'])?>"/>
          </div>
        </div>
      <?endforeach;?>
    <?endforeach;?>

    <div class="control-group">
      <input class="btn btn-primary" type="submit" name="placeIll" value="<?=$this->transEsc('request_submit_text')?>"/>
    </div>

  </form>
</div>

<div class="<?=$this->layoutClass('sidebar')?>">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'ILLRequests'))?>
</div>
