<?
  // Set page title.
  $this->headTitle($this->translate('configuration_approval'));
  
  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/">' . $this->transEsc('Main page') . '</a></li> ' .
      '<li class="active"><a href="/Admin/Approval">'.$this->transEsc('configuration_approval').'</a></li> ';
  $this->layout()->title = $this->translate('configuration_approval');
?>
<div class="row clearfix">
  <ul class="breadcrumb hidden-print"><?=$this->layout()->breadcrumbs ?></ul>
  
  <div class="col-sm-3">
    <?=$this->render("admin/menu.phtml")?>
  </div>
  <div class="col-sm-9 well">
    <h2><?=$this->transEsc('configuration_approval')?></h2>
    <?=$this->flashmessages() ?>
    <? $hasRequests = false;
      foreach($configs as $source => $config):
    
        $diff = $config['diff'];
        $configRequested = $config['requested'];
        $configActive = $config['active'];
        
        if (! empty($config['requested'])):
          $hasRequests = true;
    ?>
      <div class='well'>
        <form action='/Admin/Approval' method='POST'>
        <table class="table table-striped col-sm-12">
          <thead>
            <tr><td colspan="2"><h3><?=$this->transEsc('source_' . $source)?><img class="pull-right" src="<?=$this->logos()->getLogo($source) ?>" height="32"></h3></td></tr>
          </thead>
          <tbody>
         <? foreach($configRequested as $section => $keys): if(! empty($keys)): ?>
            <tr><td colspan="2"><b>[<?=$section ?>]</b></td></tr>
            <? foreach($keys as $key => $value):
                $isChanged = $value != $configActive[$section][$key];?>
            <tr>
              <td class="col-sm-3"><?=$key ?></td>
              <? if ($isChanged): ?>
                <td class="col-sm-9">
                  <? if (! empty($configActive[$section][$key])): ?>
                    <del style="color: red"><?=$configActive[$section][$key] ?></del>
                    <br>
                  <? endif; ?>
                  <ins style="color: green"><?=$value ?></ins>
                </td>
              <? else: ?>
                <td class="col-sm-9"><?=$value ?></td>
              <? endif; ?>
            </tr>
            <? endforeach; ?>
          <? endif; endforeach; ?>
          </tbody>
        </table>
        <div class="btn-group">
          <input class="btn btn-primary" type="submit" value="<?=$this->transEsc('approve_config_change') ?>"/>
        </div>
        <input type='hidden' name='source' value='<?=$source ?>'/>
        </form>
      </div>
      <? endif; endforeach; ?>
      <? if (! $hasRequests): ?>
        <div class='well'>
          <?=$this->transEsc('approve_no_requests') ?>
        </div>
      <? endif ?>
  </div>
</div>