<?
  // Set page title.
  $this->headTitle($this->translate('Portal pages | Administration'));
  
  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/">' . $this->transEsc('Main page') . '</a></li> ' .
      '<li><a href="/Admin/Home">'.$this->transEsc('Administration').'</a></li>'.
      '<li><a href="/Admin/PortalPages">'.$this->transEsc('Portal pages').'</a></li>'.
      '<li class="active">'.$this->translate('Edit').': '.htmlspecialchars($this->page['title']).'</li>';
  
  $this->layout()->title = $this->translate('Portal pages');
?>
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
<script>
	jQuery( document ).ready( function( $ ) {
		tinymce.init({ 
			selector:'.editor', 
			toolbar: [
			  	'undo redo | styleselect | bold italic underline | link image | alignleft aligncenter alignright | bullist numlist | image | link | table | preview'
			],
			plugins: "image imagetools link preview table",
			menubar: "edit insert view format",
			invalid_styles: {
			    '*': 'font-family'
			}
		});
		
		$( '#deletePage' ).on( 'click', function( event ) {
			event.preventDefault();
			var url = $ ( this ).attr( 'href' );
			if (confirm("<?=$this->translate('Do you really want to delete this page?')?>") == true) {
				window.location.href = url;
		    }
		});

		if ($( '#view' ).val() == 'advanced-search') {
			$( '.position-placeholder' ).addClass( 'hidden' );
		}
		$( '#view' ).on( 'change', function() {
			if( $( this ).val() == 'advanced-search' ) {
				$( '.position-placeholder' ).addClass( 'hidden' );
			} else {
				$( '.position-placeholder' ).removeClass( 'hidden' );
			}
		});
		
	});
</script>
<div class="row clearfix">
  <ul class="breadcrumb hidden-print"><?=$this->layout()->breadcrumbs ?></ul>
  
  <div class="col-sm-3">
    <?=$this->render("admin/menu.phtml")?>
  </div>
  
  <div class="col-sm-9">
    <h2><?=$this->translate('Edit').': '.htmlspecialchars($this->page['title'])?></h2>
    <div class='well'>
      <div>
        <? if (! empty($this->page)): ?>
        <form action='/Admin/PortalPages/Save' method='post'>
          <div class='admin-toolbox'>
            <div class="dropdown pull-right">
              <span class='actions' id="actions" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                <i class='fa fa-ellipsis-v fa-2x dropdown-toggle pointer'></i>
              </span>
              <ul class="dropdown-menu" aria-labelledby="actions">
                <li>
                  <a target='_blank' href='/Portal/Page/<?= $this->page['pretty_url'] ?>?displayToken=94752eedb5baaf2896e35b4a76d9575c'>
                    <i class='fa fa-tv'></i>
                    <?=$this->translate('Show preview')?>
                  </a>
                </li>
                <li role="separator" class="divider"></li>
                <li>
                  <a href='/Admin/PortalPages/Delete/<?= $this->page['id'] ?>' id='deletePage'>
                    <i class='fa fa-remove'></i>
                    <?=$this->translate('Delete page')?>
                  </a>
                </li>
              </ul>
            </div>
          </div>
          <input type='hidden' name='pageId' value='<?=$this->page['id']?>'>
          <input type='hidden' name='userId' value='<?=$this->user['id']?>'>
          <fieldset class="form-group">
            <div class="col-xs-8">
              <label><?=$this->translate('Site title')?></label>
              <input class='form-control' name='title' type='text' value='<?=htmlspecialchars($this->page['title'])?>'>
            </div>
          </fieldset>
          <fieldset class="form-group">
            <div class="col-xs-3">
              <label><?=$this->translate('Language')?></label>
              <select class='form-control' name='language'>
                <? foreach($this->layout()->allLangs as $langCode => $langName): ?>
                <option value='<?=$langCode?>'<?=($langCode == $page['language_code']) ? 'selected="selected"' : ''?>><?=$this->translate($langName)?></option>
                <? endforeach; ?>
              </select>
            </div>
          </fieldset>
          <fieldset class="form-group">
            <div class="col-xs-3">
              <label><?=$this->translate('Placement')?></label>
              <select id='view' class='form-control' name='placement'>
                <? foreach($this->placements as $placement): ?>
                <option value='<?=$placement?>'<?= ($this->page['placement'] == $placement) ? " selected='selected'" : ""?>><?=$this->translate($placement)?></option>
                <? endforeach; ?>
              </select>
            </div>
          </fieldset>
          <fieldset class="form-group position-placeholder">
            <div class="col-xs-3">
              <label><?=$this->translate('Position')?></label>
              <select id='view' class='form-control' name='position'>
                <? foreach($this->positions as $position): ?>
                <option value='<?=$position?>'<?= ($this->page['position'] == $position) ? " selected='selected'" : ""?>><?=$this->translate($position)?></option>
                <? endforeach; ?>
              </select>
            </div>
          </fieldset>
          <fieldset class="form-group">
            <div class="col-xs-1">
              <label><?=$this->translate('Published')?></label>
              <input type='checkbox' class='form-control' name='published' value='1' <?=($this->page['published'] == 1) ? 'checked': ''?>>
            </div>
          </fieldset>
          <fieldset class="form-group">
            <div class="col-xs-3">
              <label><?=$this->translate('Order priority')?></label>
              <input type='number' class='form-control' name='orderPriority' value='<?=$this->page['order_priority']?>' placeholder='<?=$this->translate('Enter number')?>'>
            </div>
          </fieldset>
          <fieldset class="form-group">
            <label><?=$this->translate('Content')?></label>
            <textarea rows='15' class='form-control editor' name='content'><?=$this->page['content']?></textarea>
          </fieldset>
          <fieldset class="form-group">
            <input type='submit' class='btn btn-lg btn-primary pull-right' value='<?=$this->translate('Save')?>'>
          </fieldset>
        </form>
        <? endif; ?>
      </div>
    </div>
  </div>
</div>