<?
  // Set page title.
  $this->headTitle($this->translate('Administration'));
  
  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/">' . $this->transEsc('Main page') . '</a></li> ' .
      '<li class="active"><a href="/Admin/Home">'.$this->transEsc('Administration').'</a></li> ';
  $this->layout()->title = $this->translate('Administration');
?>
<div class="row clearfix">
  <ul class="breadcrumb hidden-print"><?=$this->layout()->breadcrumbs ?></ul>
  
  <div class="col-sm-3">
    <?=$this->render("admin/menu.phtml")?>
  </div>
  
  <div class="col-sm-9 well">
    <h2><?=$this->transEsc('Administration')?></h2>
    <? foreach($configs as $source => $config): ?>
      <div class='well'>
        <h3><?=$source?></h3>
        <? foreach($config as $section => $keys): ?>
        <table>
          <thead>
            <tr><?=$section ?></tr>
          </thead>
          <tbody>
            <? foreach($keys as $key => $value): ?>
            <tr>
              <td><?=$key ?></td>
              <td><?=$value ?></td>
            </tr>
            <? endforeach; ?>
          </tbody>
        </table>
        <? endforeach; ?>
      </div>
    <? endforeach; ?>
  </div>
</div>