<?
  // Set page title.
  $this->headTitle($this->translate('Administration'));
  
  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/">' . $this->transEsc('Main page') . '</a></li> ' .
      '<li class="active"><a href="/Admin/Home">'.$this->transEsc('Administration').'</a></li> ';
  $this->layout()->title = $this->translate('Administration');
?>
<div class="row clearfix">
  <ul class="breadcrumb hidden-print"><?=$this->layout()->breadcrumbs ?></ul>
  
  <div class="col-sm-3">
    <?=$this->render("admin/menu.phtml")?>
  </div>
  <div class="col-sm-9 well">
    <h2><?=$this->transEsc('Administration')?></h2>
    <?=$this->flashmessages() ?>
    <? foreach($configs as $source => $configs):
    
        $hasRequested = ! empty($configs['requested']);
        
        $isAleph = isset($configs['active']['Catalog']['dlfport']);
        
        $template = $isAleph ? $alephTemplate : $ncipTemplate;
        
        $defs = $template['Definitions'];
        unset($template['Definitions']);
        
        $config = $hasRequested ? $configs['requested'] : $configs['active'];
    ?>
      <div class='well'>
        <form action='/Admin/Home' method='POST'>
        <table class="col-sm-12">
          <thead>
            <tr><td colspan="2"><h3><?=$this->transEsc('source_' . $source)?></h3></td></tr>
            <? if ($hasRequested): ?>
              <tr><td colspan="2"><div class="alert alert-warning"><?=$this->transEsc('request_config_change_pending') ?></div></td></tr>
            <? endif; ?>
          </thead>
          <tbody>
         <? foreach($template as $section => $keys): if(! empty($keys) && ! in_array($section, $restrictedSections)): ?>
            <tr><td colspan="2"><b>[<?=$section ?>]</b></td></tr>
            <? foreach($keys as $key => $value):
                if (! in_array($section . ':' . $key, $defs['hidden'])): ?>
            <tr>
              <td class="col-sm-3"><?=$key ?></td>
              <td class="col-sm-9">
                <input class="form-control"
                	type="<?=$defs[$section][$key] ?>"
                	value="<?=$config[$section][$key] ?>"
                	<?=( $defs[$section][$key] === 'checkbox' && $config[$section][$key] ) ? 'checked="checked"':''; ?>
                	placeholder="<?=$this->transEsc($value) ?>"
                	name="<?=$section . '[' . $key . ']' ?>"
                	<?=in_array($section . ':' . $key, $defs['optional']) ? '' : 'required'?>/>
              </td>
            </tr>
            <?  endif; 
               endforeach; ?>
          <? endif; endforeach; ?>
          </tbody>
        </table>
        <div class="btn-group">
          <input class="btn btn-primary" name="requestChange" type="submit" value="<?=$this->transEsc('request_config_change') ?>"/>
          <? if ($hasRequested): ?>
            <input class="btn btn-primary" name="requestChangeCancel" type="submit" value="<?=$this->transEsc('request_config_change_cancel') ?>" formnovalidate/>
          <? endif; ?>
        </div>
        <input type='hidden' name='source' value='<?=$source ?>'/>
        </form>
      </div>
      <? endforeach; ?>
  </div>
</div>