<?
  // Set page title.
  $this->headTitle($this->translate('Administration'));
  
  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/">' . $this->transEsc('Main page') . '</a></li> ' .
      '<li class="active"><a href="/Admin/Home">'.$this->transEsc('Administration').'</a></li> ';
  $this->layout()->title = $this->translate('Administration');
?>
<div class="row clearfix">
  <ul class="breadcrumb hidden-print"><?=$this->layout()->breadcrumbs ?></ul>
  
  <div class="col-sm-3">
    <?=$this->render("admin/menu.phtml")?>
  </div>
  <div class="col-sm-9 well">
    <h2><?=$this->transEsc('Administration')?></h2>
    <?=$this->flashmessages() ?>
    <? foreach($configs as $source => $configs):
    
        $hasRequested = ! empty($configs['requested']);
        
        $isAleph = isset($configs['active']['Catalog']['dlfport']);
        
        $template = $isAleph ? $alephTemplate : $ncipTemplate;
        
        $defs = $template['Definitions'];
        unset($template['Definitions']);
        
        if (! $hasRequested) :
        $config = $configs['active'];
    ?>
      <div class='well'>
        <h3><?=$this->transEsc('source_' . $source)?></h3>
        <? foreach($template as $section => $keys): ?>
        <form action='/Admin/Home' method='POST'>
        <table>
          <thead>
            <tr><b>[<?=$section ?>]</b></tr>
          </thead>
          <tbody>
            <? foreach($keys as $key => $value):
                if (! in_array($key, $defs['hidden'])): ?>
            <tr>
              <td class="col-xs-3"><?=$key ?></td>
              <td class="col-xs-9">
                <input class="form-control"
                	type="<?=$defs[$key] ?>"
                	value="<?=$config[$section][$key] ?>"
                	<?=( $defs[$key] === 'checkbox' && $config[$section][$key] ) ? 'checked="checked"':''; ?>
                	placeholder="<?=$this->transEsc($value) ?>"
                	name="<?=$section . '/' . $key ?>"
                	<?=in_array($key, $defs['optional']) ? '' : 'required'?>/>
              </td>
            </tr>
            <?  endif; 
               endforeach; ?>
            <tr>
              <td>
                <input name="requestChange" type="submit" value="<?=$this->transEsc('request_config_change') ?>"/>
              </td>
            </tr>
          </tbody>
        </table>
        <input type='hidden' name='source' value='<?=$source ?>'/>
        </form>
        <? endforeach; ?>
      </div>
    <? else: // There is already requested change .. show it
        $config = $configs['requested'];
    ?>
      <div class='well'>
        <h3><?=$this->transEsc('source_' . $source)?></h3>
        <div class="alert alert-warning"><?=$this->transEsc('request_config_change_pending') ?></div>
        <? foreach($template as $section => $keys): ?>
        <form action='/Admin/Home' method='POST'>
        <table>
          <thead>
            <tr><b>[<?=$section ?>]</b></tr>
          </thead>
          <tbody>
            <? foreach($keys as $key => $value):
                if (! in_array($key, $defs['hidden'])): ?>
            <tr>
              <td class="col-xs-3"><?=$key ?></td>
              <td class="col-xs-9">
                <input class="form-control"
                	type="<?=$defs[$key] ?>"
                	value="<?=$config[$section][$key] ?>"
                	<?=( $defs[$key] === 'checkbox' && $config[$section][$key] ) ? 'checked="checked"':''; ?>
                	placeholder="<?=$this->transEsc($value) ?>"
                	name="<?=$section . '/' . $key ?>"
                	<?=in_array($key, $defs['optional']) ? '' : 'required'?>/>
              </td>
            </tr>
            <?  endif; 
               endforeach; ?>
            <tr>
              <td>
                <input name="requestChange" type="submit" value="<?=$this->transEsc('request_config_change') ?>"/>
              </td>
              <td>
                <input name="requestChangeCancel" type="submit" value="<?=$this->transEsc('request_config_change_cancel') ?>"/>
              </td>
            </tr>
          </tbody>
        </table>
        <input type='hidden' name='source' value='<?=$source ?>'/>
        </form>
        <? endforeach; ?>
      </div>
    <? endif;
      endforeach; ?>
  </div>
</div>