<aside class="well list-group">
  <a href="/Admin/Configurations" class="list-group-item<?=strtolower($this->layout()->templateName) == "configurations/main" ? ' active' : ''?>"><?=$this->transEsc('configurations')?></a>
  <a href="/Admin/Translations" class="list-group-item<?=strtolower($this->layout()->templateName) == "translations/main" ? ' active' : ''?>"><?=$this->transEsc('translations')?></a>

  <? if ($isPortalAdmin): ?>
    <a href="/Admin/ConfigurationsApproval" class="list-group-item<?=strtolower($this->layout()->templateName) == "configurations/approval" ? ' active' : ''?>"><?=$this->transEsc('configurations_approval')?></a>
    <a href="/Admin/TranslationsApproval" class="list-group-item<?=strtolower($this->layout()->templateName) == "translations/approval" ? ' active' : ''?>"><?=$this->transEsc('translations_approval')?></a>
    <a href="/Admin/PortalPages" class="list-group-item<?=strtolower($this->layout()->templateName) == "portalpages" ? ' active' : ''?>"><?=$this->transEsc('Portal pages')?></a>
    <a href="/Admin/Widgets" class="list-group-item<?=strtolower($this->layout()->templateName) == "widgets/list" ? ' active' : ''?>"><?=$this->transEsc('Widgets')?></a>
    <div style=" margin-left: 15px; ">
    	<a href="/Admin/Infobox" class="list-group-item<?=strtolower($this->layout()->templateName) == "widgets/infobox/list" ? ' active' : ''?>"><?=$this->transEsc('Infobox')?></a>
    	<a href="/Admin/MostWanted" class="list-group-item<?=strtolower($this->layout()->templateName) == "widgets/most-wanted/list" ? ' active' : ''?>"><?=$this->transEsc('Most wanted')?></a>
    	<a href="/Admin/FavoriteAuthors" class="list-group-item<?=strtolower($this->layout()->templateName) == "widgets/favorite-authors/list" ? ' active' : ''?>"><?=$this->transEsc('Favorite authors')?></a>
    </div>
    <a href="/Admin/PermissionsManager" class="list-group-item<?=strtolower($this->layout()->templateName) == "permissions-manager" ? ' active' : ''?>"><?=$this->transEsc('Permissions manager')?></a>
  <? endif; ?>
</aside>
