<?
  // Set page title.
  $this->headTitle($this->translate('translations'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/">' . $this->transEsc('Main page') . '</a></li> ' .
      '<li class="active"><a href="/Admin/Translations">'.$this->transEsc('translations').'</a></li> ';
  $this->layout()->title = $this->translate('translations');

  // Add translations for the javascript
  $this->jsTranslations()->addStrings([
      'remove_translation' => $this->translate('remove_translation'),
      'new_translation_key_already_used' => $this->translate('new_translation_key_already_used'),
      'confirm_translation_delete_of' => $this->translate('confirm_translation_delete_of')
  ]);
?>
<div class="row clearfix">
  <ul class="breadcrumb hidden-print"><?=$this->layout()->breadcrumbs ?></ul>

  <div class="col-sm-3">
    <?=$this->render("admin/menu.phtml")?>
  </div>
  <div class="col-sm-9 well" ng-controller='TranslationsController as transCtrl'>
    <h2><?=$this->transEsc('translations')?></h2>
    <?=$this->flashmessages() ?>
    <? foreach($sourcesBeingAdmin as $source):

        $hasTranslations = isset($translations[$source]);

        $hasRequested = false;

        if ($hasTranslations) {
            $currentTranslations = $translations[$source];

            if (isset($currentTranslations['requested'])) {
                $transRequested = $currentTranslations['requested'];
                $hasRequested = true;
            }

            if (isset($currentTranslations['active'])) {
                $transActive = $currentTranslations['active'];
            }

            $joinedKeys = $currentTranslations['joinedKeys'];
        } else {
            $joinedKeys = $transRequested = $joinedKeys = [];
        }

        $newTransFormId = $source . '_newTrans';
    ?>
      <div class='well'>
        <form action='/Admin/Translations' method='POST' data-source="<?=$source?>">
        <table class="table table-striped">
          <thead>
            <tr><td id="<?=$source?>" class="blickable" colspan="2"><h3><?=$this->transEsc('source_' . $source)?><img class="pull-right" src="<?=$this->logos()->getLogo($source) ?>" height="32"></h3></td></tr>
            <? if ($hasRequested): ?>
              <tr><td colspan="2"><div class="alert alert-warning"><?=$this->transEsc('request_translations_change_pending') ?></div></td></tr>
            <? endif; ?>
          </thead>
          <tbody>
         <? foreach($supportedLanguages as $lang):
            $keys = $joinedKeys[$lang];?>
           <tr ng-language='<?=$source . '_' . $lang ?>' <?=empty($keys) ? "class='hidden'":''?>>
             <td class="text-center" colspan="2"><h5><?=$this->transEsc('lang_' . $lang) ?></h5></td>
           </tr>
            <tr ng-repeat="newTranslation in transCtrl.newTranslations['<?=$source?>']['<?=$lang?>']" ng-new-translation-template>
            </tr>
            <? if (!empty($joinedKeys)): foreach($keys as $key):
              $isChanged = $hasRequested && ((! isset($transActive[$lang][$key])) || $transActive[$lang][$key] != $transRequested[$lang][$key]);
            ?>
            <tr>
              <td><?=$key ?></td>
              <td ng-dblclick="transCtrl.editTranslation($event)">
                <div>
                  <div class="col-xs-11">
                  <? if ($isChanged): ?>
                    <? if (! empty($transActive[$lang][$key])): ?>
                      <del style="color: red"><?=$transActive[$lang][$key] ?></del>
                      <br>
                    <? endif; ?>
                    <ins style="color: green"><?=$transRequested[$lang][$key] ?></ins>
                  <? else: ?>
                    <?=$transActive[$lang][$key] ?>
                  <? endif; ?>
                  </div>
               	  <i class="fa fa-minus-circle pull-right" style="color:red;font-size:1.4em;cursor:pointer;"
              		  ng-click="transCtrl.removeTranslation($event)"
              		  title="<?=$this->transEsc('remove_translation') ?>"></i>
                </div>
                <input class="form-control hidden" type="text" name="<?=$lang . '[' . $key . ']' ?>" required="required"
                	value="<?=$isChanged ? $transRequested[$lang][$key] : $transActive[$lang][$key] ?>"
                	ng-keydown="transCtrl.oldTranslationKeyDown($event)"
                	ng-blur="transCtrl.oldTranslationBlurred($event)"/>
              </td>
            </tr>
          <? endforeach; endif; endforeach;?>
           <tr ng-language='newTransDef'>
             <td class="text-center" colspan="2"><h5><?=$this->transEsc('new_trans_def') ?></h5></td>
           </tr>
          <tr>
          	<td style="vertical-align:middle">
          		<input form="<?=$newTransFormId?>" class="form-control" type="text"
          			value="" name="" ng-new-translation="key" required
          			placeholder="<?=$this->transEsc('insert_new_translation_key') ?>"
          			title="<?=$this->transEsc('insert_new_translation_key') ?>"/>
          	</td>
			<td>
				<div class="col-xs-11">
  				<input form="<?=$newTransFormId?>" class="form-control" type="text"
  					value="" name="" ng-new-translation="cs" required
  					placeholder="<?=$this->transEsc('insert_new_cs_translation') ?>"
  					title="<?=$this->transEsc('insert_new_cs_translation') ?>"/>

  				<input form="<?=$newTransFormId?>" class="form-control" type="text"
  					value="" name="" ng-new-translation="en" required
  					placeholder="<?=$this->transEsc('insert_new_en_translation') ?>"
  					title="<?=$this->transEsc('insert_new_en_translation') ?>"/>
  				</div>
				<i class="fa fa-plus-circle pull-right" style="color:green;font-size:1.4em;cursor:pointer;padding-top: 8%;"
				    ng-click="transCtrl.addTranslation('<?=$source?>',$event)"
					title="<?=$this->transEsc('add_translation') ?>"></i>
				<input form="<?=$newTransFormId?>" type="submit" value="" class="hidden" ng-new-translation="submit" ng-click="transCtrl.addTranslation('<?=$source?>',$event)">
			</td>
          </tr>
          </tbody>
        </table>
        <div class="btn-group">
          <input class="btn btn-primary hidden" name="requestChange" type="submit" value="<?=$this->transEsc('send_for_approval') ?>" ng-submit-btn/>
          <? if ($hasRequested): ?>
            <input class="btn btn-primary" name="requestChangeCancel" type="submit" value="<?=$this->transEsc('request_translations_change_cancel') ?>" formnovalidate/>
          <? endif; ?>
        </div>
        <input type='hidden' name='source' value='<?=$source ?>'/>
        </form>
      	<form action="#<?=$source?>" id="<?=$newTransFormId?>"></form>
      </div>
      <? endforeach; ?>
  </div>
</div>