<?
  // Set page title.
  $this->headTitle($this->translate('translations'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/">' . $this->transEsc('Main page') . '</a></li> ' .
      '<li class="active"><a href="/Admin/Translations">'.$this->transEsc('translations').'</a></li> ';
  $this->layout()->title = $this->translate('translations');
?>
<div class="row clearfix">
  <ul class="breadcrumb hidden-print"><?=$this->layout()->breadcrumbs ?></ul>

  <div class="col-sm-3">
    <?=$this->render("admin/menu.phtml")?>
  </div>
  <div class="col-sm-9 well">
    <h2><?=$this->transEsc('translations')?></h2>
    <?=$this->flashmessages() ?>
    <? foreach($libCards as $libCard):
        $source = $libCard['home_library'];
        $hasRequested = false; // TODO implement some helper?
    ?>
      <div class='well'>
        <form action='/Admin/Translations' method='POST'>
        <table class="table table-striped col-sm-12">
          <thead>
            <tr><td colspan="2"><h3><?=$this->transEsc('source_' . $source)?><img class="pull-right" src="<?=$this->logos()->getLogo($source) ?>" height="32"></h3></td></tr>
            <? if ($hasRequested): ?>
              <tr><td colspan="2"><div class="alert alert-warning"><?=$this->transEsc('request_translations_change_pending') ?></div></td></tr>
            <? endif; ?>
          </thead>
          <tbody>
         <? foreach($storedValues as $key => $value): ?>
            <tr>
              <td class="col-sm-3"><?=$key ?></td>
              <td class="col-sm-9">
                <input class="form-control"
                	type="text"
                	value="<?=$value?>"
                	placeholder="<?=$this->transEsc($value)?>"
                	title="<?=$this->transEsc($value)?>"
                	name="<?=$key?>">
              </td>
            </tr>
          <? endforeach; ?>
          </tbody>
        </table>
        <div class="btn-group">
          <input class="btn btn-primary" name="requestChange" type="submit" value="<?=$this->transEsc('request_translations_change') ?>"/>
          <? if ($hasRequested): ?>
            <input class="btn btn-primary" name="requestChangeCancel" type="submit" value="<?=$this->transEsc('request_translations_change_cancel') ?>" formnovalidate/>
          <? endif; ?>
        </div>
        <input type='hidden' name='source' value='<?=$source ?>'/>
        </form>
      </div>
      <? endforeach; ?>
  </div>
</div>