<?
  // Set page title.
  $this->headTitle($this->translate('translations_approval'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/">' . $this->transEsc('Main page') . '</a></li> ' .
      '<li class="active"><a href="/Admin/TranslationsApproval">'.$this->transEsc('translations_approval').'</a></li> ';
  $this->layout()->title = $this->translate('translations_approval');

  // Add translations for the javascript
  $this->jsTranslations()->addStrings([
      'remove_translation' => $this->translate('remove_translation'),
      'new_translation_key_already_used' => $this->translate('new_translation_key_already_used'),
      'confirm_translation_delete_of' => $this->translate('confirm_translation_delete_of')
  ]);
?>
<div class="row clearfix">
  <ul class="breadcrumb hidden-print"><?=$this->layout()->breadcrumbs ?></ul>

  <div class="col-sm-3">
    <?=$this->render("admin/menu.phtml")?>
  </div>
  <div class="col-sm-9 well" ng-controller='TranslationsController as transCtrl'>
    <h2><?=$this->transEsc('translations_approval')?></h2>
    <?=$this->flashmessages() ?>
    <? $hasRequests = count($translations);
        if (! $hasRequests): ?>
        <div class='well'>
          <?=$this->transEsc('approve_no_requests') ?>
        </div>
        <? else: foreach ($translations as $source => $sourceTranslations):

            unset ($sourceTranslations['hasRequested']);

            $newTransFormId = $source . '_newTrans';
            ?>
        <div class='well'>
        <form action='/Admin/TranslationsApproval' method='POST' data-source="<?=$source?>">
        <table class="table table-striped">
          <thead>
            <tr><th id="<?=$source?>" class="blickable" colspan="4"><h3><?=$this->transEsc('source_' . $source)?><img class="pull-right" src="<?=$this->logos()->getLogo($source) ?>" height="32"></h3></th></tr>
            <tr>
              <th class="col-xs-3"><?=$this->transEsc('translation_key')?></th>
              <? foreach($supportedLanguages as $lang):?>
                <th class="col-xs-4"><?=$this->transEsc('translation_' . $lang)?></th>
              <? endforeach; ?>
              <th class="col-xs-1"><?=$this->transEsc('add_remove')?></th>
            </tr>
          </thead>
          <tbody>
          <? foreach($sourceTranslations as $key => $languageTranslations): ?>
            <tr>
              <td class="col-xs-3"><?=$key ?></td>
              <? foreach($supportedLanguages as $lang):?>
                <td ng-dblclick="transCtrl.editTranslation($event)" class="col-xs-4">
                  <div>
                  <? if (isset($languageTranslations[$lang]['diff'])):
                       $currentValue = $languageTranslations[$lang]['diff']['new'];?>
                    <? if (isset($languageTranslations[$lang]['diff']['old'])): ?>
                      <del style="color: red"><?=$languageTranslations[$lang]['diff']['old'] ?></del>
                      <br>
                    <? endif; ?>
                    <ins style="color: green"><?=$languageTranslations[$lang]['diff']['new'] ?></ins>
                  <? else:
                    $currentValue = $languageTranslations[$lang];?>
                    <?=$languageTranslations[$lang]?>
                  <? endif; ?>
                  </div>
                <input class="hidden" type="text" name="<?=$key . '[' . $lang . ']' ?>" required="required"
                	value="<?=$currentValue ?>"
                	ng-keydown="transCtrl.oldTranslationKeyDown($event)"
                	ng-blur="transCtrl.oldTranslationBlurred($event)"/>
                </td>
              <? endforeach; ?>
              <td class="col-xs-1">
                <a class="btn btn-link" href="#<?=$source?>" ng-click="transCtrl.removeTranslation($event)">
                <i class="fa fa-trash-o"></i> <?=$this->transEsc('remove_translation') ?></a>
              </td>
            </tr>
          <? endforeach; ?>
          <tr>
          	<td class="col-xs-3">
          		<input form="<?=$newTransFormId?>" class="form-control" type="text"
          			value="" name="" ng-new-translation="key" required
          			placeholder="<?=$this->transEsc('translation_key') ?>"
          			title="<?=$this->transEsc('translation_key') ?>"/>
          	</td>
			<td class="col-xs-4">
  				<input form="<?=$newTransFormId?>" class="form-control" type="text"
  					value="" name="" ng-new-translation="cs" required
  					placeholder="<?=$this->transEsc('translation_cs') ?>"
  					title="<?=$this->transEsc('translation_cs') ?>"/>
  			</td>
  			<td class="col-xs-4">
  				<input form="<?=$newTransFormId?>" class="form-control" type="text"
  					value="" name="" ng-new-translation="en" required
  					placeholder="<?=$this->transEsc('translation_en') ?>"
  					title="<?=$this->transEsc('translation_en') ?>"/>
  			</td>
  			<td class="col-xs-1">
  				<a class="btn btn-link" href="#<?=$source?>" ng-click="transCtrl.addTranslation('<?=$source?>',$event)">
  				<i class="pr-interface-plusadd"></i> <?=$this->transEsc('add_translation')?></a>
				<input form="<?=$newTransFormId?>" type="submit" value="" class="hidden" ng-new-translation="submit" ng-click="transCtrl.addTranslation('<?=$source?>',$event)">
			</td>
          </tr>
          </tbody>
        </table>
        <div class="btn-group">
          <input class="btn btn-primary" name="approved" type="submit" value="<?=$this->transEsc('approve_translations_change') ?>" ng-submit-btn/>
          <input class="btn btn-primary" name="denied" type="submit" value="<?=$this->transEsc('deny_translations_change') ?>" formnovalidate/>
        </div>
        <input type='hidden' name='source' value='<?=$source ?>'/>
        </form>
      	<form action="#<?=$source?>" id="<?=$newTransFormId?>"></form>
      </div>
      <? endforeach; endif; ?>
  </div>
</div>