<meta property="og:url"
      content="https://knihovny.cz/" />
<meta property="og:title"
      content="Knihovny.cz" />
<meta property="og:description"
      content="Knihovny pod jednou střechou. Využijte komfort a jednoduchost prohledávání fondů desítek českých knihoven současně. Využijte služeb knihoven, objednávejte, stahujte - kdykoliv a kdekoliv." />
<meta property="og:image"
      content="https://www.knihovny.cz/themes/bootstrap3/images/screenshot_20171130.png" />
<meta property="og:image:secure_url"
      content="https://www.knihovny.cz/themes/bootstrap3/images/screenshot_20171130.png" />
<meta property="og:image:type"
      content="image/png" />
<meta name="referrer"
      content="unsafe-url" />
<link href="/themes/bootstrap3/images/icon-irel.png" rel="icon" type="image/png">