<? $list = $this->params->getSortList(); if (!empty($list)): ?>
    <div class="dropdown" id="sort-container">
      <button class="btn btn-default dropdown-toggle ajax-update-sort" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        <span><?=$this->translate('Sort')." "?></span>
        <span class='value'>
            <?
                foreach ($list as $sortType => $sortData) {
                    if ($sortType == $this->sort) {
                        echo $this->translate($sortData['desc']);
                    }
                }
            ?>
        </span>
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
      	<? foreach ($list as $sortType => $sortData): ?>
            <li><a href="#" class='apply-sort' data-sort='<?=$sortType?>'><?=$this->translate($sortData['desc'])?></a></li>
        <? endforeach; ?>
      </ul>
    </div>
<? endif; ?>