<html>
  <head>
  	<meta charset='UTF-8'>
  	<title>Knihovny.cz</title>
  	<style>
  	 .error-body {
  	     background-color: #f6f6f6;
         color: #333;
         font-family: 'Lato', sans-serif;
         font-size: 15px;
         line-height: 1.42857;
         text-align: center;
  	 }
  	 .error-h2 {
  	     color: #e5004b;
  	 }
  	 .error-well {
  	     background-color: #fff;
  	     padding: 5px;
  	     margin: 50px auto;

  	 }
  	</style>
  	<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
  </head>
  <body class='error-body'>
    <div class='error-well'>
        <h2 class='error-h2'>Došlo k chybě - zkuste, prosím, zopakovat svůj požadavek později.<br> Omlouváme se za nepohodlí.</h2>
        <p>V případě přetrvávajících problémů se na nás můžete obrátit prostřednictvím formuláře zpětné vazby nebo emailem na <a href='mailto:cpk-support@mzk.cz'>cpk-support@mzk.cz.</a></p>
    </div>

	<div class='error-well'>
    	<h2 class='error-h2'>An error has occured - please try your request again later.<br> Sorry for the inconvenience.</h2>
        <p>In case of persistent problems, you can contact us via the feedback form or email <a href='mailto:cpk-support@mzk.cz'>cpk-support@mzk.cz.</a></p>
    </div>
  </body>
</html>