<html>
  <head>
  	<meta charset='UTF-8'>
  	<style>
  	 .error-body {
  	     background-color: #f6f6f6;
         color: #333;
         font-family: 'Lato', sans-serif;
         font-size: 15px;
         line-height: 1.42857;
         text-align: center;
  	 }
  	 .error-h2 {
  	     color: #e5004b;
  	 }
  	 .error-well {
  	     background-color: #fff;
  	     padding: 5px;
  	     margin: 50px auto;

  	 }
  	</style>
  	<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
  </head>
  <body class='error-body'>
    <div class='error-well'>
        <h2 class='error-h2'>Oooops, něco je špatně!</h2>

        <p>Ale nebojte se! Náš vysoce kvalifikovaný personál již sbírá veškeré knihy ze země.</p>
        <p>Omlouváme se za nepohodlí. Zkuste to, prosím, později.</p>
    </div>

	<div class='error-well'>
    	<h2 class='error-h2'>Oooops, something went wrong!</h2>

        <p>But don't worry! Our highly trained units are picking up all the books from ground at the moment.</p>
        <p>Sorry for the inconvenience. Try to come back later.</p>
    </div>
  </body>
</html>