<?
  // Set up page title:
  $pageTitle = empty($this->list->id) ? 'Create a List' : "edit_list";
  $this->headTitle($this->translate($pageTitle));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/Search">' . $this->transEsc('Main page') . '</a></li> '.
  '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'
    . '<li>' . $this->transEsc($pageTitle) . '</li>';
?>

<?=$this->flashmessages()?>
<!--<ul class="breadcrumb hidden-print"><?=$this->layout()->breadcrumbs ?></ul>-->
<h2><?=$this->transEsc($pageTitle); ?></h2>

<form action='' class="form-horizontal edit-list-form" method="post" name="<?=empty($this->list->id) ? 'newList' : 'editListForm'?>">
  <input type="hidden" name="id" value="<?=empty($this->list->id) ? 'NEW' : $this->list->id ?>"/>
  <div class="form-group">
    <label class="col-sm-3 control-label" for="list_title"><?=$this->transEsc('List'); ?>:</label>
    <div class="col-sm-9">
      <input id="list_title" class="form-control" type="text" name="title" value="<?=isset($this->list['title']) ? $this->escapeHtml($this->list['title']) : ''?>"/>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label" for="list_desc"><?=$this->transEsc('Description') ?></label>
    <div class="col-sm-9">
      <textarea id="list_desc" class="form-control" name="desc" rows="3"><?=isset($this->list['description']) ? $this->escapeHtml($this->list['description']) : ''?></textarea>
    </div>
  </div>
  <input type="hidden" name="public" value="0" />
  <div class="form-group">
    <div class="col-sm-9 col-sm-offset-3">
      <input class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEsc('Save') ?>"/>
      <a href="javascript:history.back()" class="btn btn-primary pull-right" title="<?=$this->transEsc('navigate_back')?>">
        <span> <?=$this->transEsc('navigate_back')?></span>
      </a>
    </div>
  </div>
</form>
