<?
$isAJAX = isset($AJAX) && $AJAX === true;
$i = 0;
?>
<? if (!empty($this->data)): ?>
  <? foreach ($this->data as $item): ?>
  <? $libraryId = $item['key']; ?>
  <? $resources = $item['items']; ?>
    <h3 class="well row blickable" style="margin-bottom: 3px;">
      <?= $this->transEsc("source_$libraryId", null, $libraryId) ?>
      <img class="pull-right" height="32" src="<?= $this->logos()->getLogo($libraryId) ?>"/>
    </h3>
    <? if (count($resources)): ?>
      <ul class="media-list">
        <?
        /** @var \CPK\RecordDriver\SolrMarcLocal $resource */
        foreach ($resources as $resource): ?>
          <?
          /** @var \Mzk\ZiskejApi\ResponseModel\Ticket $ticket */
          $ticket = $resource->getExtraDetail('ils_details');
          ++$i;
          ?>

          <li class="media well" id="record_<?= $this->escapeHtml($resource->getUniqueId()) ?>" data-ziskej="<?= $ticket->getId(); ?>">
            <div class="media-left text-center" style="min-width: 100px;">
              <?
              $recordId = $resource->getUniqueId() . $i; //adding order to id (as suffix) to be able to show more covers with same id
              $backLink = $this->serverUrl($this->recordLink()->getUrl($resource));
              $formats = $resource->getFormats();
              $recordId = preg_replace("/[\.:]/", "", $recordId);
              ?>
              <div id="cover_<?= $recordId ?>" class="coverThumbnail">
                <? $bibinfo = $this->record($resource)->getObalkyKnihJSONV3(); ?>
                <? if (!$isAJAX && $bibinfo): ?>
                  <script type="text/javascript">
                    $(document).ready(function () {
                      obalky.display_thumbnail("#cover_<?=$recordId?>", <?=$bibinfo?>, <?=json_encode($this->record($resource)->getObalkyKnihAdvert('checkedout'))?>);
                    });
                  </script>
                <? endif; ?>
              </div>
            </div>
            <div class="media-body">
              <h4 class="media-heading">
                <?
                // If this is a non-missing Solr record, we should display a link:
                if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault')
                  && !is_a($resource, 'VuFind\\RecordDriver\\Missing')): ?>
                  <?
                  $title = $resource->getTitle();
                  $title = empty($title) ? $this->transEsc('Title not available') : $this->escapeHtml($title);
                  ?>
                  <a href="<?= $this->recordLink()->getUrl($resource) ?>" class="title"><?= $title ?></a>
                <? else: ?>
                  <? // Last resort -- indicate that no title could be found. ?>
                  <?= $this->transEsc('Title not available') ?>
                <? endif ?>
              </h4>
              <div>
                <dl class="dl-horizontal dl-left">
                  <? $listAuthor = $resource->getPrimaryAuthor(); ?>
                  <? if (!empty($listAuthor)): ?>
                    <dt><?= $this->transEsc('by') ?>:</dt>
                    <dd>
                      <a href="<?= $this->record($resource)->getLink('author', $listAuthor) ?>">
                        <?= $this->escapeHtml($listAuthor) ?>
                      </a>
                    </dd>
                  <? endif; ?>

                  <? if (count($resource->getFormats()) > 0): ?>
                    <dt><?= $this->transEsc('ziskej_label_document_type') ?>:</dt>
                    <dd><?= $this->record($resource)->getFormatList() ?></dd>
                  <? endif; ?>

                  <? if ($ticket->getDateCreated()): ?>
                    <dt><?= $this->transEsc('ziskej_label_date_order') ?>:</dt>
                    <dd><?= date($this->config->Site->displayDateFormat, $ticket->getDateCreated()->getTimestamp()); ?></dd>
                  <? endif; ?>

                  <? if ($ticket->getDateRequested()): ?>
                    <dt><?= $this->transEsc('ziskej_label_date_deliver') ?>:</dt>
                    <dd><?= date($this->config->Site->displayDateFormat, $ticket->getDateRequested()->getTimestamp()); ?></dd>
                  <? endif; ?>

                  <? if ($ticket->getDateReturn()): ?>
                    <dt><?= $this->transEsc('ziskej_label_date_return') ?>:</dt>
                    <dd><?= date($this->config->Site->displayDateFormat, $ticket->getDateReturn()->getTimestamp()); ?></dd>
                  <? endif; ?>

                  <? if ($ticket->getStatus()): ?>
                    <dt><?= $this->transEsc('ziskej_label_order_status') ?>:</dt>
                    <dd>
                      <span class="label label-<?= \Mzk\ZiskejApi\Object\TicketStatuses::getStatus($ticket->getStatus()) ?>">
                        <?= $this->translate('ziskej_order_status_' . $ticket->getStatus()) ?>
                      </span>
                      <? if (!$ticket->isOpen()): ?>
                        (<?= $this->transEsc('ziskej_order_status_not_open') ?>)
                      <? endif; ?>
                    </dd>
                  <? endif; ?>
                </dl>
                <div class="text-right">
                  <? if ($ticket->getStatus() == 'created' && !empty($ticket->getPaymentUrl())): ?>
                    <a class="btn btn-sm btn-warning" href="<?= $ticket->getPaymentUrl() ?>" target="_blank" title="Uhradit objednávku">
                      <i class="fa fa-shopping-cart"></i> Uhradit objednávku
                    </a>
                  <? endif; ?>
                  <a class="btn btn-sm btn-primary" href="/MyResearch/ZiskejTicket/<?= $item['eppn']; ?>/<?= $ticket->getId() ?>" title="Detail objednávku">
                    <i class="fa fa-search"></i> Detail
                  </a>
                </div>
              </div>
            </div>
          </li>
        <? endforeach; ?>
      </ul>
    <? else: ?>
      <div class="panel">
        <div class="panel-body">
          <div class="alert alert-info">
            <?= $this->transEsc('ziskej_info_no_items') ?>
          </div>
        </div>
      </div>
    <? endif; ?>
  <? endforeach; ?>
<? else: ?>
  <div class="panel">
    <div class="panel-body">
      <div class="alert alert-info">
        <?= $this->transEsc('ziskej_info_no_libraries') ?>
      </div>
    </div>
  </div>
<? endif; ?>
