<?
$isAJAX = isset($AJAX) && $AJAX === true; $i = 0;
foreach ($this->libraryIdentity['transactions'] as $resource):?>
  <? $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
  <? if(remove_accent($ilsDetails['status_label']) == 'Nova'):
        ++$i;?>
    <div id="record<?=$this->escapeHtml($resource->getUniqueId())?>" class="row well" style="margin-bottom: 2px;">
      <div class="col-md-2 text-center">
        <?
          $recordId = $resource->getUniqueId() . $i; //adding order to id (as suffix) to be able to show more covers with same id
          $backLink = $this->serverUrl($this->recordLink()->getUrl($resource));
          $formats = $resource->getFormats();
        ?>
        <? $recordId =  preg_replace("/[\.:]/", "", $recordId)?>
        <div id="cover_<?=$recordId?>" class="coverThumbnail">
          <? if (! $isAJAX && $bibinfo = $this->record($resource)->getObalkyKnihJSONV3()): ?>
            <script type="text/javascript">
              $(document).ready(function() {
                obalky.display_thumbnail("#cover_<?=$recordId?>", <?=$bibinfo?>, <?=json_encode($this->record($resource)->getObalkyKnihAdvert('checkedout'))?>);
              });
            </script>
          <? endif;?>
        </div>
      </div>
      <div class="col-md-9">
        <?
          // If this is a non-missing Solr record, we should display a link:
          if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
            $title = $resource->getTitle();
            $title = empty($title) ? $this->transEsc('Title not available') : $this->escapeHtml($title);
            echo '<a href="' . $this->recordLink()->getUrl($resource) .
              '" class="title">' . $title . '</a>';
          } else if (isset($ilsDetails['title']) && !empty($ilsDetails['title'])){
            // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
            echo $this->escapeHtml($ilsDetails['title']);
          } else {
            // Last resort -- indicate that no title could be found.
            echo $this->transEsc('Title not available');
          }
        ?><br/>
        <? $listAuthor = $resource->getPrimaryAuthor(); if (!empty($listAuthor)): ?>
          <?=$this->transEsc('by')?>:
          <a href="<?=$this->record($resource)->getLink('author', $listAuthor)?>"><?=$this->escapeHtml($listAuthor)?></a><br/>
        <? endif; ?>
        <? $formats = $resource->getFormats(); if (count($formats) > 0): ?>
          <?=$this->record($resource)->getFormatList()?>
          <br/>
        <? endif; ?>

        <? if(isset($ilsDetails['date_created'])): ?>
          <strong><?=$this->transEsc('Date Created')?>:</strong> <?=$this->escapeHtml($ilsDetails['date_created'])?><br/>
        <? endif; ?>
        <? if(isset($ilsDetails['date_return'])): ?>
          <strong><?=$this->transEsc('Due Date')?>: <?=$this->escapeHtml($ilsDetails['date_return'])?></strong><br/>
        <? endif; ?>
        <? if(isset($ilsDetails['date_requested'])): ?>
          <strong><?=$this->transEsc('Date Requested')?>: <?=$this->escapeHtml($ilsDetails['date_requested'])?></strong><br/>
        <? endif; ?>

        <? if($ilsDetails['is_open']): ?>
          <strong><?=$this->transEsc('Is open')?>: <?=$this->translate('Yes')?></strong><br/>
        <?else:?>
          <strong><?=$this->transEsc('Is open')?>: <?=$this->translate('No')?></strong><br/>
        <? endif; ?>

        <? if(isset($ilsDetails['status_label'])): ?>
          <strong><?=$this->transEsc('Status')?>: <?=$this->escapeHtml($ilsDetails['status_label'])?></strong><br/>
        <? endif; ?>
      </div>
    </div>
  <?endif;?>
<? endforeach;

if ($i === 0): ?>
  <div class="row well" style="margin-bottom: 2px;">
    <div class="label label-info">
    <?=$this->transEsc('You do not have any items checked out in this institution')?>.
    </div>
  </div>
<? endif; ?>