<? if ($this->pageCount): ?>

<? if (count($this->pagesInRange) > 1):
    $arrayKeys = array_keys($this->pagesInRange);

    $first_key = current($arrayKeys);
    $lastArrayKey = array_pop($arrayKeys);
    
    $sort = filter_input(INPUT_GET, 'sort');
    if (!empty($sort)) {
      $sort = '&sort='.$sort;
    }
?>

<div class='col-md-12'>
    <div class='row'>

      <div class='col-md-2'>
          <ul class="pagination" style='float: left;'>
            <? if (isset($this->previous)): ?>
              <li><a  href="<?=$this->url('myresearch-favorites')?>?page=<?=$this->previous?><?=$sort?>"><i class="pr-interface-arrowleft"></i>
     <?=$this->transEsc('Prev')?></a></li>
            <? endif; ?>
          </ul>
      </div>

      <div class='col-md-8' style='text-align: center'>
          <ul class="pagination" align='center'>
            <? if (isset($this->previous)): ?>
              <? if (!isset($this->options['disableFirst']) || !$this->options['disableFirst']): ?>
                <? if (! isset($this->pagesInRange[1])): ?>
                  <li><a href="<?=$this->url('myresearch-favorites')?>?page=1<?=$sort?>">1</a></li>
                <? endif; ?>
              <? endif; ?>
            <? endif; ?>

              <? foreach ($this->pagesInRange as $key => $page): ?>

                <? if ($key == ($first_key)): ?>
                  <? if ($first_key > 2): ?>
                    <li class='disabled'><span>...</span></li>
                  <? endif; ?>
                <? endif; ?>

                <? if ($page != $this->current): ?>
                  <li><a href="<?=$this->url('myresearch-favorites')?>?page=<?=$page?><?=$sort?>"><?=$this->localizedNumber($page)?></a></li>
                <? else: ?>
                  <li class="active"><span><?=$page?></span></li>
                <? endif; ?>

                <? if ($key == ($lastArrayKey)): ?>
                  <? if (($this->pageCount != $lastArrayKey) > 0): ?>
                    <li class='disabled'><span>...</span></li>
                  <? endif; ?>
                <? endif; ?>

              <? endforeach; ?>

            <? if (isset($this->next)): ?>
              <? if (!isset($this->options['disableLast']) || !$this->options['disableLast']): ?>
                <? if (! isset($this->pagesInRange[$this->pageCount])): ?>
                  <li><a href="<?=$this->url('myresearch-favorites')?>?page=<?=$this->pageCount?><?=$sort?>"><?=$this->localizedNumber($this->pageCount)?></a></li>
                <? endif; ?>
              <? endif; ?>
            <? endif; ?>
          </ul>
      </div>

      <div class='col-md-2'>
          <ul class="pagination" style='float: right'>
            <? if (isset($this->next)): ?>
              <li style='float: right;'><a href="<?=$this->url('myresearch-favorites')?>?page=<?=$this->next?><?=$sort?>"><?=$this->transEsc('Next');?> <i class="pr-interface-arrowright"></i>
    </a></li>
            <? endif; ?>
          </ul>
      </div>
    </div>
</div>
<? endif; ?>
<? endif; ?>