<?
    // Set up page title:
    $this->headTitle($this->translate('Settings'));
    $this->headLink()->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css');

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/Search">' . $this->transEsc('Main page') . '</a></li> '.
    '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Settings') . '</li>';

    $this->headScript()->appendFile("user-settings.js");
    $this->headScript()->appendFile("//cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js");
?>

<div class="row" id='preferred-insitutions-container'>
  <div class="<?=$this->layoutClass('mainbody')?>">
    <h2><?=$this->transEsc('Settings') ?></h2>
    <div class='row well'>
      <div class="col-lg-4">
        <fieldset class='mb-5'>
          <legend><?=$this->translate('Citations style') ?></legend>
          <select name='citation-style' id="citation-style" class="form-control">
          <? foreach ($this->availableCitationStyles as $style): ?>
            <option<?= ($this->selectedCitationStyle === $style['id']) ? ' selected="selected"' : '' ?>
              value='<?=$style['id']?>'>
              <?=$style['description']?>
            </option>
          <? endforeach; ?>
          </select>
          <span class='citation-style-status'></span>
        </fieldset>
        <fieldset class='mb-5'>
          <legend><?=$this->translate('Records per page') ?></legend>
          <select name='records-per-page' id="records-per-page" class="form-control">
          <? foreach ($this->recordsPerPageOptions as $option): ?>
            <option<?= ($this->selectedRecordsPerPageOption == $option) ? ' selected="selected"' : '' ?>
              value='<?=$option?>'>
              <?=$option?>
            </option>
          <? endforeach; ?>
          </select>
          <span class='records-per-page-status'></span>
        </fieldset>
        <fieldset class='mb-5'>
          <legend><?=$this->translate('Default sorting') ?></legend>
          <select name='preferred-sorting' id="preferred-sorting" class="form-control">
          <? foreach ($this->sortingOptions as $key => $option): ?>
            <option<?= ($this->selectedSorting == $key) ? ' selected="selected"' : '' ?> value='<?=$key?>'>
              <?=$this->transEsc($option)?>
            </option>
          <? endforeach; ?>
          </select>
          <span class='preferred-sorting-status'></span>
        </fieldset>
      </div>
      <div class="col-lg-8">
        <fieldset class='mb-5 preferred-institutions'>
          <legend><?=$this->translate('Preferred institutions') ?></legend>
          <div class="row mb-2">
            <form action="/MyResearch/userUpdateSavedInstitution?action=saveSavedInstitution">
              <span>
                <select id="institutions" name="institution">
                  <?php foreach($institutions as $institution): ?>
                    <option value='<?=$institution['value']?>'>
                      <?=$this->translate($institution['value'])?>
                    </option>
                  <?php endforeach; ?>
                </select>
              </span>
              <button class="btn btn-primary pull-right btn-sm add-institution" id="set-preferred-institutions">
                <?=$this->translate("Add")?>
              </button>
            </form>
          </div>
          <div class="row">
            <table class="table table-striped table-responsive table-condensed">
              <tbody>
                <?php if (! empty($preferredInstitutions)): ?>
                  <?php foreach($preferredInstitutions as $institution): ?>
                    <tr>
                      <td>
                        <?=$this->translate($institution)?>
                      </td>
                      <td>
                        <a href='/MyResearch/userUpdateSavedInstitution?action=removeSavedInstitution&institution=<?=$institution?>'
                           title='<?=$this->translate('Remove')?>'
                           class='pr-interface-crosscancel3 pull-right settings-preferred-institution'>
                        </a>
                      </td>
                    </tr>
                  <?php endforeach; ?>
                <?php endif; ?>
              </tbody>
            </table>
          </div>
        </fieldset>
      </div>
    </div>
  </div>

  <div class="modal-loading"></div>
  <div class="<?=$this->layoutClass('sidebar')?>">
    <?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'settings'))?>
  </div>
</div>

<?=$this->render("Recommend/SideFacets/saveTheseInstitutionsConfirmationModal.phtml")?>
