<? $this->layout()->searchbox = false; ?>
<?
/** @var \Mzk\ZiskejApi\ResponseModel\Ticket $ticket */
$ticket = $this->ticket;

/** @var \VuFind\Db\Row\UserCard $userCard */
$userCard = $this->userCard;
?>
<?
// Set up page title:
$this->headTitle($this->translate('Objednávka Získej č. ') . $ticket->getHid());
?>

<div class="row">
  <div class="<?= $this->layoutClass('mainbody'); ?>">

    <div class="clearfix">

      <h2 class="pull-left">
        <?= $this->transEsc('Objednávka Získej č. ') . $ticket->getHid(); ?>
      </h2>

      <div class="pull-left" style="margin-top: 23px; padding-left: 1em;">
        <span class="label label-<?= \Mzk\ZiskejApi\Object\TicketStatuses::getStatus($ticket->getStatus()) ?>" style="font-size: 18px;">
          <?= $this->translate('ziskej_order_status_' . $ticket->getStatus()) ?>
        </span>
      </div>

    </div>

    <?= $this->flashmessages() ?>

    <?
    $status = $ticket->getStatus();

    $classDone = 'visited';
    $classActive = 'visited current';
    $classWaiting = '';

    ?>

    <div class="well">
      <ul class="nav-wizard">
        <? if ($status == 'created'): ?>
          <li class="part <?= $classActive; ?>">Vytvořena</li>
          <li class="part <?= $classWaiting; ?>">Uhrazena</li>
          <li class="part <?= $classWaiting; ?>">Ve zpracování</li>
          <li class="part <?= $classWaiting; ?>">Připravena</li>
          <li class="part <?= $classWaiting; ?>">Vypůjčena</li>
          <li class="part <?= $classWaiting; ?>">Uzavřena</li>
        <? elseif ($status == 'paid'): ?>
          <li class="part <?= $classDone; ?>">Vytvořena</li>
          <li class="part <?= $classActive; ?>">Uhrazena</li>
          <li class="part <?= $classWaiting; ?>">Ve zpracování</li>
          <li class="part <?= $classWaiting; ?>">Připravena</li>
          <li class="part <?= $classWaiting; ?>">Vypůjčena</li>
          <li class="part <?= $classWaiting; ?>">Uzavřena</li>
        <? elseif ($status == 'accepted'): ?>
          <li class="part <?= $classDone; ?>">Vytvořena</li>
          <li class="part <?= $classDone; ?>">Uhrazena</li>
          <li class="part <?= $classActive; ?>">Ve zpracování</li>
          <li class="part <?= $classWaiting; ?>">Připravena</li>
          <li class="part <?= $classWaiting; ?>">Vypůjčena</li>
          <li class="part <?= $classWaiting; ?>">Uzavřena</li>
        <? elseif ($status == 'prepared'): ?>
          <li class="part <?= $classDone; ?>">Vytvořena</li>
          <li class="part <?= $classDone; ?>">Uhrazena</li>
          <li class="part <?= $classDone; ?>">Ve zpracování</li>
          <li class="part <?= $classActive; ?>">Připravena</li>
          <li class="part <?= $classWaiting; ?>">Vypůjčena</li>
          <li class="part <?= $classWaiting; ?>">Uzavřena</li>
        <? elseif ($status == 'lent'): ?>
          <li class="part <?= $classDone; ?>">Vytvořena</li>
          <li class="part <?= $classDone; ?>">Uhrazena</li>
          <li class="part <?= $classDone; ?>">Ve zpracování</li>
          <li class="part <?= $classDone; ?>">Připravena</li>
          <li class="part <?= $classActive; ?>">Vypůjčena</li>
          <li class="part <?= $classWaiting; ?>">Uzavřena</li>
        <? elseif ($status == 'closed'): ?>
          <li class="part <?= $classDone; ?>">Vytvořena</li>
          <li class="part <?= $classDone; ?>">Uhrazena</li>
          <li class="part <?= $classDone; ?>">Ve zpracování</li>
          <li class="part <?= $classDone; ?>">Připravena</li>
          <li class="part <?= $classDone; ?>">Vypůjčena</li>
          <li class="part <?= $classActive; ?>">Uzavřena</li>
        <? elseif ($status == 'cancelled'): ?>
          <li class="part <?= $classDone; ?>">Vytvořena</li>
          <? /*<li class="part <?= $classDone; ?>">Uhrazena</li> //@todo */ ?>
          <li class="part <?= $classActive; ?>">Zrušena</li>
        <? elseif ($status == 'rejected'): ?>
          <li class="part <?= $classDone; ?>">Vytvořena</li>
          <li class="part <?= $classActive; ?>">Zamítnuta</li>
        <? endif; ?>
        <? //rejected ?>
      </ul>
    </div>

    <div class="text-center well border" style="margin-bottom: 1em;">
      <? if (in_array($ticket->getStatus(), ['created'])): ?>
        <a class="btn btn-primary" href="<?= $ticket->getPaymentUrl(); ?>?lang=<?= $this->layout()->userLang; ?>" title="Uhradit objednávku">
          <i class="fa fa-shopping-cart"></i> Uhradit objednávku
        </a>
      <? endif; ?>
      <? if (in_array($ticket->getStatus(), ['created', 'paid'])): ?>
        <a class="btn btn-info" href="/MyResearch/ZiskejTicketCancel/<?= $userCard->eppn; ?>/<?= $ticket->getId() ?>"
           title="Stornovat objednávku"
           onclick="return confirm('<?= sprintf("Opravdu chcete stornovat objednávku číslo %s?", $ticket->getHid()); ?>')">
          <i class="fa fa-times"></i> Stornovat objednávku
        </a>
      <? endif; ?>
      <? if (in_array($ticket->getStatus(), ['cancelled'])): ?>
        <div class="alert alert-info">Objednávka byla stornována.</div>
      <? endif; ?>
      <a class="btn btn-default" href="https://ziskej-info.techlib.cz/reklamace" target="_blank" title="Reklamovat objednávku">
        <i class="fa fa-exclamation-triangle"></i>
        Reklamovat objednávku
      </a>
    </div>

    <h3>Detail objednávky</h3>
    <div class="well border">

      <dl class="dl-horizontal dl-left">
        <? if (!empty($ticket->getCreatedAt())): ?>
          <dt><?= $this->transEsc('date_ordered'); ?>:</dt>
          <dd><?= $ticket->getCreatedAt()->format('j. n. Y H:i'); ?></dd>
        <? endif; ?>

        <? if (!empty($ticket->getUpdatedAt())
          && ($ticket->getUpdatedAt()->getTimestamp() != $ticket->getCreatedAt()->getTimestamp())): ?>
          <dt><?= $this->transEsc('date_updated'); ?>:</dt>
          <dd><?= $ticket->getUpdatedAt()->format('j. n. Y H:i'); ?></dd>
        <? endif; ?>

        <? if (!empty($ticket->getRequestedAt())): ?>
          <dt><?= $this->transEsc('date_requested'); ?>:</dt>
          <dd><?= $ticket->getRequestedAt()->format('j. n. Y'); ?></dd>
        <? endif; ?>

        <? if (!empty($ticket->getReturnAt())): ?>
          <dt><?= $this->transEsc('ziskej_label_date_return'); ?>:</dt>
          <dd><?= $ticket->getReturnAt()->format('j. n. Y'); ?></dd>
        <? endif; ?>

        <? /*
        <dt><?= $this->transEsc('ziskej_label_order_status'); ?>:</dt>
        <dd>
          <span class="label label-<?= \Mzk\ZiskejApi\Object\TicketStatuses::getStatus($ticket->getStatus()) ?>">
            <?= $this->translate('ziskej_order_status_' . $ticket->getStatus()) ?>
          </span>
          <? if (!$ticket->isOpen()): ?>
            (<?= $this->transEsc('ziskej_order_status_not_open') ?>)
          <? endif; ?>
        </dd>
        */ ?>
      </dl>
    </div>

    <h3>Dokument</h3>
    <div class="well border">
      <? include('_ziskejticket-core.phtml'); ?>
      <div class="text-right">
        <a href="<?= $this->recordLink()->getUrl($this->driver) ?>" class="title">Zobrazit detail</a>
      </div>
    </div>

    <h3>
      Zprávy k objednávce
      <? if ($ticket->getCountMessages() > 0): ?>
        <span class="badge"><?= $ticket->getCountMessages(); ?></span>
      <? endif; ?>
    </h3>

    <div class="well border">
      <? if (count($this->messages)): ?>
        <?
        /** @var \Mzk\ZiskejApi\ResponseModel\Message $message */
        foreach ($this->messages as $message): ?>
          <ul class="media-list">
            <li class="media">
              <div class="media-body">
                <p class="media-heading">
                  <? if ($message->getSender() == 'reader'): ?>
                    <span title="Vy"><i class="fa fa-user"></i></span>
                  <? else: ?>
                    Knihovna
                  <? endif; ?>
                  <?= $message->getCreatedAt()->format('j. n. Y H:i'); ?>
                </p>
                <div>
                  <?= $message->getText(); ?>
                </div>
              </div>
            </li>
          </ul>
        <? endforeach; ?>
      <? else: ?>
        <div class="alert alert-info">
          Objednávka neobsahuje žádné zprávy
        </div>
      <? endif; ?>

      <div>
        <hr>
        <h4>Nová zpráva</h4>
        <form method="post" action="/MyResearch/ZiskejTicketCreateMessageForm/<?= $userCard->eppn; ?>/<?= $ticket->getId() ?>">
          <div class="form-group">
            <label for="ticketMessage">Zpráva:</label>
            <textarea name="ticketMessage" id="ticketMessage" class="form-control" rows="3" required></textarea>
          </div>
          <button type="submit" class="btn btn-primary">Odeslat zprávu</button>
        </form>
      </div>
    </div>

  </div>


  <div class="<?= $this->layoutClass('sidebar') ?>">
    <?= $this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'ziskej')) ?>
  </div>

</div>
