<?
    // Set up convenience variables:
    $account = $this->auth()->getManager();
    $user = $account->isLoggedIn();
    $holdings = $this->driver->getRealTimeHoldings();
    $openUrl = $this->openUrl($this->driver, 'holdings');
    $openUrlActive = $openUrl->isActive();
    // Account for replace_other_urls setting
    $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
    $offlineMode = $this->ils()->getOfflineMode();
    // Set page title.
    $this->headTitle($this->translate('Holdings') . ': ' . $this->driver->getBreadcrumb());
?>
<? if ($offlineMode == "ils-offline"): ?>
  <div class="sysInfo">
    <h2><?=$this->transEsc('ils_offline_title')?></h2>
    <p><strong><?=$this->transEsc('ils_offline_status')?></strong></p>
    <p><?=$this->transEsc('ils_offline_holdings_message')?></p>
    <? $supportEmail = $this->escapeHtml($this->systemEmail()); ?>
    <p><a href="mailto:<?=$supportEmail?>"><?=$supportEmail?></a></p>
  </div>
<? endif; ?>
<? if (($this->ils()->getHoldsMode() == 'driver' && !empty($holdings)) || $this->ils()->getTitleHoldsMode() == 'driver'): ?>
  <? if ($account->loginEnabled() && $offlineMode != 'ils-offline'): ?>
    <? if (!$user): ?>
      <div class="info">
        <a href="<?=$this->currentPath()?>?login=true&catalogLogin=true"><?=$this->transEsc("Login")?></a> <?=$this->transEsc("hold_login")?>
      </div>
    <? elseif (!$user->cat_username): ?>
      <div class="info">
        <?=$this->translate("hold_profile_html", array('%%url%%' => $this->currentPath() . '?catalogLogin=true'))?>
      </div>
    <? endif; ?>
  <? endif; ?>
<? endif; ?>
<? $holdingTitleHold = $this->driver->tryMethod('getRealTimeTitleHold'); if (!empty($holdingTitleHold)): ?>
    <a class="holdPlace" href="<?=$this->recordLink()->getHoldUrl($holdingTitleHold)?>"><?=$this->transEsc('title_hold_place')?></a>
<? endif; ?>
<? if (!empty($urls) || $openUrlActive): ?>
  <h3><?=$this->transEsc("Internet")?></h3>
  <? if (!empty($urls)): ?>
    <? foreach ($urls as $current): ?>
      <a href="<?=$this->escapeHtml($this->proxyUrl($current['url']))?>"><?=$this->escapeHtml($current['desc'])?></a><br/>
    <? endforeach; ?>
  <? endif; ?>
  <? if ($openUrlActive): ?><?=$openUrl->renderTemplate()?><? endif; ?>
<? endif; ?>

<div class="holdings-filters">
  <? foreach($filters as $name => $values):?>
    <? if (!empty($values)):?>
      <? $filterName = $this->escapeHtml($name . '_filter');?>
      <? $selectedVal = $selectedFilters[$name];?>
      <? $type = $availableFilters[$name]['type'];?>
      <div class="col-md-3">
        <form class="form-inline" name="<?=$this->escapeHtml($name)?>_filter">
          <?if ($type == 'select'):?>
            <label for="<?=$this->escapeHtml($name)?>"><?=$this->transEsc($filterName)?> : </label>
            <select name="<?=$this->escapeHtml($name)?>" onchange="document.forms['<?=$filterName?>'].submit()">
              <option value=""><?=$this->transEsc('all')?></option>
              <? foreach($values as $value):?>
                <option value="<?=$this->escapeHtml($value)?>" <?=($selectedVal == $value)?'selected="selected"':''?>><?=$this->escapeHtml($value)?></option>
              <? endforeach;?>
            </select>
          <?endif;?>
          <?if ($type == 'checkbox'):?>
            <input type="checkbox" name="<?=$this->escapeHtml($name)?>" value="true"
              onchange="document.forms['<?=$filterName?>'].submit()"
              <?=($selectedVal == 'true')?'checked="true"':''?>
              >
            <label for="<?=$this->escapeHtml($name)?>"><?=$this->transEsc($filterName)?></label>
          <?endif;?>
          <?=$this->tab->asHiddenFields($name);?>
        </form>
      </div>
    <? endif; ?>
  <? endforeach;?>
</div>

<? $holdLink = $this->driver->getHoldLink();?>
<? if ($holdLink != null) : ?>
  <a href="<?=$holdLink?>"><?=$this->transEsc("Holdings in catalogue")?></a>
<? else : ?>
<table class="table table-striped">
<tbody>
  <tr>
    <th><?=$this->transEsc("item status")?>&nbsp;</th>
    <th><?=$this->transEsc("due date")?>&nbsp;</th>
    <th><?=$this->transEsc("sublibrary")?>&nbsp;</th>
    <th><?=$this->transEsc("collection")?>&nbsp;</th>
    <th><?=$this->transEsc("location / second signature")?>&nbsp;</th>
    <th><?=$this->transEsc("description")?>&nbsp;</th>
    <th><?=$this->transEsc("note")?>&nbsp;</th>
  </tr>
<? $row = 0; ?>
<? foreach ($holdings as $row): ?>
  <? $check = (isset($row['check']) && $row['check']); ?>
  <? $row++; ?>
  <tr class="<?=(($row % 2) == 0)?'oddrow':'evenrow'?>">
    <td>
      <span class="<?=($row['availability'])?'available':'checkedout'?>"><?=$this->escapeHtml($row['status'])?></span>
      <? if ($row['reserve'] == "Y"): ?>
      <?=$this->transEsc("On Reserve - Ask at Circulation Desk")?>
      <? elseif (isset($row['use_unknown_message']) && $row['use_unknown_message']): ?>
        <span class="unknown"><?=$this->transEsc("status_unknown_message")?></span>
      <? else: ?>
        <? if ($row['availability']): ?>
          <? /* Begin Available Items (Holds) */ ?>
          <div>
          <? if (isset($row['link']) && $row['link']): ?>
            <a class="holdPlace<?=$check ? ' checkRequest' : ''?>" href="<?=$this->recordLink()->getHoldUrl($row['link'])?>"><span><?=$this->transEsc($check ? "Check Hold" : "Place a Hold")?></span></a>
          <? endif; ?>
          </div>
        <? else: ?>
          <div>
          <? if (isset($row['link']) && $row['link']): ?>
            <a class="holdPlace<?=$check ? ' checkRequest' : ''?>" href="<?=$this->recordLink()->getHoldUrl($row['link'])?>"><span><?=$this->transEsc($check ? "Check Recall" : "Recall This")?></span></a>
          <? endif; ?>
          </div>
        <? endif; ?>
      <? endif; ?>
    </td>
    <td>
      <?=$this->escapeHtml($row['duedate'])?>
    </td>
    <td>
      <?=$this->escapeHtml($row['sub_lib_desc'])?>
    </td>
    <td>
      <?=$this->escapeHtml($row['collection_desc'])?>
    </td>
    <td>
      <?=$this->escapeHtml($row['callnumber_second'])?>
    </td>
    <td>
      <?=$this->escapeHtml($row['description'])?>
    </td>
    <td>
      <? if ($row['notes'] != null):?>
        <?=$this->escapeHtml($row['notes'][0])?>
      <? endif;?>
    </td>
  </tr>
<? endforeach; ?>
</tbody>
</table>
<? endif; ?>

<? $history = $this->driver->getRealTimeHistory(); ?>
<? if (is_array($history) && !empty($history)): ?>
<h3><?=$this->transEsc("Most Recent Received Issues")?></h3>
<ul>
  <? foreach ($history as $row): ?>
    <li><?=$this->escapeHtml($row['issue'])?></li>
  <? endforeach; ?>
</ul>
<? endif; ?>