<?
  // Set up page title:
  $pageTitle = empty($this->card->id) ? 'Add a Library Card' : "Edit Library Card";
  $this->headTitle($this->translate($pageTitle));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'
    . '<li><a href="' . $this->url('librarycards-home') . '">' . $this->transEsc('Library Cards') . '</a></li>'
    . '<li>' . $this->transEsc($pageTitle) . '</li>';
?>

<?=$this->flashmessages()?>

<h2><?=$this->transEsc($pageTitle); ?></h2>

<form class="form-horizontal edit-card-form" method="post" name="<?=empty($this->card->id) ? 'newCardForm' : 'editCardForm'?>">
  <input type="hidden" name="id" value="<?=empty($this->card->id) ? 'NEW' : $this->card->id ?>"/>

  <div class="form-group">
    <label class="col-sm-3 control-label" for="login_username"><?=$this->transEsc('Username')?>: <?=$this->escapeHtmlAttr($this->username)?></label>

   <!-- FIXME remove these hidden inputs ! .. -->
    <div class="col-sm-9" hidden="hidden">
      <input type="hidden" id="username" name="username" value="<?=$this->escapeHtmlAttr($this->username)?>"/>
      <input type="hidden" id="target" name="target" value="<?=$this->escapeHtmlAttr($this->target)?>"/>
    </div>
  <!-- End of FIXME -->

  </div>

    <div class="form-group">
    <label class="col-sm-3 control-label" for="card_name"><?=$this->transEsc('Library Card Name'); ?>:</label>
    <div class="col-sm-9">
      <input id="card_name" class="form-control" type="text" name="card_name" value="<?=$this->escapeHtmlAttr($this->cardName)?>"/>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-9 col-sm-offset-3">
      <input class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEsc('Save') ?>"/>
    </div>
  </div>
</form>
