<?
  // Set up page title:
  $pageTitle = "Edit Library Card Name";
  $this->headTitle($this->translate($pageTitle));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/Search">' . $this->transEsc('Main page') . '</a></li> '.
  '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'
    . '<li><a href="' . $this->url('librarycards-home') . '">' . $this->transEsc('Library Cards') . '</a></li>'
    . '<li>' . $this->transEsc($pageTitle) . '</li>';

?>

<?=$this->flashmessages()?>
<ul class="breadcrumb hidden-print"><?=$this->layout()->breadcrumbs ?></ul>
<h2><?=$this->transEsc($pageTitle); ?></h2>

<form class="form-horizontal edit-card-form" method="post" name="editCardForm">
  <input type="hidden" name="id" value="<?=$this->card->id ?>"/>

    <div class="form-group">
    <label class="col-sm-3 control-label" for="card_name"><?=$this->transEsc('New Library Card Name'); ?>:</label>
    <div class="col-sm-9">
      <input id="card_name" class="form-control" type="text" placeholder="<?=$this->transEsc("Place new Card name here")?>" name="card_name" />
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-9 col-sm-offset-3">
      <input class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEsc('Save') ?>"/>
    </div>
  </div>
</form>
