<?
    // Set up page title:
    $this->headTitle($this->translate('Linked accounts'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Library Cards') . '</li>';
?>
<div class="row">
  <div class="<?=$this->layoutClass('mainbody')?>">

    <?=$this->flashmessages()?>

    <div class="row">
     <div class="col-xs-6">
      <h2><?=$this->transEsc('Linked accounts')?></h2>
     </div>
     <div class="col-xs-6">
      <a class="btn btn-default pull-right" style="margin-top:20px;" href="<?=$this->url('myresearch-userconnect')?>"><?=$this->transEsc("Connect another account")?></a>
     </div>
    </div>
    <? if (empty($this->libraryCards)): ?>
      <div><?=$this->transEsc('You do not have any library cards')?></div>
    <? else: ?>
      <table class="table table-striped" summary="<?=$this->transEsc('Library Cards')?>">
      <tr>
        <th width="15%">&nbsp;</th>
        <th><?=$this->transEsc('Identity')?></th>
        <th><?=$this->transEsc('Associated email')?></th>
        <th width="30%">&nbsp;</th>
      </tr>
      <? foreach ($this->libraryCards as $record):
            $source = explode('.', $record['cat_username'])[0];
      if ($source === 'Dummy') {
          // The source is dummy, thus in order to parse logo & correctly tranlate it, we need to get at least eppnScope
          $atPos = strpos($record['eppn'], '@');
          $eppnScope = substr($record['eppn'], ++$atPos);

          $source = $eppnScope;
      }

      ?>
        <tr>
          <td style="text-align: center;">
            <img height="32" src="<?=$this->logos()->getLogo($source) ?>"/>
          </td>
          <td><?=$this->transEsc("source_$source", null, $source) ?></td>
          <td title="<?=$record['cat_username'] ?>"><?=$record['card_name'] ?></td>
          <td>
          <? /* Do not create a choice for deletion if this is the only card */ if(count($this->libraryCards) !== 1): ?>
            <div class="btn-group">
              <a class="btn btn-link dropdown-toggle" data-toggle="dropdown" href="<?=$this->url('librarycards-deletecard') ?>?cardID=<?=urlencode($record['id'])?>">
                <i class="fa fa-trash-o"></i> <?=$this->transEsc('Disconnect identity')?>
              </a>
              <ul class="dropdown-menu">
                <li><a href="<?=$this->url('librarycards-deletecard') ?>?cardID=<?=urlencode($record['id'])?>&amp;confirm=1"><?=$this->transEsc('confirm_dialog_yes') ?></a></li>
                <li><a href="#"><?=$this->transEsc('confirm_dialog_no')?></a></li>
              </ul>
            </div>
          <? endif; ?>
          </td>
        </tr>
      <? endforeach; ?>
      </table>
    <? endif; ?>
  </div>

  <div class="<?=$this->layoutClass('sidebar')?>">
    <?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'librarycards'))?>
  </div>

</div>
