<? if($this->recommend->isActive()): ?>
  <form name="<?= $this->recommend->getFilterName() ?>Filter" id="<?= $this->recommend->getFilterName() ?>Filter">
    <? /* Insert actual GET params */ ?>
    <? foreach($this->recommend->getParams() as $paramName => $paramValue): ?>
      <? if(is_array($paramValue)): ?>
        <? foreach($paramValue as $paramSubValue): ?>
          <input type="hidden" name="<?= htmlspecialchars($paramName) ?>[]" value="<?= htmlspecialchars($paramSubValue) ?>">
        <? endforeach; ?>
      <? else: ?>
        <input type="hidden" name="<?= htmlspecialchars($paramName) ?>" value="<?= htmlspecialchars($paramValue) ?>">
      <? endif; ?>
    <? endforeach; ?>
    <span><?= $this->transEsc('Map Scale'); ?></span>
    <input type="hidden" name="daterange[]" value="<?= $this->recommend->getFilterName() ?>">
    <select name="<?= $this->recommend->getFilterName() ?>from" id="from">
      <? foreach($this->recommend->getSettings() as $scale): ?>
        <option
          value="<?= $scale ?>"
          <?= $scale == $this->recommend->getFromValue() ? 'selected="selected"' : '' ?>>
          1:<?= $scale ?>
        </option>
      <? endforeach; ?>
    </select>
    <span><?= $this->transEsc('to') ?></span>
    <select name="<?= $this->recommend->getFilterName() ?>to" id="to">
      <? foreach(array_reverse($this->recommend->getSettings()) as $scale): ?>
        <option
          value="<?= $scale ?>"
          <?= $scale == $this->recommend->getToValue() ? 'selected="selected"' : '' ?>>
          1:<?= $scale ?>
        </option>
      <? endforeach; ?>
    </select>
    <input type="submit" value="<?= $this->transEsc('Set') ?>">
  </form>
<? endif; ?>