<?
  $this->headScript()->appendFile('jquery-geo/jquery.geo-1.0.0-b1.5.min.js');
  $this->headScript()->appendFile('map_selection.js');
  $geoField = $this->recommend->getFacetField();
  $coordinates = $this->recommend->getCoordinates();
  $height = $this->recommend->getHeight();
  $searchParams = $this->recommend->getSearchParams();
  $showSelection = ($this->recommend->getSelectedCoordinates() != null);
?>
<div id="geo_modes">
  <input type="radio" name="mode" value="move"><?=$this->transEsc('Move map')?></input>
  <input type="radio" name="mode" value="dragBox" checked="true"><?=$this->transEsc('Select rectangle')?></input>
</div>
<div id="geo_map" style="height: <?=$height?>px; ">
</div>
<?
  $js = "loadMapSelection('". $geoField . "', [" . implode(', ', $coordinates) . "]," 
      . " path, '" . $searchParams . "', " . (($showSelection) ? 'true' : 'false') . ");";
  echo $this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $js, 'SET');
?>