<?
  // Set page title.
  $this->headTitle($this->translate('Widget').' | '.$this->translate('Administration'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/Search">' . $this->transEsc('Main page') . '</a></li> ' .
      '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'.
      '<li><a href="/Admin/Home">'.$this->transEsc('Administration').'</a></li>'.
      '<li><a href="/Admin/Widgets">'.$this->transEsc('Widgets').'</a></li>'.
      '<li><a href="/Admin/Widget/'.$widgetId.'">'.$this->translate($this->widgetTitle).'</a></li>'.
      '<li class="active">'.$this->transEsc('Import').'</li>';

  $this->layout()->title = $this->translate('Widget');

  $this->headScript()->appendFile("jquery-ui.min.js");
?>
<div class="row clearfix">
  <ul class="breadcrumb hidden-print"><?=$this->layout()->breadcrumbs ?></ul>

  <div class="col-sm-3">
    <?=$this->render("admin/menu.phtml")?>
  </div>

  <div class="col-sm-9">
    <h2><?=$this->translate('Import')?></h2>
    <div class='well'>
	  <div class='row'>
        <form action='/Admin/Widget/<?=$widgetId?>/ImportItemsAction' method='post'>
          <input type='hidden' name='userId' value='<?=$this->user['id']?>'>
          <input type='hidden' name='widget_id' value='<?=$this->widgetId?>'>

		  <fieldset class="form-group">
            <div class="col-xs-8">
              <label><?=$this->translate('ID lokálních záznamů (oddělených čárkama)')?></label>
              <textarea class='form-control' name='ids'></textarea>
            </div>
          </fieldset>

          <fieldset class="form-group">
            <input type='submit' class='btn btn-lg btn-primary pull-right' value='<?=$this->translate('Save')?>'>
          </fieldset>
        </form>
      </div>
	</div>
  </div>
</div>