<?
// Set page title.
$this->headTitle($this->translate('Holdings') . ': ' . $this->driver->getBreadcrumb());
$this->headScript()->appendFile('async-holdingsils.js');

// Set up convenience variables:
$holdings = $this->driver->getRealTimeHoldings();
$filters = $this->parseFilterOptions($holdings, $config);
$firstYearFilter = null;

if ($filters !== false)
    $this->headScript()->appendFile('async-holdingsils-filters-handler.js');

$authManager = $this->auth()->getManager();
$user = $authManager->isLoggedIn();

$canReserveThisInstitution = $authManager->canReserveWithinInstitution($holdings, $user);

$offlineMode = $this->ils()->getOfflineMode();
// Account for replace_other_urls setting

// Set page title.
$this->headTitle($this->driver->getBreadcrumb());
?>
<? if ($offlineMode == "ils-offline"): ?>
<div class="alert alert-warning">
	<h2><?=$this->transEsc('ils_offline_title')?></h2>
	<p>
		<strong><?=$this->transEsc('ils_offline_status')?></strong>
	</p>
	<p><?=$this->transEsc('ils_offline_holdings_message')?></p>
    <? $supportEmail = $this->escapeHtmlAttr($this->systemEmail()); ?>
    <p>
		<a href="mailto:<?=$supportEmail?>"><?=$supportEmail?></a>
	</p>
</div>
<? endif; ?>

<? $holdingTitleHold = $this->driver->tryMethod('getRealTimeTitleHold'); if (!empty($holdingTitleHold)): ?>
<a class="placehold modal-link"
	title="<?=$this->transEsc('request_place_text')?>"
	href="<?=$this->recordLink()->getRequestUrl($holdingTitleHold)?>"><i
	class="fa fa-flag"></i>&nbsp;<?=$this->transEsc('title_hold_place')?></a>
<? endif; ?>


<? if (! empty($holdings)) : ?>
<table class="table table-view" id="no-more-tables">
    <? if ($filters !== false): ?>
      <caption>
		<div class="col-md-2"></div>
		<div class="col-md-4">
		  <? if (! empty($filters['year'])): ?>

			<label for="year"><?=$this->transEsc('Year filter')?>: </label> <select
				name="year" id="year_filter">
				<option value="ALL"><?=$this->transEsc('All')?></option>
				<?

            $isFirst = true;
            foreach ($filters['year'] as $yearFilter) {
                $yearFilterEscaped = preg_replace('/([.:])/', '\\\${1}', $yearFilter);

                if ($isFirst) { // Select first year available ..
                    echo "<option value='$yearFilterEscaped' selected>$yearFilter</option>";
                    $firstYearFilter = $yearFilter;

                    $isFirst = false;
                } else
                    echo "<option value='$yearFilterEscaped'>$yearFilter</option>";
            }
            ?>
			</select>
		  <? endif; ?>
		</div>
		<div class="col-md-4">
		  <? if (! empty($filters['volume'])): ?>
			<label for="volume"><?=$this->transEsc('Volume filter')?>: </label> <select
				name="volume" id="volume_filter">
				<option value="ALL"><?=$this->transEsc('All')?></option>
				<?

            foreach ($filters['volume'] as $volumeFilter) {
                $volumeFilterEscaped = preg_replace('/([.:])/', '\\\${1}', $volumeFilter);
                echo "<option value='$volumeFilterEscaped'>$volumeFilter</option>\n";
            }
            ?>
			</select>
		  <? endif; ?>
		</div>
		<div class="col-md-2"></div>
	</caption>
    <? endif; ?>
	<thead>
		<tr>
			<th><?=$this->transEsc("Status")?>&nbsp;</th>
			<th><?=$this->transEsc("Due Date")?>&nbsp;</th>
			<th><?=$this->transEsc("Department")?>&nbsp;</th>
			<th><?=$this->transEsc("Collection")?>&nbsp;</th>
			<th><?=$this->transEsc("Location")?>&nbsp;</th>
			<th><?=$this->transEsc("Description")?>&nbsp;</th>
			<th><?=$this->transEsc("callnumber_abbrev")?>&nbsp;</th>
		</tr>
	</thead>
	<tbody>
<? $rowNo = 0; ?>
<? foreach ($holdings as $row): ?>
  <?
        $rowNo ++;

        // Build holding ID to query ILS for status
        if (isset($row['agency_id']) && isset($row['item_id']))
            $itemId = $row['agency_id'] . ':' . $row['item_id'];
        elseif (isset($row['item_id']))
            $itemId = $row['item_id'];
        else
            $itemId = false;

            // Create link for reserve
        if (! empty($row['item_id']) && $canReserveThisInstitution) {
            $explodedItemId = explode(':', $row['item_id']);
            $row['link'] = '/Record/' . $row['id'] . '/Hold?id=' . $row['id'] . '&item_id=' . end($explodedItemId);

            if (! empty($row['agency_id']))
                $row['link'] .= '&agency_id=' . $row['agency_id'];
        }

        $class = ($rowNo % 2) == 0 ? 'oddrow' : 'evenrow';

        $attributes = '';

        $itemStatusLabel = 'label-primary';

        if ($itemId !== false) {
            $attributes .= 'id="' . $itemId . '" ';
        } else {
            $itemStatusLabel = false;
        }

        if ((! empty($filters)) && ($filters !== false)) {

            if (isset($row['year'])) {
                // There is a year of publication available ..
                $attributes .= 'data-year="' . $row['year'] . '" ';

                // Should we hide this row as it's not selected??
                if ((! empty($firstYearFilter)) && ($firstYearFilter !== $row['year']))
                    $class .= ' hidden';

                // Note that if a row is hidden, then it is waiting to be showed up using any filter ..
            }

            if (isset($row['volume'])) {
                $attributes .= 'data-volume="' . $row['volume'] . '" ';
            }
        }

        $attributes .= 'class="' . $class . '" ';

        ?>
  <tr <?=$attributes?>>

			<td data-title="<?=$this->transEsc("Status")?>">
				<div data-type="availability" class="jt" title="<?=$this->transEsc('Description Status')?>">
					<span class="availability"><?=empty($row['availability']) ? '' : $this->transEsc('availability_' . $row['availability'])?></span>
				</div>

				<div title="<?=$this->transEsc('Item Status')?>"
					data-type="item-status">
					<? if (! $itemStatusLabel): ?>
					   <span class="label label-unknown"><?=$this->transEsc('unknown status')?></span>
					<? else: ?>
					   <i class="fa fa-spinner fa-spin"></i> <span
						class="label <?=$itemStatusLabel?>"><?=$this->transEsc('Loading')?> ...</span>
					<? endif; ?>
				</div>

      <? if (!empty($row['link']) && $row['link']): ?>
      <div title="<?=$this->transEsc('Place a Hold')?>" data-type="link"
					hidden="hidden">
					<a class="holdPlace"
						href="<?=$this->recordLink()->getRequestUrl($row['link'])?>"><span></span></a>
				</div>
      <? endif; ?>

    </td>
			<td data-title="<?=$this->transEsc("Due Date")?>"
				data-type="duedate">
      <?if (!empty($row['duedate']) && $row['duedate']) : ?>
        <?=$this->transEsc($row['duedate'])?>
      <? elseif (!empty($row['duedate_status']) && $row['duedate_status'] != $row['status']):?>
        <?=$this->transEsc($row['duedate_status'])?>
      <?endif;?>
    </td>
			<td data-title="<?=$this->transEsc("Department")?>"
			    data-type="department">
				<div>
        <? if(!empty($row['department'])):?>
          <?=$row['department']?>
        <? endif; ?>
      </div>
			</td>
			<td data-title="<?=$this->transEsc("Collection")?>"
			    data-type="collection">
				<div>
        <? if(!empty($row['collection_desc'])):?>
          <?=$row['collection_desc']?>
        <? endif; ?>
      </div>
			</td>
			<td data-title="<?=$this->transEsc("location / second signature")?>">
      <?if (!empty($row['location'])):?>
        <?=$this->escapeHtml($row['location'])?>
      <?endif;?>
    </td>
			<td data-title="<?=$this->transEsc("description")?>">
      <?if (!empty($row['description'])):?>
        <?=$this->escapeHtml($row['description']);?>
      <? endif;?>
    </td>
			<td data-title="<?=$this->transEsc("callnumber in stock")?>">
      <? if (!empty($row['callnumber'])):?>
        <?=$this->escapeHtml($row['callnumber'])?>
      <? endif;?>
    </td>
		</tr>
<? endforeach; ?>
</tbody>
</table>
<? endif; ?>

<? $history = $this->driver->getRealTimeHistory(); ?>
<? if (is_array($history) && !empty($history)): ?>
<h3><?=$this->transEsc("Most Recent Received Issues")?></h3>
<ul>
  <? foreach ($history as $row): ?>
    <li><?=$this->escapeHtml($row['issue'])?></li>
  <? endforeach; ?>
</ul>
<? endif; ?>
