<?
  // Set page title.
  $this->headTitle($this->driver->getBreadcrumb());
?>

<div id="commentList">
  <?=$this->render('record/comments-list-obalkyknih.phtml')?>
</div>
<form class="comment row" name="commentRecordObalkyKnih" id="commentRecord" action="<?=$this->recordLink()->getActionUrl($this->driver, 'AddComment')?>" method="post">
  <div class="col-sm-3 name">
    <input type="hidden" name="id" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>"/>
    <input type="hidden" name="source" value="<?=$this->escapeHtmlAttr($this->driver->getResourceSource())?>"/>
    <input type="hidden" name="obalkyknihbookid" value="<?=$this->escapeHtmlAttr($this->driver->getObalkyKnihBookId())?>"/>
    <strong><?=$this->transEsc("Your Comment")?></strong>
  </div>
  <div class="col-sm-9">
    <? $user = $this->auth()->isLoggedIn() ?>
    <? if($user): ?>
      <textarea id="comment" name="comment" class="form-control" rows="3" required></textarea><br/>
      <input class="btn btn-primary" data-loading-text="<?=$this->transEsc('Submitting') ?>..." type="submit" value="<?=$this->transEsc("Add your comment")?>"/>
    <? else: ?>
      <textarea id="comment" name="comment" class="form-control" rows="3" disabled></textarea><br/>
      <a href="<?=$this->url('myresearch-userlogin')?>" class="btn btn-primary" title="<?=$this->transEsc("You must be logged in first")?>"><i class="icon-prihlasit"></i> <?=$this->transEsc("You must be logged in first")?></a>
    <? endif; ?>
  </div>
</form>
