<?
  $this->headScript()->appendFile('jquery-geo/jquery.geo-1.0.0-b1.5.min.js');
  $this->headScript()->appendFile('map_selection.js');
  $geoField = $this->recommend->getGeoField();
  $coordinates = $this->recommend->getSelectedCoordinates();
  $showSelection = true;
  if ($coordinates == null) {
    $coordinates = $this->recommend->getDefaultCoordinates();
    $showSelection = false;
  }
  $height = $this->recommend->getHeight();
  $searchParams = $this->recommend->getSearchParams();
  $params = array(json_encode($geoField), json_encode($coordinates), "path",
    json_encode($searchParams), json_encode($showSelection));
  $jsParams = implode(', ', $params);
  $jsLoad = "loadMapSelection(" . $jsParams . ");";
?>
<div class="authorbox">
  <div id="geo_search" style="display: none;">
    <div id="geo_search_modes" class="form-inline">
      <input id="geo_search_move" type="radio" name="mode" value="move" />
      <label for="geo_search_move"><?=$this->transEsc('Move map')?></label>
      <input id="geo_search_bbox" type="radio" name="mode" value="dragBox" checked="checked" />
      <label for="geo_search_bbox"><?=$this->transEsc('Select rectangle')?></label>
    </div>
    <div id="geo_search_map" style="height: <?=$height?>px;"></div>
  </div>
  <? if ($showSelection) :?>
    <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $jsLoad, 'SET');?>
  <? else: ?>
    <a href="#" onclick='<?=$jsLoad?> $(this).remove(); return false;'><?=$this->translate('Geographical search') ?></a>
  <? endif; ?>
</div>
