<? $account = $this->auth()->getManager(); ?>
<nav class="navbar header">
  <div class="navbar-header">

    <ul class="nav navbar-nav pull-left">
      <li class="header-logo">
        <a href="http://www.mzk.cz/"><img src="<?=$this->imageLink('fonoteka-header-mzk.png') ?>"></img></a>
      </li>
      <li class="header-title">
        <a href="/">Virtuální národní fonotéka</a>
      </li>
    </ul>

    <ul class="nav navbar-nav pull-right">
      <? if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
        <? foreach ($this->layout()->allLangs as $langCode => $langName): ?>
          <?
            $langImg = 'lang/' . $langCode . '.png';
            $queryParams = array('lng' => $langCode);
            parse_str($_SERVER['QUERY_STRING'], $params);
            $queryParams = array_merge($params, $queryParams);
          ?>
          <li>
            <a class="flagLink" id="flagLink" href="<?=$this->url(null, array(), array('query' => $queryParams), true);?>">
              <img class="langFlag" src="<?=$this->imageLink($langImg)?>" alt="<?=$langName?>">
            </a>
          </li>
        <? endforeach; ?>
      <? endif; ?>
      
        <li class="header-login">
          <? $cart = $this->cart(); if ($cart->isActive()): ?>
          <span id="cartSummary">
            <i class="icon-shopping-cart"></i> <a id="cartItems" class="modal-link" title="<?=$this->transEsc('View Book Bag')?>" href="<?=$this->url('cart-home')?>"><strong><?=count($cart->getItems())?></strong> <?=$this->transEsc('items')?><?=$cart->isFull() ? ' (' . $this->transEsc('bookbag_full') . ')' : ''?></a>
          </span>
        </li>
      <? endif; ?>
      
      <div class="header-finisher"/>
      
    </ul>

  </div>
</nav>
