<ul class="idp-list<?= $class ? ' ' . $class : '' ?>">
  <? foreach($idps as $idp):
    $json = json_encode($idp);
    ?>
    <li class="row link idp-record result" data-search="<?=strtolower($idp['name'])?>" data-ng-click="fedLoginCtrl.login('<?=htmlentities($json)?>')">
      <div class="col-sm-3 logo">
        <? if($idp['logo']):?>
          <img src="<?=$idp['logo']?>">
        <? endif; ?>
      </div>
      <div class="col-sm-9">
        <a href="<?=$idp['href']?>"><?=$idp['name']?></a>
      </div>
    </li>
  <? endforeach; ?>
</ul>