<?
  // Set page title.
  $this->headTitle($this->translate('Save'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li>' . $this->getLastSearchLink($this->transEsc('request_for_digitalization_header'), '', '<span class="divider">&gt;</span></li>')
    . '<li>' . $this->recordLink()->getBreadcrumb($this->driver) . '<span class="divider">&gt;</span></li><li class="active">' . $this->transEsc('request_for_digitalization') . '</li>';
?>
<p class="lead"><?=$this->transEsc("request_for_digitalization") ?> <?=$this->escapeHtml($this->driver->getBreadcrumb())?> </p>
<form id="edit-save-form" class="form-horizontal" method="post" action="<?=$this->recordLink()->getActionUrl($this->driver, 'DigiRequest')?>" name="saveRecord">
  <input type="hidden" name="submit" value="1" />
  <input type="hidden" name="id" value="<?=$this->escapeHtml($this->driver->getUniqueId()) ?>" />
  <input type="hidden" name="source" value="<?=$this->escapeHtml($this->driver->getResourceSource())?>" />
  <div class="control-group">
    <label class="control-label" for="add_mytags"><?=$this->transEsc('Email') ?></label>
    <div class="controls">
      <input class="input-xlarge" id="email" type="text" name="email" value=""/>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="add_mytags"><?=$this->transEsc('Reason') ?></label>
    <div class="controls">
      <input class="input-xlarge" id="reason" type="text" name="reason" value=""/>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <input class="btn btn-primary" type="submit" value="<?=$this->transEsc('request_for_digitalization_submit') ?>"/>
    </div>
  </div>
</form>