<?
    // Set page title.
    $this->headTitle($this->translate('request_place_text') . ': ' . $this->driver->getBreadcrumb());

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li>' . $this->getLastSearchLink($this->transEsc('Search'), '', '<span class="divider">&gt;</span> </li>')
        . '<li>' . $this->recordLink()->getBreadcrumb($this->driver) . '<span class="divider">&gt;</span> </li>'
        . '<li class="active">' . $this->transEsc('request_place_text') . '</li>';
?>
<p class="lead"><?=$this->transEsc('request_place_text')?></p>
<? if ($this->helpText): ?>
<p class="helptext"><?=$this->helpText?></p>
<? endif; ?>

<?=$this->flashmessages()?>

<? if ($this->dueDate):?>
  <div class="alert alert-block">
    <?=$this->transEsc('hold_request_item_on_loan_until_text')?>: <?=$this->escapeHtml($this->dueDate)?> <br>
    <?=$this->transEsc('hold_request_item_on_loan_text')?>
  </div>
<? endif;?>

<? if ($this->order > 1):?>
  <div class="alert alert-block">
    <?=$this->transEsc('hold_request_queue_order_text')?>: <?=$this->escapeHtml($this->order)?>
  </div>
<? endif;?>

<div class="hold-form">
  <form action="" class="form-horizontal" method="post" name="placeHold">

    <? if (in_array("comments", $this->extraHoldFields)): ?>
      <div class="control-group">
        <label class="control-label"><?=$this->transEsc("hold_request_comment")?>:</label>
        <div class="controls">
          <textarea rows="3" cols="20" name="gatheredDetails[comment]"><?=isset($this->gatheredDetails['comment']) ? $this->escapeHtml($this->gatheredDetails['comment']) : ''?></textarea>
        </div>
      </div>
    <? endif; ?>

    <? if (in_array("requiredByDate", $this->extraHoldFields)): ?>
      <? if ($queued):?>
        <div class="control-group">
          <label class="control-label">
            <input type="checkbox" id="enable_to"/>
            <?=$this->transEsc("hold_required_by")?>:
          </label>
          <div class="controls">
            <input id="requiredByDate" type="text" name="gatheredDetails[requiredBy]" value="<?=(isset($this->gatheredDetails['requiredBy']) && !empty($this->gatheredDetails['requiredBy'])) ? $this->escapeHtmlAttr($this->gatheredDetails['requiredBy']) : $this->escapeHtmlAttr($this->defaultRequiredDate)?>" size="8" />
            (<?=$this->dateTime()->getDisplayDateFormat()?>)
          </div>
        </div>
      <? else:?>
        <input id="requiredByDateHidden" type="hidden" name="gatheredDetails[requiredBy]" value="<?=$this->escapeHtmlAttr($this->defaultRequiredDate)?>"/>
      <? endif; ?>
    <? endif; ?>

    <? $showRequestGroups = in_array("requestGroup", $this->extraHoldFields)
        && (empty($this->gatheredDetails['level'])
            || $this->gatheredDetails['level'] != 'copy');
    ?>
    <? if ($this->requestGroupNeeded): ?>
      <div class="control-group">
        <?
          if (isset($this->gatheredDetails['requestGroupId']) && $this->gatheredDetails['requestGroupId'] !== "") {
              $selected = $this->gatheredDetails['requestGroupId'];
          } else {
              $selected = $this->defaultRequestGroup;
          }
       ?>
        <label class="control-label"><?=$this->transEsc("hold_request_group")?>:</label>
        <div class="controls">
          <select id="requestGroupId" name="gatheredDetails[requestGroupId]">
          <? if ($selected === false): ?>
            <option value="" selected="selected">
              <?=$this->transEsc('select_request_group')?>
            </option>
          <? endif; ?>
          <? foreach ($this->requestGroups as $group): ?>
            <option value="<?=$this->escapeHtmlAttr($group['id'])?>"<?=($selected == $group['id']) ? ' selected="selected"' : ''?>>
              <?=$this->escapeHtml($group['name'])?>
            </option>
          <? endforeach; ?>
          </select>
        </div>
      </div>
    <? endif; ?>

    <? if (in_array("pickUpLocation", $this->extraHoldFields)): ?>
      <?
        if (isset($this->gatheredDetails['pickUpLocation']) && $this->gatheredDetails['pickUpLocation'] !== "") {
            $selected = $this->gatheredDetails['pickUpLocation'];
        } elseif (isset($this->homeLibrary) && $this->homeLibrary !== "") {
            $selected = $this->homeLibrary;
        } else {
            $selected = $this->defaultPickup;
        }
      ?>
      <? if ($this->requestGroupNeeded): ?>
        <div class="control-group">
          <label id="pickUpLocationLabel" class="control-label"><i></i>&nbsp;<?=$this->transEsc("pick_up_location")?>:
          <? if (in_array("requestGroup", $this->extraHoldFields)): ?>
            <noscript> (<?=$this->transEsc("Please enable JavaScript.")?>)</noscript>
          <? endif; ?>
          </label>
          <div class="controls">
            <select id="pickUpLocation" name="gatheredDetails[pickUpLocation]" data-default="<?=$this->escapeHtmlAttr($selected)?>">
              <? if ($selected === false): ?>
              <option value="" selected="selected">
                <?=$this->transEsc('select_pickup_location')?>
              </option>
              <? endif; ?>
            </select>
          </div>
        </div>
      <? elseif (count($this->pickup) > 1): ?>
        <div class="control-group">
          <label class="control-label"><?=$this->transEsc("pick_up_location")?>:</label>
          <div class="controls">
            <select id="pickUpLocation" name="gatheredDetails[pickUpLocation]">
            <? if ($selected === false): ?>
              <option value="" selected="selected">
                <?=$this->transEsc('select_pickup_location')?>
              </option>
            <? endif; ?>
            <? foreach ($this->pickup as $lib): ?>
              <option value="<?=$this->escapeHtmlAttr($lib['locationID'])?>"<?=($selected == $lib['locationID']) ? ' selected="selected"' : ''?>>
                <?=$this->transEsc('Sublibrary ' . $lib['locationDisplay'])?>
              </option>
            <? endforeach; ?>
            </select>
          </div>
        </div>
      <? else: ?>
        <input type="hidden" name="gatheredDetails[pickUpLocation]" value="<?=$this->escapeHtmlAttr($this->defaultPickup)?>" />
      <? endif; ?>
    <? endif; ?>
    <div class="control-group">
      <div class="controls">
        <input class="btn btn-primary" type="submit" name="placeHold" value="<?=$this->transEsc('request_submit_text')?>"/>
      </div>
    </div>
  </form>
</div>

<?
    // Set up hold script; we do this inline instead of in the header for lightbox compatibility:
    $this->inlineScript()->appendFile('hold.js');

    $js = <<<JS
        if ($.isReady) {
            setUpHoldRequestForm("{$this->escapeHtml($this->driver->getUniqueId())}");
        } else {
            $(document).ready(function(){
                setUpHoldRequestForm("{$this->escapeHtml($this->driver->getUniqueId())}");
            });
        }

        $('#requiredByDate').attr("disabled", true);
        $('#enable_to').change(function() {
          var disabled = !$(this).is(':checked');
          $('#requiredByDate').attr("disabled", disabled);
          if (disabled) {
            $('#requiredByDate').val("{$this->escapeHtml($this->defaultRequiredDate)}");
          }
        });
        
JS;

    echo $this->inlineScript()->appendScript($js);
?>
