<?
  $this->headTitle($this->translate('Browse the Collection alphabetically'));
  $this->layout()->breadcrumbs = '<a href="' . $this->url('alephbrowse-home') . '">' . $this->transEsc('Browse alphabetically') . '</a>';
  $nextQuery = $this->result['Browse']['nextQuery'];
?>

<? /* LOAD THE LINK INFORMATION INTO $pageLinks, similar to smarty's {capture} */ ?>
<? ob_start(); ?>
  <ul class="pager">
    <? if (isset($nextQuery)): ?>
      <li><a href="<?=$this->escapeHtmlAttr($this->url('alephbrowse-home', array(), array('query' => $nextQuery )))?>"><?=$this->transEsc('Next')?> &raquo;</a></li>
    <? else: ?>
      <li class="disabled"><a href="#"><?=$this->transEsc('Next')?> &raquo;</a></li>
    <? endif; ?>
  </ul>
<? $pageLinks = ob_get_contents(); ?>
<? ob_end_clean(); ?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <div>
    <form class="form-inline" method="get" action="<?=$this->url('alephbrowse-home')?>" name="alephBrowseForm" id="alephBrowseForm">
      <label for="alephBrowseForm_source"><?=$this->transEsc('Browse alephbetically') ?></label>
      <select id="alephBrowseForm_source" class="form-control" name="source">
        <? foreach ($this->alephBrowseTypes as $key => $item): ?>
          <option value="<?=$this->escapeHtmlAttr($key) ?>"<? if ($this->source == $key): ?> selected="selected"<? endif; ?>><?=$this->transEsc($item) ?></option>
        <? endforeach; ?>
      </select>
      <label for="alephBrowseForm_from"><?=$this->transEsc('starting from') ?></label>
      <input type="text" class="form-control" name="from" id="alephBrowseForm_from" value="<?=$this->escapeHtmlAttr($this->from) ?>"/>
      <input class="btn btn-default" type="submit" value="<?=$this->transEsc('Browse') ?>"/>
    </form>
  </div>

  <? if ($this->result): ?>
    <?=$pageLinks ?>
    <table class="table table-striped" id="alephBrowse">
      <? foreach ($this->result['Browse']['items'] as $i => $item): ?>
      <tr>
        <td>
          <? if ($item['count'] > 0): ?>
            <?/* linking using bib ids is generally more reliable than
              doing searches for headings, but headings give shorter
              queries and don't look as strange. */?>
            <? $query = array('type' => 'ids', 'lookfor' => implode(' ', $item['ids'])); ?>
            <a class="col-sm-6" href="<?=$this->escapeHtmlAttr($this->url('search-results', array(), array('query' => $query)))?>"><?=$this->escapeHtml($item['heading'])?></a>
          <? else: ?>
            <span class="col-sm-6"><?=$this->escapeHtml($item['heading'])?></span>
          <? endif; ?>

          <?
            foreach ($this->extras as $ei => $extraName):
              $extraData = $item['extras'][$extraName];
          ?>
            <div class="col-sm-<?=floor(6/count($this->extras)) ?>">
              <?
                $extraDisplayArray = array();
                foreach ($extraData as $j => $e) {
                  $extraDisplayArray = array_unique(array_merge($extraDisplayArray, $e));
                }
                echo (empty($extraDisplayArray)) ? '&nbsp;' : implode('<br />', $extraDisplayArray);
              ?>
            </div>
          <? endforeach; ?>
          <div class="clearfix"></div>
          <? if (count($item['useInstead']) > 0): ?>
            <div>
              <?=$this->transEsc('Use instead') ?>:
              <ul>
                <? foreach ($item['useInstead'] as $heading): ?>
                <li><a href="<?=$this->escapeHtmlAttr($this->url('alephbrowse-home', array(), array('query' => array('from' => $heading) + $baseQuery)))?>"><?=$this->escapeHtml($heading)?></a></li>
                <? endforeach; ?>
              </ul>
            </div>
          <? endif; ?>

          <? if (count($item['seeAlso']) > 0): ?>
            <div>
              <?=$this->transEsc('See also') ?>:
              <ul>
                <? foreach ($item['seeAlso'] as $heading): ?>
                <li><a href="<?=$this->escapeHtmlAttr($this->url('alephbrowse-home', array(), array('query' => array('from' => $heading) + $baseQuery)))?>"><?=$this->escapeHtml($heading)?></a></li>
                <? endforeach; ?>
              </ul>
            </div>
          <? endif; ?>

          <? if ($item['note']): ?>
            <div>
              <?=$this->transEsc('Note') ?>:
              <ul>
                <li><?=$this->escapeHtml($item['note'])?></li>
              </ul>
            </div>
          <? endif; ?>
        </td>
        <td align="right" style="width: 15%;"><? if ($item['count'] > 0): echo $item['count']; endif; ?></td>
      <? endforeach; ?>
    </table>
    <?= $pageLinks ?>
  <? endif; ?>
</div>
