<? 
  /**
   * common function for rendering holdings 
   * @param array callbacks - required callbacks for methods 'transEsc' and 'driver->getExternalLinks'
   * @param array holding - holding to be displayed
   */
  function renderHolding($callbacks, &$holding) { 
      $externalLink = null;
      foreach($callbacks['getExternalLinks']('holdings') as $link) {
        if (strcasecmp($holding['library'],$link['institution']) == 0) {
          $externalLink = $link;  
        }
      }
      ?>
    <tr>
      <? if (is_array($externalLink) && isset($externalLink['url'])):?>
        <td><a href="<?=$externalLink['url']?>"><?=$callbacks['transEsc'](strtoupper($externalLink['institution']))?></a></td>
      <? else:?>
        <td><?=$holding['library']?></td>
      <? endif;?>
      <td><?=$holding['branch']?></td>
      <td><?=$holding['branch2']?></td>
      <td><?=$holding['sheduleOfPeriodics']?></td>
      <td><?=$holding['signature1']?></td>
      <td><?=$holding['signature2']?></td>
      <td><?=$holding['barcode']?></td>
      <td><?=isset($holding['status']) ? $callbacks['transEsc']($holding['status']) : ''?></td>
    </tr>
<? } ?>

<? 
  function sortHoldings(&$holdings) { 
    foreach ($holdings as $holding) {
      $libraryValues[] = $holding['library'];
      $branchValues[] = $holding['branch'];
      $branch2Values[] = $holding['branch2'];
      $sheduleOfPeriodicsValues[] = $holding['sheduleOfPeriodics'];
      $signatureValues[] = $holding['signature1'];
      $signature2Values[] = $holding['signature2'];
      $barcodeValues[] = $holding['barcode'];
    }  
    if ($holdings) {
      if (!empty($sheduleOfPeriodicsValues)) {
        array_multisort(
          $sheduleOfPeriodicsValues, SORT_DESC, SORT_NUMERIC,
          $libraryValues, SORT_ASC, SORT_LOCALE_STRING,
          $branchValues, SORT_ASC, SORT_LOCALE_STRING,
          $branch2Values, SORT_ASC, SORT_LOCALE_STRING,
          $signatureValues, SORT_ASC, SORT_NUMERIC,
          $signature2Values, SORT_ASC, SORT_NUMERIC,
          $barcodeValues, SORT_ASC, SORT_NUMERIC,
          $holdings
        );
      } else {
        array_multisort(
          $libraryValues, SORT_ASC, SORT_LOCALE_STRING,
          $branchValues, SORT_ASC, SORT_LOCALE_STRING,
          $branch2Values, SORT_ASC, SORT_LOCALE_STRING,
          $signatureValues, SORT_ASC, SORT_NUMERIC,
          $signature2Values, SORT_ASC, SORT_NUMERIC,
          $barcodeValues, SORT_ASC, SORT_NUMERIC,
          $holdings
        );
      }
    } 
  }

?>
<?
    $filters = $this->tab->getFilters();
    $availableFilters = $this->tab->getAvailableFilters();
    $selectedFilters = $this->tab->getSelectedFilters();
?>

<div class="holdings-filters">
  <? foreach($filters as $name => $values):?>
    <? if (!empty($values)):?>
      <? $filterName = $this->escapeHtml($name . '_filter');?>
      <? $selectedVal = isset($selectedFilters[$name]) ? $selectedFilters[$name] : '';?>
      <? $type = $availableFilters[$name]['type'];?>
      <div class="span5" style="width: auto;">
        <form class="form-inline" name="<?=$this->escapeHtml($name)?>_filter">
          <? if ($type == 'select'):?>
            <label class="help-inline" for="<?=$this->escapeHtml($name)?>"><?=$this->transEsc($filterName)?> : </label>
            <select class="jumpMenu" name="<?=$this->escapeHtml($name)?>" id="<?=$this->escapeHtml($name)?>" onchange="document.forms['<?=$filterName?>'].submit()">
              <option value=""><?=$this->transEsc('all')?></option>
              <? foreach($values as $value):?>
                <option value="<?=$this->escapeHtml($value)?>" <?=($selectedVal == $value)?'selected="selected"':''?>><?=$this->transEsc($value)?></option>
              <? endforeach;?>
            </select>
          <?endif;?>
          <?if ($type == 'checkbox'):?>
            <input type="checkbox" name="<?=$this->escapeHtml($name)?>" id="<?=$this->escapeHtml($name)?>" value="true"
              onchange="document.forms['<?=$filterName?>'].submit()"
              <?=($selectedVal == 'true')?'checked="true"':''?>
            >
            <label for="<?=$this->escapeHtml($name)?>"><?=$this->transEsc($filterName)?></label>
          <?endif;?>
          <?=$this->tab->asHiddenFields($name);?>
        </form>
      </div>
    <? endif; ?>
  <? endforeach;?>
</div>


<!-- table header for holdings-->
<table class="table table-striped">
  <tr>
      <td><?=$this->transEsc('Library')?></td>
      <td><?=$this->transEsc('Branch')?></td>
      <td><?=$this->transEsc('Second Level Branch')?></td>
      <td><?=$this->transEsc('Schedule of Periodics')?></td>
      <td><?=$this->transEsc('Signature 1')?></td>
      <td><?=$this->transEsc('Signature 2')?></td>
      <td><?=$this->transEsc('Barcode')?></td>
      <td><?=$this->transEsc('Status')?></td>
  </tr>
