<?
    // Set up convenience variables:
    $account = $this->auth()->getManager();
    $filters = $this->tab->getFilters();
    $selectedFilters = $this->tab->getSelectedFilters();
    $availableFilters = $this->tab->getAvailableFilters();
    $user = $account->isLoggedIn();
    $holdings = $this->tab->getRealTimeHoldings();
    $openUrl = $this->openUrl($this->driver, 'holdings');
    $openUrlActive = $openUrl->isActive();
    // Account for replace_other_urls setting
    $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
    $offlineMode = $this->ils()->getOfflineMode();

    // Set page title.
    $this->headTitle($this->driver->getBreadcrumb());
?>
<? if ($offlineMode == "ils-offline"): ?>
  <div class="sysInfo">
    <h2><?=$this->transEsc('ils_offline_title')?></h2>
    <p><strong><?=$this->transEsc('ils_offline_status')?></strong></p>
    <p><?=$this->transEsc('ils_offline_holdings_message')?></p>
    <? $supportEmail = $this->escapeHtml($this->systemEmail()); ?>
    <p><a href="mailto:<?=$supportEmail?>"><?=$supportEmail?></a></p>
  </div>
<? endif; ?>

<?if (($message = $this->mzkHelper()->getRestrictionMessage()) != null):?>
  <p class="holdings-restriction">
    <?=$this->transEsc($message);?>
  </p>
<?endif;?>

<? $restrictions = $this->driver->getRestrictions(); if (!empty($restrictions)):?>
  <? foreach ($restrictions as $restriction):?>
    <p class="holdings-restriction">
      <?=$this->transEsc($restriction);?>
    </p>
  <? endforeach;?>
<? endif;?>

<? $holdingTitleHold = $this->driver->tryMethod('getRealTimeTitleHold'); if (!empty($holdingTitleHold)): ?>
    <a class="holdPlace" href="<?=$this->recordLink()->getHoldUrl($holdingTitleHold)?>"><?=$this->transEsc('title_hold_place')?></a>
<? endif; ?>

<? foreach($this->driver->getItemLinks() as $link):?>
  <a href='<?=$this->recordLink()->related(array('type' => 'bib', 'value' => $link['id']))?>'><?=$this->escapeHtml($link['label'])?></a><br/>
<? endforeach;?>

<div class="holdings-filters">
  <? foreach($filters as $name => $values):?>
    <? if (!empty($values)):?>
      <? $filterName = $this->escapeHtml($name . '_filter');?>
      <? $selectedVal = isset($selectedFilters[$name]) ? $selectedFilters[$name] : null ;?>
      <? $type = $availableFilters[$name]['type'];?>
      <div class="col-md-4">
        <form class="form-inline" name="<?=$this->escapeHtml($name)?>_filter">
          <?if ($type == 'select'):?>
            <label for="<?=$this->escapeHtml($name)?>"><?=$this->transEsc($filterName)?> : </label>
            <select name="<?=$this->escapeHtml($name)?>" id="<?=$this->escapeHtml($name)?>" onchange="document.forms['<?=$filterName?>'].submit()">
              <option value=""><?=$this->transEsc('all')?></option>
              <? foreach($values as $value):?>
                <option value="<?=$this->escapeHtml($value)?>" <?=($selectedVal == $value)?'selected="selected"':''?>><?=$this->escapeHtml($value)?></option>
              <? endforeach;?>
            </select>
          <?endif;?>
          <?if ($type == 'checkbox'):?>
            <input type="checkbox" name="<?=$this->escapeHtml($name)?>" id="<?=$this->escapeHtml($name)?>" value="true"
              onchange="document.forms['<?=$filterName?>'].submit()"
              <?=($selectedVal == 'true')?'checked="true"':''?>
              >
            <label for="<?=$this->escapeHtml($name)?>"><?=$this->transEsc($filterName)?></label>
          <?endif;?>
          <?=$this->tab->asHiddenFields($name);?>
        </form>
      </div>
    <? endif; ?>
  <? endforeach;?>
</div>
<br/>
<? if ($holdings != null) : ?>
<table class="table table-view" id="no-more-tables">
<thead>
  <tr>
    <th><?=$this->transEsc("item status")?>&nbsp;</th>
    <th><?=$this->transEsc("due date")?>&nbsp;</th>
    <th><?=$this->transEsc("sublibrary")?>&nbsp;</th>
    <th><?=$this->transEsc("collection")?>&nbsp;</th>
    <th><?=$this->transEsc("location / second signature")?>&nbsp;</th>
    <th><?=$this->transEsc("description")?>&nbsp;</th>
    <th><?=$this->transEsc("note")?>&nbsp;</th>
    <th><?=$this->transEsc("callnumber in stock")?>&nbsp;</th>
  </tr>
</thead>
<tbody>
<? $row = 0; ?>
<? foreach ($holdings as $row): ?>
  <? $check = (isset($row['check']) && $row['check']); ?>
  <? $row++; ?>
  <tr class="<?=(($row % 2) == 0)?'oddrow':'evenrow'?>">
    <td data-title="<?=$this->transEsc("item status")?>">
      <? if ($this->transEsc('Description Status '. $row['status']) == 'Description Status '. $row['status']):?>
      <div>
      <? else: ?>
      <div class="jt" title="<?=$this->transEsc('Description Status '. $row['status'])?>">
      <? endif; ?>
      	<span class="<?=($row['availability'])?'available':'checkedout'?>"><?=$this->transEsc('Status '. $row['status'])?></span>
      </div>
      <? if ($row['reserve'] == "Y"): ?>
      <?=$this->transEsc("On Reserve - Ask at Circulation Desk")?>
      <? elseif (isset($row['use_unknown_message']) && $row['use_unknown_message']): ?>
        <span class="unknown"><?=$this->transEsc("status_unknown_message")?></span>
      <? else: ?>
        <? if ($row['holdtype'] == 'shortloan'):?>
          <? if (isset($row['link']) && $row['link']): ?>
            <a class="holdPlace<?=$check ? ' checkRequest' : ''?>" href="<?=$this->recordLink()->getRequestUrl($row['link'])?>">
              <span><?=$this->transEsc("Reserve")?></span>
            </a>
          <? endif; ?>
        <? elseif ($row['availability']): ?>
          <? /* Begin Available Items (Holds) */ ?>
          <div>
          <? if (isset($row['link']) && $row['link']): ?>
            <a class="holdPlace<?=$check ? ' checkRequest' : ''?>" href="<?=$this->recordLink()->getRequestUrl($row['link'])?>">
              <span><?=$this->transEsc($check ? "Check Hold" : "Order from stock")?></span>
            </a>
          <? endif; ?>
          </div>
        <? else: ?>
          <div>
          <? if (isset($row['link']) && $row['link']): ?>
            <a class="holdPlace<?=$check ? ' checkRequest' : ''?>" href="<?=$this->recordLink()->getRequestUrl($row['link'])?>">
              <span><?=$this->transEsc($check ? "Check Recall" : "Reserve")?></span>
            </a>
          <? endif; ?>
          </div>
        <? endif; ?>
      <? endif; ?>
    </td>
    <td data-title="<?=$this->transEsc("due date")?>">
      <?if ($row['duedate']) : ?>
        <?=$this->transEsc($row['duedate'])?><?if ($row['requested']) :?>;
          <?=$this->transEsc('hold_item_requested')?>
        <?endif;?>
      <? elseif ($row['duedate_status'] != $row['status']):?>
        <?=$this->transEsc($row['duedate_status'])?>
      <?endif;?>
    </td>
    <td data-title="<?=$this->transEsc("sublibrary")?>">
      <? if ($this->transEsc('Description Sublibrary '. $row['sub_lib_desc']) == 'Description Sublibrary '. $row['sub_lib_desc']):?>
      <div>
      <? else: ?>
      <div class="jt" title="<?=$this->transEsc('Description Sublibrary '. $row['sub_lib_desc'])?>">
      <? endif; ?>
        <? if(!empty($row['sub_lib_desc'])):?>
          <?=$this->transEsc('Sublibrary '. $row['sub_lib_desc'])?>
        <? endif; ?>
      </div>
    </td>
    <td data-title="<?=$this->transEsc("collection")?>">
      <? if ($this->transEsc('Description Collection '. $row['collection_desc']) == 'Description Collection '. $row['collection_desc']):?>
      <div>
      <? else: ?>
      <div class="jt" title="<?=$this->transEsc('Description Collection '. $row['collection_desc'])?>">
      <? endif; ?>
        <? if(!empty($row['collection_desc'])):?>
          <?=$this->transEsc('Collection ' . $row['collection_desc'])?>
        <? endif; ?>
      </div>
    </td>
    <td data-title="<?=$this->transEsc("location / second signature")?>">
      <b><?=$this->escapeHtml($row['callnumber_second'])?></b>
    </td>
    <td data-title="<?=$this->transEsc("description")?>">
      <?=$this->escapeHtml($row['description'])?>
    </td>
    <td data-title="<?=$this->transEsc("note")?>">
      <? if ($row['notes'] != null):?>
        <?=$this->escapeHtml($row['notes'][0])?>
      <? endif;?>
    </td>
    <td data-title="<?=$this->transEsc("callnumber in stock")?>">
      <? if ($row['callnumber'] != null):?>
        <?=$this->escapeHtml($row['callnumber'])?>
      <? endif;?>
    </td>
  </tr>
<? endforeach; ?>
</tbody>
</table>
<? endif; ?>

<? $history = $this->driver->getRealTimeHistory(); ?>
<? if (is_array($history) && !empty($history)): ?>
<h3><?=$this->transEsc("Most Recent Received Issues")?></h3>
<ul>
  <? foreach ($history as $row): ?>
    <li><?=$this->escapeHtml($row['issue'])?></li>
  <? endforeach; ?>
</ul>
<? endif; ?>
