<? $i = 0; foreach ($this->transactions as $resource): ?>
  <hr/>
  <? $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
  <div id="record<?=$this->escapeHtml($resource->getUniqueId())?>" class="row">
    <? if ($this->renewForm): ?>
      <? if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_details'])): ?>
        <? $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $ilsDetails['renew_details']); ?>
        <input class="pull-left" type="checkbox" name="renewSelectedIDS[]" value="<?=$this->escapeHtml($ilsDetails['renew_details'])?>" id="checkbox_<?=$safeId?>" />
        <input class="pull-left" type="hidden" name="renewAllIDS[]" value="<?=$this->escapeHtml($ilsDetails['renew_details'])?>" />
      <? endif; ?>
    <? endif; ?>
    <div class="col-md-2 text-center">
      <?
        $recordId = $resource->getUniqueId();
        $backLink = $this->serverUrl($this->recordLink()->getUrl($resource));
        $formats = $resource->getFormats();
      ?>
      <div id="cover_<?=$recordId?>" class="coverThumbnail">
        <? if ($bibinfo = $this->record($resource)->getObalkyKnihJSON()): ?>
          <script type="text/javascript">
            $(document).ready(function() {
              obalky.process("obalky_display_thumbnail", "cover_<?=$recordId?>", "<?=$backLink?>", <?=$bibinfo?>);
            });
          </script>
        <? endif;?>
        <img src="<?=$this->imageLink('format/' . $formats[0] . '.png')?>" />
      </div>
      <div class="coverFormat"><?=$this->transEsc($formats[0])?></div>
    </div>
    <div class="col-md-9">
      <?
        // If this is a non-missing Solr record, we should display a link:
        if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
          $title = $resource->getTitle();
          $title = empty($title) ? $this->transEsc('Title not available') : $this->escapeHtml($title);
          echo '<a href="' . $this->recordLink()->getUrl($resource) .
            '" class="title">' . $title . '</a>';
        } else if (isset($ilsDetails['title']) && !empty($ilsDetails['title'])){
          // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
          echo $this->escapeHtml($ilsDetails['title']);
        } else {
          // Last resort -- indicate that no title could be found.
          echo $this->transEsc('Title not available');
        }
      ?><br/>
      <? $listAuthor = $resource->getPrimaryAuthor(); if (!empty($listAuthor)): ?>
        <?=$this->transEsc('by')?>:
        <a href="<?=$this->record($resource)->getLink('author', $listAuthor)?>"><?=$this->escapeHtml($listAuthor)?></a><br/>
      <? endif; ?>
      <? /* TODO: tags
      {if $resource.tags}
        <?=$this->transEsc('Your Tags')?>:
        {foreach from=$resource.tags item=tag name=tagLoop}
          <a href="{$url}/Search/Results?tag={$tag->tag|escape:"url"}">{$tag->tag|escape}</a>{if !$smarty.foreach.tagLoop.last},{/if}
        {/foreach}
        <br/>
      {/if}
       */ ?>
      <? /* TODO: notes
      {if $resource.notes}
        <?=$this->transEsc('Notes')?>: {$resource.notes|escape}<br/>
      {/if}
       */ ?>
      <? $formats = $resource->getFormats(); if (count($formats) > 0): ?>
        <?=str_replace('class="', 'class="label label-info ', $this->record($resource)->getFormatList())?>
        <br/>
      <? endif; ?>
      <? if (isset($ilsDetails['volume']) && !empty($ilsDetails['volume'])): ?>
        <strong><?=$this->transEsc('Volume')?>:</strong> <?=$this->escapeHtml($ilsDetails['volume'])?>
        <br />
      <? endif; ?>

      <? if (isset($ilsDetails['publication_year']) && !empty($ilsDetails['publication_year'])): ?>
        <strong><?=$this->transEsc('Year of Publication')?>:</strong> <?=$this->escapeHtml($ilsDetails['publication_year'])?>
        <br />
      <? endif; ?>

      <? if (isset($ilsDetails['institution_name']) && !empty($ilsDetails['institution_name'])): ?>
        <strong><?=$this->transEsc('location_' . $ilsDetails['institution_name'], array(), $ilsDetails['institution_name'])?></strong>
        <br />
      <? endif; ?>

      <? if (isset($ilsDetails['renew'])): ?>
        <strong><?=$this->transEsc('Renewed')?>:</strong> <?=$this->transEsc($ilsDetails['renew'])?>
        <? if (isset($ilsDetails['renewLimit'])): ?>
          / <?=$this->transEsc($ilsDetails['renewLimit'])?>
        <? endif; ?>
        <br />
      <? endif; ?>

      <? $showStatus = true; ?>

      <? if (isset($this->renewResult[$ilsDetails['item_id']])): ?>
        <? $renewDetails = $this->renewResult[$ilsDetails['item_id']]; ?>
        <? if (isset($renewDetails['success']) && $renewDetails['success']): ?>
          <? $showStatus = false; ?>
          <strong><?=$this->transEsc('Due Date')?>: <?=$this->escapeHtml($ilsDetails['duedate'])?> <? if (isset($renewDetails['new_time'])): ?><?=$this->escapeHtml($renewDetails['new_time'])?><? endif; ?></strong>
          <div class="alert alert-success"><?=$this->transEsc('renew_success')?></div>
        <? else: ?>
          <strong><?=$this->transEsc('Due Date')?>: <?=$this->escapeHtml($ilsDetails['duedate'])?><? if (isset($ilsDetails['dueTime'])): ?> <?=$this->escapeHtml($ilsDetails['dueTime'])?><? endif; ?></strong>
          <div class="alert alert-error"><?=$this->transEsc('renew_fail')?><? if (isset($renewDetails['sysMessage'])): ?>: <?=$this->escapeHtml($renewDetails['sysMessage'])?><? endif; ?></div>
        <? endif; ?>
      <? else: ?>
        <strong><?=$this->transEsc('Due Date')?>: <?=$this->escapeHtml($ilsDetails['duedate'])?><? if (isset($ilsDetails['dueTime'])): ?> <?=$this->escapeHtml($ilsDetails['dueTime'])?><? endif; ?></strong>
        <?if (!empty($ilsDetails['fine'])):?>
          | <strong><?=$this->transEsc('Fine')?>: <?=$this->escapeHtml($ilsDetails['fine'])?></strong>
        <?endif;?>
        <? if ($showStatus): ?>
          <? if (isset($ilsDetails['dueStatus']) && $ilsDetails['dueStatus'] == "overdue"): ?>
            <div class="alert alert-error"><?=$this->transEsc("renew_item_overdue")?></div>
          <? elseif (isset($ilsDetails['dueStatus']) && $ilsDetails['dueStatus'] == "due"): ?>
            <div class="alert alert-info"><?=$this->transEsc("renew_item_due")?></div>
          <? endif; ?>
        <? endif; ?>
      <? endif; ?>

      <? if ($showStatus && isset($ilsDetails['message']) && !empty($ilsDetails['message'])): ?>
        <div class="alert alert-info"><?=$this->transEsc($ilsDetails['message'])?></div>
      <? endif; ?>
      <? if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_link'])): ?>
        <a href="<?=$this->escapeHtml($ilsDetails['renew_link'])?>"><?=$this->transEsc('renew_item')?></a>
      <? endif; ?>
    </div>
  </div>
<? endforeach; ?>