<?
    // Set up page title:
    $this->headTitle($this->translate('My Holds'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a> <span class="divider">&gt;</span></li>'
        . '<li class="active">' . $this->transEsc('My Holds') . '</li>';
?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <h2><?=$this->transEsc('Your Holds and Recalls') ?></h2>

  <?=$this->flashmessages()?>
  <? if (count($this->view['views']) > 1): ?>
    <div class="pull-right row">
      <? $first = true; ?>
      <? foreach ($this->view['views'] as $name => $view): ?>
        <span class="col-md-6">
        <? if(!$view['selected']): ?>
          <a href="<?=$view['uri'] ?>" title="<?=$this->transEsc('Switch view to')?> <?=$this->transEsc(ucfirst($name))?>" >
        <? endif; ?>
          <img src="<?=$this->imageLink("view_$name.png") ?>"<? if($view['selected']): ?> title="<?=$this->transEsc(ucfirst($name))?> <?=$this->transEsc('view already selected') ?>" <? endif ?> alt="<?=$this->transEsc(ucfirst($name))?>"/>
        <? if(!$view['selected']): ?>
          </a>
        <? endif; ?>
        </span>
        <? $first = false; ?>
      <? endforeach; ?>
    </div>
    <br/><br/>
  <? endif; ?>

  <? if (!empty($this->recordList)): ?>
    <? if ($this->cancelForm): ?>
      <form name="cancelForm" class="inline" action="" method="post" id="cancelHold">
        <input type="hidden" id="submitType" name="cancelSelected" value="1"/>
        <input type="hidden" id="cancelConfirm" name="confirm" value="0"/>
        <div class="btn-group">
          <input id="cancelSelected" name="cancelSelected" type="submit" value="<?=$this->transEsc("hold_cancel_selected") ?>" class="btn btn-default dropdown-toggle" data-toggle="dropdown"/>
          <ul class="dropdown-menu">
            <li class="disabled"><a><?=$this->transEsc("confirm_hold_cancel_selected_text") ?></a></li>
            <li><a href="#" onClick="$('#cancelConfirm').val(1);$('#submitType').attr('name','cancelSelected');$(this).parents('form').submit()"><?=$this->transEsc('confirm_dialog_yes') ?></a></li>
            <li><a href="#"><?=$this->transEsc('confirm_dialog_no')?></a></li>
          </ul>
        </div>
        <div class="btn-group">
          <input id="cancelAll" name="cancelAll" type="submit" value="<?=$this->transEsc("hold_cancel_all") ?>" class="btn btn-default dropdown-toggle" data-toggle="dropdown"/>
          <ul class="dropdown-menu">
            <li class="disabled"><a><?=$this->transEsc("confirm_hold_cancel_all_text") ?></a></li>
            <li><a href="#" onClick="$('#cancelConfirm').val(1);$('#submitType').attr('name','cancelAll');$(this).parents('form').submit()"><?=$this->transEsc('confirm_dialog_yes') ?></a></li>
            <li><a href="#"><?=$this->transEsc('confirm_dialog_no')?></a></li>
          </ul>
        </div>
    <? endif; ?>

    <?= $this->render("myresearch/holds-" . $this->view['selected'] . ".phtml"); ?>
    
    <? if ($this->cancelForm): ?></form><? endif; ?>
  <? else: ?>
    <?=$this->transEsc('You do not have any holds or recalls placed') ?>.
  <? endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'holds'))?>
</div>