<table class="table-view">
  <tr>
    <th></th>
    <th><?=$this->transEsc('Author') ?></th>
    <th><?=$this->transEsc('Title') ?></th>
    <th><?=$this->transEsc('Year of Publication') ?></th>
    <th><?=$this->transEsc('pick_up_location') ?></th>
    <th><?=$this->transEsc('Created') ?></th>
    <th><?=$this->transEsc('Expires') ?></th>
  </tr>

  <? $iteration = 0; ?>
  <? foreach ($this->recordList as $resource): ?>
    <? $iteration++; ?>
    <? $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
    <tr id="record<?=$this->escapeHtml($resource->getUniqueId()) ?>">
      <td>
      <? if ($this->cancelForm && isset($ilsDetails['cancel_details'])): ?>
        <? $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $resource->getUniqueId()); ?>
        <input type="hidden" name="cancelAllIDS[]" value="<?=$this->escapeHtml($ilsDetails['cancel_details']) ?>" />
        <input type="checkbox" name="cancelSelectedIDS[]" value="<?=$this->escapeHtml($ilsDetails['cancel_details']) ?>" id="checkbox_<?=$safeId?>" />
      <? endif; ?>
      </td>
      <td>
        <? $listAuthor = $resource->getPrimaryAuthor(); if (!empty($listAuthor)): ?>
          <a href="<?=$this->record($resource)->getLink('author', $listAuthor)?>"><?=$this->escapeHtml($listAuthor)?></a><br/>
        <? else: ?>
          <?= $this->transEsc('Unknown') ?>
        <? endif; ?>
      </td>
      <td>
        <?
          // If this is a non-missing Solr record, we should display a link:
          if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
            $title = $resource->getTitle();
            $title = empty($title) ? $this->transEsc('Title not available') : $this->escapeHtml($title);
            echo '<a href="' . $this->recordLink()->getUrl($resource)
              . '" class="title">' . $title . '</a>';
          } else if (isset($ilsDetails['title']) && !empty($ilsDetails['title'])){
            // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
            echo $this->escapeHtml($ilsDetails['title']);
          } else {
            // Last resort -- indicate that no title could be found.
            echo $this->transEsc('Title not available');
          }
        ?>
      </td>
      <? /* TODO: tags
      {if $resource.tags}
        <?=$this->transEsc('Your Tags')?>:
        {foreach from=$resource.tags item=tag name=tagLoop}
          <a href="{$url}/Search/Results?tag={$tag->tag|escape:"url"}">{$tag->tag|escape}</a>{if !$smarty.foreach.tagLoop.last},{/if}
        {/foreach}
        <br/>
      {/if}
       */ ?>
      <? /* TODO: notes
      {if $resource.notes}
        <?=$this->transEsc('Notes')?>: {$resource.notes|escape}<br/>
      {/if}
       */ ?>

      <td>
        <? if (isset($ilsDetails['publication_year']) && !empty($ilsDetails['publication_year'])): ?>
          <?=$this->escapeHtml($ilsDetails['publication_year'])?>
        <? else: ?>
          <?= $this->transEsc('Unknown') ?>
        <? endif; ?>
      </td>

      <td>
        <? /* Depending on the ILS driver, the "location" value may be a string or an ID; figure out the best
           value to display... */ ?>
        <? $pickupDisplay = ''; ?>
        <? $pickupTranslate = false; ?>
        <? if (isset($ilsDetails['location'])): ?>
          <? if ($this->pickup): ?>
            <? foreach ($this->pickup as $library): ?>
              <? if ($library['locationID'] == $ilsDetails['location']): ?>
                <? $pickupDisplay = $library['locationDisplay']; ?>
                <? $pickupTranslate = true; ?>
              <? endif; ?>
            <? endforeach; ?>
          <? endif; ?>
          <? if (empty($pickupDisplay)): ?>
            <? $pickupDisplay = $ilsDetails['location']; ?>
          <? endif; ?>
        <? endif; ?>
        <? if (!empty($pickupDisplay)): ?>
          <?=$this->transEsc('Sublibrary ' . $pickupDisplay);?>
        <? endif; ?>
      </td>

      <td>
        <?=$this->escapeHtml($ilsDetails['create']) ?>
      </td>
      <td>
        <?=$this->escapeHtml($ilsDetails['expire']) ?>
      </td>

      <? if (isset($this->cancelResults['items'])): ?>
        <? foreach ($this->cancelResults['items'] as $itemId=>$cancelResult): ?>
          <? if ($itemId == $ilsDetails['item_id'] && $cancelResult['success'] == false): ?>
            <div class="alert alert-danger"><?=$this->transEsc($cancelResult['status']) ?><? if ($cancelResult['sysMessage']) echo ' : ' . $this->transEsc($cancelResult['sysMessage']); ?></div>
          <? endif; ?>
        <? endforeach; ?>
      <? endif; ?>

    </tr>
  <? endforeach; ?>

</table>