<h1>Rady pro pokročilé vyhledávání</h1>

<ul class="HelpMenu">
  <li><a href="#Search Fields">Vyhledávání v polích</a></li>
  <li><a href="#Search Groups">Vyhledávácí skupiny</a></li>
</ul>

<dl class="Content">
  <dt><a name="Search Fields"></a>Vyhledávání v polích</dt>
  <dd>
     <p>Při první návštěvě stránky s pokročilým vyhledáváním si můžete všimnout několika
       vyhledávácích polí.  Do každého pole můžete vyplnit výrazy, které si přejete
       vyhledat. <a href="Home?topic=search">Vyhledávací operátory</a>
       jsou povoleny.</p>
    <p>Každé pole obsahuje vyskakovací nabídku, ve kterých si můžete vybrat typ dat
      (titul, autor, atd.), ve kterých chcete hledat. Můžete přitom dohromady míchat jakýkoliv typ dat
       jak si přejete.</p>
    <p>Nastavení "Shoda" umožňuje specifikovat, jak jsou několika násobná vyhledávací pole obslouženy:</p>
    <ul>
      <li>VŠECHNY výrazy - vrátí pouze záznamy které vyhovují každému vyhledávacímu poli.</li>
      <li>JAKÉKOLI výrazy - vrátí všechny záznamy, které vyhovují alespoň jednomu vyhledávácímu poli.</li>
      <li>ŽÁDNÉ výrazy -- vrátí všechny záznamy KROMĚ těch, které vyhovují vyhledávácím polím.</li>
    </ul>
    <p>Tlačítko "Přidat vyhledávací pole" můžete použít k přidání dalších vyhledávacích polí do formuláře.
       Počet vyhledávacích polí je prakticky neomezený.</p>
  </dd>
  
  <dt><a name="Search Groups"></a>Vyhledávácí skupiny</dt>
  <dd>
    <p>Pro složité dotazy nemusí být jednoduchá množina vyhledávacích polí dostatečná.
       Třeba pokud chcete najít všechny knihy o historii Číny NEBO Indie.
       Pokud byste hledali VŠECHNY výrazy pro Čínu, Indii a historii, dostali byste
       pouze knihy, které jsou zároveň o historii Číny a Indie.  Pokud byste hledali
       JAKÝKOLIV výraz, dostali byste mezi výsledky i knihy, které nemají nic společného
       s Indií a Čínou.</p>
    <p>Vyhledávací skupiny poskytují způsob jak sestavit vyhledávací dotazy z
       několika vyhledávacích polí. Pokaždé, když kliknete na tlačítko "Přidat
       vyhledávací skupinu" button, nová skupina vyhledávacích polí je přidána.
       Nežádoucí vyhledávací skupinu může zrušit tlačítkem "Odstranit vyhledávací
       skupinu" a u každé skupiny můžete určit, zda chcete záznamy, které vyhovují
       VŠEM vyhledávacím skupinám či JAKÉKOLIV vyhledávací skupině.</p>
    <p>Na příkladě naší historie Číny a Indie, můžete problém vyřešit následovně:</p>
    <ul>
      <li>V první vyhledávací skupině vložte výrazy "Indie" a "Čína" a zkontrolujte,
          zda nastavení shody je "JAKÉKOLIV výrazy."</li>
      <li>Přidejte další vyhledávací skupinu a zadejte do ní historie.</li>
      <li>Zkontrolujte, že nastavení shody hned vedle hlavičky vyhledávacích skupin je
          nastaveno na "VŠECHNY skupiny."</li>
    </ul>
  </dd>
</dl>
