<?=$this->render('RecordDriver/AbstractBase/export-printbase.phtml')?>
<?
$pubPlaces = $this->driver->tryMethod('getPlacesOfPublication');
$pubDates = $this->driver->tryMethod('getPublicationDates');
$pubNames = $this->driver->tryMethod('getPublishers');
if (is_array($pubPlaces) && is_array($pubDates) && is_array($pubNames)) {
    $total = min(count($pubPlaces), count($pubDates), count($pubNames));
    // if we have pub dates but no other details, we still want to export the year:
    if ($total == 0 && count($pubDates) > 0) {
        $total = 1;
    }
    for ($i = 0; $i < $total; $i++) {
        if (isset($pubNames[$i])) {
            echo $this->transEsc('adv_search_publisher') . ": " . rtrim($pubNames[$i], ", ") . "\n";
        }
        $date = trim($pubDates[$i], '[]. ');
        if (strlen($date) > 4) {
            $date = $this->dateTime()->extractYear($date);
        }
        if ($date) {
            echo $this->transEsc('Published') . ": $date\n";
        }
        if (isset($pubPlaces[$i])) {
            echo $this->transEsc('Published in') . ": " . rtrim(str_replace(array('[', ']'), '', $pubPlaces[$i]), ': '). "\n";
        }
    }
}

$languages = $this->driver->tryMethod('getLanguages');
if (is_array($languages)) {
    foreach ($languages as $lang) {
        echo $this->transEsc('Language') . ": $lang\n";
    }
}

$series = $this->driver->tryMethod('getSeries');
if (is_array($series)) {
    foreach ($series as $current) {
        echo $this->transEsc('Series') . ': ' . (is_array($current) ? $current['name'] : $current) . "\n";
    }
}

$isbns = $this->driver->tryMethod('getISBNs');
if (is_array($isbns)) {
    foreach ($isbns as $isbn) {
        echo $this->transEsc('ISBN') . ": $isbn\n";
    }
}

$issns = $this->driver->tryMethod('getISSNs');
if (is_array($issns)) {
    foreach ($issns as $issn) {
        echo $this->transEsc('ISSN') . ": $issn\n";
    }
}

$subjects = $this->driver->tryMethod('getAllSubjectHeadings');
if (is_array($subjects)) {
    echo $this->transEsc('Subjects') . ":\n";
    foreach ($subjects as $subject) {
        if (is_array($subject)) {
            echo '  ' . $subject[0] . "\n";
        } else {
            echo '  ' . $subject . "\n";
        }
    }
}

$callNumbers = $this->driver->getCallNumber();
if (is_array($callNumbers)) {
    echo $this->transEsc('Callnumber') . ":\n";
    foreach ($callNumbers as $callNumber) {
        echo '  ' . $callNumber . "\n";
    }
}

$physicalDescr = $this->driver->getPhysicalDescriptions();
if (is_array($physicalDescr)) {
    foreach ($physicalDescr as $descr) {
        echo $this->transEsc('Physical Description') . ": $descr\n";
    }
}

// Record separator:
echo "\n";
?>